### ISSUE TITLE
Restrictions described in the comments for `get_write_ptr`, `get_read_ptr` seem incorrect.

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent-metal/tt-metal#1050]
Comments to `dataflow_api` were added through this commit: https://github.com/tenstorrent-metal/tt-metal/commit/caea1e797fc30d3946b973f72cb58e8527b6aef3#diff-2081a858a36ada2e02b61a9c0d355f456c40900acf28ff39b7548b061dfda53bR301
which seem incorrectly mentioning the usage restrictions. Need to update/fix those.

**Comment by davorchap** [comment]
Not relevant anymore.
