### ISSUE TITLE
Program cache, remembering profiling state

### ISSUE THREAD

**Issue by mo-tenstorrent** [tenstorrent-metal/tt-metal#1162]
@arakhmati 
As of [e5402e8](https://github.com/tenstorrent-metal/tt-metal/commit/e5402e8e0914151bca2c169a8344db226601f6b0) development on program caching is enabled. We need to make note of programs that were cached with a profiling state, different from the global op profiling flag. 

One solution is to have the program class also hold a `isProfiled` flag. Check the flag when program is retrieved and decide to either ignore the global flag for that op or regenerate with the global profiler flag state if different from the cached state.

**Comment by davorchap** [comment]
@mo-tenstorrent is this still relevant?

**Comment by mo-tenstorrent** [comment]
No
