### ISSUE TITLE
llk_3c.h and dataflow_api.h cleanup and refactor

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent-metal/tt-metal#1365]
https://docs.google.com/document/d/1em0MZ9SbhpAPYq60DSdPYZnFZM8dkcaAJxGiO5Q_20I/edit?pli=1

A superset of https://github.com/tenstorrent-metal/tt-metal/issues/247

- [x] Move compute kernel api to top level include
- [ ] ~~Move dataflow kernel api to top level include and split it into user facing and internal
- [ ] Introduce compute namespace
- [ ] Introduce dataflow and dataflow_internal namespace
- [ ] Move various functions in dataflow_internal to dataflow which need to be exposed to user~~

**Comment by davorchap** [comment]
@mywoodstock we completed some of this planned work. 
We can close and open new cases if we plan for similar features?

**Comment by mywoodstock** [comment]
we decided not to add these namespaces, and keep the dataflow api as it is now. Closing.
