### ISSUE TITLE
test_full_buffer under programming example is hanging when cache persistence is enabled.

### ISSUE THREAD

**Issue by mo-tenstorrent** [tenstorrent-metal/tt-metal#1757]
https://github.com/tenstorrent-metal/tt-metal/tree/main/tt_metal/programming_examples/profiler/device/grayskull/test_full_buffer

When `enable_compile_cache` is set to true in `tt_metal.cpp` if there is a cached miss on the kernel (i.e. built folder is removed) test runs fine. On cache hit however the test hangs. 

This is on main commit f51799d01c428a47efe58f7155958b5e3a970baa

**Comment by TT-billteng** [comment]
@mo-tenstorrent can you re-test to see if this is still happening?

**Comment by davorchap** [comment]
> @mo-tenstorrent can you re-test to see if this is still happening?

@mo-tenstorrent ping :), let close this if fixed
