### ISSUE TITLE
Signbit incorrect output when input value is 0

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent-metal/tt-metal#1939]
@muthutt

**Comment by davorchap** [comment]
@muthutt need update on this :)

**Comment by bharane-abb** [comment]
methods tried for signbit bug:

- Observe that when we pass input and return as it is . we notice the change in sign, for -0 it return 0 but for -1 it return -1 so in our device its not handle for -0.
- I tried your suggestion mentioned above , but  it give the same result  for 0 and -0 .
- Recipe  (1/0 is inf ) is not working as it not take sign to consideration
- Ascii value is same for both 0 and -0 so no use in convert to hexa decimal value or other type.
- In tf there is no difference in 0 and -0 . sign function consider 0 as neutral value and give result as 0 for both 0 and -0 and for pos it return  1 and neg as -1
- Setsgn is uses to fix the symbol but in our case we don’t get the sign
- Tried using arithematic fun like sub,add and mul it is not helping in our -0 case
