### ISSUE TITLE
Command queue commands should be smaller

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent-metal/tt-metal#2095]
Right now, a command takes up 22KB. Once I support double-slotting commands, that's 44KB of space I am taking up just for commands, which is quite a bit. 
The main reason commands are this big is because of unicasting runtime arguments to 108 worker cores (theoretical max). One possibility to lower the command size is to send multiple device commands in case we have lots of runtime arguments, however this should be more thoroughly thought out.

fyi @davorchap

**Comment by davorchap** [comment]
implemented in FD2
