### ISSUE TITLE
Investigate Jenkins integration

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent-metal/tt-metal#2438]
Some things Jenkins can do that I feel like we're missing 

> Summarizes the results: Most plugins also summarize the test results and display them as an HTML page.
> 
> Provides Trends: Jenkins keeps track of results and displays them as a trend graph. This offers a better view of how the tests have fared in the past.
> 
> Display details on Test Failures: Test results are tabulated, and failures are logged with the test results.

https://www.browserstack.com/guide/jenkins-for-test-automation

**Comment by tt-rkim** [comment]
Closing for now, and can pull in Jenkins in some other flows if we need.
