### ISSUE TITLE
tt-gdb productize

### ISSUE THREAD

**Issue by davorchap** [tenstorrent-metal/tt-metal#277]
This is the top-level case. We need to open sub-cases and link them here.

@DrJessop can you provide the list of outstanding tasks (issues)

- Currently it works on NCRISC.

- What needs to be done to make it work BRISC / TRISCs?

- What needs to be done with the compilation / linking in order to get symbols / larger L1 space?

- Can we print variable state w/o setting it to volatile, ie, w/o having to  compile all variables to L1. We probably need to use trisc-debug interface to access RISC-V local memory + registers. We have debuda docs / RISC debug spec, we can see how it is done there.

**Comment by ihamer-tt** [comment]
Are there any instructions on how to try this out, or links to the implementation?

**Comment by davorchap** [comment]
@ihamer-tt Most likely this doesn't work on latest main.
