### ISSUE TITLE
Debug tools for compute kernels

### ISSUE THREAD

**Issue by davorchap** [tenstorrent-metal/tt-metal#279]
Top-level case. Need sub-cases for tasks below:

Debugging data mismatch:
- Print a tile from CB (basically print a tile from L1) 
- Print a tile from DST (needs to first pack to a location, then print a tile from L1)
 
Debugging hangs:
- Print CB state (num tiles in CB, rd_ptr, wrt_ptr, etc)
- Print math/pack semaphore state (ie acquire/release dst state)
- Print unpack / math / pack engine instruction queue state (running / empty / stalled  -- need to talk to Alex C)

These prints should work with DPRINT but should also be callable from `tt-gdb`

@DrJessop  @coffeeandcheesecake  What else?

**Comment by davorchap** [comment]
@ihamer-tt and @tt-dma I think most of these features are implemented, and issues for feature requests are being tracked. You can close this one.

**Comment by ihamer-tt** [comment]
The first two points are completed.
The rest will go into a new issue.
