### ISSUE TITLE
Build binaries take too much space

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent-metal/tt-metal#2875]
This is preventing us from creating build artifacts efficiently which enables multi-stage CI pipelines. Enabling multi-stage CI pipelines is critical to accelerating CI runs #2128

```
(python_env) billteng@e03cs01:~/ttm2/build/lib$ ls -l
total 1469128
-rw-rw-r-- 1 billteng billteng  22417748 Sep 26 01:54 libbuild_kernels_for_riscv.a
-rw-rw-r-- 1 billteng billteng  10787880 Sep 26 01:53 libcommon.a
-rwxrwxr-x 1 billteng billteng   3278184 Sep 26 01:53 libdevice.so
-rw-rw-r-- 1 billteng billteng  37724542 Sep 26 01:54 libdtx.a
-rw-rw-r-- 1 billteng billteng  43536404 Sep 26 01:54 libllrt.a
-rw-rw-r-- 1 billteng billteng  56667894 Sep 26 01:54 libtensor.a
-rwxrwxr-x 1 billteng billteng     27984 Sep 26 01:53 libtracy.a
-rw-rw-r-- 1 billteng billteng 817002186 Sep 26 01:54 libtt_dnn.a
-rw-rw-r-- 1 billteng billteng  17988820 Sep 26 01:54 libtt_gdb.a
-rwxrwxr-x 1 billteng billteng 308021640 Sep 26 01:54 libtt_lib_csrc.so
-rw-rw-r-- 1 billteng billteng  10397064 Sep 26 01:54 libtt_metal_detail.a
-rw-rw-r-- 1 billteng billteng 103962010 Sep 26 01:54 libtt_metal_impl.a
-rwxrwxr-x 1 billteng billteng  72528088 Sep 26 01:54 libtt_metal.so
drwxrwxr-x 2 billteng billteng      4096 Sep 26 01:53 tools
(python_env) billteng@e03cs01:~/ttm2/build/lib$ du . -h --max-depth=1
9.7M    ./tools
1.5G    .
```

Perhaps the best way out is to redo build with #2662 and/or #2874

**Comment by TT-billteng** [comment]
![image](https://github.com/tenstorrent-metal/tt-metal/assets/135061747/c5fa2607-e3a5-4e27-b8d1-172ee5a57b96)

**Comment by ttjchu** [comment]
Assuming you guys are running with `CONFIG=ci`, this is a non-issue:

# With default build (i.e. CONFIG=assert):

![original](https://github.com/tenstorrent-metal/tt-metal/assets/122298491/8086228a-d797-4b66-8056-9d6b001843be)


# with `CONFIG=ci`:

![ci_1](https://github.com/tenstorrent-metal/tt-metal/assets/122298491/3646a3db-255f-47d6-a29c-118b0c35a95b)

![ci_2](https://github.com/tenstorrent-metal/tt-metal/assets/122298491/b685782e-02ca-474b-a63c-749e26aed2b8)

**Comment by ttjchu** [comment]
With `assert` it's getting compiled with `-g` and size bloat is from the debug symbols

**Comment by TT-billteng** [comment]
does build=ci work in post-commit? If so, that would be an easy way to enable artifacts

**Comment by ttjchu** [comment]
> does build=ci work in post-commit? If so, that would be an easy way to enable artifacts

@tt-rkim

**Comment by tt-rkim** [comment]
@TT-billteng @cfjchu @ttmchiou

got a PR up to integrate `CONFIG=ci` into all our flows and add it as part of build binaries step: https://github.com/tenstorrent-metal/tt-metal/pull/5655

Build itself looks good and I've tested eager package pipeline + profilier pipeline and they work. Both libs and tests build wonderfully. Note for those unfamiliar with build binaries pipeline, we upload everything in `build/lib` and `build/test`. I believe we could (and possibly should) add `build/hw` and `build/programming_examples`

https://github.com/tenstorrent-metal/tt-metal/actions/runs/8054614149 
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8055845818
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8055846477

is all post commit.

Once this passes, we'll merge this immediately and we can start using `ci` config on all tests. We could consider a slow rollout such as incorporating these artifacts into the profiler regression.

**Comment by tt-rkim** [comment]
We have switched over all pipelines to use `ci` config and added `CONFIG=ci` to the build C++ binaries pipeline.

There's some work to be done to verify that we can just download and use these binaries that we built on Github-hosted runners.

**Comment by tt-rkim** [comment]
This is hw toolchain, lib, test, and programming_examples on a per config basis (specification for build folder in workflow: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8067848579/workflow) :

<img width="861" alt="Screenshot 2024-02-27 at 12 28 39 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/109366641/e9168b6c-b073-451a-a3f3-d25fac8f3d6e">

**Comment by tt-rkim** [comment]
We're going to close this now as we now have a much more reasonable output of <100MB.
