### ISSUE TITLE
WormholeB0 BERT Large Slow/Fast Dispatch Bad PCC and Hang

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent-metal/tt-metal#2890]
**Describe the bug**
Currently when running bert large perf on WH, we can achieve one run with bad pcc.

In slow dispatch, if we run again, we just get bad PCC again. In fast dispatch, we hang if we run again.

**To Reproduce**
On`agrebenisan/bert-large-on-wh`, run the following twice in a row

```
TT_METAL_LOGGER_LEVEL=debug pytest tests/models/bert_large_perf/test_bert_batch_dram.py::test_bert_batch_dram[phiyodr/bert-large-finetuned-squad2-9-384-True-True-True-0.98]
```

**Expected behavior**
You should see a crappy PCC with the following log

```
PCC on wormhole_b0 for bert batch dram is expected to be poor
```

and then running again (if in fast dispatch), you should get a hang.

**Comment by jliangTT** [comment]
This issue has grown extremely stale. Does this still apply? Can we close this and re-open it when we run into new issues?

**Comment by boris-drazic** [comment]
Yes, this is way out of date.
