### ISSUE TITLE
ttl.tensor.relu_min operation breaks with low PCC [Grayskull]

### ISSUE THREAD

**Issue by banekg** [tenstorrent-metal/tt-metal#2904]
**Describe the bug**
**ttl.tensor.relu_min** operation breaks with low PCC error in some test cases. 

**To Reproduce**
1. Checkout `main` branch
2. Run unit test `test_eltwise_relu_min.py` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_relu_min.py`

**Expected behavior**
There are six test cases presented in the unit test `tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_relu_min.py` and three of them are expected to fail with low PCC error (other three tests should pass). 
For example, one of the tests is expected to fail with this result: 
`Max ATOL Delta: 0.49987030029296875, Max RTOL Delta: 0.0050481162033975124, PCC: 0.9176552370023291`

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for ttl.tensor.relu_min and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_grayskull/pytorch_eltwise_relu_min_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `eltwise_relu_min_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Find on ARA**

1. Navigate to `http://172.27.44.162:8080/op_test_sweeps`
2. Select `pytorch_eltwise_relu_min_test` for the test sweep name and date interval to consists of `2023-09-21 09:22`

**Comment by ruthreshx** [comment]
Hi @banekg, @nemanjagrujic,
From the latest main, I don't see any failures on running the relu_min op.
I have attached the sweep test results FYR.
[eltwise_relu_min_sweep.csv](https://github.com/tenstorrent-metal/tt-metal/files/13783824/eltwise_relu_min_sweep.csv)

**Comment by yugaoTT** [comment]
test passed, close issue
