### ISSUE TITLE
cudaStreamWaitEvent / clEnqueueMarkerWithWaitList TTMetal equivalent API

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent-metal/tt-metal#2946]
https://docs.google.com/document/d/137U9uTLByRXX7JcS5fSoUnzRZ0pohP0f/edit?usp=sharing&ouid=114502124043371428589&rtpof=true&sd=true

Synchronization between queue 1 ↔︎ queue 2 (between different queues)
Host API functions (1) to enqueue a “marker” to the first queue and (2) to make the second queue to wait until all commands enqueued before the marker in the first queue finish
Use case
A host program enqueues one or more commands (let C1) to the first queue
The program calls the API function 1 to enqueue a marker to the first queue
The program may enqueue one or more additional commands (let C2) to the first queue
Meanwhile, the program may enqueue one or more commands (let C3) to the second queue
The program calls the API function 2, and then enqueue one or more additional commands (let C4) to the second queue
All the commands in C4 will be issued and executed AFTER all the commands in C1 finish
Note that there are no ordering constraints between C2 → C4 and C1 → C3.
Also note that the API function 2 does not block the host program (i.e., this API just defines the dependency between two queues and returns immediately).
Example API
CUDA: cudaStreamWaitEvent
OpenCL: clEnqueueMarkerWithWaitList

**Comment by davorchap** [comment]
implemented
