### ISSUE TITLE
Top Level issue for remaining WH features to bringup/test

### ISSUE THREAD

**Issue by kkwong10** [tenstorrent-metal/tt-metal#2978]
P1
- [x] #952 
- [x] #4461 
- [x] #4463 

P2
- [ ] #4686 
- [x] #4462 

P3
- [ ] #3102

**Comment by davorchap** [comment]
fyi @chekangliang  and @rtawfik01

**Comment by jliangTT** [comment]
@rtawfik01. Hey want to check if this is in progress and if it has an ETA? 
@davorchap , after the llk piece, do we need to do development on the metal side to plumb it through?

**Comment by rtawfik01** [comment]
> @rtawfik01. Hey want to check if this is in progress and if it has an ETA? @davorchap , after the llk piece, do we need to do development on the metal side to plumb it through?

Hey @jliangTT , the llk apis for these features are already available, what's left is for metal team to enable these features across the stack, and let me or @acejkov know if anything goes wrong and we can debug

**Comment by jliangTT** [comment]
thank you so much @rtawfik01. ok i will follow up within the team to the enablement piece. thanks!

**Comment by davorchap** [comment]
close as only 2 remaining issues
