### ISSUE TITLE
Investigate creating new CI machines and full coverage on them for multi device

### ISSUE THREAD

**Issue by jvasilje** [tenstorrent-metal/tt-metal#3007]
The machine configurations we want in CI for testing that @jvasilje and I agreed on are:

1 x e150
2 x e150
1 x n150 
2 x n150
1 x n300
2 x n300

@tt-rkim what is possible today in the cloud?

**Comment by tt-rkim** [comment]
@aliuTT brought up a good point of still having some sort of scheduled matrix coverage of different multi card setups, but not for post commit.

Can schedule for multiple runs during workday etc.

**Comment by tt-rkim** [comment]
Synced with @aliuTT + @jliangTT today, and goal is to have ad-hoc CI on cloud/lab, pending what's available Monday, with:

- One-time setup with manually ported tools while we're waiting for tt-topo and new SMI to be released
- No SMI reset, but rather scheduled reboots for now
- No post-commit guarantee for multi chip w/ ethernet, however multiple runs over the day and night.

**Comment by tt-rkim** [comment]
@aliuTT @TT-BrianLiu @tt-aho are now watching: https://github.com/tenstorrent-metal/tt-metal/actions/workflows/multi-device-slow-dispatch-build-and-unit-tests.yaml

it will be running on a frequent schedule like a transit system, but no push trigger so no block on main.

**Comment by jliangTT** [comment]
yes. That is consistent with my view. @davorchap , we are not thinking of supporting 2 x n150 right for llm-box?

**Comment by tt-rkim** [comment]
@davorchap Please advise on 2 x n150 plans

Right now we are not guaranteeing it runs on more than 1 N150. @abhullar-tt , @farbabi and @aliuTT noticed that 2 x n150 connected actually had a failure via UMD.
