### ISSUE TITLE
Metal API request for multiple queues

### ISSUE THREAD

**Issue by razorback3** [tenstorrent-metal/tt-metal#3089]
Current Metal supports a single queue for a device.
There is no way to make multiple queues and synchronize between them for a device.

To support multiple queues, there should be...
- APIs to create and destroy queues
- APIs to synchronize between host ↔︎ queue
  - A host API function to wait for all previously enqueued commands in the queue
    - Use case
      - A host program enqueues one or more commands (let **C**) to the queue
      - Then, the program calls this API to wait until all the commands in **C** finish
    - Example API
      - CUDA: cudaStreamSynchronize
      - OpenCL: clFinish
  - Host API functions (**1**) to enqueue a “marker” to the queue and (**2**) to wait until all commands enqueued before the marker finish
    - Use case
      - A host program enqueues one or more commands (let **C1**) to the queue
      - The program calls the API function **1** to enqueue a marker to the same queue
      - The program may enqueue one or more additional commands (let **C2**) to the same queue
      - The program calls the API function **2** to wait until all the commands in **C1** finish
        - Note that there are no guarantees about the completion of the commands in **C2**
    - Example API
      - CUDA: cudaEventRecord / cudaEventSynchronize
      - OpenCL: clEnqueueMarkerWithWaitList / clWaitForEvents
- APIs to synchronize between queue 1 ↔︎ queue 2 (between different queues)
  - Host API functions (**1**) to enqueue a “marker” to the first queue and (**2**) to make the second queue to wait until all commands enqueued before the marker in the first queue finish
    - Use case
      - A host program enqueues one or more commands (let **C1**) to the first queue
      - The program calls the API function **1** to enqueue a marker to the first queue
      - The program may enqueue one or more additional commands (let **C2**) to the first queue
      - Meanwhile, the program may enqueue one or more commands (let **C3**) to the second queue
      - The program calls the API function **2**, and then enqueue one or more additional commands (let **C4**) to the second queue
      - All the commands in **C4** will be issued and executed AFTER all the commands in **C1** finish
        - Note that there are no ordering constraints between C2 → C4 and C1 → C3.
        - Also note that the API function **2** does not block the host program (i.e., this API just defines the dependency between two queues and returns immediately).
    - Example API
      - CUDA: cudaStreamWaitEvent
      - OpenCL: clEnqueueMarkerWithWaitList
- APIs for performance profiling (these are relatively low priority)
  - A host API function to obtain the profiling information of a specific command (current status, enqueued time, start time, and completion time)
    - Example API
      - CUDA: cudaEventQuery, cudaEventElapsedTime
      - OpenCL: clGetEventInfo, clGetEventProfilingInfo
  - A host API function to register a callback function to be invoked when the status of a specific command changes (e.g., changed from queued to running / from running to completed)
    - Example API
      - CUDA: cudaStreamAddCallback
      - OpenCL: clSetEventCallback

In addition, every TT-DNN op should receive a queue that the op will be enqueued.
```
ttdnnOp1(queue1, ...)
ttdnnOp2(queue2, ...)
```

Below is an example flow of using multiple queues and TT-DNN ops.
```
ttdnnOp1(queue1, ...)
ttdnnOp2(queue1, ...)
event = hostToDeviceCopy(queue2, ...) // this can be overlapped with Op1 and Op2
add_marker(queue1, event)
ttdnnOp3(queue1, ...)
ttdnnOp4(queue1, ...)
```

Moreover, I attach an example OpenCL code which shows all the usages described above.
[example.cpp.zip](https://github.com/tenstorrent-metal/tt-metal/files/12857521/example.cpp.zip)

**Comment by davorchap** [comment]
fyi @jliangTT, @TT-billteng , @tt-asaigal and @jvasilje 
The spec of this requested has been discussed, planned and implemented.
