### ISSUE TITLE
Stable Diffusion Demo Fails on WH

### ISSUE THREAD

**Issue by farbabi** [tenstorrent-metal/tt-metal#3108]
**Describe the Bug:**
Unbached Stable Diffusion demo on WH fails after 8 iterations, for both fast and slow dispatch. 50 iterations are needed to generate a proper image. 

The pcc looks ok (0.996 after 8 iterations) which is in line with GS.

**To Reproduce:**
on `farbabi/wh_models` run:
`pytest models/stable_diffusion/demo/unbatched_demo.py`

**Expected Behaviour:**
`Segmentation fault (core dumped)`

**Comment by jliangTT** [comment]
I think we can close this as the SD is progress in a separate path.
