### ISSUE TITLE
ttl.tensor.layernorm operation breaks with low PCC [Wormhole]

### ISSUE THREAD

**Issue by banekg** [tenstorrent-metal/tt-metal#3180]
**ttl.tensor.layernorm** operation breaks with low PCC error in some test cases. 

**To Reproduce**

1. Checkout `main` branch
2. Run unit test `test_layernorm.py` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_layernorm.py`

**Expected behavior**

There are 4 test cases presented in the unit test `test_layernorm.py` and they all are expected to fail with low PCC error. 
For example, one of the tests is expected to fail with this result: 
`Max ATOL Delta: 15.265962600708008, Max RTOL Delta: inf, PCC: 0.981145692416358, PCC check failed`

**Getting Additional info for the operation under test and its behavior**

To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for ttl.tensor.ne and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_wormhole/pytorch_layernorm_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `layernorm_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by yugaoTT** [comment]
test removed? can we close
