### ISSUE TITLE
DPRINT - elaboration on documentation and full-working examples

### ISSUE THREAD

**Issue by mbahnasTT** [tenstorrent-metal/tt-metal#3217]
- elaborate that core coordinates starts from (1,1) and not (0,0): `export TT_METAL_DPRINT_CORES="(1,1)"`
- elaborate on output will be saved in that file `export TT_METAL_DPRINT_FILE="dprint.log"`
- List examples of use cases: 1) print variables and addresses.   2) print CB data. .. anything else?
- Elaborate on the need of the 'TileSlice' to be within `cb_reserve_back<>cb_push_back` or `cb_wait_front<>cb_pop_front`
-  MATH(( DPRINT << x << ENDL() )) gives me empty print with 'TileSlice'
- PACK() and UNPACK() are good with `TileSlice` but on different locations in the kernel code
- I added 'TileSlice' in my 3 kernels read/write/compute to give example on all possibilities. I may be missing some more functionalities

- The code snippet for TileSlice
```
                        uint32_t debug_cb_id = 1; 
                        for (int32_t r = 0; r < 32; ++ r) {
                            SliceRange sr = SliceRange{.h0 = r, .h1 = r+1, .hs = 1, .w0 = 0, .w1 = 32, .ws = 1};
                            DPRINT << (uint)r << " --READ--cin1-- " << TileSlice(debug_cb_id, 0, sr, true, false) << ENDL();
                        }
```

**Comment by tt-dma** [comment]
@mbahnasTT There have been some updates to the DPRINT documentation: https://tenstorrent-metal.github.io/tt-metal/latest/tools/kernel_print.html

I think all of the comments from this issue and #3770 should be addressed, could you take a look and see if you think anything is missing?

**Comment by mbahnasTT** [comment]
Thanks @tt-dma , it looks very good!
