### ISSUE TITLE
tt_lib.tensor.rdiv fails with low PCC [Grayskull]

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent-metal/tt-metal#3310]
**Describe the bug**

ttl.tensor.rdiv operation breaks with low PCC error in few test cases.

**To Reproduce**

Checkout `main` branch
Run unit test `test_eltwise_rdiv.py` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_rdiv.py`
Expected behavior

There are seven test cases presented in the unit test `test_eltwise_rdiv.py` and all except one fail with low PCC error like this:
`Max ATOL Delta: inf, Max RTOL Delta: inf, PCC: 1.2885153220106043e-08, PCC check failed`
The one exception is the test which fails with memory allocation error:
`Out of Memory: Not enough space to allocate 36126720 B L1 buffer across 128 banks, where each bank needs to store 282624 B`

**Getting Additional info for the operation under test and its behavior**

To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for ttl.tensor.ne and check the results. To do this you should:

Follow the Getting Started page to setup the repo, environment variables and python-env
Activate `source build/python_env/bin/activate`
Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_grayskull/pytorch_eltwise_rdiv_test -o ./result-sweeps`
After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find eltwise_rdiv_sweep.csv which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique data_seed field.

**Comment by npetrovic-tenstorrent** [comment]
Still exhibits low PCC

**Comment by Aswinmcw** [comment]
Hi @npetrovic-tenstorrent , @eyonland @jliangTT ,
PR #7150 will fix this issue.
One exception case where the input shape is larger, it is throwing out of memory error, apart from that, remaining tests passing with good pcc value
<img width="1512" alt="Screenshot 2024-04-05 at 4 40 19 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/156493059/88d23f53-449f-462b-a6d6-be4d8ddea934">

**Comment by npetrovic-tenstorrent** [comment]
I confirm that it works as well (assuming that we avoid too large shapes, as in the last test case), so we can definitely close the issue as the original problem appears to be resolved.
