### ISSUE TITLE
ttl.tensor bert ops crash on wormhole

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent-metal/tt-metal#3391]
**Describe the bug**
**ttl.tensor** **bert** operations break on wormhole mashines.

 1. bert_large_fused_qkv_matmul
 2. bert_large_pre_softmax_bmm
 3. bert_large_post_softmax_bmm
 4. bert_large_selfout_matmul
 5. bert_large_ff1_matmul 
 6. bert_large_ff2_matmul

**To Reproduce**
1. Checkout `main` branch
2. Run unit test `test_bert_ternary.py` and `test_bert_binary.py` using the command:

`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_bert_ternary.py`

and

`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_bert_binary.py`

**Expected behavior**
Expected error is:

`RuntimeError: TT_ASSERT @ tt_metal/impl/device/device.cpp:308: (logical_core.x < logical_grid_size.x) and (logical_core.y < logical_grid_size.y)`

**Comment by yugaoTT** [comment]
the functions you called `(ex, bert_large_selfout_matmul)` is hardcoded to grid.x=12, which is not supported in WH. We are not using these functions anymore in our model. 
I'll close this issue

**Comment by yugaoTT** [comment]
The funcuons here are really old, and not used by any models. I don't think it should be documented and exposed to the user.
