### ISSUE TITLE
ttl.tensor.addcdiv operation fails with low PCC error on WH

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent-metal/tt-metal#3417]
**ttl.tensor.addcdiv** breaks with low PCC error in one test case on Wormhole card. Note test passes on Grayskull.

**To Reproduce**

1. Checkout `main` branch
2. Run unit test `test_addcdiv.py` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_addcdiv.py`

**Expected behavior**

There is one test case presented in the unit test `tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_addcdiv.py` which is expected to fail with low PCC error, like this:
`Max ATOL Delta: inf, Max RTOL Delta: inf, PCC: 1.0766980060983223e-06, PCC check failed`

**Getting Additional info for the operation under test and its behavior**

To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for ttl.tensor.addcdiv and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_wormhole/pytorch_eltwise_addcdiv_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `eltwise_addcdiv_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by nemanjagrujic** [comment]
Tested. Still failing.

**Comment by VirdhatchaniKN** [comment]
Hi @nemanjagrujic , @jliangTT , @eyonland , @tt-aho 
Fix provided for forward addcdiv op (Tested is both GS, WH_B0) - [Link](https://github.com/tenstorrent-metal/tt-metal/pull/7152)
All post-commit tests - [Link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/8570318957)

**Comment by VirdhatchaniKN** [comment]
Hi @nemanjagrujic 
I've merged the changes and now the issue is fixed. Can you confirm once before closing the issue
Thanks

**Comment by nemanjagrujic** [comment]
Tested and works now.
