### ISSUE TITLE
Erisc Compile Cleanup Items

### ISSUE THREAD

**Issue by aliuTT** [tenstorrent-metal/tt-metal#3420]
Some cleanup items:

- [ ] generate linkers
- [ ] delete eth_l1 map and consume from UMD
- [ ] make base and kernel FW data and code sections non-static
- [ ] load iram

**Comment by abhullar-tt** [comment]
@aliuTT is this still relevant?

**Comment by aliuTT** [comment]
yea, but there are probably other items that we can open to track this

**Comment by aliuTT** [comment]
Closing, I opened new items for relevant TODOs
