### ISSUE TITLE
ResNet50 perf=3000fps

### ISSUE THREAD

**Issue by jvasilje** [tenstorrent-metal/tt-metal#3454]
**Kernel/OP Optimizations**

- [x] https://github.com/tenstorrent-metal/tt-metal/issues/3572
- [ ] https://github.com/tenstorrent-metal/tt-metal/issues/3472
- [x] https://github.com/tenstorrent-metal/tt-metal/issues/3473 
- [x] https://github.com/tenstorrent-metal/tt-metal/issues/3474
- [x] https://github.com/tenstorrent-metal/tt-metal/issues/3278
- [x] https://github.com/tenstorrent-metal/tt-metal/issues/3538
- [x] https://github.com/tenstorrent-metal/tt-metal/issues/3759

**End-to-end Metal Optimizations**
- [ ] https://github.com/tenstorrent-metal/tt-metal/issues/3468
- [ ] https://github.com/tenstorrent-metal/tt-metal/issues/3535

**Comment by nsmithtt** [comment]
Closing, new perf effort tracked here #4236
