### ISSUE TITLE
BERT perf=400 sent/s on GS

### ISSUE THREAD

**Issue by jvasilje** [tenstorrent-metal/tt-metal#3455]
**Performance Optimizations:**
- [x] #3629 
- [x] #3632 
- [x] #3633 
- [x] #3630 
- [x] #3634 
- [x] #3631 
- [x] #3635 

**Accuracy Tuning:**
- Tune accuracy for Lofi/Bfp8 BERT

**Comment by davorchap** [comment]
410 sent/sec has been achieved, closing this case

LN / Softmax still need to be optimized, not P0/P1 , will open separate cases
