### ISSUE TITLE
fast dispatch perf optimization

### ISSUE THREAD

**Issue by davorchap** [tenstorrent-metal/tt-metal#3468]
1. investigation on page size impact on WH BW 
https://github.com/tenstorrent-metal/tt-metal/issues/3491

2. ~~send rt arg refs piece by piece
https://github.com/tenstorrent-metal/tt-metal/issues/3441~~

3. ~~use write_one_packet to write run-time args
https://github.com/tenstorrent-metal/tt-metal/issues/3487~~

4. use of cmd bufs for writes
https://github.com/tenstorrent-metal/tt-metal/issues/3490

5. VC round-robin for DRAM
https://github.com/tenstorrent-metal/tt-metal/issues/3488

6. any low-hanging fruit on host performance

7. investigate caching of commands on host and DRAM
https://github.com/tenstorrent-metal/tt-metal/issues/3486

8. ~~use multicast_one_packet to write program pages
https://github.com/tenstorrent-metal/tt-metal/issues/3716~~

9. ~~Link back-to-back multicasts
https://github.com/tenstorrent-metal/tt-metal/issues/3718~~

**Comment by DrJessop** [comment]
Closing since stale.
