### ISSUE TITLE
test_untilize_with_halo_and_max_pool has test case failures in slow dispatch mode

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent-metal/tt-metal#3516]
`pytest tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_and_max_pool.py` passes.

`TT_METAL_SLOW_DISPATCH_MODE=1 pytest tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_and_max_pool.py` fails for 2 test cases.

Specifically the configuration `dilation0-stride0-padding0-kernel_size0-act_shape2` is the only one that fails. For bfloat16 it is a minor mismatch, and for bfp8_b output is completely incorrect.

**Comment by mywoodstock** [comment]
This version of the op is now deprecated.
