### ISSUE TITLE
MetalGraph capture / replay design and APIs

### ISSUE THREAD

**Issue by davorchap** [tenstorrent-metal/tt-metal#3535]
@DrJessop has started the design plan for the Metal level support for metal graph. 
Initial implementation is a trace of the content in the HW CQ. So no actual graph support at this point.

It will be done in 3 phases.
Phase 1: @DrJessop Metal HW CQ level impl: capture and reply of the graph cannot be mixed with other dynamic operations (allocs/deallocs, etc). That is, once the graph is captured, we cannot allocate additional tensors.  
Phase 2: architect memory pool in the allocator (low/high watermarks) to allow the MetalGraph to co-exist with dynamic tensors (@abhullar-tt )
Phase 3:  actual graph design @arakhmati 

Design plan (to be updated):
- [ ] Metal-level API and data structures for HW CQ, capturing/tracing, replaying/enqueueing a metal MetalGraph 
- [ ] Metal-level unit tests
- [ ] Impact on the allocator and lifetime of Tensors within the MetalGraph (phase 1 is restrictive, to be designed for phase 2)
- [ ] design of the Graph at Metal/ttnn level (phase 3)

**Comment by davorchap** [comment]
@DrJessop has started the design plan for the Metal level support for metal graph. 
Initial implementation is a trace of the content in the HW CQ. So no actual graph support at this point.

It will be done in 3 phases.
Phase 1: @DrJessop Metal HW CQ level impl: capture and reply of the graph cannot be mixed with other dynamic operations (allocs/deallocs, etc). That is, once the graph is captured, we cannot allocate additional tensors.  
Phase 2: architect memory pool in the allocator (low/high watermarks) to allow the MetalGraph to co-exist with dynamic tensors (@abhullar-tt )
Phase 3:  actual graph design @arakhmati

**Comment by DrJessop** [comment]
Closing since @tooniz should have his own issues tracking metal graph/trace.
