### ISSUE TITLE
tt_lib.tensor.imag operation fails with low PCC error [Grayskull]

### ISSUE THREAD

**Issue by JelenaTosicJtosic** [tenstorrent-metal/tt-metal#3554]
**Describe the bug**
**tt_lib.tensor.imag** operation breaks with low PCC error in some test cases. 

**To Reproduce**
1. Run unit test `test_complex_imag.py ` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_complex_imag.py`

**Expected behavior**
There are six test cases presented in the unit test `tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_complex_imag.py` and they all are expected to fail with low PCC error. 
For example, one of the tests is expected to fail with this result: 
` Max ATOL Delta: 200.0, Max RTOL Delta: 117709.2890625, PCC: 0.04657801319009787, Equal check failed`

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for tt_lib.tensor.imag and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_grayskull/pytorch_complex_imag_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `complex_imag_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by umadevimcw** [comment]
@JelenaTosicJtosic and @muthutt Same reason as mentioned here https://github.com/tenstorrent-metal/tt-metal/issues/3559#issuecomment-1871120372

**Comment by tarafdarTT** [comment]
is this the same issue as https://github.com/tenstorrent-metal/tt-metal/issues/4518

**Comment by umadevimcw** [comment]
Yes @tarafdarTT
