### ISSUE TITLE
Running tt_lib.tensor.imag operation makes the program to get stuck [Grayskull]

### ISSUE THREAD

**Issue by JelenaTosicJtosic** [tenstorrent-metal/tt-metal#3557]
**Describe the bug**
Running unit test for ```tt_lib.tensor.imag``` operations makes the program to get stuck.
Operation gets stuck only when L1 is used as output buffer type.

There are two test-cases presented in unit test `test_complex_imag_stuck.py.` The program should get stuck after running the first test case which should break with error like this:
`RuntimeError: TT_ASSERT @ tt_metal/llrt/llrt.cpp:306: run_mailbox_read_val[0] == run_state || run_mailbox_read_val...`

**To Reproduce**
1. Checkout branch `syrmia/complex-ops`
2. Run unit test `test_complex_imag_stuck.py ` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_complex_imag_stuck.py`

**Expected behavior**
Test finishes

**Comment by umadevimcw** [comment]
Not getting this issue in recent main
