### ISSUE TITLE
tt_lib.tensor.complex_abs operation fails with low PCC error [Grayskull]

### ISSUE THREAD

**Issue by banekg** [tenstorrent-metal/tt-metal#3559]
**Describe the bug**
**tt_lib.tensor.complex_abs** operation breaks with low PCC error in some test cases. 

**To Reproduce**
1. Run unit test `test_complex_abs.py ` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_complex_abs.py`

**Expected behavior**
There are eight test cases presented in the unit test `tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_complex_abs.py` and they all are expected to fail with low PCC error. 
For example, one of the tests is expected to fail with this result: 
`Max ATOL Delta: 132.24835205078125, Max RTOL Delta: 211.43600463867188, PCC: 0.07754900249515366, PCC check failed`

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for tt_lib.tensor.complex_abs and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_grayskull/pytorch_complex_abs_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `complex_abs_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by umadevimcw** [comment]
@JelenaTosicJtosic - Unit tests are passing without any issues. For sweep tests the tests fail whenever the last dimension is 448 (example, [1,1,192,448] hence I have reduced the range in yaml file.

@muthutt `split_last_dim_two_chunks_tiled` used in complex type 1 module expected to return a tensor with the first half of dimension with real value and the second half with imaginary value. But when the last dim is 448 it is not working as expected. It is the case for all failed complex operations. Will raise the bug on split dimension with simple test case
