### ISSUE TITLE
document compute_kernel_api/reduce.h (reduce_init, reduce_init_short, reduce_init_delta, reduce_revert_delta) 4 API

### ISSUE THREAD

**Issue by tarafdarTT** [tenstorrent-metal/tt-metal#3586]
https://github.com/tenstorrent-metal/tt-metal/blob/main/tt_metal/include/compute_kernel_api/reduce.h

**Comment by davorchap** [comment]
@tarafdarTT can we close this one?

**Comment by tarafdarTT** [comment]
@davorchap , yup closing now
