### ISSUE TITLE
tt_lib.operations.primary.transformers.scale_mask_softmax_in_place fails with low PCC [Wormhole]

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent-metal/tt-metal#3602]
Operation breaks with low PCC error in most test cases from test sweeps, ranging from very low PCC close to zero (when input values are in range from -100 to 100) to around 0.97 (input values in range from -1 to 1)

**To Reproduce**
1. Checkout `main` branch
2. Run unit test test_eltwise_softmax_in_place.py using the command:  `pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_scale_mask_softmax_in_place.py`
[Same unit as for grayskull]

**Expected behavior**
PCC is expected to be higher
Some of results for inputs BFLOAT16 (tilized inputs):

Max ATOL Delta: 0.41890114545822144, Max RTOL Delta: 10.899720191955566, PCC: 0.9352338132343222, PCC check failed

Max ATOL Delta: 1.0, Max RTOL Delta: nan, PCC: 0.520704372226457, PCC check failed

Max ATOL Delta: 0.06841403990983963, Max RTOL Delta: 7.280715465545654, PCC: 0.6461773923938984, PCC check failed

**Comment by yugaoTT** [comment]
the shapes in the unit test has been tested extensively, problem should be in the unit test itself

**Comment by nemanjagrujic** [comment]
@yugaoTT , @boris-drazic I checked existing unit test (is it `tests/tt_eager/python_api_testing/unit_testing/misc/test_softmax.py`?). 

Here scale seems to be the issues. If you change line 137 to:

```
import random
scale = random.uniform(1.0, 100.0)
```

you will start getting failed unit tests.

Is there any limit on range of `scale` parameter?

**Comment by yugaoTT** [comment]
yes, the scale is too large, it will scale all inputs to 1~100, and e^x will make this value extremely large and produce a wrong result.

**Comment by nemanjagrujic** [comment]
@yugaoTT, @boris-drazic  Maybe something can be done on numerical stability. Check out this annalasys for example:

```
The only accident that might happen is over- or under-flow in the exponentials. Overflow of a single or underflow of all elements of x will render the output more or less useless.

But it is easy to guard against that by using the identity softmax(x) = softmax(x + c) which holds for any scalar c: Subtracting max(x) from x leaves a vector that has only non-positive entries, ruling out overflow and at least one element that is zero ruling out a vanishing denominator (underflow in some but not all entries is harmless).
```

**Comment by nemanjagrujic** [comment]
@yugaoTT , @boris-drazic I think idea is tu subtract max(x). Since softmax(x) = softmax(x  - max(x)) then largest element would be exp(0) which is 1. And adding those up would be numerically stable.

**Comment by yugaoTT** [comment]
@nemanjagrujic could you please close all the issues related to the input range issues for softmax, and then let's create a new issue for stable softmax. Thank you

**Comment by nemanjagrujic** [comment]
Closing this issue since new ticket is created to improve numerical stability of softmax: https://github.com/tenstorrent-metal/tt-metal/issues/7148

**Comment by nemanjagrujic** [comment]
> close all the issues related to the input range issues for softmax, and then let's create a new issue for stable softmax. Thank you

@yugaoTT @boris-drazic 

Done. Here is the new ticket https://github.com/tenstorrent-metal/tt-metal/issues/7148
