### ISSUE TITLE
tt_lib.tensor.imag operation fails with low PCC and Logical Core Bounds Error [Wormhole]

### ISSUE THREAD

**Issue by JelenaTosicJtosic** [tenstorrent-metal/tt-metal#3613]
**Describe the bug**
**tt_lib.tensor.imag** operation breaks with low PCC error and Logical Core Bounds Error in some test cases. 

**To Reproduce**
Run unit test `test_complex_imag.py ` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_complex_imag.py`

**Expected behavior**
There are six test cases presented in the unit test `tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_complex_imag.py` and they all are expected to fail.

- Two of them fail with low PCC error like this:
`Max ATOL Delta: 200.0, Max RTOL Delta: 309911.46875, PCC: 0.048729322186643456, Equal check failed`
- And the rest of them fail with Logical Core Bounds Error like this: 
` RuntimeError: TT_ASSERT @ tt_metal/impl/device/device.cpp:328: (logical_core.x < logical_grid_size.x) and (logical_core.y < logical_grid_size.y) info:
Bounds-Error -- Logical_core={} is outside of logical_grid_size={}
(x=8,y=3)
(x=8,y=9)`

**Note**
Unit test for complex_imag for wormhole has the same code as unit test for GS, so to avoid code duplication we use the same unit to replicate errors on WH.

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for tt_lib.tensor.imag and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_wormhole/pytorch_complex_imag_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `complex_imag_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by umadevimcw** [comment]
Merged to main and logical core issue is fixed by paul in this commit https://github.com/tenstorrent-metal/tt-metal/commit/dd103bca14d6c942ebce4d3f45e8fe585fd5d265
