### ISSUE TITLE
tt_lib.tensor.complex_mul breaks with low PCC and Logical Core - Bounds Error [Wormhole]

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent-metal/tt-metal#3616]
**Describe the bug**
**tt_lib.tensor.complex_mul** operation fails in all test cases on wormhole with PCC and Logical Core Bounds errors.

**To Reproduce**
1. Checkout branch `syrmia/complex-ops`
2. Run unit test `test_complex_mul.py ` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_complex_mul.py`

**Expected behavior**
There are five test cases presented in the unit test `tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_complex_mul.py` and they all are expected to fail.

- First three test cases are breaking with error like this:
`Max ATOL Delta: 1388427.75, Max RTOL Delta: inf, PCC: 0.0049808559787721364, PCC check failed`

- And the last two with: 
`
 RuntimeError: TT_ASSERT @ tt_metal/impl/device/device.cpp:328: (logical_core.x < logical_grid_size.x) and (logical_core.y < logical_grid_size.y)
  info:
Bounds-Error -- Logical_core={} is outside of logical_grid_size={}
(x=9,y=3)
(x=8,y=9)
`

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for tt_lib.tensor.complex_mul and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_wormhole/pytorch_complex_mul_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `complex_mul_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by umadevimcw** [comment]
Merged in to main

**Comment by umadevimcw** [comment]
Logical core bound issued is fixed by the commit by Paul  https://github.com/tenstorrent-metal/tt-metal/commit/dd103bca14d6c942ebce4d3f45e8fe585fd5d265
