### ISSUE TITLE
test_untilize_with_halo_and_max_pool.py non-deterministic PCC with watcher enabled

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent-metal/tt-metal#3625]
`pytest tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_and_max_pool.py`
passes pcc checks when run without watcher, but enabling the watcher causes pcc to be incorrect/non-deterministic.
`TT_METAL_WATCHER=1 pytest tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_and_max_pool.py`

**Comment by davorchap** [comment]
@mywoodstock @chekangliang @pgkeller Maxpool has went through lots of changes based on the new halo infra, and Abhinav is optimizing reader/writer and compute. It would be good to see if we still have the same issue on the new kernel.
Let's discuss today.

**Comment by mywoodstock** [comment]
This particular test is already deprecated, and I haven't seen such issue with the new version. I ran the unit tests in a loop with and without watcher, with FD and SD, didn't see any issues. LMK if you see any.
The new test is: `tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_and_max_pool_v2.py`

**Comment by TT-billteng** [comment]
closing this issue as the old test is deprecated and new test is already part of CI
