### ISSUE TITLE
Sharding utilities cleanup

### ISSUE THREAD

**Issue by TT-BrianLiu** [tenstorrent-metal/tt-metal#3677]
Writing down some TODOs for later:
- [ ] Rename PoolConfig to something more generic to maxpool and convs
- [ ] Rename `get_inout`?
- [ ] Consolidate the S1 and S2 functions into a generic one, after which `get_specs_for_sharding_partition` should be unused
- [ ] `get_shard_specs_with_halo` is unused
- [ ] Clean up unused parameters from `get_inout_shard_specs`. Don't have to delete them from the helper, but kernels should only get ones that are used.

**Comment by mywoodstock** [comment]
This version of UTWH has been deprecated, and replaced by the v2. Closing this.
