### ISSUE TITLE
Reduce tilize-untilize operator in succession in inference pipeline of Mistral

### ISSUE THREAD

**Issue by muthutt** [tenstorrent-metal/tt-metal#3700]
We need to reduce the number of Tile-Untile pairs between end of 1 op and successive op - this is indicated by our profiling data; this can reduce the number of unnecesaary ops in Mistral

ref profiling information at https://docs.google.com/spreadsheets/d/1Wqgr-yZpzANP4KU1kARvS0q_G-KWZ1NAayO1A8llXYI/edit?usp=sharing

**Comment by boris-drazic** [comment]
With the new implementation of mistral this is no longer relevant.
