### ISSUE TITLE
tt_lib.tensor.rmsnorm with no beta and gamma provided breaks with low PCC for BFLOAT8_B input and gets stuck [Wormhole]

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent-metal/tt-metal#3707]
**Describe the bug**
**tt_lib.tensor.rmsnorm** operation in case without beta and gamma tensor provided fails in all combinations of test cases involving BFLOAT8_B type input tensor on Wormhole with low PCC errors. Also, it was noticed that it gets stuck either for larger input dimensions or after low PCC failure, so the next test after the failing one will never be executed. The problem was first noticed in sweep tests, and then reproduced within unit test.

**To Reproduce**
1. Checkout branch `main`
2. Run unit test `test_rmsnorm_noweights.py ` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_rmsnorm_noweights.py`

**Expected behavior**
There are four test cases presented in the unit test `tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_rmsnorm_noweights.py` and the first one is expected to fail. After that, the execution gets stuck.

- The first test case is breaking with error like this:
`Max ATOL Delta: 1.2105675798371893e+20, Max RTOL Delta: inf, PCC: 0.8654571727427982, PCC check failed`

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for tt_lib.tensor.rmsnorm and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_wormholel/pytorch_rmsnorm_noweights_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `rmsnorm_noweights_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by npetrovic-tenstorrent** [comment]
Unfortunately, it still gets stuck and exhibits low PCC for the same test case

**Comment by tt-aho** [comment]
I see this test pass on main. Are you rebased on main after 51b163010a98d3d610b90950bb57e23005f75574?

**Comment by npetrovic-tenstorrent** [comment]
I rebased and confirm that it is now working. Issue can be closed.
