### ISSUE TITLE
tt_lib.tensor.rmsnorm with beta and gamma tensors provided breaks with low PCC for any combination of BFLOAT8_B [Grayskull]

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent-metal/tt-metal#3709]
**Describe the bug**
**tt_lib.tensor.rmsnorm** operation in cases when beta and gamma tensors are provided fails in all combinations of test cases involving BFLOAT8_B type input tensor on Grayskull with low PCC errors.

**To Reproduce**
1. Checkout branch `main`
2. Run unit test `test_rmsnorm.py ` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_rmsnorm.py`

**Expected behavior**
There are four test cases presented in the unit test `tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_rmsnorm.py` and they all are expected to fail.

- These four test cases are breaking with error like this:
` Max ATOL Delta: 27.281375885009766, Max RTOL Delta: inf, PCC: -0.04282729783298479, PCC check failed`

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for tt_lib.tensor.rmsnorm and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_grayskull/pytorch_rmsnorm_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `rmsnorm_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by tt-aho** [comment]
Please retry on latest. I've updated mixed precision support for rmsnorm

**Comment by npetrovic-tenstorrent** [comment]
Confirm it is resolved

**Comment by yugaoTT** [comment]
@npetrovic-tenstorrent I'll close it
