### ISSUE TITLE
[Review Request] Review Tracker for Microbenchmark and new custom operators  

### ISSUE THREAD

**Issue by chekangliang** [tenstorrent-metal/tt-metal#3728]
PR(s) #3644 and #3060 Requires review from TT teams. This is the master issue to track reviews of key deliverables from Moreh at the end of Q3. The issue will decompose to sub-issues, each representing a logically 

#3644 - Moreh Ops for 2023 3Q
- [x] #3729
- [x] #3730
- [x] #3731
- [x] #3732
- [x] #3733
- [ ] #3734

#3060 - Add microbenchmarks covering SoW (Moreh, TT)

- [ ] #3735
- [ ] #3736
- [ ] #3737
- [ ] #3738
- [ ] #3739

Given the scope of the review, let's target need-by date to be 11/27 for reference, await the team's prioritization to confirm. 

@razorback3 @mywoodstock

**Comment by razorback3** [comment]
@jliangTT
I think we can close this issue as completed because
1. all the above Moreh ops are merged to the main
2. microbenchmarks are reviewed and in the stage of optimization by Metal team

How do you think?

**Comment by jliangTT** [comment]
yes we can close this. this makes sense.
