### ISSUE TITLE
Investigate infrastructure needed to support Galaxy development

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent-metal/tt-metal#3762]
Preliminary issue for CI, installation requirements, FW and tool requirements etc.

**Comment by TT-billteng** [comment]
@vtangTT

**Comment by aliuTT** [comment]
Fyi, I logged on a few days ago and installed all the missing stuff. I can build tt-metal on the machine now

**Comment by tt-rkim** [comment]
Moving in favour of internal workflows issue
