### ISSUE TITLE
[On Hold] Mistral GS Demo Benchmarking

### ISSUE THREAD

**Issue by saichandax** [tenstorrent-metal/tt-metal#3779]
GS e2e Demo

test uses batched real inputs and produces batched outputs

this test is looped (takes several batches of inputs, produces several batches of outputs)

test evaluates results of TT model against validation data in selected data set

test is documented

how to run test (commands to execute)
what does the model do (high-level explanation in a couple of sentences)
description of what is input and what is output
this demo should load inputs and expected outputs from a data set on Weka (TBD which one)

**Comment by saichandax** [comment]
This PR is on hold until issue with Cache (https://github.com/tenstorrent-metal/tt-metal/issues/4344) is resolved.

**Comment by boris-drazic** [comment]
With the new implementation of mistral this is no longer needed.
