### ISSUE TITLE
Optimize LLK untilize speed for GS

### ISSUE THREAD

**Issue by davorchap** [tenstorrent-metal/tt-metal#3786]
* GS is higher priority since we are first doing 10,000 fps ResNet50 on GS

Options per @acejkov 
1) If inputs can be non bfp format (assuming we can convert to non - bfp before untilize) and there is no header we can use strided reads the sam way we use for tilizer
2) we can do tile unpack and then use packer to assemble 8 (half sync) or 16 (full sync) 32x(8x32) untilized blocks in l1. We can then use data movement to untilize between blocks. 
 is that a valid option?
3) we can do 2. but reprogram packer to untilize entire output. There will be some overhead and I’m not sure we can achieve 12B/c. With 1&2 we can but if data movement is not a bottleneck. 
Modifying existing solution won’t yield much perf gain

@davorchap: Option 2 would be a good option. Packer can untilize a block of 32x256 (half dst 8 tiles) in one shot (1 tile height, 8 tiles width), and then if block is say 256x256 , then we can loop this 32x256 eight times, or if 512x256, we loop 16 times 
If we keep the block width constant (say 256) during untilize with packer, and just stride down the height of the block.
We can keep max width to say 256 w/ half dst, and then via NOC we can concatenate to larger widths, but we do need to be able to loop across the height of the block.

@acejkov:
I think we can run that at full packer speed. Looping for height won’t be an issue, basically we are building 32x256 blocks on top of each other which requires minimal reprogramming.

Option 2 is the plan.

**Comment by mywoodstock** [comment]
@acejkov I believe this can be closed?

**Comment by nsmithtt** [comment]
Closing, this has been done
