### ISSUE TITLE
Use tilized operators for Mistral AI speedup on inference

### ISSUE THREAD

**Issue by muthutt** [tenstorrent-metal/tt-metal#3812]
- use tilized operators for Mistral AI migrate from row-major
- tilized tensors are faster on GS/WH TT Tensix cores
- use the tt_lib.tensor.tilize_with_val_padding when necessary

Reference: [https://github.com/tenstorrent-metal/tt-metal/tree/a3740def58c3b8672b7e3279261506ae70b97810/models/demos/resnet/tt
/metalResnetBlock50.py](https://github.com/tenstorrent-metal/tt-metal/blob/main/models/demos/resnet/tt/metalResnetBlock50.py)

**Comment by Sudharsan-V** [comment]
The commit is reverted to preserve the sensible output.
Corresponding PR: https://github.com/tenstorrent-metal/tt-metal/pull/4029
