### ISSUE TITLE
Resnet 50 host behaviour after multiple back to back runs

### ISSUE THREAD

**Issue by mo-tenstorrent** [tenstorrent-metal/tt-metal#3839]
**Summary**

The cached inference run of resnet 50 was looped to see if host behaviour will reach a steady state in 2nd or higher iterations of the loop. 

Higher iterations did not help and the variations in duration of the inference runs were random. 

These variation are most likely coming from HW and low level OS behaviours that are randomly elongating our host side durations.  

So next step would be to try to run the test on a dirt box machine under our control where we can turn ethernet off and such. That will also allow us to avoid weka and the 2 package CPU setup as well. 2 package CPU can be the culprit here as only one CPU is physically connected to the PCIe device but linux sees 1 pool of CPU cores.

**Details**

The following was the modified looped code, instrumented with tracy marks for better visibility. 

<img width="363" alt="Screenshot 2023-11-16 at 5 38 12 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/109363418/b61f6790-f226-4bf3-9056-1793ec004162">

`pytest models/demos/resnet/tests/test_perf_resnet.py::test_perf_bare_metal[8-0.02-28]` was used to run the test off of latest on main on commit `1a02e2a10ac5`

test branch : `mo/resnet_perf`

The following is an example of one run:

<img width="1655" alt="Screenshot 2023-11-16 at 5 53 03 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/109363418/cc48bc01-7c29-427c-9492-67b7441616d2">

`OP Run` between `to` and `cpu` is the parent to call to all OP call. 

Runs with 1000 iterations were done to observe the various hiccups that we have observed randomly.

**Particular to `OP Run` you can see from the histogram below that almost all of the runs are within a 2 ms band from as low as 4ms to as high as 6ms. There are few outliers as high as 10ms.** 
 
<img width="1475" alt="Screenshot 2023-11-16 at 5 59 14 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/109363418/4754a19a-afe8-4a3a-9c14-76b31caa4b88">

In general `to`, `cpu` and `pre processor` saw a variability of 2-3 ms each. 

These variation are most likely coming from HW and low level OS behaviours that are randomly elongating our host side durations.  

`nice` and `taskset` were used to set priority and core affinity respectively but no improvement was observed. 

The 200us dead gap was also caught and it is demonstrated in the gif below

![tracy_resnet](https://github.com/tenstorrent-metal/tt-metal/assets/109363418/b17f359e-16ea-47cf-a1f6-5489f68c554c)

With multiple runs of cached inference, I was able to catch the dead spot mentioned. As demonstrated in the gif above, it happens between a Matmul and an eltwise binary this time and it is under the pybind python call.

**Comment by tt-rkim** [comment]
@mo-tenstorrent @TT-billteng @davorchap 
Closing this , and people can refer to this in other places if needed
