### ISSUE TITLE
hang running test_composite.py with watcher enabled (in cb_wait_front)

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent-metal/tt-metal#3856]
See also: #3832

On Grayskull, running the following in a loop:
    pytest tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_composite.py::test_run_eltwise_composite_test
in subtest:
tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_composite.py::test_run_eltwise_composite_test[log1p-input_shapes15]

with:
    export TT_METAL_WATCHER=10ms

the test hung after ~2500 iterations.  The relevant watcher info is:

Core (x=1,y=1):    CWFW,W,WPCD,D,D rmsg:D0G|BNT smsg:GGGG k_ids:196|195|197
Core (x=2,y=1):    GW,W,W,W,W rmsg:D0D|BNT smsg:DDDD k_ids:196|195|197
... (all the other workers are identical to 2,1 - ie, done)
Core (x=1,y=11):   NRBD,W,W,W,W rmsg:H0G|Bnt smsg:DDDD k_ids:193|0|0
Core (x=7,y=11):   QW,W,W,W,W rmsg:H0G|Bnt smsg:DDDD k_ids:193|0|0

k_id[193]: tt_metal/impl/dispatch/kernels/command_queue_producer.cpp
k_id[195]: tt_eager/tt_dnn/kernels/dataflow/reader_bcast_hw_interleaved_partitioned.cpp
k_id[196]: tt_eager/tt_dnn/kernels/dataflow/writer_unary_interleaved_start_id.cpp

Looks like the problem is on core 1,1:
 - brisc is in cb_wait_front
 - ncrisc ncrisc either was never started or has completed
 - unpacker last hit wait_for_pack_config_done and is done w/ that - question is where is it stalled?
 - math and packer are done

**Comment by TT-billteng** [comment]
This now passes with watcher enabled!! https://github.com/tenstorrent-metal/tt-metal/actions/runs/7441497962
