### ISSUE TITLE
backward op for tan

### ISSUE THREAD

**Issue by muthutt** [tenstorrent-metal/tt-metal#3898]
backward op for tan

**Comment by VirdhatchaniKN** [comment]
Tan Op :
Issue : [Link](https://github.com/tenstorrent-metal/tt-metal/issues/3898)
PR : [Link](https://github.com/tenstorrent-metal/tt-metal/pull/4030)
Commit : [Link](https://github.com/tenstorrent-metal/tt-metal/pull/4030/commits/7422587990503ffba77e266df406fcf67e8282b8)
