### ISSUE TITLE
Conv optimizations to improve perf/memory usage

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent-metal/tt-metal#3936]
- [x] #3538 Block based apis
- [ ] No spill
- [ ] Full dst
- [x] 1d height blocking support
- [x] Don't reread weights when height blocking
- [x] Reduce cb syncs

**Comment by tt-aho** [comment]
I don't really think this is currently being looked at/relevant anymore. Can close this issue and create new individual ones if they come up again.

**Comment by nsmithtt** [comment]
Thanks @tt-aho ! Closing, we can create new individual ones if they come up again
