### ISSUE TITLE
Investigate non-deterministic metal BERT output mismatches on CI

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent-metal/tt-metal#3961]
We are seeing metal BERT mismatches in frequent pipeline: https://github.com/tenstorrent-metal/tt-metal/actions/runs/6953525002/job/18918791714

Haven't seen this before yesterday personally.

**Comment by davorchap** [comment]
@tt-rkim is this still an issue?

**Comment by tt-rkim** [comment]
Not in a while, let's close and reopen if we see again.
