### ISSUE TITLE
WATCHER user feedback

### ISSUE THREAD

**Issue by mbahnasTT** [tenstorrent-metal/tt-metal#3969]
Overall feedback is positive and no blocker for project GS release. Thanks, Paul!
I was able to generate device status message log file using one synthesized hanging issue.
Next comment has a list of explanations that I'd like to understand so I can support the tool. 

![Image](https://github.com/tenstorrent-metal/tt-metal/assets/116673264/a246cdaa-f53c-400e-b464-2ccf65762a59)

![Image](https://github.com/tenstorrent-metal/tt-metal/assets/116673264/0c51d89a-61df-4621-b440-d4d2f95e205d)

**Comment by pgkeller** [comment]
Closing

**Comment by mbahnasTT** [comment]
Thanks @pgkeller , it looks very good and covered all feedback points.
