### ISSUE TITLE
[Resnet perf] accuracy run is failing

### ISSUE THREAD

**Issue by mbahnasTT** [tenstorrent-metal/tt-metal#3980]
Resnet perf failing test:
models/demos/resnet/tests/test_perf_accuracy_resnet.py:105: IndexError
FAILED models/demos/resnet/tests/test_perf_accuracy_resnet.py::test_perf_bare_metal[16-0.225-33-160] - IndexError: list index out of range

**Comment by farbabi** [comment]
It was due to unmounted weka. fixed.
