### ISSUE TITLE
GS  fast dispatch Stress test hangs

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent-metal/tt-metal#4023]
1st iteration, tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_permute.py::test_run_permute_test[input_shapes372-permute_args372]

https://github.com/tenstorrent-metal/tt-metal/actions/runs/6993316550/job/19025857058

4th iteration,
tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_eltwise_unary.py::TestEltwiseUnary::test_run_eltwise_log_sigmoid_op[output_mem_config0-input_mem_config0-input_shapes0] 

https://github.com/tenstorrent-metal/tt-metal/actions/runs/6976730053/job/18985573705

15th iteration,
tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_eltwise_unary.py::TestEltwiseUnary::test_run_eltwise_log_sigmoid_op[output_mem_config0-input_mem_config0-input_shapes0]

https://github.com/tenstorrent-metal/tt-metal/actions/runs/6952732603/job/18916769015

3rd iteration,
tests/tt_eager/python_api_testing/unit_testing/test_max_pool.py::test_run_max_pool[True-8-out_L1-in_L1-dilation0-stride1-padding0-kernel_size0-act_shape5]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/6925385763/job/18835968664

7th iteration,
tests/tt_eager/python_api_testing/unit_testing/test_update_cache.py::TestUpdateCache::test_update_cache_and_slice_decode[127-64-2048-64]

https://github.com/tenstorrent-metal/tt-metal/actions/runs/6911705590/job/18806564750

**Comment by jliangTT** [comment]
@TT-billteng @pgkeller , can we update if the status on this given our recent progress?

**Comment by TT-billteng** [comment]
With some tests disabled on my watcher CI branch (see `bteng/watcher_ci`) + UMD fix, 24h FD stress test passed! 

https://github.com/tenstorrent-metal/tt-metal/actions/runs/7271307725
