### ISSUE TITLE
tt_lib.tensor.power_fp fails with low PCC [Grayskull] 

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent-metal/tt-metal#4027]
**Describe the bug**
**tt_lib.tensor.power_fp** exhibits low PCC failure.

**To Reproduce**
1. Checkout branch ` npetrovic/power-fp-unit`
2. Run unit test `test_power_fp.py ` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_power_fp.py`

**Expected behavior**
There are three test cases presented in the unit test `tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_power_fp.py` and they all are expected to fail.

- These three test cases are breaking with error like this:
`Max ATOL Delta: nan, Max RTOL Delta: nan, PCC: 0.8068043771920167, PCC check failed`

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for tt_lib.tensor.power_fp and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_grayskull/pytorch_eltwise_power_fp_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `eltwise_power_fp_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by umadevimcw** [comment]
@muthutt @npetrovic-tenstorrent Issue is fixed and it is passing for GS 
commit : 1e7752f99c6f591b07a2e46d6e2a1a12e4e573b2 branch: `umadevimcw/merge_power_op`
