### ISSUE TITLE
Re-factor stress test bash function to get suite_duration from a first run, rather than a hardcoded value

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent-metal/tt-metal#4039]
Per @TT-billteng 's advice, instead of hardcoding the suite duration value of post-commit which can change over time, we will need to make it dynamic by first getting the value from a first run.

**Comment by TT-billteng** [comment]
fixed https://github.com/tenstorrent-metal/tt-metal/commit/e6282dcec6aab4b0f3915ceb71140e064c9fd3cd
