### ISSUE TITLE
[Bug Report] Zero-sized noc transaction from unreserved base in test_untilize_with_halo_and_max_pool on GS

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent-metal/tt-metal#4084]
**Describe the bug**
Running `TT_METAL_WATCHER=1 pytest tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_and_max_pool.py` on main results in 

```
On core (x=1,y=1): noc0:brisc{(01,01) 0x0001e000, 0}
```

**Expected behavior**
Should not be seeing a 0-sized noc transactions

**Comment by mywoodstock** [comment]
I have deprecated this version, and is replaced by new UTWH and maxpool. Once the resnet branch and `jedi_main` is merged to `main`, we'll have the latest version.
