### ISSUE TITLE
Add spec for how to enable multiple HW command queues for Galaxy

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent-metal/tt-metal#4087]
When initializing UMD, we can configure the number of host memory channels per MMIO device. This value is 1:1 with the number of hugepages. 

For N300 we will set `num_host_mem_ch_per_mmio_device = 2`, which gives us two hugepages (one for each device). 

This doesn't scale to Galaxy because each MMIO device can have a maximum of 4 hugepages. 

FYI @aliuTT @davorchap

**Comment by tt-rkim** [comment]
For context: we originally tried re-provisioning our WH machines with 4 HPs per mmio, but we were running into crashes/Out of mem exceptions, specifically when running falcon on the models pipeline. Lowering it to 2 helped, but it isn't necessarily stable: https://github.com/tenstorrent-metal/tt-metal/issues/4425

**Comment by abhullar-tt** [comment]
Closing this because it is a duplicate of #4211
