### ISSUE TITLE
Fix env var export for unit tests

### ISSUE THREAD

**Issue by JelenaTosicJtosic** [tenstorrent-metal/tt-metal#4121]
Fix exporting TT_METAL_SLOW_DISPATCH_MODE environment var in `tests/tt_eager/python_api_testing/sweep_tests/common.py` to fix issue within unit tests.

**Comment by nemanjagrujic** [comment]
https://github.com/tenstorrent-metal/tt-metal/commit/fb92cb3a45809779cac0b1f94a2e068c1971dafb
