### ISSUE TITLE
Investigate deterministic hangs in WH frequent models pipelines (both SD FD)

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent-metal/tt-metal#4122]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7040766725/job/19162249783
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7042681847/job/19167219245
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7054516505/job/19203503627

And a newer issue: https://github.com/tenstorrent-metal/tt-metal/actions/runs/7056443656/job/19208434790

**Comment by farbabi** [comment]
> Right, @farbabi can you try running the full demo test after the slow dispatch python api unit tests? From my own experiments, there seems to something in that suite leaving the machine in a weird state.

No errors was observed after running the full demo test after slow dispatch unit tests.

**Comment by tt-rkim** [comment]
@farbabi How many times did you attempt this in a loop? It may require more than 1.

**Comment by farbabi** [comment]
> @farbabi How many times did you attempt this in a loop? It may require more than 1.

I ran 5 times; each time python_api_tests.sh and gs_demo_wteacher.py back to back. on WH VM, with SD on. All passed.

**Comment by tt-rkim** [comment]
Can we try the full models script?

**Comment by tt-rkim** [comment]
Another instance of the issue on deit: https://github.com/tenstorrent-metal/tt-metal/actions/runs/7261004535/job/19781313523

**Comment by tt-rkim** [comment]
As evidenced above, we're seeing this on FD now too: https://github.com/tenstorrent-metal/tt-metal/actions/runs/7254382698/job/19762994534

Updated title

**Comment by tt-rkim** [comment]
screenshot because logs expired
![image](https://github.com/tenstorrent-metal/tt-metal/assets/109366641/26ac53fc-05a9-4b41-a509-e30fb30ed728)

**Comment by farbabi** [comment]
> Can we try the full models script?

Full unit tests and full models were run 5 times back to back, once for SD once for FD. All passed. Is this machine dependant?

**Comment by tt-rkim** [comment]
Do you want to try logging into a CI machine and trying?
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7457295706/job/20289267737

**Comment by tt-rkim** [comment]
We're still seeing this on pipelines.

**Comment by farbabi** [comment]
I completed 10 iterations, unit tests and models, FD and SD, all passed (VM). I will need one of the BMs that's showing this behaviour to do further tests.

**Comment by tt-rkim** [comment]
@farbabi We discussed previously in private Slack that this is our only WH perf and we're quite tight on WH BMs right now.

Could you please borrow another `e04cs04` or `e04cs05` per the BM machine sharing spreadsheet and try your tests there? That should be our next step, as those machines should be essentially identical to the perf machine.

**Comment by TT-billteng** [comment]
nightly pipeline looks clean, thanks @tt-rkim
