### ISSUE TITLE
Falcon 40B on 2x/3x/4x N300 system

### ISSUE THREAD

**Issue by davorchap** [tenstorrent-metal/tt-metal#4142]
This is a top-level case.

UMD:
- [x] #4146
- [ ] #4329

Ethernet FW: 
- [ ] #4145 

Metal features:
- [x] #2372 
- [x] #2371 

Metal OPs:
- [x] #4143  
- [ ] #4144 
- [x] #4148

**Comment by aliuTT** [comment]
Added a cluster op issue to top level. I'm thinking we create this concept of a cluster op that launches one thread per device used in an op that spans two multiple devices. I.e. ring gather on four chips, or send/receive on two chips. @davorchap

**Comment by davorchap** [comment]
completed!
