### ISSUE TITLE
Send/recieve interleaved buffers between L and R on N300 (impl and unit tests)

### ISSUE THREAD

**Issue by davorchap** [tenstorrent-metal/tt-metal#4143]

**Comment by aliuTT** [comment]
This issue will include fixes for the arrays not defined problem: https://github.com/tenstorrent-metal/tt-metal/issues/4253

**Comment by aliuTT** [comment]
Basic sending buffers working on `aliu/load-base-erisc`, which has a rework of the erisc FW compile and loading, which fixes the mysterious bug @tt-aho discovered where some included addrs are not actually defined... @tt-aho, I took your test fixes from `aho/noc-erisc` and tried the new tests. BTW I changed the usage of MAX_L1_LOADING_SIZE. That isn't the free L1 space. MAX useable L1 is actually `eth_l1_mem::address_map::MAX_L1_LOADING_SIZE - eth_l1_mem::address_map::ERISC_L1_UNRESERVED_BASE`. So now on that branch, default test_config and 
```
test_config = BankedConfig{.num_pages = 200, .size_bytes = 200 * 2 * 32 * 32, .page_size_bytes = 2 * 32 * 32};
``` 
are passing. This one is causing hangs: 
```
 test_config = BankedConfig{
            .num_pages = 200,
            .size_bytes = 200 * 2 * 32 * 32,
            .page_size_bytes = 2 * 32 * 32,
            .input_buffer_type = BufferType::DRAM,
            .output_buffer_type = BufferType::DRAM};
```
We can debug on monday

**Comment by davorchap** [comment]
We're getting there!!

**Comment by aliuTT** [comment]
Hang seen when trying to read from dram banks. I narrowed the issue down to a bad noc addr being retrieved from the `dram_bank_to_noc_xy[noc_index][bank_id]`. Weirdly only the first two entries in the mapping is wrong, asked Paul for help...

**Comment by aliuTT** [comment]
@davorchap all interleaved tests passing on all chips on `t3002`: https://github.com/tenstorrent-metal/tt-metal/pull/4394/files

**Comment by davorchap** [comment]
> @davorchap all interleaved tests passing on all chips on `t3002`: https://github.com/tenstorrent-metal/tt-metal/pull/4394/files

That's great!
On all links, even QSFP?

**Comment by aliuTT** [comment]
Yes :)

**Comment by aliuTT** [comment]
Send/Receive interleaved buffer tests and features now in main

**Comment by aliuTT** [comment]
closing this issue
