### ISSUE TITLE
[Bug Report] Process tear-down on machine with two N150s

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent-metal/tt-metal#4176]
In CreateDevice, we see the following error

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  TT_THROW @ tt_metal/impl/device/device.cpp:28: tt::exception
info:
Process tear down with device {} still active
0
```

Run any device test on this machine: 172.27.28.71 to reproduce.

**Comment by aliuTT** [comment]
debugging segfault seen with umd logger changes: https://github.com/tenstorrent-metal/tt-metal/issues/4271

**Comment by chekangliang** [comment]
@aliuTT, is this a P0 showstopper? who is being blocked?

**Comment by aliuTT** [comment]
We need a few commits from umd main to make sure our dev flow works on some multi card machines. I was seeing BM 71 crapping out. afaik, Andrew was seeing some issues with GS machines as well, but we have work arounds to pick up commits locally, so maybe we can downgrade to P1? In any case, we found the issues with the umd uplift, I should have a sweep of CI today. Hopefully we can get this done end of day

**Comment by chekangliang** [comment]
Ok. Sounds good

**Comment by DrJessop** [comment]
Hey @aliuTT , I am still seeing a device set up error on 172.27.28.71 with the latest UMD. The error is the following 

```
C++ exception with description "_Map_base::at" thrown in SetUp().
```
