### ISSUE TITLE
Watcher support for n300

### ISSUE THREAD

**Issue by aliuTT** [tenstorrent-metal/tt-metal#4210]
I think there are separate buckets of work:
- Testing watcher running on the remote device without any ethernet kernels loaded.
- This should probably just work as long as there are no weird race conditions with remote transfers

The other set of work is:
- Having watcher also monitor ethernet cores/kernels, this will likely be blocked by this issue: https://github.com/tenstorrent-metal/tt-metal/issues/3547

**Comment by tt-dma** [comment]
Issue #4756 adds CI testing for watcher on worker cores, everything appears to run fine for watcher on worker cores for remote device on n300. Remaining tasks for this:

- [ ] When fast dispatch on remote device in, update watcher sanitization test to run on remote device - currently the test only runs on fast dispatch and therefore not on the remote device (I have verified manually that this feature still works on remote device using slow dispatch however)
- [ ] Add watcher support for ethernet cores

**Comment by tt-dma** [comment]
All child issues closed now
