### ISSUE TITLE
DPRINT + SD/FD + Multichip

### ISSUE THREAD

**Issue by aliuTT** [tenstorrent-metal/tt-metal#4214]
Dprint starts one server per Device. It then tries to manage any number of chip ids. How does this work when there are many Devices created? Do we create a dprint server per Device object?

apis to look at:
- `tt_start_debug_print_server`
- `DebugPrintServerContext` which manages a `chip_ids` vector

**Comment by tt-dma** [comment]
PRs https://github.com/tenstorrent-metal/tt-metal/pull/4480 + https://github.com/tenstorrent-metal/tt-metal/pull/4401 add support + testing for this. The implementation is to run a single DPRINT server and then attach/detach devices individually. Both PRs are approved and merged, and things appear to be working, so closing this.
