### ISSUE TITLE
Investigate stagnant clock speeds despite using software stack on GS/WH

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent-metal/tt-metal#4234]
@mbahnasTT ran into an issue on his machine after tt-kmd update where the device clock was running at ~250MHz, which is why he was seeing really poor perf on resnet. We should not allow this to happen in metal unless the user provides some explicit override.

**Comment by davorchap** [comment]
fyi @chekangliang 
It would probably be useful to at  least emit a warning if we're running at a really low frequency , i.e. < 800 MHz .
This could be done on Metal side.
