### ISSUE TITLE
[ttnn ops Docs some example ops generate errors] 

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent-metal/tt-metal#4267]
**Describe the bug**
some of the ops examples included in TTNN documentation [https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/operations.html](url) generate errors both building from main and building via v-38 release. it seems like docs are not synced with latest code changes, 

**To Reproduce**
1. build from **main**
2. git checkout dvartanians/ttnn_ops
3. launch a jupyter notebook and open ttnn/tutorials/ttnn_ops.ipynb
4. test cells and you will see errors when running mtx @ vec & vec @ vec muls. 
5. **building from v38**, there is error with deallocator op in addition to mtx @ vec mul ops. 

**Expected behavior**
no errors should be generated and documentation should match the release or have notes regarding compatibility with what release ... 

**Screenshots**

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- branch: dvartanians/ttnn_ops: commit 3e1ac423c27eb9b1c831eef20aa259305310c8e8

**Additional context**
![Screenshot 2023-12-08 at 3 27 06 PM](https://github.com/tenstorrent-metal/tt-metal/assets/132954887/97c2ddab-3047-4fe0-a0d0-31fa8561f8f5)
![Screenshot 2023-12-08 at 3 28 40 PM](https://github.com/tenstorrent-metal/tt-metal/assets/132954887/bf260d8b-bf72-4d1d-a217-13558edda169)
![Screenshot 2023-12-08 at 3 29 38 PM](https://github.com/tenstorrent-metal/tt-metal/assets/132954887/aa5b54dc-16fc-4c69-8bc1-3dc00b773943)
![Screenshot 2023-12-08 at 3 31 38 PM](https://github.com/tenstorrent-metal/tt-metal/assets/132954887/89905f7d-6467-422c-ae64-23742ace1df3)
![Screenshot 2023-12-08 at 3 32 17 PM](https://github.com/tenstorrent-metal/tt-metal/assets/132954887/6da86cca-41a5-4aac-9cbe-3803981780b2)
![Screenshot 2023-12-08 at 4 49 58 PM](https://github.com/tenstorrent-metal/tt-metal/assets/132954887/7b41a341-849e-47f2-ad0b-835851b76f1c)

**Comment by tt-rkim** [comment]
@arakhmati @eyonland could you give us some insight here?

**Comment by arakhmati** [comment]
@tt-rkim we are going to resolve these issues as soon as we finish writing whisper and t5 using ttnn
