### ISSUE TITLE
Backward op support for binary assign

### ISSUE THREAD

**Issue by umadevimcw** [tenstorrent-metal/tt-metal#4283]
- Backward op support for binary assign

**Comment by VirdhatchaniKN** [comment]
Issue : [Link](https://github.com/tenstorrent-metal/tt-metal/issues/4283)
PR : [Link](https://github.com/tenstorrent-metal/tt-metal/pull/4313)
Commit : [Link](https://github.com/tenstorrent-metal/tt-metal/pull/4313/commits/7df5b65c7a472335c173b0247422753264960f1e)
CI : [Link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/7194325922)
