### ISSUE TITLE
Binary minimum - Backward

### ISSUE THREAD

**Issue by umadevimcw** [tenstorrent-metal/tt-metal#4284]
Backward op support for binary minimum

**Comment by VirdhatchaniKN** [comment]
Backward support for min op
- changed where op used in max op

Issue : [Link](https://github.com/tenstorrent-metal/tt-metal/issues/4284)
PR : [Link](https://github.com/tenstorrent-metal/tt-metal/pull/4293)
Commit : [Link](https://github.com/tenstorrent-metal/tt-metal/pull/4293/commits/df956c92596862b6ecf6f2a2ff9f4aa3fcd0060a)
CI : [Link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/7194014953)
