### ISSUE TITLE
Remove "If you have ideas you would like to bounce off others in the community before formally proposing it, you can make a post in the ideas discussions page."  --- The link here doesn't work. Maybe we can remove this line , its under comms section

### ISSUE THREAD

**Issue by chekangliang** [tenstorrent-metal/tt-metal#4301]
The link here doesn't work. Maybe we can remove this line, its under comms section here - https://github.com/tenstorrent-metal/tt-metal?tab=readme-ov-file#communication

**Comment by tt-rkim** [comment]
@Shubhamsaboo 

You can access as a non-authorized user, correct?: https://github.com/tenstorrent-metal/tt-metal/discussions/categories/general-announcements

This is the new location. We can change this work to use this link instead, or we could get rid of GitHub discussions all together if you think it's too much.

I invite input from @chekangliang .

**Comment by chekangliang** [comment]
I elect that we update the link as this was something we talked about as a place to have technical discussion

**Comment by Shubhamsaboo** [comment]
I am fine either ways, if we completely remove this section or change it to a working link.

**Comment by tt-rkim** [comment]
This is done. Thank you both
