### ISSUE TITLE
Remove any mention of harvested or unharvested (like this line: At least 1 unharvested E150 attached to a PCIe x16 slot). We don't want the customers to be confused about harvested and unharvested cards.

### ISSUE THREAD

**Issue by chekangliang** [tenstorrent-metal/tt-metal#4302]

**Comment by jliangTT** [comment]
@tt-rkim , anything input on this one? the thoughts from the product side is that that this verbiage is not there when we sell the card online. 

maybe we can move this to the developer section?

**Comment by tt-rkim** [comment]
Sure - let me take that out.

We are okay if we mention it in the developers section OF the front page readme?
