### ISSUE TITLE
Remove any mention of Wormhole as it isn't released yet and we aren't communicating anything to customers apart from GS (there are a few instances where WH is mentioned in the readme)

### ISSUE THREAD

**Issue by chekangliang** [tenstorrent-metal/tt-metal#4303]

**Comment by tt-rkim** [comment]
@chekangliang @Shubhamsaboo 

I heard there were similar complaints about Buda's documentation.

I'm not sure how to reconcile this as there are actual TT developers who read the README and CONTRIBUTING who use WH.

We could potentially put wording such as "For other architectures, please refer to this internal webpage", but that's about it.

Note that getting rid of WH references in anything code or API documentation is almost impossible / non-negotiable, so pls don't consider that on the table.

**Comment by tt-rkim** [comment]
I discussed with @milank94 , and we're going to push back on the initial request, and ask that we think of some alternatives to not confuse customers but sensibly work on WH in the same repo.

**Comment by jliangTT** [comment]
after the conversation with @Shubhamsaboo and given the input from Buda/Metal , i think the current position is okay. closing
