### ISSUE TITLE
Data mismatch when running full link testing

### ISSUE THREAD

**Issue by aliuTT** [tenstorrent-metal/tt-metal#4329]
When sweeping full eth links with direct send test, seeing a mismatch non-deterministically when sending to a PCI device. It looks like the test's clearing of result buffer is happening after test is finished.

Repro (most reproducible on dirtbox 1):
- `git checkout aliu/load-base-erisc`
- `TT_METAL_SLOW_DISPATCH_MODE=1 ./build/test/tt_metal/unit_tests --gtest_filter="DeviceFixture.EthKernelsDirectSendAllConnectedChips"`

**Comment by davorchap** [comment]
completed
