### ISSUE TITLE
Use tilized operators for VGG model to speedup the Inference:

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent-metal/tt-metal#4346]
- Tilized tensors are faster on Gray-skull TT Tensix cores.
- Change the layout of all the tensors from Row-major to TILE to enable the functionality of the operators in the TILE layout.
- Use padding and unpadding when necessary.

Reference: https://github.com/tenstorrent-metal/tt-metal/tree/sudharsan/tilize_mistral_model/models/experimental/mistral

**Comment by jayasuryamaganuru** [comment]
commit for uplifting VGG model, 
storing Linear weight tensors as TT tensors on weka in TILE layout - #4346

**Comment by jayasuryamaganuru** [comment]
@Sudharsan-V merged to main
