### ISSUE TITLE
Move VGG tensors to L1

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent-metal/tt-metal#4347]
-  store all intermedaite tensors of the VGG model in L1 Cache.
-  store all weights in L1 (if they fit).

**Comment by kkeerthana0573** [comment]
- moved the intermediate tensors to L1 cache
- removed passing state_dict to TtVGG and its variants

**Comment by kkeerthana0573** [comment]
- enabled support for batch_size > 1
- unable to move linear and relu layers to L1 cache for batch size 32 ( Out of Memory: Not enough space to allocate )

**Comment by saichandax** [comment]
PR approved, and waiting for CI to pass.

**Comment by Sudharsan-V** [comment]
The PR is merged with the main.
