### ISSUE TITLE
BERT-Tiny with TTNN

### ISSUE THREAD

**Issue by boris-drazic** [tenstorrent-metal/tt-metal#4352]
Implement BERT Tiny using instructions from https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/about.html

**Comment by Sudharsan-V** [comment]
The sub-modules attention, intermediate, and output are implemented using ttnn.
Corresponding [commit](https://github.com/tenstorrent-metal/tt-metal/commit/a66a38ae6833c3ce27c295bb3a10d85d1c607744)

Note: When the ttnn tensor in the TILE layout is converted to a torch tensor, the pcc is reduced. Therefore the layout of the ttnn tensor is changed to ROWMAJOR before converting it into torch.

**Comment by Sudharsan-V** [comment]
The Bert-tiny model is completed using ttnn ops.
Corresponding [commit](https://github.com/tenstorrent-metal/tt-metal/commit/5c9d59864009dd22ae1906c37c1697a2e026bd36)

**Comment by Sudharsan-V** [comment]
The CI tests for PR https://github.com/tenstorrent-metal/tt-metal/pull/4507 and https://github.com/tenstorrent-metal/tt-metal/pull/4508 were successful. Hence it is merged with the main.
