### ISSUE TITLE
Wrong input argument description for tt_lib.tensor.embeddings in documentation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent-metal/tt-metal#4354]
It was noticed that arguments for this operation were changed. 

In documentation: 
https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/dependencies/tt_lib.html#tt-lib-api-through-tt-lib

It is written the following for the input tensor:
Each element greater than 0 and less than number of embeddings in table. Shape [batch_size, 1, num_rows, 1]

However, the sweep tests complain that only dims 0 and dim 3 can be different than 1. On the other side, from documentation it seems that it holds for dims 0 and 2.

However, in the unit test, another input shape was used which seems correct considering the error message
    input_rows_shape = [batch_size, 1, 1, num_rows]

in tt_metal/tests/tt_eager/python_api_testing/unit_testing/test_embedding.py

**Comment by tt-aho** [comment]
This was a recent change and docs weren't updated. It was switched from num_rows being on second last dim to the last dim. Will update
