### ISSUE TITLE
HPR on Metalium

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent-metal/tt-metal#4355]
1) input data tiled in DRAM, or ideally sharded in L1 , the first OP is currently reading row major w/ row size=16 from DRAM which is super slow due to DRAM + very small row size
2) maxpool sharded on device
3) multi-core upsample, sharded on device
4) all convs have shallow C<=64 & small weights, which means all of them could use the 2 readers (split reader) & weights pre-loaded
  - based on current experiments, HiFi4 -> Lofi didn't improve convs much (~15% on avg), suggesting they are reader bound , so weight pre-load split reader should help
 
Also, seems almost everything in RN50 10K list also applies to HPR. The above 1-4 + 10K list should be enough to get HPR to hit 3000 fps per device , thus N300 (2x) hits 6000 fps.    

Scope out HPR model development

- [x] List of Ops and corresponding shapes
- [x] #4487
- [x] #4473
- [x] #4547
- [x] #4954 
- [x] [batchnorm fold](https://github.com/tenstorrent-metal/tt-metal/issues/5132)
- [x] https://github.com/tenstorrent-metal/tt-metal/issues/5094

**Comment by mywoodstock** [comment]
list of ops and shapes: https://docs.google.com/spreadsheets/d/1dP1wKU1qfCdOlQ0MzN11HkiJxEutntT7_j5-9jUJH2I/edit#gid=876648598

**Comment by nsmithtt** [comment]
Task is done, follow on work tracked via CNNs on Metal project
