### ISSUE TITLE
Bloom GS Demo Benchmarking

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent-metal/tt-metal#4374]
GS e2e Demo

test uses batched real inputs and produces batched outputs

this test is looped (takes several batches of inputs, produces several batches of outputs)

test evaluates results of TT model against validation data in selected data set

test is documented

how to run test (commands to execute)
what does the model do (high-level explanation in a couple of sentences)
description of what is input and what is output
this demo should load inputs and expected outputs from a data set on Weka (TBD which one)

**Comment by punithsekar** [comment]
- Benchmarking for BloomCausalLM(Text generation) is done with hellaswag dataset . We are getting valid words but not meaningful sentence as output but its not matching with the dataset outputs. 

Example:
```
Input : A man is sitting on a roof.
output: A man is sitting on a roof. Really too ninine meas,,"
```

- Benchmarking for BloomQA is done with squad dataset and squad mertic. 
   The output of TT model is similar to torch output but its not matching with dataset output and is inconsistent.

Corresponding commit [Link](https://github.com/tenstorrent-metal/tt-metal/compare/main...punith/bloom_perf_accuracy)

**Comment by punithsekar** [comment]
We are not getting proper outputs while using cache implemented in test_perf_accuracy file. So the benchmarking is done on the gs_demo itself.

**Comment by punithsekar** [comment]
Corresponding PR #4772

**Comment by saichandax** [comment]
PR is merged. Closing the ticket.
