### ISSUE TITLE
ldexp operation fails with low PCC when one argument is BFLOAT8_B type and other is BFLOAT16

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent-metal/tt-metal#4376]
ldexp operation fails with low PCC when one argument is BFLOAT8_B type and other is BFLOAT16. When both arguments are of same type (BFLOAT16 or BFLOAT8_B) the operation gives good PCC. Problem is happening on Wormhole cards (on grayskull it works correctly).

**To Reproduce**
Checkout `syrmia/new_sweeps` branch (Soon to be merged in `main`). Run unit `test_eltwise_ldexp.py`  using this command:

```
pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_ldexp.py
```

**Expected behavior**
There are multiple test cases presented in the unit test and they all are expected to fail with low PCC error.
For example, one of the tests is expected to fail with this result:

```
 Max ATOL Delta: 198.5, Max RTOL Delta: 20581.400390625, PCC: 0.33608663831046326, Equal check failed
```

**Comment by tt-aho** [comment]
Please retry on latest main, I pushed a fix.

**Comment by tt-aho** [comment]
That would be expected since the compute kernel reconfig functions don't actually do anything / don't call the llk reconfig functions for wh since they were missing when we initially added these apis.

PR #4393 should have the WH fix if you want to try it out

**Comment by tt-aho** [comment]
This is merged to main now, please retry again :)

**Comment by nemanjagrujic** [comment]
Fixed in latest main
