### ISSUE TITLE
Skipping untilize hangs for certain UTWH v2 unit tests

### ISSUE THREAD

**Issue by TT-BrianLiu** [tenstorrent-metal/tt-metal#4386]
These skipped tests in `tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_v2.py` hang. 
![image](https://github.com/tenstorrent-metal/tt-metal/assets/109366241/ffa7ab8c-4e3b-416a-853c-a3b4753cde6e)

On `origin/new_halo_infra_on_device`, these tests were passing, so something after https://github.com/tenstorrent-metal/tt-metal/pull/4325 broke these tests.

**Comment by mywoodstock** [comment]
hang is on `interleaved_to_sharded`. The input in these hanging configs is `ROW_MAJOR`. Works fine with `TILE` layout.

**Comment by tarafdarTT** [comment]
there were changes to interleaved_to_sharded that got pushed before we had any tests for this in CI such that we regressed. I added a commit reversing the changes

**Comment by tarafdarTT** [comment]
has this been resolved with @tt-aho 's fix?

**Comment by TT-BrianLiu** [comment]
Fixed with 07906e318753a2ea3cf119f
