### ISSUE TITLE
WH: bert hangs in CI

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent-metal/tt-metal#4392]
FIled for tracking.

Per slack thread, Raymond says "bert tests have been killing us recently", been going on "for at least two weeks", "they're hard to reproduce locally"

I've hit this twice in the last couple days, here's a link:
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7226117440/job/19696961504

Hung in:
tests/tt_eager/python_api_testing/unit_testing/test_bert_ops.py::test_bert_linear_batch7[True-False-True-2688-1024-4096-None-bias-LoFi]

**Comment by TT-billteng** [comment]
not specific to fast dispatch it seems:

https://pipelinesghubeus24.actions.githubusercontent.com/kE5pH1GYM3Yhxzhzfofu0B5IIUz8dzneBRSYuWcoacd9fWqJEP/_apis/pipelines/1/runs/22479/signedlogcontent/2?urlExpires=2023-12-21T03%3A59%3A51.6842838Z&urlSigningMethod=HMACV1&urlSignature=0poNAwo8Jq9s%2Bx%2FGrW9YPbNyfe0itlqjVMZ5yBJbxgM%3D

**Comment by TT-billteng** [comment]
Watcher threw error in my stress test run:

https://github.com/tenstorrent-metal/tt-metal/actions/runs/7284851030/job/19850819516

```
tests/tt_eager/python_api_testing/unit_testing/test_bert_ops.py::test_bert_linear_batch7[False-True-True-2688-1024-3072-None-bias-LoFi]                   Metal | INFO     | Initializing device 0
                 Device | INFO     | Opening user mode device driver
CHECKING: [0, 0, 0, 0]
CHECKING: [1, 0, 0, 0]
2023-12-21 06:39:54.259 | INFO     | SiliconDriver   - Detected 1 PCI device : {0}
2023-12-21 06:39:54.325 | INFO     | SiliconDriver   - Using 2 Hugepages/NumHostMemChannels for TTDevice (logical_device_id: 0 pci_interface_id: 0 device_id: 0x401e revision: 1)
2023-12-21 06:39:54.331 | WARNING  | SiliconDriver   - hwloc_set_area_membind(): failed for physical_device_id: 0 on NodeSet: {1} with errno: Input/output error (pid: 1625032 tid: 140350235825984)
---- ttSiliconDevice::init_hugepage: bind_area_to_memory_nodeset() failed (physical_device_id: 0 ch: 1). Hugepage allocation is not on NumaNode matching TT Device. Side-Effect is decreased Device->Host perf (Issue #893).
2023-12-21 06:39:54.454 | INFO     | SiliconDriver   - Disable PCIE DMA
2023-12-21 06:39:54.454 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 6.3.0 (Device 0)
2023-12-21 06:39:54.455 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 6.3.0 (Device 1)
                  Metal | INFO     | AI CLK for device 0 is:   1000 MHz
              LLRuntime | INFO     | Watcher log file: /home/tt-admin/actions-runner/_work/tt-metal/tt-metal/built/watcher.log
              LLRuntime | INFO     | Watcher attached device 0
              LLRuntime | INFO     | Watcher thread watching...
2023-12-21 06:39:55.597 | DEBUG    | tests.tt_eager.python_api_testing.unit_testing.test_bert_ops:test_bert_linear_batch7:300 - in0 block w h 128 384
2023-12-21 06:39:55.597 | DEBUG    | tests.tt_eager.python_api_testing.unit_testing.test_bert_ops:test_bert_linear_batch7:301 - in1 block w h 384 128
2023-12-21 06:39:55.597 | DEBUG    | tests.tt_eager.python_api_testing.unit_testing.test_bert_ops:test_bert_linear_batch7:302 - out block w h 384 384
2023-12-21 06:39:55.597 | DEBUG    | tests.tt_eager.python_api_testing.unit_testing.test_bert_ops:test_bert_linear_batch7:303 - out subblock w h [192](https://github.com/tenstorrent-metal/tt-metal/actions/runs/7284851030/job/19850819516#step:7:193) 32
              LLRuntime | INFO     | Watcher checking device 0
                 Always | INFO     | Watcher stopped the device due to bad NOC unicast transaction
                 Always | INFO     | While running kernels:
                 Always | INFO     |  brisc : tt_eager/tt_dnn/op_library/sharded/kernels/dataflow/writer_unary_sharded.cpp
                 Always | INFO     |  ncrisc: tt_eager/tt_dnn/op_library/sharded/kernels/dataflow/reader_unary_sharded_blocks_interleaved_start_id.cpp
                 Always | INFO     |  triscs: blank
                 Always | INFO     | Last waypoint: CWFW,NRTW,W,W,W 
terminate called after throwing an instance of 'std::runtime_error'
  what():  TT_THROW @ tt_metal/llrt/watcher.cpp:226: tt::exception
info:
On core (x=1,y=1): ncrisc using noc0 tried to accesss core (00,48) L1[addr=0x00000020,len=1088]
backtrace:
 --- /home/tt-admin/actions-runner/_work/tt-metal/tt-metal/build/lib/libtt_metal.so(+0x2ac7a8) [0x7fa513c137a8]
```

**Comment by jliangTT** [comment]
@jvasilje @davorchap , please help identified the op owner.

**Comment by davorchap** [comment]
> @jvasilje @davorchap , please help identified the op owner. Will hold unto this issue under my name until handed-off
> 
> 

Assigned @tt-aho and @TT-BrianLiu ,they own MM variants. 

@yugaoTT is this an interleaved or sharded test?

**Comment by yugaoTT** [comment]
@davorchap It is a mixed test with sharded/interleaved, with weights in L1/DRAM

**Comment by tt-aho** [comment]
Per https://github.com/tenstorrent-metal/tt-metal/issues/4136#issuecomment-1872210991

The watcher error that is being seen when running this test isn't the root cause of the hang as the watcher error is due to incorrect bit shifts during watcher verification, and not an issue with the op/kernel itself.

Currently trying to repro hang locally now but haven't been able to yet

**Comment by pgkeller** [comment]
@tt-aho do you have more info on the watcher issues (or has it been filed as an issue)?  Thanks

**Comment by tt-aho** [comment]
@pgkeller it is issue #4136 which is the top level issue that links to a bunch of failed WH tests with watcher enabled due to this error. I added a comment on the issue for what is the cause https://github.com/tenstorrent-metal/tt-metal/issues/4136#issuecomment-1872210991

> The problem for this error, `On core (x=1,y=1): noc0:brisc{(00,48) 0x000005a0, 2048}`, is that when extracting the noc_x and noc_y for watcher verification, there are extra bit shifts.
> 
> When we generate the xy values in `genfiles.cpp`, we bit shift the xy values by 4 for WH already (noc_addr_local_bits is 36)
> 
> ![image](https://private-user-images.githubusercontent.com/109362939/293395798-425218b5-6ff5-44c5-b80b-a5f1d2035dc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMjI2NTQsIm5iZiI6MTcwNDIyMjM1NCwicGF0aCI6Ii8xMDkzNjI5MzkvMjkzMzk1Nzk4LTQyNTIxOGI1LTZmZjUtNDRjNS1iODBiLWE1ZjFkMjAzNWRjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxOTA1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzdhOTBlMGJiZGQ0MTY0MjBiMjQ3YWM5MzljYzk2ZDFmY2YwZTc5ZWIwODhkZDEyZDk5NDAxMWIzNTc0Y2M4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dJ2SnKUS_X2uf63FDAajZFrwTguLSLnuxOa1TkysWvA)
> 
> To create the address for watcher sanitization, we use NOC_XY_ADDR2, which shifts the xy passed in by 36 which means that xy now starts at bit 40 since the xy value is already shifted by 4. ![image](https://private-user-images.githubusercontent.com/109362939/293396051-95697aba-8456-4b57-8d05-51b831945f21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMjI2NTQsIm5iZiI6MTcwNDIyMjM1NCwicGF0aCI6Ii8xMDkzNjI5MzkvMjkzMzk2MDUxLTk1Njk3YWJhLTg0NTYtNGI1Ny04ZDA1LTUxYjgzMTk0NWYyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxOTA1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGZmMTdmZjMyMzg4N2Q1MDdmNGQ1YjhiMWNkYWMyNDRiYmQxNWUzYWYxNzVjMmEzMDU3ZjMxYzZkZDQzZjIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S8o4GsyDJZLo4xZV4SiWuoO0KQjw4sBbUmWrTMoT5Ng)
> 
> The correct dram noc is (0, 11), where 11 is 0b001011, but when watcher is validating it is reading it shifted by 4 as 0b110000 which is 48. This should only affect watcher validation so the actual reads should be correct.

**Comment by vtangTT** [comment]
Update: I was able to repro in main (```bf25587```, no watcher): I'm seeing >200 timeouts not specific to any parametrization 

```pytest tests/tt_eager/python_api_testing/unit_testing/test_bert_ops.py```

**Comment by eyonland** [comment]
We started noticing that Finish(cq); was causing WH to hang.     Could could this be somehow related?

**Comment by yugaoTT** [comment]
@eyonland is it in fast dispatch mode and a ND hang?

**Comment by eyonland** [comment]
That is correct!

**Comment by davorchap** [comment]
@DrJessop should take a look.

@yugaoTT this hang is not related to di/dt ?
