### ISSUE TITLE
logit operation fails with low PCC on Wormhole and Grayskull cards

### ISSUE THREAD

**Issue by JelenaTosicJtosic** [tenstorrent-metal/tt-metal#4405]
`logit` operation breaks with low PCC error in some test cases on Wormhole cards. 

* Problem is observed both on tt_lib.tensor and ttnn variants. 
* Problem happens on both GS and WH cards

**To Reproduce**
1. Checkout `main` branch
2. Run unit test `test_logit.py ` using this command:
`pytest tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_logit.py`

(NOTE: Use the same unit test for Grayskyll card1)

**Expected behavior**
There are three test cases presented in the unit test `tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_logit.py`
For GS first two are expected to fail and for WH all three are expected to fail with low PCC error.
For example, one of the tests is expected to fail with this result: 
`Max ATOL Delta: 5.001336097717285, Max RTOL Delta: 2.0224297046661377, PCC: -0.7121394672631166, PCC check failed`.  

Also, we should expect the operation to return `nan when the epsilon argument is greater than 1. For this test case GS returns tensor filled with `nan` values, but for WH this is not the case and we get error printed like this:

`ERROR    | tests.tt_eager.python_api_testing.sweep_tests.comparison_funcs:get_pcc:32 - One tensor is all nan, the other is not.`
 
Moreover the documentation for logit needs to be updated, so that epsilon is defined appropriately like `the epsilon for input clamp bound` and not `dimension to logit along`. Also the ranges need to be updated, so that epsilon as well as input have valid input ranges mentioned in the documentation.

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for `logit` operation and check the results:

```
tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_wormhole/pytorch_eltwise_logit_test.yaml
```

for tt_lib variant. And:

```
tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/wormhole/ttnn_eltwise_logit_test.yaml
```

for ttnn variant.

To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
3. Activate `source build/python_env/bin/activate`
4. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_wormhole/pytorch_eltwise_logit_test.yaml -o ./result-sweeps`
5. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `eltwise_logit_sweep.csv` which holds all executed sweeps.

**Comment by nemanjagrujic** [comment]
@umadevimcw Tested and seems to be passing both unit and sweeps tests! Great!

Please let us know when you merge to main so we can update sweep tests (move it to working folders etc).

**Comment by umadevimcw** [comment]
Sure waiting for approval. Will let you know

**Comment by umadevimcw** [comment]
@nemanjagrujic Merged PR into the main
