### ISSUE TITLE
merge op implementation for power_fp into power

### ISSUE THREAD

**Issue by muthutt** [tenstorrent-metal/tt-metal#4428]
merge op implementation for power_fp into power

TT Metalium supports **tt_lib.tensor.power(tensor, exponent)** where exponent is positive integer and **tt_lib.tensor.power_fp(tensor, exponent)** for positive fractional exponent.

These should both be supported via same interface.

**Comment by umadevimcw** [comment]
Raised the PR #4555

**Comment by umadevimcw** [comment]
Merged to main
