### ISSUE TITLE
MNIST GS demo Benchmarking

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent-metal/tt-metal#4431]
GS e2e Demo

test uses batched real inputs and produces batched outputs

this test is looped (takes several batches of inputs, produces several batches of outputs)

test evaluates results of TT model against validation data in selected data set

test is documented

how to run test (commands to execute)
what does the model do (high-level explanation in a couple of sentences)
description of what is input and what is output
this demo should load inputs and expected outputs from a data set on Weka (TBD which one)

**Comment by Sudharsan-V** [comment]
The Benchmarking of GS MNIST model is completed.
Data-set: MNIST
Metric: Accuracy

Corresponding: [commit](https://github.com/tenstorrent-metal/tt-metal/commit/1f197629fbc1dc0e0b05009e00fbb7f238d20665)

**Comment by jayasuryamaganuru** [comment]
PR for MNIST GS demo benchmarking ,
model is tested with 1000 datapoints extracted from the MNIST handwritten digits dataset ,
the accuracy is listed below:

Metric: Accuracy
Accuracy: 62.2

Link - #4502

**Comment by saichandax** [comment]
* Needs review from @muthutt 
* CI is pending.

**Comment by saichandax** [comment]
PR is approved. CI is pending

**Comment by saichandax** [comment]
PR is merged. Hence closing the ticket.
