### ISSUE TITLE
Enable "unlinked" ETH cores to be controlled and used by SW

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent-metal/tt-metal#4450]
To specify where the RISC-V kernels start executing their firmware in tensix, brisc overwrites some cfg_registers at the RISC-V reset addresses. For example, in brisc.cc
```c++
cfg_regs[NCRISC_RESET_PC_PC_ADDR32] = MEM_NCRISC_IRAM_BASE;
cfg_regs[TRISC_RESET_PC_SEC0_PC_ADDR32] = MEM_TRISC0_BASE;
cfg_regs[TRISC_RESET_PC_SEC1_PC_ADDR32] = MEM_TRISC1_BASE;
cfg_regs[TRISC_RESET_PC_SEC2_PC_ADDR32] = MEM_TRISC2_BASE;
cfg_regs[TRISC_RESET_PC_OVERRIDE_Reset_PC_Override_en_ADDR32] = 0b111;
cfg_regs[NCRISC_RESET_PC_OVERRIDE_Reset_PC_Override_en_ADDR32] = 0x1;
```

And then from host, host programs a special jump instruction so that when brisc gets deasserted and runs from address 0, it jumps to the actual firmware start. 

In metal, we want to write our own custom base firmware at some other address that doesn't conflict with the current ethernet base firmware. I would have liked to program my own jump instruction for ethernet, but unfortunately I cannot since syseng tools operate under the premise that the original base firmware should not be corrupted. Therefore, I'd like to somehow update the cfg register for erisc, yet there doesn't seem to be a file that I can find which contains mention of the erisc deassert start addr register. This issue can be closed once details on how to do this are supplied.

cc: @davorchap 

Updates from syseng
---------------------
Apparently, we can write a jump instruction at the beginning of the current firmware to jump to our custom firmware. Unfortunately, this corrupts the base firmware, and syseng tools run and continuously check that this firmware is not corrupted. We also cannot just context switch into our base firmware, since the syseng tools also check that the base firmware has not changed. They recommend we just use the base firmware and have dispatch run as an app. We don't want to do this since we lose a lot of space due to the base firmware (about 10%) and we have no reason to context switch between the two.

**Comment by davorchap** [comment]
fyi @TTDRosen this is the case to update with the current design description after you discuss with the team

**Comment by jliangTT** [comment]
did some catching up.. 

context: we want to use ethernet cores for fast dispatch BUT the code size is constrained (due to existing base firmware) and context switching (using current context switching flow) has high perf hit and is complex. 

Next steps: 

- enumerate all the considerations required to remove doing syseng health checks on unused ethernet cores
- further brainstorm

**Comment by TTDRosen** [comment]
Do we have the numbers to show how big a perf hit would be taken by performing the context switch every 100 or so milliseconds? It'll help add context to why it's important to put in the time to make an architectural change at this point during development.

**Comment by davorchap** [comment]
> Do we have the numbers to show how big a perf hit would be taken by performing the context switch every 100 or so milliseconds? It'll help add context to why it's important to put in the time to make an architectural change at this point during development.

* perf: dispatch code that would run on ETH cores is already performance critical and undergoing optimizations even when running unobstructed on an Tensix core
* functionality:

**Comment by jliangTT** [comment]
@DrJessop , offline that this is unblocked provided we just need to not-touch the lowest 8KB of L1 memory. Can this be closed?

**Comment by jliangTT** [comment]
The contract between the team in the implementation: 

- preserve lower 8KB
- increment 0x1C at interval <= 100ms (likely much shorter internal, every 100 cycles)

**Comment by davorchap** [comment]
completed, great work @ubcheema !
