### ISSUE TITLE
PCC mismatch on final whisper layer

### ISSUE THREAD

**Issue by eyonland** [tenstorrent-metal/tt-metal#4455]

**Comment by eyonland** [comment]
torch computations produced different results on bfloat16 based on whether the tensor is contiguous.  The solution was to put contiguous in a number of locations to get the final layer to match to torch.

**Comment by jliangTT** [comment]
some data: 

- FP32 is bug free for the continguous and non-continguous (for bfloat16, PCC mismatch is seen non-continguous but not seen in continguous format)
- this is observed with torch op in its functional form vs. huggingface form (not in ttnn)

Next step: we should align to use fp32 with torch program as golden (and not bfloat)
