### ISSUE TITLE
Update split_query_key_value_and_split_heads and concatenate_heads to work with other shapes and add split_heads, split_key_value_and_split_heads

### ISSUE THREAD

**Issue by arakhmati** [tenstorrent-metal/tt-metal#4456]

**Comment by jliangTT** [comment]
This issue to also track the generalization of `ttnn.nlp.concatenate_heads`

**Comment by TT-BrianLiu** [comment]
Functionality in `ttlib` for split and concat heads should be all there now.

**Comment by arakhmati** [comment]
Closing the issue as @TT-BrianLiu has implemented everything
