### ISSUE TITLE
Cleanup of python layer for CNN ops

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent-metal/tt-metal#4473]
- [ ] compositize ops (UTWH + conv)
- [ ] compositize ops (UTWH + maxpool etc)
- [ ] cleanup and simplify API
- [ ] port conv op to ttnn

**Comment by davorchap** [comment]
user passes:
* core grid
* 1D or 2D systolic array
* determine automatically / allow an override:
  * assume half DST mode — can have override
shard size per core , per_core_m , per_core_n —> direct, 1 options
out subblock m, n
pick the largest config that fits into half DST — also needs to preserve RM in the output shard
1D systolic specific:
block height for 1D — tied to subblock m ?
manual override if no fit?
what do we use in RN50 as heuristic?
inner block dim
2D systolic specific:
