### ISSUE TITLE
DistilBert gs demo benchmarking

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent-metal/tt-metal#4482]
GS e2e Demo

test uses batched real inputs and produces batched outputs

this test is looped (takes several batches of inputs, produces several batches of outputs)

test evaluates results of TT model against validation data in selected data set

test is documented

how to run test (commands to execute)
what does the model do (high-level explanation in a couple of sentences)
description of what is input and what is output
this demo should load inputs and expected outputs from a data set on Weka (TBD which one)

**Comment by kkeerthana0573** [comment]
This commit contains benchmarking of Distilbert for Question and Answering using SQUAD dataset.

- Exact Match : 62.0
- F1 Score : 74.24285714285713

Corresponding commit - [commit](https://github.com/tenstorrent-metal/tt-metal/compare/main...keerthana/distilbert_benchmarking)

**Comment by Sudharsan-V** [comment]
Distilbert GS demo Benchmarking is completed and it is merged with mail. All the CI tests passed.
