### ISSUE TITLE
Debug bloom PCC mismatch

### ISSUE THREAD

**Issue by arakhmati** [tenstorrent-metal/tt-metal#4489]
Bloom fails in ttnn.add when the results of the add are put into L1

**Comment by jliangTT** [comment]
Data - 
- if everything placed to dram, this issue is not seen; if to L1, it appears. 

Suggested next step: 
- Do the hack (putting in the dram) to smoke up other e2e pcc error. 
- continue to debug

**Comment by jliangTT** [comment]
@davorchap @jvasilje , this is surfaced as an issue for ttnn productionization sprint and need help with the triaging. I am flagging this as P1_critical and add it to ttnn board. Please assign owner

@muthutt , since this is an element-wise ops, maybe you can advise as well on this

**Comment by arakhmati** [comment]
I narrowed down the mismatch. `ttnn.add` itself isn't the issue.

The add is used for a residual connection in `bloom`.  And it causes the mismatch when the skip connection is stored in L1. Putting the skip connection into DRAM fixes the issue. Which most likely means that the memory somehow gets overridden.

**Comment by Sudharsan-V** [comment]
@arakhmati  @muthutt 
we feel that we don't have a problem in layer_norm. Output from the ttnn.layer_norm is consistent irrespective of the memory_config passed to the layer_norm op.
We are facing a problem in add op.
Case 1:  
`ttnn.add(attenion_ouput, hidden_state_with_mem_config_DRAM, mem_config = DRAM)`
Case 2:
`ttnn.add(attenion_ouput, hidden_state_with_mem_config_L1, mem_config = DRAM)`

In both cases, we have the same input,
ie:  
attention_ouput in case1 = attention_output in case2
similarly, hidden_state_with_mem_config_DRAM in case 1= hidden_state_with_mem_config_L1 in case2

In case1, hidden_state was calculated with mem_config = DRAM
In case2, hidden_state was calculated with mem_config = L1

but addition ouptut from case1 != addition ouptut from case2

This mismatch is happening in the first iteration itself. In total, we have 24 iterations. So, this mismatch gets accumulated to form a significant reduction in pcc.

We tried deallocating the tensors in L1, in many places Akhmed Rakhmati has already deallocated. And this didn't help us to improve pcc.

In both the cases atention_output is in L1,

Even with the same mem_config the behaviour of the add op is varying. But when we create a unit test for add op this behavior is not seen.

**Comment by jliangTT** [comment]
@Sudharsan-V , that is consistent with team's observation. What are the next steps for debugging add? Are you blocked? Anything help / input you need from the team? thanks!

**Comment by Sudharsan-V** [comment]
@jliangTT, As a next step, we have planned to
- Replace add op with sub and mul op. `a + b = a - (-1 * b)`. After replacing, if we are getting the expected pcc, we can make sure that only add op is creating trouble.
- In case 2 (`ttnn.add(attenion_ouput, hidden_state_with_mem_config_L1, mem_config = DRAM`), we can fill `attention output` with zeros(zero tensor), in this case, the add op should return `hidden_state_with_mem_config_L1` as output. If we are not getting `hidden_state_with_mem_config_L1` as output, there is a fluctuation in the value when we switch the tensor from L1 to DRAM.

And, it will be helpful to dig deeper into this issue, if you have any suggestions or input.

**Comment by jliangTT** [comment]
thanks. no suggestion. looks like a good plan (let me know if you need anything).

**Comment by Sudharsan-V** [comment]
@jliangTT The above-mentioned debugging steps were completed. Please find the results/observations obtained in the attached document.
[bloom_pcc_issue.docx](https://github.com/tenstorrent-metal/tt-metal/files/13904868/bloom_pcc_issue.docx)
Thanks!.

**Comment by boris-drazic** [comment]
The PCC mismatch has been traced down to and issue with hashing of `add` OP.

If the test is invoked with `tt_lib.program_cache.disable_and_clear()` at start, the test will pass.

Looking at `compute_program_hash` for `add` op in `tt_eager/tt_dnn/op_library/eltwise_binary/eltwise_binary_op.cpp`, if `this->output_mem_config.buffer_type` is added to `tt::stl::hash::hash_objects`, the test passes without disabling cache.

**Comment by arakhmati** [comment]
> The PCC mismatch has been traced down to and issue with hashing of `add` OP.
> 
> If the test is invoked with `tt_lib.program_cache.disable_and_clear()` at start, the test will pass.
> 
> Looking at `compute_program_hash` for `add` op in `tt_eager/tt_dnn/op_library/eltwise_binary/eltwise_binary_op.cpp`, if `this->output_mem_config.buffer_type` is added to `tt::stl::hash::hash_objects`, the test passes without disabling cache.

That's an amazing find! Thank you everyone who participated in the debug!

I made a PR with the fix: https://github.com/tenstorrent-metal/tt-metal/pull/4842
