### ISSUE TITLE
Demo for functional bloom [Pending CI]

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent-metal/tt-metal#4503]
GS e2e Demo

test uses batched real inputs and produces batched outputs

this test is looped (takes several batches of inputs, produces several batches of outputs)

test evaluates results of TT model against validation data in selected data set

test is documented

how to run test (commands to execute)
what does the model do (high-level explanation in a couple of sentences)
description of what is input and what is output
this demo should load inputs and expected outputs from a data set on Weka (TBD which one)

**Comment by punithsekar** [comment]
The end-to-end demo for the functional bloom model .
corresponding [commit](https://github.com/tenstorrent-metal/tt-metal/compare/main...punith/functional_bloom_demo)


Working on batch_size>1 for bloom_causalLM_inference.

**Comment by punithsekar** [comment]
The end-to-end demo for the functional bloom model .
corresponding PR #4554

**Comment by saichandax** [comment]
PR merged. Hence, closing the ticket.
