### ISSUE TITLE
Demo for functional bert

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent-metal/tt-metal#4505]
GS e2e Demo

test uses batched real inputs and produces batched outputs

this test is looped (takes several batches of inputs, produces several batches of outputs)

test evaluates results of TT model against validation data in selected data set

test is documented

how to run test (commands to execute)
what does the model do (high-level explanation in a couple of sentences)
description of what is input and what is output
this demo should load inputs and expected outputs from a data set on Weka (TBD which one)

**Comment by boris-drazic** [comment]
For optimized version the attention mask does not seem to be set correctly. I left a comment in the commit with changes that make the test run.

**Comment by Sudharsan-V** [comment]
The demo for the functional bert is completed by incorporating the comments shared by Boris. Now, we can run the tests for both variants of the functional_bert with batch_size>1.

For Batch_size = 1, we are facing the following issue in the optimized version
```
E               RuntimeError: TT_ASSERT @ tt_eager/tt_dnn/op_library/bmm/multi_core_reuse_mcast_2d_optimized/bmm_op_multi_core_reuse_mcast_2d_optimized.cpp:925: false
E               info:
E               mcast_in0 is not implemented yet.
E               backtrace:
E                --- tt::tt_metal::matmul_multi_core_reuse_mcast_2d_optimized(tt::tt_metal::Tensor const&, tt::tt_metal::Tensor const&, std::optional<tt::tt_metal::Tensor const>, tt::tt_metal::Tensor&, bool, tt_xy_pair, MathFidelity, bool, bool, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, bool, bool, std::optional<tt::tt_metal::UnaryWithParam>)
E                --- /home/ubuntu/sudharsan/tt-metal/tt_eager/tt_lib/_C.so(+0x33f73d) [0x7f6ea54d373d]
E                --- /home/ubuntu/sudharsan/tt-metal/tt_eager/tt_lib/_C.so(+0x33f832) [0x7f6ea54d3832]
```
We do not face any issue with the other variant(ttnn_functional_bert)

Corresponding PR[#4582](https://github.com/tenstorrent-metal/tt-metal/pull/4582)

**Comment by saichandax** [comment]
PR merged, Closing the ticket.
