### ISSUE TITLE
SSD gs demo Benchmarking [Pending CI]

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent-metal/tt-metal#4506]
GS e2e Demo

test uses batched real inputs and produces batched outputs

this test is looped (takes several batches of inputs, produces several batches of outputs)

test evaluates results of TT model against validation data in selected data set

test is documented

how to run test (commands to execute)
what does the model do (high-level explanation in a couple of sentences)
description of what is input and what is output
this demo should load inputs and expected outputs from a data set on Weka (TBD which one)

**Comment by kkeerthana0573** [comment]
This commit contains benchmarking of SSD using coco128 dataset ( moved to weka path - /mnt/MLPerf/tt_dnn-models/ssd/coco128 )

- Note: PCC for this model is low, thereby affecting average precision while benchmarking:
    -   PCC for Scores: 0.4450223310843609
    -   PCC for Labels: -0.29295572559612937
    -   PCC for Boxes: 0.16220816595909118

Currently, one image is used.

Metrics used:
- average precision:  0.0

Corresponding commit - [commit](https://github.com/tenstorrent-metal/tt-metal/compare/main...keerthana/ssd_benchmarking)

**Comment by saichandax** [comment]
PR is merged, hence closing the ticket.
