### ISSUE TITLE
Split last dim failed to split the data correctly

### ISSUE THREAD

**Issue by umadevimcw** [tenstorrent-metal/tt-metal#4518]
**Describe the bug**
**_split_last_dim_two_chunks_tiled_**  failed to split the data correctly for few dimensions. This particular function is used in all type1 complex ops

**To Reproduce**
- Checkout to `umadevimcw/split_dim_bug`
- Run `pytest tests/tt_eager/python_api_testing/split_two_chunks_last_dim_test/test_split_dim.py`

**Expected behavior**
All the test in the file are expected to return wrong value.

**Screenshots**
<img width="1138" alt="Screenshot 2023-12-29 at 12 01 10 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/29221091/4b332bd1-8d4e-4ad6-8643-918ecb015822">

In the image wrong values are highlighted with the red box

**Additional context**
Reused the test_complex_real test file to report the error
Filled the real and imaginary tensors with constant values to visualize the issue better

**Comment by umadevimcw** [comment]
@tarafdarTT  - split_last_dim_two_chunks_tiled module is used in complex ops to split the real and imaginary part as i mentioned above you can see in the image the second half of the tensors are not real part , that too it fails for few specific dimensions mentioned in the test file

**Comment by tarafdarTT** [comment]
ah I see, I will look into this on the weekend.

**Comment by tarafdarTT** [comment]
is this still an issue because I see this issue: https://github.com/tenstorrent-metal/tt-metal/issues/3554 has been closed

**Comment by umadevimcw** [comment]
@tarafdarTT it is still an issue. For that issue we just updated the range for the test to get pass. But the issue is still there

**Comment by tarafdarTT** [comment]
> @umadevimcw - this should be possible to do with new APIs developed by Naif on the SplitTile op

sorry I may have miscommunicated, you should be able to use Unpad to do this.
Unpad is now synonymous with slice. 
This is where you give it a tensor and two shapes , a start and an end. 
So if you need to split a tensor N ways, you would call Unpad N times.
An example of this op is here:
`tests/tt_eager/python_api_testing/unit_testing/test_unpadding_test.py`

**Comment by umadevimcw** [comment]
Closing this issue as we have updated the complex ops with unpad instead of split last dimension function
