### ISSUE TITLE
use pack_untilize in Maxpool

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent-metal/tt-metal#4533]
Idea is to use `llk_pack_untilize` function instead of `llk_pack` along with reduce in the maxpool kernel. I updated the compute api to perform this sequence of operations, but the computed result is only partially correct.

Branch: `asarje/mp-opt`
PR: https://github.com/tenstorrent-metal/tt-metal/pull/4492

This is the new `reduce` kernel to use `llk_pack_untilize`: https://github.com/tenstorrent-metal/tt-metal/pull/4492/files#diff-eaa8ba863bda49a67e643f86ebf762fa9a2ec5ec689e221473a15476b9d6ee84R111

I added few compute api's here: https://github.com/tenstorrent-metal/tt-metal/pull/4492/files#diff-67d97fd08db903b5866e849551d27109305d680a2c35d299d47a355a23c6cc04R72

My intuition is that some init config is missing or misconfigured.

Unit test: `pytest tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_and_max_pool_v2.py::test_run_max_pool[dtype0-1-dilation0-stride0-padding0-kernel_size0-act_shape0]`

**Comment by mywoodstock** [comment]
works. this is in branch `asarje/mp-opt-new`

**Comment by mywoodstock** [comment]
https://github.com/tenstorrent-metal/tt-metal/pull/4680

**Comment by mywoodstock** [comment]
The code works well, but the perf is slightly worse than previous version. Needs further opt.

**Comment by davorchap** [comment]
@mywoodstock this is complete and can be closed?
