### ISSUE TITLE
Swin model gs demo Benchmarking

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent-metal/tt-metal#4557]
GS e2e Demo

test uses batched real inputs and produces batched outputs

this test is looped (takes several batches of inputs, produces several batches of outputs)

test evaluates results of TT model against validation data in selected data set

test is documented

how to run test (commands to execute)
what does the model do (high-level explanation in a couple of sentences)
description of what is input and what is output
this demo should load inputs and expected outputs from a data set on Weka (TBD which one)

**Comment by jayasuryamaganuru** [comment]
The Benchmarking of GS Swin Classification model is completed.
Data-set: IMAGENET
Metric: Accuracy
commit [link](https://github.com/tenstorrent-metal/tt-metal/compare/main...jayasurya/swin_gs_demo_benchmarking)

**Comment by jayasuryamaganuru** [comment]
This PR contains benchmarking of Swin gs_demo for IMAGENET test dataset.
model is tested with 20 datapoints extracted from the dataset and the accuracy is listed below:
Metric: Accuracy
Accuracy: 0.0
Note: Swin model getting low PCC, thereby affecting its accuracy during benchmarking.

PR - #4774

**Comment by saichandax** [comment]
PR merged, closing the ticket.
