### ISSUE TITLE
ttnn.layer_norm low PCC on Wormhole

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent-metal/tt-metal#4568]
`ttnn.layer_norm` operation fails with low PCC in several combination on WH cards (any memory layout, type or buffer layout)
**To Reproduce**
Checkout `syrmia/ttnn-sweeps` branch (Soon to be merged in `main`). Run unit `tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_layernorm.py`  using this command variants, depending whether weights, bias and residual are included:

```
1. pytest tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_layernorm_noweights.py
2. pytest tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_layernorm.py
3. pytest tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_layernorm_residual.py
```

**Expected behavior**
There are two test cases per unit test and they all are expected to fail with low PCC error (still close to 0.99 but failing).
For example, one of the tests is expected to fail with this result:
```
Max ATOL Delta: 64.0, Max RTOL Delta: inf, PCC: 0.9882473011538487, PCC check failed
```

**Getting Details**
You can get more combinations tested using test sweep: `tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/wormhole/ttnn_layernorm_noweights_test.yaml` or 
`tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/wormhole/ttnn_layernorm_test.yaml` or
`tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/wormhole/ttnn_layernorm_residual_test.yaml`with command:

```
python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/wormhole/ttnn_layernorm_test.yaml -o ./result-sweeps
```

Result will be saved in `./result-sweeps` folder

**Comment by yugaoTT** [comment]
@npetrovic-tenstorrent is this test file  `tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_layernorm_noweights.py` removed from main?

**Comment by yugaoTT** [comment]
@npetrovic-tenstorrent is the branch already `syrmia/ttnn-sweeps` merged? can we close this issue?

**Comment by npetrovic-tenstorrent** [comment]
Yes, it is merged

**Comment by npetrovic-tenstorrent** [comment]
> @npetrovic-tenstorrent is the branch already `syrmia/ttnn-sweeps` merged? can we close this issue?

Yes, it is merged
