### ISSUE TITLE
ttnn.softmax fails with low PCC  on Wormhole

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent-metal/tt-metal#4570]
`ttnn.softmax` operation fails with low PCC in several combination on WH (any memory layout, type or buffer layout)
**To Reproduce**
Checkout `syrmia/ttnn-sweeps` branch (Soon to be merged in `main`). Run unit `tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_softmax.py`  using this command:
```
 pytest tests/ttnn/python_api_testing/non_working_unit_tests/wormhole/test_softmax.py

```

**Expected behavior**
For WH, it fails in all three cases, with following results for one of them:
```
Max ATOL Delta: 0.02685546875, Max RTOL Delta: 0.484375, PCC: 0.9655609181708856, PCC check failed
```

**Getting Details**
You can get more combinations tested using test sweep: `tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/wormhole/ttnn_eltwise_softmax_test.yaml`
with command:

```
python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/wormhole/ttnn_eltwise_softmax_test.yaml -o ./result-sweeps
```

Result will be saved in `./result-sweeps` folder

**Comment by yugaoTT** [comment]
@npetrovic-tenstorrent is the branch already `syrmia/ttnn-sweeps` merged? can we close this issue?

**Comment by npetrovic-tenstorrent** [comment]
> it is not supporting RM layout, there are asserts that checks it in latest main.

If it is now outdated and not relevant anymore according to this, we can close it.
