### ISSUE TITLE
Block based API matmul_block deterministic hangs on WH_B0

### ISSUE THREAD

**Issue by yugaoTT** [tenstorrent-metal/tt-metal#4573]
When using the block based api `matmul_block` for WH, we spot a non-deterministic hang when `subblock` dim > 1.
When `subblock_h` (rt_dim) and `subblock_w` (ct_dim) both equal to 1, there is no hang. 
When `subblock_h` > 1, it hangs immediately, and when `subblock_w` > 1, it hangs randomly.

The compute kernel is in `tt_eager/tt_dnn/op_library/bmm/kernels/compute/bmm_large_block_zm_fused_bias_activation_matmul_tiles.cpp`

When commented out `matmul_block`, there is no hang.

**To Reproduce**
1. go to branch `yugao/wh_block_matmu`
2. run the pytest `pytest tests/tt_eager/python_api_testing/unit_testing/test_bert_ops.py`

**Comment by rtawfik01** [comment]
I have a fix here: https://github.com/tenstorrent-metal/tt-metal/pull/4724/commits

@yugaoTT please try it out and let me know if it works with all WH block matmul use cases

**Comment by davorchap** [comment]
@yugaoTT has this been tested / merged?

**Comment by davorchap** [comment]
If you suspect in0 reader can you open a new issue, and we can close this LLK issue?


> > @yugaoTT has this been tested / merged?
> 
> @davorchap I haven't merged yet, the deterministic hang was fixed by @rtawfik01. The ND hang is not solved yet and I think it might relate to the in0 reader.

**Comment by davorchap** [comment]
the deterministic LLK fix -- @yugaoTT can we merge that and close?

**Comment by davorchap** [comment]
deterministic hang has been fixed. non-determinisitc hang tracked here #4968
