### ISSUE TITLE
Many ttnn operations fail with low PCC when slow dispatch mode is "1"

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent-metal/tt-metal#4581]
Many ttnn operations fail with low PCC when slow dispatch mode is "1"

Affected ops: add, sub, mul, tanh, gelu, permute, exp 

Note! Problem is not observed when running operations with profiling!

**To Reproduce**
Checkout `syrmia/ttnn-sweeps` branch (Soon to be merged in `main`). Run unit `tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_slow_dispatch_mode.py`  using this command:

```
pytest tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_slow_dispatch_mode.py
```

**Expected behavior**
There are multiple test cases presented in the unit test and some of them are expected to fail with low PCC error.
For example, one of the tests is expected to fail with this result:

```
Max ATOL Delta: 1.0, Max RTOL Delta: 1.0, PCC: 0.0, PCC check failed
```

Reason why some do not fail is possible because they are needed to mako others fail.

**Getting Details**
You can get more combinations tested using test sweeps: 

`tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_eltwise_add_test.yaml` `tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_eltwise_exp_test.yaml`
`tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_eltwise_gelu_test.yaml`
`tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_eltwise_mul_test.yaml`
`tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_eltwise_sub_test.yaml`
`tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_eltwise_tanh_test.yaml`
`tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_permute_test.yaml`

with command for example:

```
python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_eltwise_add_test.yaml -o ./result-sweeps
```

Result will be saved in `./result-sweeps` folder

Note! Problem is not observed when running operations with profiling!

**Comment by jliangTT** [comment]
Labeling as P3 as sweep on slow dispatch is lower priority

**Comment by boris-drazic** [comment]
Retested after pulling from main, these tests no longer fail.

**Comment by nemanjagrujic** [comment]
> Retested after pulling from main, these tests no longer fail.

@boris-drazic Are you sure? Just tested today on latest main (and grayskull card) and still failing.

**Comment by eyonland** [comment]
Getting low PCC when we run in slow dispatch without profiling smells like a move semantics (or similar) bug.   

@nemanjagrujic , do you know if we have a C++ test that exposes this?   If so, I can easily kick this off through valgrind and callgrind and take a closer look.

**Comment by nemanjagrujic** [comment]
> Getting low PCC when we run in slow dispatch without profiling smells like a move semantics (or similar) bug.
> 
> @nemanjagrujic , do you know if we have a C++ test that exposes this? If so, I can easily kick this off through valgrind and callgrind and take a closer look.

@eyonland We did not make C++ test which exposes that issue.

**Comment by nemanjagrujic** [comment]
Works now
