### ISSUE TITLE
Demo for functional Whisper model

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent-metal/tt-metal#4584]
GS e2e Demo

test uses batched real inputs and produces batched outputs

this test is looped (takes several batches of inputs, produces several batches of outputs)

test evaluates results of TT model against validation data in selected data set

test is documented

how to run test (commands to execute)
what does the model do (high-level explanation in a couple of sentences)
description of what is input and what is output
this demo should load inputs and expected outputs from a data set on Weka (TBD which one)

**Comment by vigneshkeerthivasanx** [comment]
Demo file for  **ttnn_functional_whisper** for audio-to-text is done referencing the **models/experimental/whisper/tests/test_whisper_for_conditional_generation.py.**
However, the output from the demo file is not meaningful, consistently yielding "ga" for all input.

We also used this generate method to decode the tokens generated from torch_functional_whisper in **tests/ttnn/integration_tests/whisper/test_ttnn_functional_whisper.py** .

```
Iteration - 0
tokens [50259]
decode output - 

Iteration - 1 
tokens [50259]
decode output - 

Iteration - 2 
tokens [973]
decode output - ö

Iteration - 3 
tokens [275]
decode output - ö m

Iteration - 4 
tokens [50257]
decode output - ö m
```

decoded outputs for ttnn_functional_whisper
```
Iteration - 0 
tokens [50259]
decode output -
 
Iteration - 1
tokens [50259]
decode output - 

Iteration - 2 
tokens [3680]
decode output - ga

Iteration - 3 
tokens [50257]
decode output - ga

Iteration - 4 
tokens [50257]
decode output - ga
```

We are not getting proper outputs using this demo. We are further looking into debugging this issue.

Commit Link : [Link](https://github.com/tenstorrent-metal/tt-metal/compare/main...vignesh/functional_whisper_demo)

**Comment by boris-drazic** [comment]
Please use optimized implementation `models/experimental/functional_whisper/tt/ttnn_optimized_functional_whisper.py` for this demo.

**Comment by punithsekar** [comment]
Audio classification results:
Time taken: Around 45 seconds
dataset value: Afrikaans
ttnn model result: Afrikaans


Conditional generation results:
Time taken: Around 1 minute
Dataset value: MISTER QUILTER IS THE APOSTLE OF THE MIDDLE CLASSES AND WE ARE GLAD TO WELCOME HIS GOSPEL
ttnn model result: Mr. Quilter is the apostle of the middle classes, and we are glad to welcome his gospel.

**Comment by punithsekar** [comment]
Corresponding PR (#6489)

**Comment by Sudharsan-V** [comment]
The demo for functional Whisper is merged to main.
CI [Link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/8353573487)

Closing the ticket.
