### ISSUE TITLE
fused tilize/reduce LLK

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent-metal/tt-metal#4588]
My working branch: `asarje/mp-unpack-tilize-fused`
Test: `pytest tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_and_max_pool_v2.py::test_run_max_pool[dtype1-1-dilation0-stride0-padding0-kernel_size0-act_shape4]"`

The current device execution time of this particular shape (used in resnet50) for maxpool is about 290K in `main`, but about 310K on this branch (fused pack_tilize with reduce). With fusing unpack_tilize with reduce, we should get execution time around 140K.

**Comment by rtawfik01** [comment]
@mywoodstock now that the fix is here: https://github.com/tenstorrent-metal/tt-metal/pull/5033, what are the updated performance numbers?
