### ISSUE TITLE
Efficientnet GS demo benchmarking [Pending CI]

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent-metal/tt-metal#4610]
GS e2e Demo

test uses batched real inputs and produces batched outputs

this test is looped (takes several batches of inputs, produces several batches of outputs)

test evaluates results of TT model against validation data in selected data set

test is documented

how to run test (commands to execute)
what does the model do (high-level explanation in a couple of sentences)
description of what is input and what is output
this demo should load inputs and expected outputs from a data set on Weka (TBD which one)

**Comment by jayasuryamaganuru** [comment]
The Benchmarking of GS EfficientNet model is completed.
Data-set: IMAGENET
Metric: Accuracy
commit [link](https://github.com/tenstorrent-metal/tt-metal/compare/main...jayasurya/efficientnet_gs_demo_benchmarking)

**Comment by jayasuryamaganuru** [comment]
PR for EffcientNet GS demo benchmarking,
model is tested with 1000 datapoints extracted from IMAGENET test dataset.
metric: accuracy
accuracy: 66.0

PR- #4633
