### ISSUE TITLE
ViT GS Demo Benchmarking [Pending CI]

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent-metal/tt-metal#4611]
GS e2e Demo

test uses batched real inputs and produces batched outputs

this test is looped (takes several batches of inputs, produces several batches of outputs)

test evaluates results of TT model against validation data in selected data set

test is documented

how to run test (commands to execute)
what does the model do (high-level explanation in a couple of sentences)
description of what is input and what is output
this demo should load inputs and expected outputs from a data set on Weka (TBD which one)

**Comment by Sudharsan-V** [comment]
The benchmarking for the ViT model is completed.
Corresponding [commit](https://github.com/tenstorrent-metal/tt-metal/commit/1dbae32bd574343fabb57a889f05451e06fccc13)

**Comment by Sudharsan-V** [comment]
The benchmarking for the Vit model using the `ImageNet` dataset is completed.
When `use_program_cache` is used in the fixtures the performance of the model is affected significantly (accuracy = 0), Hence `use_program_cache` is removed from the commit. After removing `use_program_cache`, the ViT model achieves accuracy  = 0.74.
Corresponding PR [#4749](https://github.com/tenstorrent-metal/tt-metal/pull/4749)

**Comment by saichandax** [comment]
PR merged to main. Closing the ticket.
