### ISSUE TITLE
matmul pcc at 0.93 when comparing to torch

### ISSUE THREAD

**Issue by eyonland** [tenstorrent-metal/tt-metal#4617]
The test mentioned below is on the branch eland/whisper-perf
Unfortunately the size of the tensor_a.pt and tensor_b.pt are too large to put into git so they are attached as zip files to be downloaded and placed in the same directory as the test_matmul.py under tests/ttnn/unit_tests

**Comment by eyonland** [comment]
```
def test_specific_tensor_combination(device):
    current_dir = os.path.dirname(os.path.realpath(__file__))
    tensor_file = os.path.join(current_dir, "tensor_a.pt")
    torch_input_tensor_a = torch.load(tensor_file)
    tensor_file = os.path.join(current_dir, "tensor_b.pt")
    torch_input_tensor_b = torch.load(tensor_file)

    torch_output_tensor = torch.matmul(torch_input_tensor_a, torch_input_tensor_b)

    input_tensor_a = ttnn.from_torch(torch_input_tensor_a)
    input_tensor_b = ttnn.from_torch(torch_input_tensor_b)
    input_tensor_a = ttnn.to_device(input_tensor_a, device)
    input_tensor_b = ttnn.to_device(input_tensor_b, device)

    output = ttnn.matmul(input_tensor_a, input_tensor_b)
    output = ttnn.from_device(output)
    output = ttnn.to_torch(output)

    assert len(output.shape) == len(torch_output_tensor.shape)
    assert output.shape == torch_output_tensor.shape
    assert_with_pcc(torch_output_tensor, output, 0.99)

```

**Comment by eyonland** [comment]
[tensor_b.pt.zip](https://github.com/tenstorrent-metal/tt-metal/files/13865681/tensor_b.pt.zip)



[tensor_a.pt.zip](https://github.com/tenstorrent-metal/tt-metal/files/13865682/tensor_a.pt.zip)

**Comment by eyonland** [comment]
These tensors provided for the test come directly from the whisper functional test.

**Comment by TT-BrianLiu** [comment]
What PCC do you get if you take the tensor dims and use randn as input?

**Comment by TT-BrianLiu** [comment]
Some updates:
- This is the bmm op in `tt_eager/tt_dnn/op_library/bmm/multi_core/bmm_op_multi_core.cpp`. Very simple
- With random inputs, test passes. Seems like inputs in the serialized tensors are very small.
- I tried on wormhole_b0 with fp32 accum, PCC is not much better 

Something might be sus, so I want to try to reproduce the PCC failure with similar values as the serialized tensors.

**Comment by jliangTT** [comment]
Next step: 
- compare to the FP32 in pytorch, because FP16 implementation in pytorch may be different.

**Comment by TT-BrianLiu** [comment]
Test passes if i switch to fp32 for torch matmul

**Comment by davorchap** [comment]
> Test passes if i switch to fp32 for torch matmul

Great to know. We should stay away from non-fp32 formats in torch.

**Comment by davorchap** [comment]
@arakhmati and @eyonland -- using fp32 as the go-to way of running PT data -- ok with you guys? if yes, we can close this?

**Comment by TT-BrianLiu** [comment]
only exception would be for TMs where we expect all equal compared to pytorch

**Comment by jliangTT** [comment]
Decision tree: re-run against fp32 pytorch, if the result is with 4 .9999, close; otherwise, we will plan then. 
Align that we will compare to fp32 in pytorch, and not fp16 pytorch format.

**Comment by eyonland** [comment]
I get 0.9998887677925289 with the following test. 

```
def test_specific_tensor_combination(device):
    current_dir = os.path.dirname(os.path.realpath(__file__))
    tensor_file = os.path.join(current_dir, "tensor_a.pt")
    torch_input_tensor_a = torch.load(tensor_file)
    tensor_file = os.path.join(current_dir, "tensor_b.pt")
    torch_input_tensor_b = torch.load(tensor_file)

    torch_input_tensor_a_float = torch_input_tensor_a.to(torch.float)
    torch_input_tensor_b_float = torch_input_tensor_b.to(torch.float)
    torch_output_tensor_float = torch.matmul(torch_input_tensor_a_float, torch_input_tensor_b_float)
    torch_output_tensor = torch_output_tensor_float.to(torch.bfloat16)

    input_tensor_a = ttnn.from_torch(torch_input_tensor_a)
    input_tensor_b = ttnn.from_torch(torch_input_tensor_b)
    input_tensor_a = ttnn.to_device(input_tensor_a, device)
    input_tensor_b = ttnn.to_device(input_tensor_b, device)

    output = ttnn.matmul(input_tensor_a, input_tensor_b)
    output = ttnn.from_device(output)
    output = ttnn.to_torch(output)

    assert len(output.shape) == len(torch_output_tensor.shape)
    assert output.shape == torch_output_tensor.shape
    assert_with_pcc(torch_output_tensor, output, 0.9998887677925289)

````
