### ISSUE TITLE
Performant Reshard OP

### ISSUE THREAD

**Issue by davorchap** [tenstorrent-metal/tt-metal#4641]
Currently the reshard op at the ttnn level is a composite wrapper of sharded_to_interleaved and interleaved_to_sharded.
For functionality this is great, for top-perf (RN50 10k fps), LLMs we will need a standalone high-perf re-shard kernel.

**Comment by davorchap** [comment]
@tarafdarTT should we close this case?

**Comment by tarafdarTT** [comment]
Yup closing this.
