### ISSUE TITLE
Demo for functional_Roberta

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent-metal/tt-metal#4670]
GS e2e Demo

test uses batched real inputs and produces batched outputs

this test is looped (takes several batches of inputs, produces several batches of outputs)

test evaluates results of TT model against validation data in selected data set

test is documented

how to run test (commands to execute)
what does the model do (high-level explanation in a couple of sentences)
description of what is input and what is output
this demo should load inputs and expected outputs from a data set on Weka (TBD which one)

**Comment by Sudharsan-V** [comment]
The demo for the functional Roberta model is completed. The PR is created for the same.
corresponding PR[#4718](https://github.com/tenstorrent-metal/tt-metal/pull/4718)

Note: The problems observed in the functional_bert model are mirrored in the functional_roberta model as well.
Please find the problems in functional_bert in the ticket [#4505](https://github.com/tenstorrent-metal/tt-metal/issues/4505)

**Comment by Sudharsan-V** [comment]
The demo for functiona_roberta is merged with the main.

**Comment by saichandax** [comment]
PR merged. Hence, closing the ticket.
