### ISSUE TITLE
tt_lib.logical_ori Low PCC failure [Grayskull and Wormhole] 

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent-metal/tt-metal#4674]
Logical eltwise operations `tt_lib.tensor.logical_ori` operation fails with low PCC

**To Reproduce**
Checkout `main` branch. Run unit test 

`tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_ori.py`  

```
pytest tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_ori.py
```

**Expected behavior**
There is at least one test cases per unit test expected to fail with low PCC error.

For example, one of the tests is expected to fail with this result:
```
 Max ATOL Delta: 1.0, Max RTOL Delta: inf, PCC: 0.0, PCC check failed
```

**Getting Details**
You can get more combinations tested using test sweep: `tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_wormhole/pytorch_eltwise_logical_ori.yaml` 

Result will be saved in `./result-sweeps` folder

**Comment by npetrovic-tenstorrent** [comment]
It seems to be passing now this unit test.

**Comment by npetrovic-tenstorrent** [comment]
Resolved for Grayskull.

**Comment by umadevimcw** [comment]
@npetrovic-tenstorrent is this issue resolved? I didn't find the test file to replicate this also in previous comment it is mentioned as Resolved.

**Comment by npetrovic-tenstorrent** [comment]
> @npetrovic-tenstorrent is this issue resolved? I didn't find the test file to replicate this also in previous comment it is mentioned as Resolved.

Yes, it is. I will close it. Thanks for noticing.
