### ISSUE TITLE
Profiler output not printing in jupyter notebooks for ttnn tutorials 

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent-metal/tt-metal#4679]
**Describe the bug**
Despite building with profiler enabled, when running the ttnn/tutorials notebooks, the profiler output does not print. 

**To Reproduce**
1. Go to main branch, follow the [build instructions here](https://github.com/tenstorrent-metal/tt-metal?tab=readme-ov-file#from-source), but for the build step, run [build with profiler enabled](https://github.com/tenstorrent-metal/tt-metal/blob/main/scripts/build_scripts/build_with_profiler_opt.sh)
2. launch and run ttnn/tutorial notebooks: [003.ipynb](https://github.com/tenstorrent-metal/tt-metal/blob/main/ttnn/tutorials/003.ipynb)

**Expected behavior**
See the profiler output after running the cells as follows: 

**Screenshots**
<img width="1359" alt="Screenshot 2024-01-11 at 9 10 04 AM" src="https://github.com/tenstorrent-metal/tt-metal/assets/132954887/5bfdb98b-8035-4e54-89cc-1ed47254ef02">

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit e0a98a6ced92841023bbbaa1029f43dff72226df)

**Comment by tt-rkim** [comment]
Did you run the notebook with environment variable `TT_METAL_DEVICE_PROFILER=1` enabled at startup?

**Comment by dvartaniansTT** [comment]
no, I only built it with  "make build ENABLE_PROFILER=1"

**Comment by tt-rkim** [comment]
Pls try and let us know

**Comment by arakhmati** [comment]
Hey guys,

`ENABLE_PROFILER` is not what adds the logs to the ttnn tutorials. This flag is for dumping a civ file with the profiler results

To enable the logs, run:
```
export TTNN_ENABLE_LOGGING=1
make clean
make build
``` 

It's documented here: https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/tutorials.html

**Comment by tt-rkim** [comment]
@dvartaniansTT pls try Akhmed's suggestions, read along in tutorial, and report back with what you see

**Comment by dvartaniansTT** [comment]
Thanks @arakhmati and @tt-rkim . works now!
