### ISSUE TITLE
Supporting tracing programs

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent-metal/tt-metal#4683]
For resnet, it is clear that when enqueueing a bunch of short operations in a row, we end up being host bound. To address this, we would like a mechanism to create a trace of our programs we ran and replay them. 

In this mode, once we replay a trace, we just notify the device that all the commands in the trace are available, no more creating them on the fly.

**Comment by jliangTT** [comment]
In support of metal graph

**Comment by DrJessop** [comment]
Closing since stale, I'm sure @tooniz has more specific tracing issues.
