### ISSUE TITLE
tt_lib.tensor.eltiwse_identity low PCC sweeps [Grayskull and Wormhole]

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent-metal/tt-metal#4694]
Some of the eltwise identity operation `tt_lib.tensor.eltwise_identity` cases run as sweeps fail with low PCC. However, the same cases pass within unit test

**To Reproduce**

Checkout `main` branch. 

**Run the sweeps**
You can get more combinations tested using test sweep: `tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_grayskull/pytorch_eltwise_identity_test.yam` 

Result will be saved in `./result-sweeps` folder

**Expected behavior**
There is at least one test cases per unit test expected to fail with low PCC error, but close to 0.99.

For example, one of the tests is expected to fail with this result:
```
Max ATOL Delta: 200.0, Max RTOL Delta: inf, PCC: 0.9773677395305844, PCC check failed
```

There is a unit test as well:

`tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_identity.py`  

However, the same cases that fail in sweeps do pass when unit test is run as follows.
```
pytest tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_ori.py
```

**Comment by nemanjagrujic** [comment]
Working now.
