### ISSUE TITLE
Uplift ttlib matmul to support sharding

### ISSUE THREAD

**Issue by TT-BrianLiu** [tenstorrent-metal/tt-metal#4710]
TODOs:
- [x] Add separate path for sharded tensors for `tt:tt_metal::matmul`. If both are interleaved, we use old matmul. Otherwise, we figure out matmul program configs and directly call `operations::primary::matmul`.
- [x] Same for bmm
- [ ] Test/sweep

Future TODOs:
- [ ] Deprecate `tt:tt_metal::matmul` op and have it directly call `operations::primary::matmul` for interleaved tensors. Most of the behaviour should be captured by `MatmulDefaultProgramConfig`. Basically, our matmul code should look like this throughout our whole stack:
<img width="1289" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/109366241/da191d35-1ef3-41cb-a1a2-7d927c0f5919">

- [ ] How does auto format work with sharded tensors?

**Comment by eyonland** [comment]
@TT-BrianLiu was there any remaining work on your end for this effort?

**Comment by TT-BrianLiu** [comment]
I think we can close. Right now, we are focusing on improving sharding for primary matmuls. Let's review after Javelin.
