### ISSUE TITLE
ttl.operations.primary.layernorm fails with low PCC when beta input tensor is BFLOAT8_B [Grayskull and Wormhole] 

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent-metal/tt-metal#4712]
Layenorm operation `ttl.operations.primary.layernorm` operation fails with low PCC, in case when the last input tensor - beta is BFLOAT8_B for both GS and WH.

**To Reproduce**
Checkout `npetrovic/slow-dispatch-removal` branch that will be soon merged into main. Run unit test 

`tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_bfloat8_layernorm_updated.py`  

With command
```
pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_bfloat8_layernorm_updated.py
```

**Expected behavior**
Test cases expected to fail with low PCC error.

For example, one of the tests is expected to fail with this result:
```
Max ATOL Delta: 20.485897064208984, Max RTOL Delta: inf, PCC: 0.7677724836037157, PCC check failed
```

**Getting Details**
You can get more combinations tested using test sweep: `tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_grayskull/pytorch_layernorm_test.yaml` 

or 

`tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_wormhole/pytorch_layernorm_test.yaml` 

Result will be saved in `./result-sweeps` folder

**Comment by npetrovic-tenstorrent** [comment]
Seems to be working now.

**Comment by davorchap** [comment]
@yugaoTT is this fixed?

**Comment by yugaoTT** [comment]
Hey sry about the delayed response, I found the problem, after set beta to bfp8_b, it needs to reconfigure the format back. I created the PR for fix, and when CI finishes it will be merged.

**Comment by yugaoTT** [comment]
merged, closing issue
