### ISSUE TITLE
[On Hold] llama gs demo Benchmarking

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent-metal/tt-metal#4717]
GS e2e Demo

test uses batched real inputs and produces batched outputs

this test is looped (takes several batches of inputs, produces several batches of outputs)

test evaluates results of TT model against validation data in selected data set

test is documented

how to run test (commands to execute)
what does the model do (high-level explanation in a couple of sentences)
description of what is input and what is output
this demo should load inputs and expected outputs from a data set on Weka (TBD which one)

**Comment by jayasuryamaganuru** [comment]
The Benchmarking of GS llama model is completed.
Data-set: hellaswag
Metric: bert-score
For 10 iterations the accuracy (mean of 10 bert-scores) is 0.23
commit [link](https://github.com/tenstorrent-metal/tt-metal/compare/main...jayasurya/llama_gs_demo_benchmarking)

**Comment by jayasuryamaganuru** [comment]
Commented out first and second runs in the commit at [line](https://github.com/tenstorrent-metal/tt-metal/blob/b745b5c325a24c3e3c8fe4e0adff8da79404aac5/models/experimental/llama/tests/test_perf_accuracy_llama.py#L274) .

If not encountering a segmentation fault in the third run , 
when either the first or second run has taken place in the test.

**Comment by boris-drazic** [comment]
With new work on llama implementation this is no longer relevant.
