### ISSUE TITLE
Add sweep tests for ttnn.rms_norm operation

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent-metal/tt-metal#4722]
Corresponding YAML files, operation definition and input generation functions should be added

**Comment by boris-drazic** [comment]
@npetrovic-tenstorrent is this issue still relevant?

**Comment by npetrovic-tenstorrent** [comment]
> @npetrovic-tenstorrent is this issue still relevant?

No, it is completed, and I will close it.

**Comment by npetrovic-tenstorrent** [comment]
Completed
