### ISSUE TITLE
Investigate ttnn perf pipeline hangs/board errors

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent-metal/tt-metal#4726]
Examples: 

https://github.com/tenstorrent-metal/tt-metal/actions/runs/7543257653/job/20533865375
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7541280950/job/20527667414
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7541280950/job/20527666605

ttnn tests in the perf pipeline such as bert and roberta have been leaving the machines in a bad state / hanging. This is getting more frequent.

cc: @tt-aho @arakhmati @eyonland 

@jliangTT Let me know if we need to pull some stats to see how often this is bricking the pipelines to change the priority of this.

**Comment by jliangTT** [comment]
once the pipeline is bricked, what are way to unbrick it? What is the downstream developer impact when pipeline brick the system?

**Comment by tt-rkim** [comment]
With the way the machine bricked here, we are:

- unable to detect during set up / cleanup that the machine is in a bad state
- we catch this problem during actual testing
- therefore devs have to read through error logs to see what the problem is, and may be confusing for people unfamiliar with this bad state error

Technical detail: the problem caused by these tests seems to make a memory region read at the beginning of device setup unreadable. This region is not read during SMI reset / setup, so we don't catch it in our pre/post test infra.

Per @arakhmati , we're working on moving CI around to reduce confusion / flakiness. We will talk soon on a plan and post here.

**Comment by abhullar-tt** [comment]
Another data point for this issue:
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7559993776/job/20585042467

seen for 74cc3e60bd40ad771163db8a808ed39edb4fe020

**Comment by vtangTT** [comment]
Update: ran 50 iterations on WH vm on main (```8953795```), encountered a timeout on device init on the 50th run

**Comment by davorchap** [comment]
@vtangTT can we close?

**Comment by vtangTT** [comment]
not sure, i was only asked to try to reproduce 

assigning to @jliangTT per his request for further triage

**Comment by tt-rkim** [comment]
I think we can close this as we haven't seen this in a while
