### ISSUE TITLE
metal BERT test hangs non-deterministically 

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent-metal/tt-metal#4759]
The commit in question is 1b4ed083cc973f76f7f43058d63250512f46007f.  8a3766efcdcaa219665e3324c5d7a0e43e2ec022 ran this test successfully for 20 iterations. 

`pytest models/demos/metal_BERT_large_11/tests/test_bert_batch_dram.py::test_bert_batch_dram_with_program_cache[BERT_LARGE-batch_9-BFLOAT16-DRAM]`

**Comment by DrJessop** [comment]
Just for history tracking.
- Bill did a bisect, and he originally found 1b4ed083cc973f76f7f43058d63250512f46007f to be the bad commit
- I confirmed that bert can pass 20 times in a row on the commit before this (8a3766efcdcaa219665e3324c5d7a0e43e2ec022) and that it hangs on the second iteration for me on the bad commit
- On main as of yesterday, I was seeing a hang on every iteration, so it seems like there were more issues introduced since then

I tested on Austin cloud machine, IP: 172.27.28.139

@TT-billteng @mywoodstock  please feel free to track what you have seen

**Comment by TT-billteng** [comment]
During the bisect process, running a bad commit required a full BM reset; board reset didn't help

**Comment by mywoodstock** [comment]
Current status for me:

Not able to repro the hang on `main`, or the "good" commit [8a3766e](https://github.com/tenstorrent-metal/tt-metal/commit/8a3766efcdcaa219665e3324c5d7a0e43e2ec022), or the "bad" commit [1b4ed08](https://github.com/tenstorrent-metal/tt-metal/commit/1b4ed083cc973f76f7f43058d63250512f46007f).
Tried on the following:
- my lab machine (150+ runs)
- Bill's BM (150+ runs)
- Andrew's BM (20+ runs).

It hanged once on Andrew's machine before the reboot on the "bad" commit. But not after reboot.

**Comment by vtangTT** [comment]
Update: ran 2 x 50 iterations on main (```8a3766e```) on Bill's bm and seeing timeouts on ```test_bert_batch_dram_with_program_cache[BERT_LARGE-batch_9-BFLOAT8_B-DRAM]``` after 6 successful iterations and ```test_bert_batch_dram[BERT_LARGE-batch_9-MIXED_PRECISION_BATCH9]``` after 46 successful iterations

```pytest models/demos/metal_BERT_large_11/tests/test_bert_batch_dram.py```

Now doing a rerun to see if can repro on "good" commit ```8a3766e```

**Comment by vtangTT** [comment]
haven't run this test in a while now, not sure if still non-dert hanging on main

**Comment by jliangTT** [comment]
ok thanks. Please confirmed that this test is currently disabled on the automated pipeline then, right?

pytest models/demos/metal_BERT_large_11/tests/test_bert_batch_dram.py::test_bert_batch_dram_with_program_cache[BERT_LARGE-batch_9-BFLOAT16-DRAM]

Is it possible to gather the latest status?

**Comment by vtangTT** [comment]
this test is only run on perf pipelines which are no longer part of post-commit, not sure if we've seen this failure on that side.. @TT-billteng ?

**Comment by davorchap** [comment]
@vtangTT is this still an issue after FW updates?

**Comment by vtangTT** [comment]
not sure/qualified to say, i was originally asked  to try to reproduce

assigning to @jliangTT per his request for further triage

**Comment by jliangTT** [comment]
hey @vtangTT , can you help me to reproduce this again with the latest firmware + latest rebase? we should have the 800MHz + new syseng firmware systems that we can test with.

**Comment by TT-billteng** [comment]
closing since we're unable to repro, please re-open if this is a problem
