### ISSUE TITLE
SD functional TTNN model

### ISSUE THREAD

**Issue by boris-drazic** [tenstorrent-metal/tt-metal#4765]
We have an existing implementation of Stable Diffusion (SD) in `models/experimental/stable_diffusion` implemented using TT-DNN OPs and now want to implement this model using new TTNN operations.

TTNN OPs are decomented here: https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/api.html#operations is documentation.
Some OPs are not yet in documentation, but you can find examples of uses in tests here: `tests/ttnn/unit_tests` has unit tests for TTNN operations.

You should make a new folder for functional stable diffusion (similar to functional BERT, Bloom, ...) and implement sub-graphs for SD and the whole model.

These are the sub-modules:

- [x] TtUpsampleNearest2d #4786 
- [x] TtDownsample2D #4788
- [x] TtUpsample2D #4789 
- [x] TtGEGLU #4790 
- [x] TtFeedForward #4791
- [x] TtCrossAttention #4792
- [x] TtResnetBlock2D #4793
- [x] TtDownBlock2D #4794
- [x] TtUpBlock2D #4795
- [x] TtTransformer2DModel #4796
- [x] TtBasicTransformerBlock #4797
- [x] TtCrossAttnUpBlock2D #4798
- [x] TtCrossAttnDownBlock2D #4799
- [x] TtUNetMidBlock2DCrossAttn #4800
- [x] UNet2DConditionModel #4801

**Comment by saichandax** [comment]
Current status of the SD functional TTNN Model:
All the sub-modules are complete with a draft pipeline (commits are available). Initial test results are reported in the [sheet](https://docs.google.com/spreadsheets/d/1Kx1KxHg_qf7zyK7gbxhXa-g40oFIXUpk6Wx5fIkOhMU/edit#gid=1513996761) and in respective tickets.
Some sub-modules are failing with low PCC. We've raised issues accordingly.

3 PRs have been merged for GeGLU(#4790), FeedForward(#4791), UpsampleNearest2D(#4786).

We are creating PRs for the other sub-modules.
Current work is focused on updating the current sub-modules with ttnn.conv2d and resolve any issues.
We have faced few issues with L1, sharded input. We are yet to present our observations.

Once we consolidate the observations, we'll share further details.
Thank you.

**Comment by saichandax** [comment]
All the 15 sub-modules of the SD have PRs with working commits at the top.
Currently, the sub-modules are based on fallback op for the conv. We are working on bringing up using ttnn conv.
Final sub-module has been successfully implemented as well, late Friday.
PR for the final sub-module Unet2DConditionModel is available now at #5119.
PCC for the final sub-module is at 0.77 (256x256 input) and 0.87(512x512 input).

**Comment by saichandax** [comment]
- [x] TtGEGLU #4869 [**Merged**]
- [x] TtFeedForward #4868 [**Merged**]
- [x] TtUpsampleNearest2d #4870 [**Merged**]
- [ ] TtUpsample2D #5080 
- [ ] TtResnetBlock2D #5084 
- [ ] TtDownsample2D #5090 
- [ ] TtCrossAttention #4927 
- [ ] TtDownBlock2D #5091 
- [ ] TtBasicTransformerBlock #5081 
- [ ] TtUpBlock2D #5085 
- [ ] TtTransformer2DModel #5092 
- [ ] TtCrossAttnUpBlock2D #5089 
- [ ] TtUNetMidBlock2DCrossAttn #5093 
- [ ] TtCrossAttnDownBlock2D #5086 
- [ ] UNet2DConditionModel #5119

**Comment by saichandax** [comment]
**Current status:**

- - 6 sub-modules' PRs are yet to be merged. We are rebasing the commits and checking the CI for these PRs.
- We are working on improving PCC for some of the sub-modules such as, BasicTransformerBlock, CrossAttnDownBlock2D, CrossAttnUpBlock2D, UNet2DConditionModel.
- We tried to check op-by-op, keeping all appearances of an op in torch and checking if it is the reason for drop in PCC. The experiment concluded and we didn't get major improvement with most of the ops except a marginal improvement for bmm op. Observations [here](https://docs.google.com/spreadsheets/d/1Kx1KxHg_qf7zyK7gbxhXa-g40oFIXUpk6Wx5fIkOhMU/edit#gid=1844898435)
- We will try reverse approach to check all ops in torch (as a sanity check), then keep op-by-op in ttnn to see where the PCC dips. Experiment in progress.

**Comment by saichandax** [comment]
Updates on StableDiffusion PCC debugging:
We were working on improving the PCC for the SD sub-modules.
With a [fix](https://github.com/tenstorrent-metal/tt-metal/pull/5211) in BasicTransformerBlock, we were able to achieve improved PCC in 4 sub-modules.
BasicTransformerBlock (improved 6 tests to >0.985) [ Now all cases pass with > 0.98]
Transformer2DModel (improved 5 tests to >0.99) [ Now all cases pass with > 0.99]
UNetMidBloclk2DCrossAttn (improved 2 tests to >0.99) [ Now all cases pass with > 0.99]
CrossAttnDownBlock2D (improved 2 tests to >0.98) [ Now all cases pass with > 0.98]
Results are updated in the tickets, PRs are updated with the fix. Details can be found in the [sheet](https://docs.google.com/spreadsheets/d/1Kx1KxHg_qf7zyK7gbxhXa-g40oFIXUpk6Wx5fIkOhMU/edit#gid=1513996761).
The above improvement resulted in marginal increase in PCC for final module (UNet2DConditionModel).
We are currently working on improving the PCC in CrossAttnUpBlock2D, there by improving PCC for UNet2DConditionModel.

**Comment by boris-drazic** [comment]
Can we measure PCC for sub-graphs on WH device without fallbacks.
Add results in same [sheet](https://docs.google.com/spreadsheets/d/1Kx1KxHg_qf7zyK7gbxhXa-g40oFIXUpk6Wx5fIkOhMU/edit#gid=1513996761) as before, columns labeled _Status WH_ and _Comments WH_.

**Comment by Sudharsan-V** [comment]
@boris-drazic, Currently we do not have access to the WH device, Could you please help us get access to it, or kindly let us know if there are any other ways to test it on the WH device?

**Comment by boris-drazic** [comment]
@Sudharsan-V yes, I will work on getting you WH machines today

**Comment by boris-drazic** [comment]
@Sudharsan-V 
I have created two VMs with WH cards (they have same authorized users as `tt-metal-dev-mcw-15` so you should be able to log in without password)
```
tt-metal-dev-mcw-wh-30		  ssh ubuntu@172.27.44.181
tt-metal-dev-mcw-wh-31		  ssh ubuntu@172.27.44.33
```

You can use these machines in the same way as existing VMs with GS cards, but specify `wormhole_b0` as arch.
```
cd tt-metal
export ARCH_NAME=wormhole_b0
export TT_METAL_HOME=$(pwd)
export PYTHONPATH=$(pwd)
export TT_METAL_ENV=dev
make build
source build/python_env/bin/activate
```

**Comment by jayasuryamaganuru** [comment]
@boris-drazic measured the PCC of sub-graphs on WH device and added the observations in the [sheet](https://docs.google.com/spreadsheets/d/1Kx1KxHg_qf7zyK7gbxhXa-g40oFIXUpk6Wx5fIkOhMU/edit#gid=1513996761)

**Comment by Sudharsan-V** [comment]
The comprehensive results and observations from the Stable Diffusion demo have been added to ticket [#5372](https://github.com/tenstorrent-metal/tt-metal/issues/5372)

**Comment by Sudharsan-V** [comment]
The pcc on GS and WH for all the sub-graphs are measured and the results are updated in the sheet.
PFA the link for the sheet [here](https://docs.google.com/spreadsheets/d/1Kx1KxHg_qf7zyK7gbxhXa-g40oFIXUpk6Wx5fIkOhMU/edit#gid=1513996761)
