### ISSUE TITLE
Change profiler scripts to handle hungs

### ISSUE THREAD

**Issue by banekg** [tenstorrent-metal/tt-metal#4778]
Change profiler scripts to handle hangs, because we want that AWX should be able to proceed with other tests from folder.

**Comment by jliangTT** [comment]
Can you provide the step to reproduce?

**Comment by boris-drazic** [comment]
@jliangTT yes, the assignee is correct. This is issue specific to test infra Syrmia team has built, it is not about general hangs in tests.

**Comment by jliangTT** [comment]
understood.
