### ISSUE TITLE
SD TTNN: TtGEGLU

### ISSUE THREAD

**Issue by boris-drazic** [tenstorrent-metal/tt-metal#4790]
Implement subgraph `TtGEGLU` and make two tests: one for 256x256 image size and one for 512x512 image size.
Have one test file named something like `test_ geglu.py` and inside it two tests `test_geglu_256x256` and `test_geglu_512x512`. Tests should be parametrized with following input shapes:

- [x] Shape 1:  **256x256**
    - [x] hidden_states case 1: [1, 2, 1024, 320]
    - [x] hidden_states case 2: [1, 2, 256, 640]
    - [x] hidden_states case 3: [1, 2, 64, 1280]
    - [x] hidden_states case 4: [1, 2, 16, 1280]

- [x] Shape 2:  **512x512**
    - [x] hidden_states case 1: [1, 2, 4096, 320]
    - [x] hidden_states case 2: [1, 2, 1024, 640]
    - [x] hidden_states case 3: [1, 2, 256, 1280]
    - [x] hidden_states case 4: [1, 2, 64, 1280]

**Comment by Sudharsan-V** [comment]
@boris-drazic, Implementing GEGLU using ttnn for the Stable diffusion model is nearly done.
Corresponding [Commit (WIP)](https://github.com/tenstorrent-metal/tt-metal/commit/39c832139727207d955010ec9f5c1a7f479b8031)

During implementation, we encountered the following issues:
1) While pre-processing the model parameters using `preprocess_model_parameters`, we faced the following issue in the conv op.
```
if not named_children:

      if isinstance(model, torch.nn.Linear):
        parameters = {"weight": model.weight.T.contiguous()}
        if model.bias is not None:
          parameters["bias"] = model.bias
        return make_parameter_dict(parameters)
      elif isinstance(model, torch.nn.Conv2d):
>        raise RuntimeError("Transpose conv weights?")
E        RuntimeError: Transpose conv weights?
```

2)  When tested GEGLU with ttnn.linear, we are getting pcc in the range ~[0.6 - 0.75], when replaced ttnn.linear with matmul and add, the pcc increased to 0.99.

**Comment by saichandax** [comment]
PR merged, hence closing the ticket.
