### ISSUE TITLE
SD TTNN: TtFeedForward

### ISSUE THREAD

**Issue by boris-drazic** [tenstorrent-metal/tt-metal#4791]
Implement subgraph `TtFeedForward` and make two tests: one for 256x256 image size and one for 512x512 image size.
Have one test file named something like `test_feed_forward.py` and inside it two tests `test_feed_forward_256x256` and `test_feed_forward_512x512`. Tests should be parametrized with following input shapes:

- [x] Shape 1:  **256x256**
    - [x] hidden_states case 1: [1, 2, 1024, 320]
    - [x] hidden_states case 2: [1, 2, 256, 640]
    - [x] hidden_states case 3: [1, 2, 64, 1280]
    - [x] hidden_states case 4: [1, 2, 16, 1280]

- [x] Shape 2:  **512x512**
    - [x] hidden_states case 1: [1, 2, 4096, 320]
    - [x] hidden_states case 2: [1, 2, 1024, 640]
    - [x] hidden_states case 3: [1, 2, 256, 1280]
    - [x] hidden_states case 4: [1, 2, 64, 1280]

**Comment by Sudharsan-V** [comment]
The feedforward sub-module using ttnn ops for the stable diffusion model is completed.
Corresponding [commit](https://github.com/tenstorrent-metal/tt-metal/commit/1a2b8cae5878baaee9fb4220cffd8037bfda4d6d)

Using ttnn.linear op in the feedforward submodule reduces the pcc significantly. Hence replaced linear with matmul and add op.
ttnn.linear affects the result of geglu submodule as well and it is briefly discussed in the ticket [#4790](https://github.com/tenstorrent-metal/tt-metal/issues/4790)

**Comment by saichandax** [comment]
PR merged, closing the ticket.
