### ISSUE TITLE
dprint support for src/dst Tensix registers

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent-metal/tt-metal#4809]
Currently there is no visibility into the Tensix srca/srcb/destination registers.  This feature request is to add dprint support for those registers.

That register has no data path back to L1, however, there is access through reading/writing debug registers.
This has to be done w/ care: accessing those while the chip is active may result in a hang.

Some notes below from Alex:
BUDA APIs are also added for each thread src/ckernels/grayskull/buda/llk_api/llk_*_api.h
At the moment the expectation is that dump works at the tile level granularity. If we want to go deeper which would allow us to dump data after every instruction we would need to break down mops.

You can implement HLK funcs as

dbg_thread_halt() {
 PACK ((llk_pack_thread_halt()))
 UNPACK (( llk_unpack_thread_halt()))
 MATH (( llk_math_thread_halt()))
}

dbg_thread_unhalt() {
 PACK ((llk_pack_thread_unhalt()))
 UNPACK (( llk_unpack_thread_unhalt()))
 MATH (( llk_math_thread_unhalt()))
}

dbg_thread_dump_dest_acc_row(int row_addr) {
 MATH (( llk_math_dump_dest_acc_row(row_addr))))
}

dbg_thread_dump_srca_row(int row_addr, int bank) {
 MATH (( llk_math_dump_srca_row(row_addr, bank))))
}

dbg_thread_dump_srcb_row(int row_addr, int bank) {
 MATH (( llk_math_dump_srcb_row(row_addr, bank))))
}

**Comment by davorchap** [comment]
@tt-dma will you be working on this soon (this / next) week?

**Comment by tt-dma** [comment]
> @tt-dma will you be working on this soon (this / next) week?

Not currently, plan is to be working on watcher features for the next while, let me know if this is higher priority

**Comment by miacim** [comment]
Currently only dest register print is supported using hlk function ```dprint_tensix_dest_reg```. Printing SrcA and SrcB are moved under #6195 

exaple.
```cpp
acquire_dst(tt::DstMode::Half);

// Pop tile after tile, copy to DST and pack
cb_wait_front(tt::CB::c_in0, 1);
cb_reserve_back(tt::CB::c_out0, 1);
copy_tile(tt::CB::c_in0, 0, 0);

// PRINT DEST
dprint_tensix_dest_reg();

pack_tile(0, tt::CB::c_out0);

cb_pop_front(tt::CB::c_in0, 1);
cb_push_back(tt::CB::c_out0, 1);

release_dst(tt::DstMode::Half);
```
