### ISSUE TITLE
Sharded tensor to/from device not supported for certain tensor shapes

### ISSUE THREAD

**Issue by tt-nshanker** [tenstorrent-metal/tt-metal#4811]
There are 2 issues with using .to(..) api for sharded tensors -
1. copying input tensor to device with sharded spec before running the conv op results in incorrect output. Bad pcc.
2. copying sharded tensor from device to host results in an assertion - TT_ASSERT @ tt_metal/impl/dispatch/command_queue.cpp:832: dev_page_id < num_pages and dev_page_id >= 0

The above issues can be reproduced with conv unit test -`test_optimized_conv_v2.py`. The input and output transfers to/from device are hidden from the user and is implemented in `tt_py_composite_conv.py` with `copy_input_to_device_with_sharded_api` and `copy_output_from_device_with_sharded_api`. @tarafdarTT Please take a look at these functions and let me know if you have any questions. 
Currently, the conv test copies the tensor to device with interleaved mem config and then calls interleaved_to_sharded and this works. But, using the sharded api directly has issues.

Steps to reproduce issue 1:
1. Go to 'tests/tt_eager/python_api_testing/unit_testing/test_optimized_conv_v2.py'
2. Replace `copy_input_to_device(` to `copy_input_to_device_with_sharded_api(`
3. Run: pytest tests/tt_eager/python_api_testing/unit_testing/test_optimized_conv_v2.py::test_optimized_conv_v2[LoFi-activations_BFLOAT16-weights_BFLOAT16-8-512-512-7-7-3-3-1-1-1-1-False]
5. See error - bad pcc

Steps to reproduce issue 2:
1. Go to 'tests/tt_eager/python_api_testing/unit_testing/test_optimized_conv_v2.py'
2. Replace `copy_output_from_device(` to `copy_output_from_device_with_sharded_api(`
3. Run: pytest tests/tt_eager/python_api_testing/unit_testing/test_optimized_conv_v2.py::test_optimized_conv_v2[LoFi-activations_BFLOAT16-weights_BFLOAT16-8-512-512-7-7-3-3-1-1-1-1-False]
5. See assertion error - TT_ASSERT @ tt_metal/impl/dispatch/command_queue.cpp:832: dev_page_id < num_pages and dev_page_id >= 0

**Comment by tt-nshanker** [comment]
Notes:
We only see the issue with BLOCK_SHARDING and not HEIGHT_SHARDING.

**Comment by jliangTT** [comment]
hey @tt-nshanker, this issue has gone quite stale. Is it still valid and any action being taken on it?

**Comment by tt-nshanker** [comment]
This is still valid. Issue was seen in unit tests so far so we didn't bump up priority. @nsmithtt sees something similar in a Unet model test so I think it should be bumped up.

**Comment by jvasilje** [comment]
@tarafdarTT can you address this one tomorrow? It's almost 2mo old! :/

**Comment by tarafdarTT** [comment]
@tt-nshanker I think I fixed the bug using this PR : https://github.com/tenstorrent-metal/tt-metal/pull/6381

I had trouble recreating the tests above. could you see if cherry-picking the commit in my PR fixes it?
