### ISSUE TITLE
Add cumsum op to tt_dnn

### ISSUE THREAD

**Issue by dongjin-na** [tenstorrent-metal/tt-metal#4821]
We need to implement a cumsum operation that supports the torch.cumsum method.
This mean op should support both forward and backward operations.
https://pytorch.org/docs/stable/generated/torch.cumsum.html

**Comment by blozano-tt** [comment]
@dongjin-na @ayerofieiev-tt 

Why are there no include guards or #pragma once here?

Asking for a friend: @dmakoviichuk-tt

**Comment by ayerofieiev-tt** [comment]
@blozano-tt , there should be pragma once. 
There is no infra to prevent you from making this mistake.
And because it's a kernel code, you won't even notice, because the object file is small and unlikely to include same header twice.

**Comment by dongjin-na** [comment]
@blozano-tt, thanks for the check.
I also found another header that doesn’t have #pragma once.
I will add it.
