### ISSUE TITLE
Bring up ttnn Mistral

### ISSUE THREAD

**Issue by farbabi** [tenstorrent-metal/tt-metal#4854]
This issue is to bring up mistral 7b on ttnn

**Comment by Sudharsan-V** [comment]
mistral_transformer_block sub-module is completed.
Corresponding [commit](https://github.com/tenstorrent-metal/tt-metal/commit/b964a43646f40821493c635cf966c0e009297cfa)

**Comment by farbabi** [comment]
> Completed implementing mistral transformer using ttnn. Corresponding: [commit](https://github.com/tenstorrent-metal/tt-metal/compare/main...sudharsan/mistral_ttnn_transformer)
> 
> The mistral transformer test is configured to use only a single layer because the model_preprocessing method encounters an Out-of-memory error when processing the parameters of the entire model.
> 
> ```
> E       RuntimeError: TT_THROW @ tt_metal/impl/allocator/allocator.cpp:96: tt::exception
> E       info:
> E       Out of Memory: Not enough space to allocate {} B {} buffer across {} banks, where each bank needs to store {} B
> E       8388608
> E       DRAM
> E       8
> E       1048576
> ```
> 
> Moreover, using ttnn.permute in the mistral attention sub-modules throws the following error from `ttnn/ttnn/operations/data_movement.py:158`
> 
> ```
>             def torch_permute(tensor, order):
>                 return tensor.permute(order).contiguous().clone()
>     
> >           tensor = ttnn.to_torch(tensor)
> E           UnboundLocalError: local variable 'tensor' referenced before assignment
> ```
> 
> changing `tensor = ttnn.to_torch(tensor)` to `tensor = ttnn.to_torch(input_tensor)` resolves this issue.
> 
> Please find below, pcc of the mistral ttnn sub-modules:
> 
> * rms_norm > 0.99
> * attention > 0.98
> * feed_forward > 0.99
> * transformer_block > 0.99
> * transformer with single layer > 0.98

@Sudharsan-V how much free RAM does your VM have? For tt_lib version we needed to have >128GB free RAM, have you tested on VMs with large RAM?

**Comment by Sudharsan-V** [comment]
Created PR for all the sub-modules of the mistral transformer.
PFB the sub-modules and corresponding PR.
attention and rms_norm sub-modules: [#5157](https://github.com/tenstorrent-metal/tt-metal/pull/5175)
feed_forward sub-module: [#5176](https://github.com/tenstorrent-metal/tt-metal/pull/5176)
transformer_block sub-module: [#5177](https://github.com/tenstorrent-metal/tt-metal/pull/5177)
transformer(single layer): [#5178](https://github.com/tenstorrent-metal/tt-metal/pull/5178)

**Comment by Sudharsan-V** [comment]
> > Completed implementing mistral transformer using ttnn. Corresponding: [commit](https://github.com/tenstorrent-metal/tt-metal/compare/main...sudharsan/mistral_ttnn_transformer)
> > The mistral transformer test is configured to use only a single layer because the model_preprocessing method encounters an Out-of-memory error when processing the parameters of the entire model.
> > ```
> > E       RuntimeError: TT_THROW @ tt_metal/impl/allocator/allocator.cpp:96: tt::exception
> > E       info:
> > E       Out of Memory: Not enough space to allocate {} B {} buffer across {} banks, where each bank needs to store {} B
> > E       8388608
> > E       DRAM
> > E       8
> > E       1048576
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Moreover, using ttnn.permute in the mistral attention sub-modules throws the following error from `ttnn/ttnn/operations/data_movement.py:158`
> > ```
> >             def torch_permute(tensor, order):
> >                 return tensor.permute(order).contiguous().clone()
> >     
> > >           tensor = ttnn.to_torch(tensor)
> > E           UnboundLocalError: local variable 'tensor' referenced before assignment
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > changing `tensor = ttnn.to_torch(tensor)` to `tensor = ttnn.to_torch(input_tensor)` resolves this issue.
> > Please find below, pcc of the mistral ttnn sub-modules:
> > 
> > * rms_norm > 0.99
> > * attention > 0.98
> > * feed_forward > 0.99
> > * transformer_block > 0.99
> > * transformer with single layer > 0.98
> 
> [@Sudharsan-V](https://github.com/Sudharsan-V) how much free RAM does your VM have? For tt_lib version we needed to have >128GB free RAM, have you tested on VMs with large RAM?

Yes, @farbabi , using high-ram VM. But while moving the parameters to the device, encountered Out Of Memory Error.

**Comment by Sudharsan-V** [comment]
Demo for ttnn mistral model is completed.
Corresponding PR [#5338](https://github.com/tenstorrent-metal/tt-metal/pull/5338)

**Comment by yieldthought** [comment]
There are a million reviewers for these PRs that are blocking a merge to main. I don't have time to wait for them, this code doesn't affect anything else. I have cherry-picked these commits to our WIP branch for mixtral bringup and am adapting the code there to run on wormhole_b0 and will look at optimizing it for performance today.
If these changes ever make it to main independently I'll figure out the merge conflicts then.

**Comment by jliangTT** [comment]
I think with javelin, this is no long relevant. I think we can close this. We can re-open if need to be.
