### ISSUE TITLE
[Bug Report] test_moreh_layernorm hanging fast dispatch post commit pipelines

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent-metal/tt-metal#4862]
**Describe the bug**
test_moreh_layernorm hanging every time on fast dispatch post commit

**To Reproduce**
I tried locally running 
`tests/tt_eager/python_api_testing/unit_testing/test_moreh_layernorm.py::test_moreh_layernorm[input_shape0-elementwise_affine=False-W-1e-5]`
and it passed, so not sure if non-deterministic. Either way, on pipelines, it always hangs.

**Screenshots**
<img width="775" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/33402477/d9110941-db63-405c-9d36-7fe27ead80aa">

**Comment by seunghwan100** [comment]
I can't reproduce the hang locally. 
How can I debug it?

**Comment by TT-billteng** [comment]
This test also hung the stress test pipeline: https://github.com/tenstorrent-metal/tt-metal/actions/runs/7606330103

Try running the test in a loop using a bash script or pytest-repeat

You can also try running with `TT_METAL_WATCHER=30 <pytest command>` as stress test pipeline runs with it

**Comment by TT-billteng** [comment]
also did you just disable the wrong test? @DrJessop shows in his screenshot that the failing test is `test_moreh_layernorm.py`

**Comment by seunghwan100** [comment]
> also did you just disable the wrong test? @DrJessop shows in his screenshot that the failing test is `test_moreh_layernorm.py`

I found that the ```test_moreh_clip_grad_norm_with_error_if_nonfinite``` in ```test_moreh_clip_grad_norm.py``` causes hang
So I disable the ```test_moreh_clip_grad_norm_with_error_if_nonfinite```

**Comment by TT-billteng** [comment]
ok great thx
