### ISSUE TITLE
[Feature Request] SFPI Open Sourcing

### ISSUE THREAD

**Issue by jliangTT** [tenstorrent-metal/tt-metal#4863]
**Is your feature request related to a problem? Please describe.**
SFPI open sourcing on Tenstorrent Discord.

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by jliangTT** [comment]
c.c. @pgkeller @tt-rkim @davorchap 

This is in-planning. Solution is under discussion.

**Comment by pgkeller** [comment]
Buda is open sourcing soon and will update sfpi to use sfpi from github.  Future development of sfpi/gcc can happen on github instead of gitlab, this will simplify the release process quite a bit.  I'm thinking rather than squashing the commits to date, just pushing them all, that'll keep everything in sync.  Not ideal in some ways, but...oh well.

Next step is to create the 4 repos.  @tt-rkim is that something you can do?

**Comment by tt-rkim** [comment]
That sounds fantastic @pgkeller 

Let me know whenever you'd like me to make them. Just got to click a couple buttons and make you admin.

**Comment by pgkeller** [comment]
Go ahead and make them, I'll try to get this done by the end of the week

**Comment by tt-rkim** [comment]
<img width="352" alt="Screen Shot 2024-01-23 at 3 03 43 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/109366641/fde6074a-b2d6-442e-85aa-4e9085e3731d">

Done @pgkeller and you're maintainer. All GIthub actions disabled on these repos

**Comment by pgkeller** [comment]
This is done.  While working on it, I found myself slightly regretting our module names as being under-qualified.  If we want to change anything, now is the time.  I'm thinking something like:
sfpi
sfpi-tt-gcc
sfpi-gcc
sfpi-binutils

Thoughts?
@davorchap @tt-rkim

**Comment by tt-rkim** [comment]
I am very very much a fan of qualified names. @pgkeller 

I'd invite @TT-billteng 's opinion too

**Comment by pgkeller** [comment]
if we can rename on github keeping the content I can just force push the last commit which changed the submodule locations.

**Comment by pgkeller** [comment]
let's go ahead and do the rename.  @tt-rkim is that a delete and redo or can the modules be renamed?  let me know when its done and I'll fix the contents.  thanks.

**Comment by tt-rkim** [comment]
@pgkeller it's done - let me know if it doesn't look good

**Comment by TT-billteng** [comment]
What's the difference between sfpi-tt-gcc and sfpi-gcc  ?

looks good otherwise

**Comment by pgkeller** [comment]
gcc is a submodule of gcc, unfortunately.  sfpi renames the top level tt-gcc

**Comment by pgkeller** [comment]
this is done
