### ISSUE TITLE
model_preprocessing fails to preprocess conv weights

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent-metal/tt-metal#4878]
**Describe the bug**
While preprocessing the stable diffusion model's parameters, the method  `_preprocess_model_parameters` in                         
 `tt-metal/ttnn/model_preprocessing.py` throws `RuntimeError: Transpose conv weights?`

**To Reproduce**
1. Pick the files from the PR https://github.com/tenstorrent-metal/tt-metal/pull/4869
2. Replace 
```
    parameters = preprocess_model_parameters(
        initialize_model=lambda: ref_model,
        device=device,
    )
```
with 
```
    parameters = preprocess_model_parameters(
        initialize_model=lambda: model,
        device=device,
    )
```
in `tests/ttnn/integration_tests/stable_diffusion/test_geglu.py` and run the test.

**Expected behavior**
Expecting the preprocess the input parameters of the model.

**Screenshots**
Encountered the following error:
```
if not named_children:

      if isinstance(model, torch.nn.Linear):
        parameters = {"weight": model.weight.T.contiguous()}
        if model.bias is not None:
          parameters["bias"] = model.bias
        return make_parameter_dict(parameters)
      elif isinstance(model, torch.nn.Conv2d):
>        raise RuntimeError("Transpose conv weights?")
E        RuntimeError: Transpose conv weights?
```

**Comment by arakhmati** [comment]
Here is the PR with the fix: https://github.com/tenstorrent-metal/tt-metal/pull/4966

I think the API can be improved by breaking down the functionality of Conv2D into 2 parts:
1. Creating weights
2. Creating the function to run
@tt-nshanker

**Comment by arakhmati** [comment]
PR #4966 has been merged. Please refer to `tests/ttnn/unit_tests/test_preprocess_model_parameters.py` for an example of how use `preprocess_model_parameters` with convolutions. I believe this issue can be closed now.

And I have added a new issue for simplifying the API: #5002
