### ISSUE TITLE
Runtime error: Placing Row-Major Tensor on Device

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent-metal/tt-metal#4880]
**Describe the bug**
Encountered a runtime error while trying to place a row-major tensor with a shape of (1280, 1280, 3, 3) onto a device.

**To Reproduce**
The following unit test will reproduce the issue mentioned above.
```
def test_row_major_device(device):
    input = torch.rand(1280, 1280, 3, 3)
    input = ttnn.from_torch(input, ttnn.bfloat16)
    input = ttnn.to_layout(input, ttnn.ROW_MAJOR_LAYOUT)
    input = ttnn.to_device(input, device, memory_config=ttnn.DRAM_MEMORY_CONFIG)
```

**Screenshots**
When attempting to place the row-major tensor on the device, we encountered the following issue.
```
>       return Tensor(ttl_tensor.to(device, memory_config))
E       RuntimeError: TT_FATAL @ tt_metal/impl/buffers/buffer.cpp:30: page_size % sizeof(uint32_t) == 0
E       info:
E       Page size must be divisible by sizeof(uint32_t) because buffers hold uint32_t values
E       backtrace:
E        --- tt::tt_metal::Buffer::Buffer(tt::tt_metal::Device*, unsigned long, unsigned long, tt::tt_metal::BufferType, tt::tt_metal::TensorMemoryLayout, std::optional<tt::tt_metal::ShardSpecBuffer>)
```

**Comment by boris-drazic** [comment]
@Sudharsan-V What OP is consuming output of this? Can we try and use tile layout?

**Comment by Sudharsan-V** [comment]
@boris-drazic, This issue is not directly related to any op.
Conv op expects the weight tensor to be in the ROW_MAJOR layout. When the layout of the weight tensor is set to ROW_MAJOR, the method `move_to_device` in the `preprocess_model_parameters` throws the above mentioned error.

**Comment by jliangTT** [comment]
@arakhmati / @eyonland, this currently blocks the SD functionality. Can you take a look and suggest the next step?

c.c. @tt-nshanker

**Comment by eyonland** [comment]
It is not possible to create a tensor with dtype bfloat16 with ROW_MAJOR_LAYOUT when the width is not even.   The only solution is to use TILE_LAYOUT with padding.

**Comment by eyonland** [comment]
The action item here will be to add documentation explaining this.

**Comment by jliangTT** [comment]
@tt-nshanker, please review the latest comment while @eyonland and @arakhmati looks to update the documentation.

**Comment by arakhmati** [comment]
We updated tensor documentation for data type to specify the multiple of width required by each data type when using ROW_MAJOR layout: https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/tensor.html#data-type

The documentation will be up-to-date once this pipeline finishes: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8253862049/job/22576685362
