### ISSUE TITLE
[Bug Report] Investigate if uni/multicast microbenchmark cycle bounds need to be lowered

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent-metal/tt-metal#4898]
The microbenchmarks have been failing for over a week. The specific test that seems to fail every time is `test_noc_unicast_vs_multicast_to_single_core_latency`.

However, we seem to have actually sped up a microbenchmark and are now falling outside of the expected lower bound for number of cycles for `test_noc_unicast_vs_multicast_to_single_core_latency`.

```
test_noc_unicast_vs_multicast_to_single_core_latency:45 - Unicast cycles not within bounds. Received 245, was expecting between 330 and 400
```

We consistently seem to be falling under 300 cycles.

Commit `cfac2137c263f21ffaf048fa1cfe66a146bfa62b` seem to pass, but then soon after at `243b1aa36e44d2629eca55fe451812a61f92fee2` this is where the bounds seem to fail.

cc: @yugaoTT @davorchap @mo-tenstorrent @DrJessop

**Comment by tt-rkim** [comment]
@mo-tenstorrent @DrJessop Are we lowering the bounds or no?

**Comment by DrJessop** [comment]
I can lower the bounds. This is a good thing that the latency improved.

**Comment by DrJessop** [comment]
Running ubenchmark on https://github.com/tenstorrent-metal/tt-metal/pull/4937

**Comment by DrJessop** [comment]
Closing this issue, https://github.com/tenstorrent-metal/tt-metal/pull/4937 merged.
