### ISSUE TITLE
Runtime error: ttnn.add fails with tensor on host

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent-metal/tt-metal#4899]
**Describe the bug**
The runtime error in the addition operation occurs when the tensor, initially with a shape of (1, 1, 2, 1280), is permuted to (2, 1280, 1, 1) is transferred to host. The addition operation expects the tensor to be on the device, leading to the encountered error.

**To Reproduce**
Run the following test to reproduce the issue.
```
def test_add(device):
    hidden_states=torch.randn(2,1280,8,8)
    temb=torch.randn(1,1,2,1280)
    hidden_states = ttnn.from_torch(hidden_states, layout=ttnn.TILE_LAYOUT, device=device, dtype=ttnn.bfloat16)
    temb = ttnn.from_torch(temb, layout=ttnn.ROW_MAJOR_LAYOUT, device=device, dtype=ttnn.bfloat16)
    temb=ttnn.permute(temb,(2,3,0,1))
    output=hidden_states+temb
```

**Screenshots**
```
            input_tensor_b = ttnn.unsqueeze_to_4D(input_tensor_b)
            ttl_input_tensor_b = input_tensor_b.value
            if ttl_input_tensor_b.storage_type() != ttl.tensor.StorageType.DEVICE:
>               raise RuntimeError("input_tensor_a must be on device!")
E               RuntimeError: input_tensor_a must be on device!
```

**Comment by eyonland** [comment]
Trying to do a permute with a ROW_MAJOR layout can through it off device if the width is not a multiple of 2.  I realize the documentation needs to be a bit more clear here: [https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/tensor.html](https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/tensor.html)

I think the correct way to handle this is to use TILE_LAYOUT instead.   In this case permute would operate on the intended shape.   The result of the permute operation on the intended shape could require padding which will automatically be done for TILE_LAYOUT.  At the moment the code will convert to ROW_MAJAOR_LAYOUT underneath if the width and height have padding but will convert it back to TILE_LAYOUT before returning.   This should unblock your efforts for now until we get this code pushed back into the op itself.
 
See test [https://github.com/tenstorrent-metal/tt-metal/pull/4951/files#diff-e8e0e0582f3cda84e2715528c5d320beee5f3c5528d5251e1c705563277be8ee](https://github.com/tenstorrent-metal/tt-metal/pull/4951/files#diff-e8e0e0582f3cda84e2715528c5d320beee5f3c5528d5251e1c705563277be8ee)

**Comment by Sudharsan-V** [comment]
@eyonland, the above-suggested approach helped us to resolve this issue.
Thank you!!

**Comment by eyonland** [comment]
My position on this that that permute op should be updated to support the intended shape and not the full shape.

**Comment by jliangTT** [comment]
hey this issue has gone pretty stale (more than 1.5 month old). @Sudharsan-V , is this issue resolved? what is still pending?

**Comment by Sudharsan-V** [comment]
@jliangTT, the problem was resolved after implementing Eyon's [suggestions](https://github.com/tenstorrent-metal/tt-metal/issues/4899#issuecomment-1911230234).

**Comment by umadevimcw** [comment]
The fix is merged with the main. Closing this issue.
