### ISSUE TITLE
LLK support for Blackhole

### ISSUE THREAD

**Issue by davorchap** [tenstorrent-metal/tt-metal#4900]
LLK common submodule  work still in progress by LLK team

**Comment by smehtaTT** [comment]
3/22 update from Reem - BH submodule ready, pending feedback from @olofj to publish it externally - https://github.com/tenstorrent/tt-llk-bh 
FYI - This is already public in Budabackend.

**Comment by rtawfik01** [comment]
@davorchap the llk blackhole submodule is ready here: #7031 ; however, what is the status of blackhole across the stack? I can add the submodule but it also needs llk wrappers, but these wrappers will need to be tested for correctness. Let me know if youd like me to merge the submodule first, then add the wrappers once we have the blackhole arch compiling across the stack

**Comment by tt-rkim** [comment]
https://github.com/tenstorrent-metal/tt-metal/issues/5174 updates here
