### ISSUE TITLE
test_optimized_conv_v2.py test not pass

### ISSUE THREAD

**Issue by hschoi4448** [tenstorrent-metal/tt-metal#4925]
I tested the convolution of several models, but the test fails.

for test copy and paste right most column value to 'test_optimized_conv_v2.py'

https://docs.google.com/spreadsheets/d/1SdXlC4XQzIhkGZOWZoRT1dn3VYrWmcqi_jHnARJJFpc/edit#gid=0

**Comment by jliangTT** [comment]
@shwetankTT @nsmithtt @hschoi4448  can we close this in lieu of the other issue https://github.com/tenstorrent-metal/tt-metal/issues/4974? It seems to be the same topic.

**Comment by nsmithtt** [comment]
Closing this issue, tracking moved here https://github.com/tenstorrent-metal/tt-metal/issues/4974
