### ISSUE TITLE
watcher: add watcher assert

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent-metal/tt-metal#4940]
Implement a macro, enabled when watcher is enabled, disabled when watcher is disabled that:
 - grabs the line number at compile time
 - checks the supplied condition at run time
 - if the condition fails, puts the condition into L1 and hangs so host watcher can poll
 - host throws an error with the assert info
I suspect these could be used fairly heavily, I don't think the assert should contain a string as memory is scarce.  Final report will be kernel path and line number.

**Comment by tt-dma** [comment]
PR: https://github.com/tenstorrent-metal/tt-metal/pull/6175 implements this. See  #6098 too improve this feature further
