### ISSUE TITLE
watcher: check if noc transfers meet alignment requirements

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent-metal/tt-metal#4947]
Currently, noc transactions are sanitized  for core and address range (address+size) only.  Noc also has alignment restrictions.  This rfe is to update watcher to track the alignment restrictions for each transaction type (L1, DRAM, PCIe).

**Comment by tt-dma** [comment]
PR https://github.com/tenstorrent-metal/tt-metal/pull/5998 implements this
