### ISSUE TITLE
Reduce number of tests that run in slow dispatch mode

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent-metal/tt-metal#4958]
I believe we are over-testing SD mode with the python unit tests. I think we should split the `post_commit` step in `run_test.sh` into  `post_commit_cpp` and `post_commit_py`. 

For SD mode in the post-commit action, we test with only `post_commit_cpp`.

For FD mode in the post-commit action, we test with both.

**Comment by abhullar-tt** [comment]
Slow dispatch tests under `tests/tt_metal/tt_metal/unit_tests`

Tests that require Device initialization but do not run on device
- tests/tt_metal/tt_metal/unit_tests/allocator/*
- tests/tt_metal/tt_metal/unit_tests/basic/test_soc_descriptor.cpp
- tests/tt_metal/tt_metal/unit_tests/multichip/device_cluster_api.cpp
- tests/tt_metal/tt_metal/unit_tests/basic/test_noc.cpp

Host only tests:
- tests/tt_metal/tt_metal/unit_tests/core_coord/*
- tests/tt_metal/tt_metal/unit_tests/host_apis

Not slow dispatch specific and can be migrated to use fast dispatch APIs:
- tests/tt_metal/tt_metal/unit_tests/basic/runtime_args.cpp
- tests/tt_metal/tt_metal/unit_tests/basic/initialize_semaphores.cpp
- tests/tt_metal/tt_metal/unit_tests/buffer/test_banked.cpp
- tests/tt_metal/tt_metal/unit_tests/circular_buffer/*
- tests/tt_metal/tt_metal/unit_tests/basic/device.cpp (many of these tests just do directed dram/l1 read/writes)
- tests/tt_metal/tt_metal/unit_tests/dram/direct.cpp

**Comment by TT-billteng** [comment]
@abhullar-tt are there any remaining tests in the SD suite if you strip out the ones you listed?

**Comment by abhullar-tt** [comment]
> @abhullar-tt are there any remaining tests in the SD suite if you strip out the ones you listed?

yeah there are the non-gtests which Ill go over (and should be updated to gtests)

**Comment by TT-billteng** [comment]
SD tests run on every commit has been greatly reduced
