### ISSUE TITLE
maxpool2D in TTNN should be supported for shallow depths too ( < 32)

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent-metal/tt-metal#5017]
**Describe the bug**
maxpool2D current requires channel depths to be >=32. We need support for shallow depths as well

please see the model summary here: [model summary](https://docs.google.com/document/d/1gd3Ue9_ljhDGlhWiuCvz4rG2Yx-q3THMJgRKDX5hXMo/edit)

also see, [model status](https://docs.google.com/spreadsheets/d/1yA6kq0BS8nb4wiHxdY1KOqOhIuqUsj_UY28tC1wFJqo/edit#gid=1630505613)

**Comment by jliangTT** [comment]
changing this from a bug to feature. Let me know if you disagree

**Comment by dvartaniansTT** [comment]
This is resolved for the shallow UNet. However, we still are debugging the bad PCC for the end to end model. Maxpool was contributing to bad PCC as well but now seems to be resolved at least for the max pool ops. @tapspatel and @nsmithtt Do you think we can close this issue now?

**Comment by nsmithtt** [comment]
Supported added w/ 9be4a81026

**Comment by nsmithtt** [comment]
Dup of https://github.com/tenstorrent-metal/tt-metal/issues/4954
