### ISSUE TITLE
Asking for loading kernels to all active eth cores causes some tensix cores to stop running FW

### ISSUE THREAD

**Issue by mo-tenstorrent** [tenstorrent-metal/tt-metal#5028]
As part of profiler unit test, all active cores on WH (eth & tensix) are loaded with kernels to collect profiling data on a fully loaded chip. 

When eth active cores are loaded tensix cores with physical coordinates (1,1) and (1,2)  stop running as their L1 stays wiped and reports all zeros. 

When eth cores are not loaded these two same cores run with no problem.

**Comment by aliuTT** [comment]
Is this Slow Dispatch? If so, this may be related to the launch msg 32 byte alignment issue.

**Comment by mo-tenstorrent** [comment]
Yep this is slow dispatch. I see, yeah.

**Comment by davorchap** [comment]
@aliuTT can we close?

**Comment by aliuTT** [comment]
I think this is fixed with the worker + eth core support. @mo-tenstorrent reopen if you still see issues
