### ISSUE TITLE
Output tensors as arguments to TT C++ Ops

### ISSUE THREAD

**Issue by muthutt** [tenstorrent-metal/tt-metal#5053]
Output tensors as arguments to TT C++ Ops

_Model 1_
1. Linear
2. Softmax
3. NLLLoss
4. SGD
5. Argmax
6. ElemwiseBinary/ELEMWISE_BINARY_EQ
7. Typecast
8. Sum

_Model 2_

1. BatchedMatmul
2. ElemwiseBinary/ELEMWISE_BINARY_ADD
3. ElemwiseBinary/ELEMWISE_BINARY_ADDALPHA
4. ElemwiseBinary/ELEMWISE_BINARY_MUL
5. ElemwiseUnary/ELEMWISE_UNARY_ADD
6. ElemwiseUnary/ELEMWISE_UNARY_ASSIGN
7. ElemwiseUnary/ELEMWISE_UNARY_DIV
8. ElemwiseUnary/ELEMWISE_UNARY_EXP
9. ElemwiseUnary/ELEMWISE_UNARY_FILL
10. ElemwiseUnary/ELEMWISE_UNARY_FILLZERO
11. ElemwiseUnary/ELEMWISE_UNARY_MUL
12. ElemwiseUnary/ELEMWISE_UNARY_POW
13. ElemwiseUnary/ELEMWISE_UNARY_SQRT
14. ElemwiseUnary/ELEMWISE_UNARY_TANH
15. Layernorm
16. Linear
17. Matmul
18. Softmax
19. AdamW
20. Arange
21. ClipGradNorm
22. ElemwiseTernary/ELEMWISE_TERNARY_ADDCDIV
23. ElemwiseTernary/ELEMWISE_TERNARY_ADDCMUL
24. Embedding
25. GenerateRandomBitMask
26. NLLLoss
27. NLLLossMeanPre
28. NLLLossUnreduced
29. Repeat
30. RepeatBackward
31. Sum
32. Typecast
33. Where
34. DropoutScaling
35. Groupnorm
36. MaskedFill
37. Prod
38. Tril

**Comment by jliangTT** [comment]
closing this one as dup to #5044

**Comment by davorchap** [comment]
@muthutt please sync on infra with @arakhmati and @eyonland
