### ISSUE TITLE
Integrate and test Top-k SFPU

### ISSUE THREAD

**Issue by davorchap** [tenstorrent-metal/tt-metal#5063]

**Comment by rdjogoTT** [comment]
### **High Level TopK Summary:**
* Sorts for top K elements from each row of length N in the input tensor 
* Returns top K elements or their respective indices
    * If both are needed, must burn extra core(s) 
* Output shape is 32x32 for K <= 32, where the first K columns contain the top K values/indeces 
* Output shape is 32x64 for K = 64 

**Supported Configurations:**
* K: can be in {4, 8, 16, 32, 64} 
* N: can be in {32, 64, 128, 256, 512, 1024, 2048, 4096} 
* Data formats: 
    * Values in {Float16_b, Bfp8_b} 
    * Indices only UInt16 
* Sort: 
    * max: return values 
    * argmax: return indices 
* Kreduce: 
    * False: for regular top K 
    * True: for reduction version of top K op (faster for pre-sorted sequences) 
        * Works by replacing initial local sort step of algorithm with just a rebuild phase 
* Input dimensions: 
    * mblock_m = 1 and ublock_rt = 1 
    * If values > 1 tile are needed, reshape other rows along the t dimension instead 
    * mblock_n = {1, 2, 4, 8, 16, 32} 
    * ublock_ct = {1, 2, 4} 

**Limitations:**
* For N = 32, K = {4, 8} not yet functional 
* For values in Float16_b format, both max and argmax configurations match golden with pcc/pct = 1.0 
* For values in Bfp8_b format, repeated packing of datums to common exponent format results in loss of precision 
    * Neither max nor argmax match golden with pcc/pct = 1.0

**Comment by davorchap** [comment]
@rdjogoTT this is merged, ready to close?

**Comment by rdjogoTT** [comment]
> @rdjogoTT this is merged, ready to close?

@davorchap yes, ready to close

**Comment by rdjogoTT** [comment]
The API for TopK has been added to the compute kernel API, and has been tested in BUDA.

**Comment by jliangTT** [comment]
based on @rdjogoTT's comment. closing
