### ISSUE TITLE
ttnn.Conv2D fails with Runtime Error for filter_h,filter_w = 1 & pad_h,pad_w = 0

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent-metal/tt-metal#5094]
**Describe the bug**
Encountered a runtime error while trying to use ttnn.Conv2D with filter_h,filter_w = 1 and  pad_w,pad_h = 0.

**To Reproduce**
1. Go to `tt-metal/tests/ttnn/unit_tests/operations/test_conv.py` file, `test_unet_conv` function.
2. Pass the following inputs to the function, 
[batch_size = 2, output_channels = 320, input_channels = 320, input_height = 32, input_width = 32, filter_height = 1, filter_width = 1, stride_h = 1, stride_w = 1, pad_h = 0, pad_w = 0, use_1d_systolic_array = True , config_override = None"] 

**Screenshots**
When running the  test file with filter_h,filter_w = 1 and  pad_w,pad_h = 0, we encountered the following issue.
```
E       RuntimeError: TT_ASSERT @ tt_eager/tt_dnn/op_library/conv/multi_core_optimized_conv_sharded/optimized_conv_op_sharded_v2.cpp:640: false
E       info:
E       Sharded input not supported for this conv yet!
E       backtrace:
E        --- tt::tt_metal::OptimizedConv::create_program(std::vector<tt::tt_metal::Tensor, std::allocator<tt::tt_metal::Tensor> > const&, std::vector<std::optional<tt::tt_metal::Tensor const>, std::allocator<std::optional<tt::tt_metal::Tensor const> > > const&, std::vector<tt::tt_metal::Tensor, std::allocator<tt::tt_metal::Tensor> >&) const
```

**Comment by davorchap** [comment]
@tt-nshanker this is fixed?

**Comment by tt-nshanker** [comment]
Yes, closing this issue
