### ISSUE TITLE
[UNet2DConditionModel pipeline] the following issue arises in the UpBlock2D sub-module.

### ISSUE THREAD

**Issue by jliangTT** [tenstorrent-metal/tt-metal#5096]
During the testing of the UNet2DConditionModel pipeline, the following issue arises in the UpBlock2D sub-module. 

```
            if len(shape) != len(first_tensor_shape) or any(
                shape[i] != first_tensor_shape[i] for i in range(len(shape)) if i != dim
            ):
>               raise ValueError(
                    "All dimensions must be the same size except for the dimension along which the contenation is taking place."
                )
E               ValueError: All dimensions must be the same size except for the dimension along which the contenation is taking place.

ttnn/ttnn/operations/data_movement.py:224: ValueError 
```
The error is triggered due to a disparity in tensor dimensions when performing the concatenation operation. Specifically, one tensor has a shape of [1, 1280, 4+28, 4+28], while another tensor has a shape of [1, 1280, 8+24, 8+24].

As the tensors which we pass for UpBlock2D is received from cross_attention_down_block_2d and DonwBlock2D, As this sub_modules returns two outputs but we are testing only the first output in the test file(Even in tt_lib version we are testing only first output of cross_attention_down_block_2d and DonwBlock2D) we think the tensor might be the issue for this.
So,we are further debugging on this issue.

Corresponding [commit](https://github.com/tenstorrent-metal/tt-metal/compare/main...punith/stable_diffusion_ttnn_unet_2d_condition_model)

_Originally posted by @punithsekar in https://github.com/tenstorrent-metal/tt-metal/issues/4801#issuecomment-1923736678_

**Comment by punithsekar** [comment]
While testing the Unet2dConditionModel pipeline with latest pipeline(Code) of dependent sub-modules, We are not facing this issue.

Working Unet2dConditionModdel pipeline, Corresponding PR #5119.
