### ISSUE TITLE
TestWatcherSanitize fails if run after DRAMLoopbackSingleCore on both WH and GS

### ISSUE THREAD

**Issue by vtangTT** [tenstorrent-metal/tt-metal#5099]
**Describe the bug**
TestWatcherSanitize is FD only and should be throwing an error due to an intended bad NoC read. However, if run after DRAMLoopbackSingleCore unexpected behaviour occurs that I was able to recreate both on CI and locally

- on GS: the watcher test will hang the board and a hard reset would be required
- on WH: the watcher test  will fail with this signature: ```Test Error: Expected file built/watcher.log to contain the following strings: Device 0, Core (x=1,y=2):    NAWW,*,*,*,*  brisc using noc0 tried to access core (16,16) L1[addr=0x00019020,len=102400]``` 

DRAMLoopbackSingleCore is currently disabled.

**To Reproduce**
Steps to reproduce the behavior on main rn (e032c8b)
1. go to ```tests/tt_metal/tt_metal/unit_tests_common/dram/test_dram.cpp``` and re-enable the test by commenting out line 150
2. run ```./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter=*TestWatcherSanitize*:*DRAMLoopbackSingleCore```

**Additional context**
Example CI runs:
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7733575135/job/21085927764
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7745307121/job/21120980451

Seems to be related: 
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7751015320/job/21138180579

**Comment by tt-dma** [comment]
Should be fixed with https://github.com/tenstorrent-metal/tt-metal/pull/5502
