### ISSUE TITLE
Low PCC failure : backward sqrt - tt_lib.tensor.sqrt_bw [Grayskull]

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent-metal/tt-metal#5148]
Backward clamp operation (`tt_lib.tensor.sqrt_bw`) fails with low PCC on Grayskull. 

**To Reproduce**

Checkout `main` branch. 

**Run the sweeps**
You can get more combinations tested using test sweep: `tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_grayskull/pytorch_backward_sqrt.yaml` 

Result will be saved in `./result-sweeps` folder

**Expected behavior**
Test cases (2 of them) for sqrt_bw is expected to fail with low PCC error.

For example, one of the tests for clamp_max is expected to fail with this result:
```
Max ATOL Delta: nan, Max RTOL Delta: nan, PCC: -3.9570702997157375e-07, PCC check failed
```

There are unit tests for each, clamp_max is the only one that here fails:
`tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_sqrt_bw.py`

**Comment by npetrovic-tenstorrent** [comment]
Still fails due to low PCC

**Comment by nemanjagrujic** [comment]
Tested works now.
