### ISSUE TITLE
Support optional_output_tensors argument in create_program

### ISSUE THREAD

**Issue by seunghwan100** [tenstorrent-metal/tt-metal#5163]
Now, arguments of create_program are input_tensors, optional_input_tensors and output_tensors.

```cpp
    operation::ProgramWithCallbacks create_program(
        const std::vector<Tensor> &input_tensors,
        const std::vector<std::optional<const Tensor>> &optional_input_tensors,
        std::vector<Tensor> &output_tensors) const;
```

We need optional_output_tensors argument especially for backward. 
Some forward operations need it, too.
In moreh_layernorm, mean and rstd are optional_output_tensors.
moreh_layernorm_backward can be called only when mean and rsted are computed in moreh_layernorm.
https://github.com/tenstorrent-metal/tt-metal/blob/5d391c6035dbbe59db024c9860bdf9fe9684af2f/tt_eager/tt_dnn/op_library/moreh_layernorm/moreh_layernorm_op.cpp#L496

[Example code]
a.grad and b.grad should be optional_output_tensors of binary_mul_backward.
```python
import torch
torch.manual_seed(2024)

a = torch.randn(2, 2).requires_grad_()
b = torch.randn(2, 2)
c = torch.mul(a, b)
c.backward(torch.randn_like(c))

print(a.grad)
# tensor([[-0.2246, -0.0911],
#         [-0.4701,  0.4315]])
print(b.grad)
# None
```

```python
import torch
torch.manual_seed(2024)

a = torch.randn(2, 2)
b = torch.randn(2, 2).requires_grad_()
c = torch.mul(a, b)
c.backward(torch.randn_like(c))

print(a.grad)
# None
print(b.grad)
# tensor([[ 0.0179,  0.3259],
#         [-0.4873,  0.8862]])
```

**Comment by razorback3** [comment]
@eyonland @muthutt @jliangTT

**Comment by nadongguri** [comment]
Also, I've identified a necessary modification in the operation.hpp.

```
diff --git a/tt_eager/tt_dnn/op_library/operation.hpp b/tt_eager/tt_dnn/op_library/operation.hpp
index 8edaf84c5..6b37ad2cc 100644
--- a/tt_eager/tt_dnn/op_library/operation.hpp
+++ b/tt_eager/tt_dnn/op_library/operation.hpp
@@ -368,7 +368,7 @@ struct DeviceOperation final {
                 } else if constexpr (detail::implements_validate_with_output_tensors_and_optional_input_tensors<T>()){
                     TT_FATAL(not optional_input_tensors.empty());
                     TT_FATAL(not optional_output_tensors.empty());
-                    operation.validate_with_output_tensors(input_tensors, optional_output_tensors);
+                    operation.validate_with_output_tensors(input_tensors, optional_input_tensors, optional_output_tensors);
                 }else{
                     static_assert(tt::stl::concepts::always_false_v<T>, "Operation must implement either validate or validate_with_output_tensors");
                 }
```

**Comment by eyonland** [comment]
Yeah I totally missed that.  We need to get fixed ASAP.  Thanks @nadongguri

**Comment by seunghwan100** [comment]
I need optional_output_tensors for backward operations.

**Comment by dongjin-na** [comment]
Dear @muthutt and @eyonland ,
FYI, the patch in https://github.com/tenstorrent-metal/tt-metal/commit/b505deb9803b0a9fa1ec55ecd2c8e9230cea089b was merged into the main branch by https://github.com/tenstorrent-metal/tt-metal/pull/5490.

**Comment by seunghwan100** [comment]
I think there should be a vector<bool> to know whether there should be an output or not.

**Comment by eyonland** [comment]
@seunghwan100 , our thinking is that the the optional indicates already whether the tensor is available.

**Comment by seunghwan100** [comment]
It has been observed that there is no argument for an **optional output tensor**.

This results in no argument being available for scenarios where an output tensor is not required.

Eltwise Binary Backward produce only one grad when one of Eltwise Binary Forward' inputs doesn't require grad.

Implementing this as a simple optional input tensor, similar to std::optional, is not advisable.

So, I think there should be a vector<bool> to know whether there should be an output or not.

Reason: This approach does not allow differentiation between scenarios where an output is unnecessary and those where the output is automatically generated internally.

Do you understand clear?

**Comment by seunghwan100** [comment]
@eyonland 

It has been observed that there is no argument for an optional output tensor.

This results in no argument being available for scenarios where an output tensor is not required.

Eltwise Binary Backward produce only one grad when one of Eltwise Binary Forward' inputs doesn't require grad.

Implementing this as a simple optional input tensor, similar to std::optional, is not advisable.

So, I think there should be a vector to know whether there should be an output or not.

Reason: This approach does not allow differentiation between scenarios where an output is unnecessary and those where the output is automatically generated internally.

Do you understand clear?

**Comment by seunghwan100** [comment]
We need a are_needed_output_tensors argument.

```
struct MorehOp {
    std::vector<bool> are_needed_output_tensors = {true, true}; // Moreh need this

    void validate(const std::vector<Tensor> &input_tensors, std::vector<Tensor> &output_tensors) const;
    std::vector<Shape> compute_output_shapes(const std::vector<Tensor> &input_tensors) const;
    std::vector<Tensor> create_output_tensors(const std::vector<Tensor> &input_tensors, std::vector<Tensor> &output_tensors) const;
    operation::ProgramWithCallbacks create_program(
        const std::vector<Tensor> &input_tensors, std::vector<Tensor> &output_tensors) const;
};
```

**Comment by jliangTT** [comment]
@seunghwan100, can you help us understand what is missing here. I am putting @eyonland here to clarify what the gaps are.

**Comment by eyonland** [comment]
Would you rebase on main?
Seeing a lot files changed trying to compare with: [https://github.com/tenstorrent-metal/tt-metal/compare/seunghwan100/support_optional_output_tensors...main](https://github.com/tenstorrent-metal/tt-metal/compare/seunghwan100/support_optional_output_tensors...main)

**Comment by seunghwan100** [comment]
> Would you rebase on main? Seeing a lot files changed trying to compare with: [seunghwan100/support_optional_output_tensors...main](https://github.com/tenstorrent-metal/tt-metal/compare/seunghwan100/support_optional_output_tensors...main)

I rebased the seunghwan100/support_optional_output_tensors branch

**Comment by eyonland** [comment]
I am not seeing any difference to main.  [https://github.com/tenstorrent-metal/tt-metal/compare/seunghwan100/support_optional_output_tensors...main](https://github.com/tenstorrent-metal/tt-metal/compare/seunghwan100/support_optional_output_tensors...main)

**Comment by eyonland** [comment]
@arakhmati and I looked at this.  It looks like you solution should work.  Clearly we need a different version of the api.   In about 10 days we should have a proposal for a better version of this infrastructure to handle the backward ops with conditional tensors much more cleanly.

**Comment by seunghwan100** [comment]
> @seunghwan100 @razorback3 @dongjin-na: for this issue, can we agree on the following next step:
> 
> * 1. merge @seunghwan100 commit to enable this support (immediate term)
> * 2. @eyonland / @arakhmati to provide the API with more polished implementation
> 
> @razorback3 , are you in agreement if we do (i), this issue is resolved. If not, please articulate the gap to help us understand.

My commits have already been merged and it works well. So, this issue can be resolved.

**Comment by jliangTT** [comment]
thank you driving to work on your end!

**Comment by eyonland** [comment]
@razorback3 and @seunghwan100 , there is worked being done on #5044 that I'd like to have your comments on.
