### ISSUE TITLE
ttl.tensor.empty operation fails for all close check [Grayskull]

### ISSUE THREAD

**Issue by banekg** [tenstorrent-metal/tt-metal#5206]
ttl.tensor.fill_bw operation fails with low PCC in some test cases on both Worhhole and Grayskull cards.

**To Reproduce**
Checkout `barsic/empty-op-issue` branch. Run unit `tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_empty.py`  using this command:

```
pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_empty.py
```

**Expected behavior**
There is a test case presented in the unit test which fails with "Allclose check failed"
For example output can be:

```
 Max ATOL Delta: 5.21875, Max RTOL Delta: nan, PCC: 0.0, Allclose check failed
```

<img width="1538" alt="Screenshot 2024-02-08 at 09 48 55" src="https://github.com/tenstorrent-metal/tt-metal/assets/102523164/595b9475-2159-4615-bb8b-787d6fb21051">

**Getting Details**
You can get more combinations tested using test sweep: 

`tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/pytorch_empty_test.yaml` or
`tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_beroken/wormhole/pytorch_empty_test.yaml`  

with command for example:

```
python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/pytorch_empty_test.yaml -o ./result-sweeps
```

Result will be saved in `./result-sweeps` folder

**Comment by tt-aho** [comment]
I don't think this is an issue. The functionality of empty is to basically create/allocate a tensor but the values are uninitialized so you can't just be comparing pt empty and tt empty as both do not guarantee anything about the values you are getting out of it.

**Comment by tarafdarTT** [comment]
@banekg is this a non-issue, if so can you close this?
