### ISSUE TITLE
Broken link on Contributing guidelines

### ISSUE THREAD

**Issue by adifrancescoTT** [tenstorrent-metal/tt-metal#5216]
**Describe the bug**

**To Reproduce**
1. Go to 'https://github.com/tenstorrent-metal/tt-metal/blob/main/CONTRIBUTING.md'
2. Select "developing-tt-metal" which will bring you to 'https://github.com/tenstorrent-metal/tt-metal/blob/f765cad2d86f55a5e471bc415f43f0f0f257e226/CONTRIBUTING.md#developing-tt-metal'
3. Click on 'developer-page'
4. The page you are directed to "https://github.com/tenstorrent-metal/tt-metal/blob/f765cad2d86f55a5e471bc415f43f0f0f257e226/docs/source/dev_onboarding/get_started.rst" says page not found

**Expected behavior**

**Screenshots**
<img width="1389" alt="Screenshot 2024-02-08 at 8 18 52 AM" src="https://github.com/tenstorrent-metal/tt-metal/assets/153237835/07448b80-9e78-4f75-9526-b3cc558e26be">

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**

**Comment by tt-rkim** [comment]
Fixed, thank you @adifrancescoTT
