### ISSUE TITLE
Convert hex8_to_hex32.py to cpp to shave off some compile time.

### ISSUE THREAD

**Issue by vtangTT** [tenstorrent-metal/tt-metal#5222]
Temporary fix: convert the script to cpp 

End goal: remove the process altogether

Fix would help #4358 and #4959

**Comment by jliangTT** [comment]
@TT-billteng , is this a item for the infra project board?

**Comment by vtangTT** [comment]
change pushed to main 
https://github.com/tenstorrent-metal/tt-metal/pull/5220
