### ISSUE TITLE
upsample2D TTNN op bringup for UNet 

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent-metal/tt-metal#5224]
**Is your feature request related to a problem? Please describe.**
There are currently 8 unit tests I run for upsample2D for UNet. (4 different input shapes and testing them all on single core and multi-core: 4x2 = 8). Depending on which grid-size I pick, at least one of the multi-core tests fail. 
: [here is the link to the unit test in my branch](https://github.com/tenstorrent-metal/tt-metal/blob/dvartanians/unitTests/tests/ttnn/unit_tests/operations/test_upsample_unet.py)

**Describe the solution you'd like**
add some simple heuristics to the unit test to help with deciding on the grid size (ideally for the entire model). 
Please see attached the graph of the full model. 

**Additional context**
Abhinav is already aware of this. 
for a graph of the full model please ping me @dvartaniansTT

**Comment by mywoodstock** [comment]
this is in main now.
