### ISSUE TITLE
Support 1x1 conv in TTNN for UNet

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent-metal/tt-metal#5225]
**Is your feature request related to a problem? Please describe.**
Enable 1x1 conv2D in TTNN for UNet 

**Describe the solution you'd like**
the last convolution in UNet used for classification is a 1x1 kernel and takes input shape (Batch-size, input-channels=16, img_height=1056, img_width=160) output-channels=1. 

**Additional context**
Nitika is already working on this. 
for a graph of the full model please ping me @dvartaniansTT

**Comment by nsmithtt** [comment]
This was done as part of #5153
