### ISSUE TITLE
Running BERT-large Demo on wormhole_b0 n150 - RuntimeError complaining about device-grids

### ISSUE THREAD

**Issue by cfjchu** [tenstorrent-metal/tt-metal#5230]
**Describe the bug**

Failure Signature:
```
- RuntimeError: TT_FATAL @ tt_eager/tt_dnn/op_library/sharded/sharded_op.cpp:36: this->grid_size.x <= device_grid.x && this->grid_size.y <= device_grid.y
```

**To Reproduce**
Repro: wormhole_b0, n150 (1-row-harvested), just running one of the off-the-shelf BERT large demo scripts. I was on commit: 9dac56d35e0d0842d2929acbebba066883bfca6c

```
 pytest --disable-warnings models/demos/metal_BERT_large_11/demo/demo.py::test_demo_squadv2 
```
from: https://github.com/tenstorrent-metal/tt-metal/tree/main/models/demos/metal_BERT_large_11

**Please complete the following environment information:**
- OS: Ubuntu 20.04

**Comment by tarafdarTT** [comment]
cc: @tt-aho @davorchap

**Comment by tt-aho** [comment]
This is expected. Metal bert demo has hardcoded configs for Grayskull using batch 12 on a 12x8 grid, so would not work for WH out of the box.

It should be able to support batch 8 sharded on WH/GS, just need to update the configs

**Comment by tt-aho** [comment]
Will look into updating model configs to generically support some other batches when batch is parallelized on a core grid dim and properly assert/skip if it doesn't support it

**Comment by tt-aho** [comment]
Should be resolved now with support for smaller batch to match device grid sizes
