### ISSUE TITLE
[Bug Report] Incorrect fast dispatch tunnelling test

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent-metal/tt-metal#5241]
**Describe the bug**
TestCommandReachesRemoteDevice performs a non-blocking write, after which the host uses UMD APIs to check that the device is in a certain state (checking L1 values). This is non-deterministic for one, and two, now with my events changes, the host expects that all issued commands have finished in the CQ destructor. This means we need the event to be written back to host, and add a Finish to ensure that happens before the CQ is destroyed.

For now, that test is skipped in main.

fyi: @davorchap

**Comment by abhullar-tt** [comment]
This test was more as a sanity check to see if commands ever make it to the remote device when the backward path was not brought up. It is meant to be deprecated with the full check fwd + bwd path check in

**Comment by DrJessop** [comment]
@abhullar-tt I see. If that is the case, you can still test locally by removing the skip and removing the assertions in the CQ destructor that there are no commands in flight.

**Comment by abhullar-tt** [comment]
This test has been deleted with the 1.3 refactor
