### ISSUE TITLE
Enable python unit tests to run on wormhole_b0 

### ISSUE THREAD

**Issue by acejkov** [tenstorrent-metal/tt-metal#5258]
**Describe the bug**
Large number of unit tests are skipped on b0: 

tests/tt_eager/python_api_testing/unit_testing/test_attn_matmul.py:from models.utility_functions import comp_pcc, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_average_pool.py:from models.utility_functions import skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_average_pool.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_bert_ops.py:from models.utility_functions import is_wormhole_b0, is_grayskull, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_bert_ops.py:# # @skip_for_wormhole_b0("WH ND hang, see issue #4392")
tests/tt_eager/python_api_testing/unit_testing/test_bert_sharded.py:from models.utility_functions import skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_bert_sharded.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_concat.py:from models.utility_functions import skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_concat.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_concat.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_concat.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_downsample.py:from models.utility_functions import skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_downsample.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_embedding.py:from models.utility_functions import skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_embedding.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_eps.py:from models.utility_functions import is_wormhole_b0, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_fully_connected.py:from models.utility_functions import is_wormhole_b0, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_fully_connected.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_groupnorm_sharded.py:from models.utility_functions import torch2tt_tensor, tt2torch_tensor, pad_by_zero, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_groupnorm_sharded.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_layernorm.py:from models.utility_functions import is_wormhole_b0, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_layernorm.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_layernorm.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_layernorm_sharded.py:from models.utility_functions import is_wormhole_b0, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_layernorm_sharded.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_layernorm_sharded.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_layernorm_sharded.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_max_pool.py:from models.utility_functions import skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_max_pool.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_moreh_clip_grad_norm.py:from models.utility_functions import comp_allclose_and_pcc, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_moreh_clip_grad_norm.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_moreh_clip_grad_norm.py:# @skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_moreh_layernorm.py:from models.utility_functions import comp_allclose_and_pcc, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_moreh_layernorm.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_moreh_matmul.py:from models.utility_functions import comp_allclose_and_pcc, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_moreh_matmul.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_moreh_matmul.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_moreh_matmul.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_moreh_matmul.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_moreh_matmul.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_moreh_sum.py:from models.utility_functions import comp_allclose_and_pcc, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_moreh_sum.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_move_sharded.py:from models.utility_functions import skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_move_sharded.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_nlp_concat_heads.py:from models.utility_functions import is_wormhole_b0, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_nlp_concat_heads.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_nlp_concat_heads.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_optimized_conv.py:from models.utility_functions import print_diff_argmax, is_close, comp_pcc, comp_allclose_and_pcc, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_optimized_conv.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_optimized_conv_multi_core.py:from models.utility_functions import print_diff_argmax, is_close, comp_pcc, comp_allclose_and_pcc, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_optimized_conv_multi_core.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_optimized_conv_v2.py:from models.utility_functions import skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_optimized_conv_v2.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_pow_fractional.py:from models.utility_functions import skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_pow_fractional.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_resnet50_first_conv.py:from models.utility_functions import is_wormhole_b0, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_resnet50_first_conv.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_resnet50_first_conv_folding_on_host.py:    skip_for_wormhole_b0,
tests/tt_eager/python_api_testing/unit_testing/test_resnet50_first_conv_folding_on_host.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_resnet50_untilize_with_halo_and_conv_v2.py:from models.utility_functions import skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_resnet50_untilize_with_halo_and_conv_v2.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_rmsnorm.py:from models.utility_functions import is_wormhole_b0, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_rmsnorm.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_rotate_half.py:from models.utility_functions import skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_rotate_half.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_sfpu_chain.py:from models.utility_functions import is_wormhole_b0, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_sfpu_chain.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_sfpu_chain.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_single_core_fused_ops.py:from models.utility_functions import skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_and_max_pool_v2.py:from models.utility_functions import is_wormhole_b0, skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_and_max_pool_v2.py:@skip_for_wormhole_b0()
tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_v2.py:from models.utility_functions import skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_v2.py:@skip_for_wormhole_b0()
skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_single_core_fused_ops.py
skip_for_wormhole_b0
tests/tt_eager/python_api_testing/unit_testing/test_softmax_sharded.py

**To Reproduce**
Run any of the aforementioned tests on wh_b0 and look at the list of skipped tests

e.g pytest -svv tests/tt_eager/python_api_testing/unit_testing/test_softmax_sharded.py

**Expected behavior**
Test needs to run and pass on wh_b0 arch. If test is not applicable for specific arch there has to be a clear message on why specific test can't run (e.g. unsupported feature, not enough resources etc.)

**Comment by acejkov** [comment]
test_softmax_sharded requires fix on Yu's branch yugao/gs_wh_block_matmul_hang

Hope others will work as well

**Comment by acejkov** [comment]
@muthutt all resnet tests fail with this error

                 Always | FATAL    | No L1 bank exists for core (x=8,y=0)
FAILED    

do you know if anybody is looking into this?

**Comment by acejkov** [comment]
no worries, it's a hardcoded grid size in some of the tests 
I'm adjusting grid size based on the device we run on and available cores

**Comment by ttmtrajkovic** [comment]
> @acejkov - most of tests for simple eltwise ops should have parity on WHB0 and work with just changing PCC if anything needs changing.

@muthutt, 
what kind of PCC changing do you expect? the PCC target or something else?

**Comment by acejkov** [comment]
Following tests remain to be enabled:
tests/tt_eager/python_api_testing/unit_testing/test_moreh_*.py

tests/tt_eager/python_api_testing/unit_testing/test_move_sharded.py
tests/tt_eager/python_api_testing/unit_testing/test_groupnorm_sharded.py:

tests/tt_eager/python_api_testing/unit_testing/test_optimized_conv.py
tests/tt_eager/python_api_testing/unit_testing/test_optimized_conv_multi_core.py
tests/tt_eager/python_api_testing/unit_testing/test_optimized_conv_v2.py
tests/tt_eager/python_api_testing/unit_testing/test_resnet50_first_conv.py
tests/tt_eager/python_api_testing/unit_testing/test_resnet50_first_conv_folding_on_host.py
tests/tt_eager/python_api_testing/unit_testing/test_resnet50_untilize_with_halo_and_conv_v2.py
tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_and_max_pool_v2.py
tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_v2.py

**Comment by acejkov** [comment]
latest merge https://github.com/tenstorrent-metal/tt-metal/pull/5425 enables following tests 

tests/tt_eager/python_api_testing/unit_testing/test_optimized_conv.py
tests/tt_eager/python_api_testing/unit_testing/test_optimized_conv_multi_core.py
tests/tt_eager/python_api_testing/unit_testing/test_resnet50_first_conv.py
tests/tt_eager/python_api_testing/unit_testing/test_resnet50_first_conv_folding_on_host.py
tests/tt_eager/python_api_testing/unit_testing/test_resnet50_untilize_with_halo_and_conv_v2.py
tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_v2.py

Remaining tests will be enabled as part of ttnn unit tests.
