### ISSUE TITLE
Add support for sharded RMSNorm

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent-metal/tt-metal#5269]
The host code for sharded RMSnorm should be basically exactly the same as sharded LN in terms of asserts/checks/setup, apart from maybe not needing some CBs.

Need to add modifications to sharded LN compute kernel to support skipping the first reduction.

**Comment by davorchap** [comment]
Perhaps host code for LN and RMS can be shared?

**Comment by tt-aho** [comment]
Yes, that is how we have it for the interleaved version, and what I plan to do for the sharded version. It's just that we made new host code for sharded ln, but didnt include rmsnorm with it.
