### ISSUE TITLE
Resnet Untilize_With_Halo_and_conv_V2 unit test

### ISSUE THREAD

**Issue by tarafdarTT** [tenstorrent-metal/tt-metal#5273]
in my underlying buffer code there was a bug where the `num_cores` member function which would calculate the total number of cores a sharded buffer would use. 

the following test: 
`pytest tests/tt_eager/python_api_testing/unit_testing/test_resnet50_untilize_with_halo_and_conv_v2.py -k test_resnet50_conv[LoFi-activations_BFLOAT16-weights_BFLOAT16-64-16-115-115-4-4-1-1-0-0-batch_8]`

Creates an input tensor of shape [1, 1, 105800, 16] and uses a shard_shape of [1088, 16]. This does not divide evenly but underneath the hood it will only read and write from 97 instead of 98 cores. 

When I fixed the bug from 97 to 98 this breaks the test. When looking at the test, it looks like the authors of the test intended the shard_shape to be evenly divisible (but 1088 is not evenly divisible within 105800). In my PR I am going to disable this test for now and can be re-enabled when this is clarified. the num_cores is correct now and it should be designed for this number of cores. 

Not sure who to assign this as well. So I tagged a bunch of you. Feel free to redistribute.

**Comment by jliangTT** [comment]
it seems no one is tagged?

**Comment by tarafdarTT** [comment]
False diagnosis and non-problem
