### ISSUE TITLE
support modulo functionality (SFPU)

### ISSUE THREAD

**Issue by muthutt** [tenstorrent-metal/tt-metal#5289]
support modulo functionality (SFPU)

required for LCM, GCD

**Comment by jliangTT** [comment]
Will close this for now and use https://docs.google.com/spreadsheets/d/18g0QjVsOApHfMtDbzJmlP7a4YX3ZmxP1RRyu2Z-R7LQ/edit#gid=1055366612 spreadsheet (internal) to plan op implementation.
