### ISSUE TITLE
[Feature Request] RMS Norm Op that supports hidden size greater than 4k

### ISSUE THREAD

**Issue by caixunshiren** [tenstorrent-metal/tt-metal#5294]
**The Problem**
The current RMS Norm Op supports hidden size (column dimension) up to 4k with the interleaved config. Hidden states beyond that would cause exceed L1 memory error on current hardware (Grayskule and Wormhole). A lot of models that uses RMS Norm, such as Llama-2, has hidden dimension of 8k.

**Proposed Solution**
Currently, the LayerNorm op used in Falcon40B supports the sharded config, and it is being used for 8k hidden dim of the Falcon40B model. However, the same config is not yet supported for RMS Norm. Since RMS and Layer Norm are very similar and share some fundamental ops, it would be great to add supported for RMS Norm using an interface modified from LayerNorm.

**Alternative for Work Around**
The Reduction op can supports reduction on arbitrary column dimension. Hence, we can work around by decomposing the RMS Norm for now.

FYI @cglagovich

**Comment by davorchap** [comment]
Great! Also good to sync with @tt-aho

**Comment by tt-aho** [comment]
We've synced previously. I have eta of tomorrow (Feb 12) for this,

**Comment by tt-aho** [comment]
You can try cherry-picking [f3a9038](https://github.com/tenstorrent-metal/tt-metal/commit/f3a90384a6a619b17bc4a7b7ca5616c495dcfc0e) to try out sharded rmsnorm while I work on getting it merged to main

**Comment by cglagovich** [comment]
@tt-aho Sharded RMSNorm tests are working on our model branch. Closing this issue. Thanks!

**Comment by cglagovich** [comment]
Found a debug print in main
```
    if (rms_norm) {
        compute_defines["RMSNORM"] = "1";
        std::cout<<'a'<<std::endl;
    }
```

https://github.com/tenstorrent-metal/tt-metal/blob/9e992783b7ecafb3a2c67f86d29a0b33a50a44a4/tt_eager/tt_dnn/op_library/layernorm/multi_core/layernorm_op_multi_core.cpp#L757

**Comment by tt-aho** [comment]
Removed 🙃
