### ISSUE TITLE
Pip warning at build time about incompatible numpy / numba dependencies

### ISSUE THREAD

**Issue by olofj** [tenstorrent-metal/tt-metal#5303]
I noticed the following as part of a build:

```
ERROR: numba 0.56.4 has requirement numpy<1.24,>=1.18, but you'll have numpy 1.24.4 which is incompatible.
```

Seen as part of the build here:

https://github.com/tenstorrent-metal/tt-metal/actions/runs/7867635921/job/21463612011

Might be harmless? Either way, it's a bit of noise in the build system that could be good to get rid of. Perhaps easiest to just move to more modern versions of all dependencies, but I'm not sure how many subtle dependency fixups might be needed, so not going to do it casually.

Cc: @tt-rkim

**Comment by tt-rkim** [comment]
I've checked `pipdeptree` in a recent commit and some recent workflows - not seeing this anymore.

We also have a `numba` pin, and looks like @cfjchu fixed for us

Thanks for flagging Olof - closing this now
