### ISSUE TITLE
DPRINT: fix race at exit

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent-metal/tt-metal#5309]
DPRINTS from a kernel that occur just prior to the programming exiting never show up as tear down occurs before the DPRINT server polls the device.  The device tear down could prod the DPRINT server to run or wait until it runs so that these show up (currently have to manually put a pause in place).

**Comment by pgkeller** [comment]
this is a long standing issue, but should really be resolved...

**Comment by tt-dma** [comment]
Should be fixed with https://github.com/tenstorrent-metal/tt-metal/pull/5463
