### ISSUE TITLE
tt-metal depends on Python 3.8 in several places

### ISSUE THREAD

**Issue by olofj** [tenstorrent-metal/tt-metal#5331]
Python 3.8 is getting old, and newer distros have either 3.10 or 3.11. We need to fix our dependencies and hardcoded paths to make it easier to use metal on newer OSes as well.

Reported by GS user as well:

https://x.com/jonmasters/status/1756551350605738307?s=20

**Comment by jliangTT** [comment]
@TT-billteng, let me know if the infra board is the right one for this.

**Comment by TT-billteng** [comment]
yes definitely, I think @tt-rkim already has an issue tracking this

**Comment by tt-rkim** [comment]
Yes sirs - https://github.com/tenstorrent-metal/tt-metal/issues/3766

Closing this issue as redundant. Thanks for raising it @olofj
