### ISSUE TITLE
Enable CNN Ops on WHB0: Resnet & SD

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent-metal/tt-metal#5353]
Ops:
- [x] Downsample
- [x] MaxPool
- [x] Move
- [x] OptimizedConv
- [x] UntilizeWithHaloV2
- [x] UntilizeWithUnpadding
- [x] Upsample

Full models:
- [ ] Resnet
- [ ] Stable Diffusion

**Comment by nsmithtt** [comment]
@acejkov, all core ops are working on WH right?  Have you tried running full Resnet?  If not, maybe @tapspatel can take over the porting effort of the model.

**Comment by acejkov** [comment]
@nsmithtt this is the latest status

All legacy op tests are enabled and passing expect for following:
tests/tt_eager/python_api_testing/unit_testing/test_move_sharded.py
tests/tt_eager/python_api_testing/unit_testing/test_groupnorm_sharded.py
tests/tt_eager/python_api_testing/unit_testing/test_optimized_conv_v2.py (covered by ttnn test)
tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_and_max_pool_v2.py (covered by ttnn test)

Regarding new ttnn tests under tests/ttnn/unit_tests/operations following  still have skip_b0 flag
tests/ttnn/unit_tests/operations/test_conv2d.py (48 pass, 197 skipped)
tests/ttnn/unit_tests/operations/test_embedding.py
tests/ttnn/unit_tests/operations/test_global_avg_pool2d.py
tests/ttnn/unit_tests/operations/test_group_norm.py
tests/ttnn/unit_tests/operations/test_layer_norm.py
tests/ttnn/unit_tests/operations/test_matmul.py
tests/ttnn/unit_tests/operations/test_mean.py
tests/ttnn/unit_tests/operations/test_pad.py
tests/ttnn/unit_tests/operations/test_rms_norm.py
tests/ttnn/unit_tests/operations/test_softmax.py
tests/ttnn/unit_tests/operations/test_split.py

Most of this are passing locally if skip flag is removed expect test_group_norm which is under debug. 
@tapspatel took a task to remove skips and then it makes sense to try running full resnet.

**Comment by acejkov** [comment]
tests/tt_eager/python_api_testing/unit_testing/test_move_sharded.py enabled for wh_b0

**Comment by nsmithtt** [comment]
@tapspatel / @acejkov , this task is done right?  Please re-open if this isn't the case! :)

**Comment by acejkov** [comment]
@tapspatel pls confirm for ttnn tests

for legacy tests  test_group_norm still hangs on b0. Everything else is enabled. I'll open separate issue to track it.

**Comment by mywoodstock** [comment]
@nsmithtt what about Resnet and SD full model? Is there another issue tracking those?

**Comment by nsmithtt** [comment]
Yes sorry:
- Resnet: https://github.com/tenstorrent-metal/tt-metal/issues/5586
- SD: https://github.com/tenstorrent-metal/tt-metal/issues/5606

**Comment by tapspatel** [comment]
All passing wormhole unit tests have been merged into main and run on post commit
