### ISSUE TITLE
Port Resnet50 to TTNN

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent-metal/tt-metal#5354]
Resnet50 model needs to be uplifted to TTNN layer.

**Comment by AleksKnezevic** [comment]
@tt-nshanker, as part of this conversion, are you planning on targeting wormhole too or keeping the model grayskull only?

**Comment by tt-nshanker** [comment]
First step is grayskull only. We wrote the model with the previous tt_lib python library. ttnn is the new and formal entry point for all models. So, it would be good to port it.

**Comment by mywoodstock** [comment]
@AleksKnezevic Here is the other task covering port to WHB0: https://github.com/tenstorrent-metal/tt-metal/issues/5353

**Comment by nsmithtt** [comment]
Is this a dup of https://github.com/tenstorrent-metal/tt-metal/issues/5233?

**Comment by shwetankTT** [comment]
> Is this a dup of #5233?

this issue is for resent-18.

**Comment by mywoodstock** [comment]
@shwetankTT ok to close, right? TTNN port is done (getting the perf to match ttlib is being tracked separately).

**Comment by shwetankTT** [comment]
Sure... :)
