### ISSUE TITLE
TTNN conv parallelization assumes GS, extend it to WH

### ISSUE THREAD

**Issue by AleksKnezevic** [tenstorrent-metal/tt-metal#5365]
Currently convolution parallelization in TTNN assumes a maximum grid size of 12x9.  It should be dependant on the device.

**Comment by tt-nshanker** [comment]
@AleksKnezevic We can close this issue now right?

**Comment by AleksKnezevic** [comment]
Yes we can @tt-nshanker. Closing issue.
