### ISSUE TITLE
Add Demo for Stable Diffusion model

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent-metal/tt-metal#5372]
GS e2e Demo

test uses batched real inputs and produces batched outputs

this test is looped (takes several batches of inputs, produces several batches of outputs)

test evaluates results of TT model against validation data in selected data set

test is documented

how to run test (commands to execute)
what does the model do (high-level explanation in a couple of sentences)
description of what is input and what is output
this demo should load inputs and expected outputs from a data set on Weka (TBD which one)

**Comment by kkeerthana0573** [comment]
The end to end demo for functional stable diffusion model is complete. 
pcc is 0.8998042840139845

Corresponding commit - [commit](https://github.com/tenstorrent-metal/tt-metal/compare/main...keerthana/stable_diffusion_ttnn_demo)

**Comment by kkeerthana0573** [comment]
For the same input prompt used in tt_lib SD - [prompt](https://github.com/tenstorrent-metal/tt-metal/blob/main/models/experimental/stable_diffusion/demo/demo.py#L147)
When num_inference_steps is 2 , pcc for SD using tt_lib ops is 0.61
However, for the same num_inference_steps, pcc for functional SD is 0.899 

Dataset used - [poloclub/diffusiondb](https://huggingface.co/datasets/poloclub/diffusiondb/viewer/large_random_1k) in demo

After randomly selecting a prompt from the dataset and considering FID scores and CLIP scores as evaluation metrics, below are the scores when num_inference_steps is 5:

FID Score (Reference vs Torch): 382.81951904296875
FID Score (Reference vs TTN): 441.47882080078125
FID Score (Torch vs TTN): 170.1981658935547

CLIP Score (Reference): 16.75223159790039
CLIP Score (Torch): 18.257747650146484
CLIP Score (TTNN): 17.973737716674805

Here is the reference for evaluation metrics: [link](https://huggingface.co/docs/diffusers/en/conceptual/evaluation)
Here is the document with output images - [SD_FID_CLIP_scores.pdf](https://github.com/tenstorrent-metal/tt-metal/files/14345433/SD_FID_CLIP_scores.pdf)

**Comment by punithsekar** [comment]
The following PDF contains results when the output from PyTorch is used as input for the TTNN model at each denoising step.
[SD_obseravtion.pdf](https://github.com/tenstorrent-metal/tt-metal/files/14375688/SD_obseravtion.pdf)

**Comment by jayasuryamaganuru** [comment]
The following PDF contains results, when the demo file is run on Warmhole device , with variable denoising steps - 
[wormhole ttnn vs torch.pdf](https://github.com/tenstorrent-metal/tt-metal/files/14376931/wormhole.ttnn.vs.torch.pdf)

**Comment by Sudharsan-V** [comment]
The Stable Diffusion model demo has been initiated with 1000 denoising steps.
Note: The demo encounters a hang at the 12th denoising step in GS. As a result, an earlier commit is picked and the test is initiated.

**Comment by kkeerthana0573** [comment]
Updated requirements_dev with torchmetrics and torch-fidelity libraries essential for computing FID, CLIP scores. 
The demo has been updated to support 512x512 image size with ttnn conv on device.
If required, please update the image_size to (256, 256)

Corresponding commit - [commit](https://github.com/tenstorrent-metal/tt-metal/compare/main...keerthana/stable_diffusion_ttnn_demo)

**Comment by Sudharsan-V** [comment]
Please find the [link ](https://docs.google.com/document/d/1QXveRuzl7iIL9tShVNAlybPWzWpxy5_X2dj8pHAi_zA/edit?usp=sharing) for the file containing the results of PyTorch and ttnn Stable diffusion model with input size 512x512.

**Comment by boris-drazic** [comment]
@Sudharsan-V can you adjust access to document to allow tenstorrent people? I can't open it.

**Comment by Sudharsan-V** [comment]
> @Sudharsan-V can you adjust access to document to allow tenstorrent people? I can't open it.

I have modified it @boris-drazic .

**Comment by kkeerthana0573** [comment]
The demo is hanging at different stages in each trigger on WH.

To be specific, demo has run_demo_inference and run_demo_diffusion_db and both runs for 256x256 and 512x512 image sizes for 2 num_inference_steps,
In the first run, the test hung for 512x512 image size in 2nd denoising step in run_demo_diffusion_db.
and in the next run, it hung for 512x512 image size in 1st denoising step in run_demo_diffusion_db.

**Comment by vigneshkeerthivasanx** [comment]
This PR has been updated. The current demo for ttnn stable diffusion model uses all ttnn ops ireplaced n the scheduler functions.

**Comment by Sudharsan-V** [comment]
The PR is merged with the main.
CIs passed. Link [here](https://github.com/tenstorrent-metal/tt-metal/actions/runs/8155716782)
