### ISSUE TITLE
Queue API Support

### ISSUE THREAD

**Issue by eyonland** [tenstorrent-metal/tt-metal#5387]
We have functionality still missing on the draft implementation:  [https://github.com/tenstorrent-metal/tt-metal/pull/5293](https://github.com/tenstorrent-metal/tt-metal/pull/5293)

Some of the API work however can be moved into ttnn.   See: [test example](https://github.com/tenstorrent-metal/tt-metal/pull/5293/files#diff-c3079d8457cabbdaf0e246203e5956361cc56681523a885f566a8df1c77331ce)

**Comment by jliangTT** [comment]
hey @eyonland, earlier on we have had an agreement that we will use API here: https://github.com/tenstorrent-metal/tt-metal/pull/4421 (with our key developer partner). We did this with @arakhmati and @TT-billteng. Are we deviating from our point of agreement?

**Comment by eyonland** [comment]
Done has part of #4421
