### ISSUE TITLE
ttnn bert

### ISSUE THREAD

**Issue by TT-BrianLiu** [tenstorrent-metal/tt-metal#5391]
- [x]  Re-write tt_lib implementation of BERT using ttnn to figure out missing functionality of ttnn needed to run sharded models: https://github.com/tenstorrent-metal/tt-metal/blob/main/models/experimental/functional_bert/tt/ttnn_optimized_functional_bert.py
- [ ] Use sharded tensors to run ttnn BERT

**Comment by eyonland** [comment]
Bert was delivered by @arakhmati
