### ISSUE TITLE
Fast Dispatch + multiple ethernet cores sharing a kernel id via CoreRange doesn't work

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent-metal/tt-metal#5398]
Steps to reproduce:

- Check out `tests/tt_metal/tt_metal/unit_tests/common/watcher/test_waypoint.cpp
- Change the test body to use a single kernel id for all eth cores (using `eth_core_ranges`)
- Run `TT_METAL_SLOW_DISPATCH_MODE=1 ./build/test/tt_metal/unit_tests --gtest_filter=*.TestWatcherWaypoints` -> Passes
- Run `./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter=*.TestWatcherWaypoints` -> Fails on one of the ethernet cores

We observed that the L1 memory where the kernel should be on the failing core is all 0s

**Comment by tt-dma** [comment]
Suspect shared root cause with #5604

**Comment by aliuTT** [comment]
Taking a look, today and tomorrow

**Comment by aliuTT** [comment]
fixed on main, closing now
