### ISSUE TITLE
Guidance Needed on Which Local Tests to Run Before Pushing to Prevent Failures in GitHub Actions

### ISSUE THREAD

**Issue by sangwon-chae** [tenstorrent-metal/tt-metal#5406]
Hello Team,

We've been following the tutorial to run post-commit regressions locally before pushing commits to avoid test failures in GitHub Actions. However, upon inspecting the `run_test.sh` script, we noticed there are multiple pipeline-type options available, including `post_commit`, `frequent_models`, `frequent_api`, `eager_host_side`, among others, totaling ten different options.

This has left us unsure about which tests are essential to run locally to ensure a smooth integration process. Could we have a guide or recommendations on which local tests should be executed before pushing the commits?

Additionally, it appears that the `CONTRIBUTING.md` may require an update regarding the post-commit regression guide. The current instruction `./tests/scripts/run_tests.sh --tt-arch $ARCH_NAME --pipeline-type post_commit` seems to only test the `post-commit` all - Fast dispatch post-commit main build and unit tests job in Git Actions. There is also a mention of a `pytest` example with an incorrect path.

Could we consider revising the documentation to address these points and provide clearer guidance?

Thank you for your attention to this matter.

**Comment by jliangTT** [comment]
c.c. @tt-rkim @TT-billteng . pushing this into your board. priority probablly needs to be determined by you based on the nature of the issue.

**Comment by jliangTT** [comment]
bumping it up as this is more about clarification / education on the developer.

**Comment by TT-billteng** [comment]
the GH action you are responsible for is https://github.com/tenstorrent-metal/tt-metal/actions/workflows/all-post-commit-workflows.yaml

**Comment by sangwon-chae** [comment]
@TT-billteng Thanks for your comment. We are going to do the GH action as you commented.
