### ISSUE TITLE
Cannot dprint in ethernet/dataflow_api.h due to circular dependency

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent-metal/tt-metal#5417]
Currently dprint.h includes  "ethernet/dataflow_api.h", which means we cannot currently include dprint.h in dataflow_api.h.

This makes debug in data_flow_api.h very difficult, and we need it promptly for multichip debug.

**Comment by DrJessop** [comment]
Lowered priority of this issue from P0 -> P1 due to workaround.

**Comment by tt-dma** [comment]
Should be fixed (I tested and I can print from "ethernet/dataflow_api.h") with https://github.com/tenstorrent-metal/tt-metal/pull/5357
