### ISSUE TITLE
DPRINT causes either issue with packet sending or data corruption of fd flag on R chip

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent-metal/tt-metal#5422]
Steps to reproduce:
```
git checkout agrebenisan/dprint-debug-tunnelling
git submodule update --init --recursive
make clean
make build
make tests
./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter=CommandQueueFixture.WriteOneTileToDramBank0
```

you should see the test pass.

Then, run the following
```
TT_METAL_DPRINT_CORES=all ./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter=CommandQueueFixture.WriteOneTileToDramBank0
```

you should see a hang and the following printout 
```
FD BUFFER MSGS SENT 0
FD BUFFER MSGS SENT 0
FD BUFFER MSGS SENT 0
FD BUFFER MSGS SENT 0
FD BUFFER MSGS SENT 0
...
```

Ideas for debug from earlier meeting:
```
Write via UMD to R chip eth core
remove DPRINTS, run server
DPRINTs that don't get compiled out, but no server
```

**Comment by aliuTT** [comment]
Datapoint, on t3005, the DPRINT enabled run passes for me sometimes.

**Comment by DrJessop** [comment]
Another datapoint. I dprinted the src/dst coords, and it turns out, I was only seeing my dprints on the L chip. None of the R chip dprints made it through.

**Comment by DrJessop** [comment]
From @tt-dma , by default, only L chip has its dprint buffer drained. Solution is to run TT_METAL_DPRINT_CHIPS=0,1

Passes with back to back runs.
