### ISSUE TITLE
Softplus

### ISSUE THREAD

**Issue by aguhaTT** [tenstorrent-metal/tt-metal#5426]
`torch.nn.Softplus` is not supported by ttnn.

**Comment by kpaigwar** [comment]
There is softplus implementation in tt_lib, but I am seeing its not feature complete to consider the threshold as set in Pytorch implementation.
<img width="887" alt="Screenshot 2024-03-06 at 12 12 57 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/132708568/10bfe975-6b78-4df7-8b85-cc4e2db3e86d">

**Comment by jliangTT** [comment]
update: 

- it is composite op - @kpaigwar commented in slack that composite implementation is okay
- triaging into op_misc as p1 priority and into the kernel board as feature. 
- P1 priority

**Comment by jliangTT** [comment]
uplifting from the slack discussion: 

- align with @aguhaTT in short term composite implementation will be used for functionality but (if performance demands it) uplift it to fused op may be in order in the future.

**Comment by umadevimcw** [comment]
@aguhaTT and @kpaigwar What kind of change is required from the existing implementation for this issue? Do you want me to handle the threshold condition? or Some thing else? Kindly let me know the requirement in slack

**Comment by kpaigwar** [comment]
Yes, Op needs to handle the threshold condition.

**Comment by jliangTT** [comment]
@kpaigwar , to help @umadevimcw to really deliver precisely what you need, we have been asking requesters to write op unit test that include the proper functionality as well as configuration it will need to support. We haven't officially roll this out as a process yet, but this is one of the example case: https://github.com/tenstorrent-metal/tt-metal/commit/507a4105f006b568269743369af963a462b822d6

I am wondering if it will be helpful here.

**Comment by umadevimcw** [comment]
@kpaigwar, @aguhaTT and @jliangTT Updated the soft plus implementation to consider beta and threshold param.
PR : https://github.com/tenstorrent-metal/tt-metal/pull/6239 
Merged the PR to main as well

**Comment by aguhaTT** [comment]
> @kpaigwar , to help @umadevimcw to really deliver precisely what you need, we have been asking requesters to write op unit test that include the proper functionality as well as configuration it will need to support. We haven't officially roll this out as a process yet, but this is one of the example case: [507a410](https://github.com/tenstorrent-metal/tt-metal/commit/507a4105f006b568269743369af963a462b822d6)
> 
> I am wondering if it will be helpful here.

I think that is a good idea. Does this feature have a unit test yet?

**Comment by kpaigwar** [comment]
@umadevimcw has pushed the fix and merged into main. We can close this
