### ISSUE TITLE
Conv2D

### ISSUE THREAD

**Issue by aguhaTT** [tenstorrent-metal/tt-metal#5427]
`Conv2D` not supported in `ttnn`.

**Comment by mywoodstock** [comment]
is support other than this needed?
https://github.com/tenstorrent-metal/tt-metal/blob/main/ttnn/ttnn/operations/conv2d.py

**Comment by davorchap** [comment]
> is support other than this needed? https://github.com/tenstorrent-metal/tt-metal/blob/main/ttnn/ttnn/operations/conv2d.py
> 
> can you elaborate on the requirements? @aguhaTT

My guess is the request came in because it's not in the docs: https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/api.html :)

**Comment by aguhaTT** [comment]
> > is support other than this needed? https://github.com/tenstorrent-metal/tt-metal/blob/main/ttnn/ttnn/operations/conv2d.py
> > can you elaborate on the requirements? @aguhaTT
> 
> My guess is the request came in because it's not in the docs: https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/api.html :)

I think that is correct. I will close this issue.
