### ISSUE TITLE
whisper failure

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent-metal/tt-metal#5430]
failing in regression as of 2/15/24

@vtangTT will do some bisect analysis

**Comment by vtangTT** [comment]
After bisect, this is the commit that broke it (feb 14)
```#4003: use faster TMs in optimized ttnn whisper```
```a41f2ffb4c03836e5b7d4a5ec3e6a934c58a1588```

**Comment by TT-billteng** [comment]
@arakhmati

**Comment by TT-billteng** [comment]
has this been fixed?

**Comment by arakhmati** [comment]
The test is fixed
