### ISSUE TITLE
Fuse bcast add into conv 

### ISSUE THREAD

**Issue by tt-nshanker** [tenstorrent-metal/tt-metal#5453]
The Unet resblock 2d has a bcast add after conv.  We broadcast the time embedding module output which has the shape (batchsize=2, 1, 1, out_channels). 
We can fuse this with the conv. Conv bias has the shape (1, 1, 1, out_channels).  We can duplicate this to make it (2, 1, 1, out_channels). We can perform an eltwise add between conv bias and time embedding output. Then, we can fuse a segmented bcast add with the conv.

**Comment by nsmithtt** [comment]
Closing, replaced with sharding support https://github.com/tenstorrent-metal/tt-metal/issues/5657
