### ISSUE TITLE
[Bug Report] test_max_pool.py hangs on n300

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent-metal/tt-metal#5458]
**Describe the bug**
CI (and my n300 BM) hang when this test runs, seems specific to n300.

**To Reproduce**
Run `pytest -svv tests/tt_eager/python_api_testing/unit_testing/test_max_pool.py::test_run_max_pool[True-1-out_DRAM-in_DRAM-dilation0-stride1-padding1-kernel_size1-act_shape2]`

Expected output is a hang with the following displayed:
```
davidma@e04cs04:~/tt-metal$ pytest -svv tests/tt_eager/python_api_testing/unit_testing/test_max_pool.py::test_run_max_pool[True-1-out_DRAM-in_DRAM-dilation0-stride1-padding1-kernel_size1-act_shape2]
=========================================================================================================================================================================== test session starts ============================================================================================================================================================================
platform linux -- Python 3.8.10, pytest-7.2.2, pluggy-1.3.0 -- /home/davidma/tt-metal/build/python_env/bin/python
cachedir: .pytest_cache
rootdir: /home/davidma/tt-metal, configfile: pytest.ini
plugins: timeout-2.2.0, dash-2.8.1, anyio-4.1.0
timeout: 600.0s
timeout method: signal
timeout func_only: False
collected 1 item

tests/tt_eager/python_api_testing/unit_testing/test_max_pool.py::test_run_max_pool[True-1-out_DRAM-in_DRAM-dilation0-stride1-padding1-kernel_size1-act_shape2]                   Metal | INFO     | Initializing device 0
                 Device | INFO     | Opening user mode device driver
CHECKING: [0, 0, 0, 0]
CHECKING: [1, 0, 0, 0]
2024-02-16 20:36:18.688 | INFO     | SiliconDriver   - Detected 1 PCI device : {0}
2024-02-16 20:36:18.754 | WARNING  | SiliconDriver   - hwloc_set_area_membind(): failed for physical_device_id: 0 on NodeSet: {1} with errno: Input/output error (pid: 672257 tid: 139872934950720)
---- ttSiliconDevice::init_hugepage: bind_area_to_memory_nodeset() failed (physical_device_id: 0 ch: 1). Hugepage allocation is not on NumaNode matching TT Device. Side-Effect is decreased Device->Host perf (Issue #893).
2024-02-16 20:36:18.873 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 6.3.0 (Device 0)
2024-02-16 20:36:18.873 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 6.3.0 (Device 1)
                  Metal | INFO     | AI CLK for device 0 is:   1000 MHz
```

**Comment by acejkov** [comment]
adding Davor and Andrew in case they have any ideas on when op test would hang only on N300. This specific config runs only on single core so it shouldn't be related to harvested

**Comment by DrJessop** [comment]
Has there been any investigation on bisecting? Additionally, can this be skipped in Ci in the short-term?

**Comment by acejkov** [comment]
yeah, I'm going to skip this one for now on N300 (8x7 core grid) but I would expect other op tests to hang as well (let's see)
I've been running everything on n150 systems and unharvested lab-37 up to this point and haven't seen any hangs

**Comment by tt-dma** [comment]
@vtangTT is bisecting, will update this issue when he finds something

**Comment by tt-rkim** [comment]
@vtangTT 
Gonna be a long bisect.... we've had this hang for weeks, possibly months.

**Comment by acejkov** [comment]
disabled test for now for n300

**Comment by acejkov** [comment]
@tt-rkim this test was enabled on b0 3 days ago
commit c39643829c3f73676dccf470d429f40358a2f1c9
Author: acejkov <acejkov@tenstorrent.com>
Date:   Tue Feb 13 16:55:38 2024 +0000

was is also hanging before with everything skipped on b0?

**Comment by tt-rkim** [comment]
With @yugaoTT , we found out the problem was because the CI machines are on older FW.

The problem is that we are currently unable to upgrade to anything past `2023-09-19` WH FW because the tt-metal stack causes crashes on WH cloud VMs combined with warm resets with FW past that date.

This means we are not able to get the 800MHz clock downgrade update onto the runners, causing these non-det hangs

We are actively working on trying to upgrade. We should be able to upgrade after we fix and upgrade the CI machines.

cc: @ttmchiou @davorchap
