### ISSUE TITLE
Remove resolved broken tests and fix slow dispatch mode in unit tests

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent-metal/tt-metal#5486]
- All unit tests which now PASS should not remain in broken folders. 
- All tests should exclude scenarios with SLOW dispatch mode
- Update issues accordingly

**Comment by TT-billteng** [comment]
why is this part of infra board? @jliangTT

**Comment by jliangTT** [comment]
yes this is a mis-triaged.

**Comment by jliangTT** [comment]
@npetrovic-tenstorrent, is this something you are working on?

**Comment by npetrovic-tenstorrent** [comment]
> @npetrovic-tenstorrent, is this something you are working on?

Yes, I already did it, still not merged
