### ISSUE TITLE
Profiler regression failing on WH N300 intermittently due to hangs

### ISSUE THREAD

**Issue by mo-tenstorrent** [tenstorrent-metal/tt-metal#5489]
On WHB0 N300 runs hang occur similar to this https://github.com/tenstorrent-metal/tt-metal/actions/runs/7936985311/attempts/1

Initial analysis suggests that hangs only happen as part of the second `tt-dnn` test for Tracy which seem to be hanging after close device.

**Comment by mo-tenstorrent** [comment]
This could be related to this issue https://github.com/orgs/tenstorrent-metal/projects/4/views/6?pane=issue&itemId=52588304

Or it could be a Tracy python profiling issue that is only showing up on N300

**Comment by dongjin-na** [comment]
Hi @mo-tenstorrent ,
It looks very similar to this issue [#5168](https://github.com/tenstorrent-metal/tt-metal/issues/5168).

**Comment by vtangTT** [comment]
bisecting through the custom script @mo-tenstorrent gave me, the offending commit seems to be: 
`0292778`
CC: @TT-billteng

**Comment by TT-billteng** [comment]
will look into bringing pipeline back after all N300 runners are upgraded

**Comment by TT-billteng** [comment]
N300 runners are stable again and profiler regression on N300 is back online
