### ISSUE TITLE
tt_lib.tensor.complex operations fail with low PCC when last input dimension is relatively large

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent-metal/tt-metal#5519]
**tt_lib.tensor.complex** operations (abs, conj, div, mul, recip, imag, real) fail with low PCC for tensors of specific input dimensions. Eg. [4, 2, 96, 448]

The bug is happening when last dimension is relatively large (eg >400)

**To Reproduce**
Checkout `main` branch. Run unit test `test_complex_pcc.py ` using this command:

```
pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_complex_pcc.py
```

(Same unit test is for wormhole cards as well)

**Expected behavior**
There are few test cases presented in the unit test `tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_complex_pcc.py` and they are expected to fail with error similar to:

```
Max ATOL Delta: 93.02752685546875, Max RTOL Delta: 38.713680267333984, PCC: 0.4779800043725184, PCC check failed
```

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweep tests for those ops:

```
tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/pytorch_complex_abs_test.yaml
tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/pytorch_complex_conj_test.yaml
tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/pytorch_complex_div_test.yaml
tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/pytorch_complex_mul_test.yaml
tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/pytorch_complex_real_test.yaml
tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/pytorch_complex_imag_test.yaml
tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/pytorch_complex_recip_test.yaml
```

or for Wormhole:

```
tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/wormhole/pytorch_complex_abs_test.yaml
tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/wormhole/pytorch_complex_conj_test.yaml
tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/wormhole/pytorch_complex_div_test.yaml
tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/wormhole/pytorch_complex_mul_test.yaml
tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/wormhole/pytorch_complex_real_test.yaml
tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/wormhole/pytorch_complex_imag_test.yaml
tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/wormhole/pytorch_complex_recip_test.yaml
```

To do this you should:

1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/pytorch_complex_abs_logical_coord_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `complex_abs_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by nemanjagrujic** [comment]
Checked. Still fails.

**Comment by nemanjagrujic** [comment]
@boris-drazic Updated this. Checked and is still issue.

**Comment by umadevimcw** [comment]
https://github.com/tenstorrent-metal/tt-metal/pull/7199 Fixed the issue in this PR

**Comment by umadevimcw** [comment]
PR merged to main hence closing this issue.
