### ISSUE TITLE
Add support for `HEIGHT_SHARDING` to `UntilizeWithUnpadding`

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent-metal/tt-metal#5530]
Currently it only supports `BLOCK` and `WIDTH` sharding.

**Comment by jliangTT** [comment]
Per @mywoodstock: 
- we have a workaround (to do sharded_to_interleaved -> interleaved_to_sharded), but we need to avoid it 
- this came from the need for UNET (@dvartaniansTT ) but it is needed elwhere. Unet model shouldn't be blocked. 

Given that there is a workaround, let's make it a p2.

**Comment by jliangTT** [comment]
bumping the priority as this is affecting stable diffusion

**Comment by tarafdarTT** [comment]
@mywoodstock , I spoke to @tt-nshanker , and she said this is no longer a blocker. Should I close this issue or did I misunderstand.

**Comment by mywoodstock** [comment]
> @mywoodstock , I spoke to @tt-nshanker , and she said this is no longer a blocker. Should I close this issue or did I misunderstand.

@tarafdarTT Its no longer a blocker for UNET. But we still need the feature

**Comment by tarafdarTT** [comment]
oh okay is it still blocking SD? (asking if I should leave it as P1 or downgrade to P2)

**Comment by mywoodstock** [comment]
> oh okay is it still blocking SD? (asking if I should leave it as P1 or downgrade to P2)

you can downgrade :)

**Comment by jliangTT** [comment]
love seeing the collaboration between developers on adjusting the right priority!

**Comment by mywoodstock** [comment]
@tarafdarTT I ended up updating the op to support HEIGHT_SHARDING. It was partially supported, so did not had to make any major changes. This is part of this PR: https://github.com/tenstorrent-metal/tt-metal/pull/5632
