### ISSUE TITLE
tt_eager pytests failing when building with ENABLE_TRACY=1

### ISSUE THREAD

**Issue by vtangTT** [tenstorrent-metal/tt-metal#5558]
**Describe the bug**
after ```make clean/nuke && make build ENABLE_TRACY=1``` observing ~500+ pytests failures mostly from ```tests/tt_eager/python_api_testing/unit_testing/fallback_ops``` with the same failure signature: 

Example run: ```pytest tests/tt_eager/python_api_testing/unit_testing/fallback_ops/test_trunc_ops.py::TestTruncOp::test_trunc_fallbackop[False-input_shape0]```
![image](https://github.com/tenstorrent-metal/tt-metal/assets/157417475/f382fbcd-5c80-45f1-b9ca-c86c746491e6)

Originally observed when trying to run all of FD post commit with TRACY enabled. This was only observed with these tests and not with anything else from FD post commit.

These tests do not fail if not built with ENABLE_TRACY=1.

**To Reproduce**
1. make nuke && make build ENABLE_TRACY=1
2. Run FD post commit or ```pytest $TT_METAL_HOME/tests/tt_eager/python_api_testing/unit_testing/ -vvv``` or run most if not any pytest from fallback_ops
3. Observe failure

CC: @TT-billteng

**Comment by vtangTT** [comment]
pulling the newest Tracy does not fix the problem

the same behaviour shows up on both gs and wh

**Comment by jliangTT** [comment]
what is the impact of this issue to the pipeline (this should dtermine the priority)? should we triage this to the tool's board? @mo-tenstorrent ?

**Comment by mo-tenstorrent** [comment]
I would say this is a P1. Turning on Tracy by default and profiling post commit with Tracy are both in the roadmap and this is blocking both.

**Comment by mo-tenstorrent** [comment]
I actually did some further investigation and this seems to be a a build issue. 

With the Tracy build, `ttl_tensor.Tensor` represents an object instance which the `isinstance` call in the code below does not like. 

```
def convert_tt_tensors_to_pt_tensors(args, output_format):
    check_log_pytorch_warning(args)
    print (ttl_tensor.Tensor)
    if isinstance(args, ttl_tensor.Tensor):
```

In the non-Tracy build, `ttl_tensor.Tensor` represent the type.

**Comment by vtangTT** [comment]
these model perf tests are also failing with the same signature: 
<img width="1352" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/157417475/66a8f603-91be-4b0a-ae77-40028f3595be">


```FAILED models/experimental/vgg/tests/test_perf_vgg.py::test_perf_bare_metal[expected_inference_time=3.0-expected_compile_time=14] - TypeError: isinstance() arg 2 must be a type or tuple of types
FAILED models/experimental/vit/tests/test_perf_accuracy_vit.py::test_perf_bare_metal[expected_inference_time=2.1-expected_compile_time=16-iterations=50] - TypeError: isinstance() arg 2 must be a type or tuple of types
FAILED models/experimental/vit/tests/test_perf_vit.py::test_perf_bare_metal[expected_inference_time=2.1-expected_compile_time=16] - TypeError: isinstance() arg 2 must be a type or tuple of types
FAILED models/experimental/llama_old/tests/test_perf_llama.py::test_perf_bare_metal[expected_inference_time=0.15-expected_compile_time=10] - TypeError: isinstance() arg 2 must be a type or tuple of types
FAILED models/experimental/roberta/tests/test_perf_accuracy_roberta.py::test_perf_bare_metal[expected_inference_time=0.405-expected_compile_time=17-iterations=100] - TypeError: isinstance() arg 2 must be a type or tuple of types
FAILED models/experimental/roberta/tests/test_perf_roberta.py::test_perf_bare_metal[expected_inference_time=0.405-expected_compile_time=17] - TypeError: isinstance() arg 2 must be a type or tuple of types
FAILED models/demos/resnet/tests/test_perf_accuracy_resnet.py::test_perf_bare_metal[batch_size=20-expected_inference_time=0.015-expected_compile_time=33-iterations=160] - RuntimeError: TT_THROW @ tt_metal/impl/program/program.cpp:490: tt::exception
FAILED models/demos/resnet/tests/test_perf_resnet.py::test_perf_bare_metal[batch_size=20-expected_inference_time=0.0185-expected_compile_time=25] - RuntimeError: TT_THROW @ tt_metal/impl/program/program.cpp:490: tt::exception
FAILED models/experimental/deit/tests/test_perf_accuracy_deit.py::test_perf_bare_metal[expected_inference_time=1.8-expected_compile_time=18-iterations=50] - TypeError: isinstance() arg 2 must be a type or tuple of types
FAILED models/experimental/deit/tests/test_perf_deit.py::test_perf_bare_metal[expected_inference_time=1.8-expected_compile_time=18] - TypeError: isinstance() arg 2 must be a type or tuple of types
FAILED models/experimental/stable_diffusion/tests/test_perf_unbatched_stable_diffusion.py::test_perf_bare_metal[expected_inference_time=42-expected_compile_time=95] - TypeError: isinstance() arg 2 must be a type or tuple of types
FAILED models/experimental/whisper/tests/test_perf_whisper.py::test_perf_bare_metal[expected_inference_time=4.5-expected_compile_time=25] - TypeError: isinstance() arg 2 must be a type or tuple of types
FAILED models/experimental/bloom/tests/test_perf_bloom.py::test_perf_bare_metal[expected_inference_time=1.5-expected_compile_time=16] - TypeError: isinstance() arg 2 must be a type or tuple of types ```

**Comment by mo-tenstorrent** [comment]
@tapspatel  tried resnet and saw the same issue with our Tracy build

`pytest -ssv tests/ttnn/integration_tests/resnet/test_ttnn_functional_resnet.py::test_resnet_50`

gave 
```
def merge_ttnn_module_args_into_parameters(parameters: dict, ttnn_module_args: dict, path=[]):
        if isinstance(ttnn_module_args, ModuleArgs):
            for key, value in list(ttnn_module_args.items()):
>               if isinstance(value, ttnn.Device):
E               TypeError: isinstance() arg 2 must be a type or tuple of types
```

Without tracy build it runs fine. 

This time device data type is generated wrong.

**Comment by mo-tenstorrent** [comment]
@eyonland Actually fixed the issue which is comin in with https://github.com/tenstorrent-metal/tt-metal/pull/5875#pullrequestreview-1915400167

@vtangTT I would try again after above PR is in main.

**Comment by vtangTT** [comment]
PR has fixed this problem
