### ISSUE TITLE
Perf_Mon: Bring WH ARCH support

### ISSUE THREAD

**Issue by mo-tenstorrent** [tenstorrent-metal/tt-metal#557]
Bring WH support for kernel and host side profilers

- [x] Device side CSV is marked with device ARCH
- [x] Post process script denotes device type in webapp
- [ ] #2908
- [x] Post process `devicesData` add field for device type

**Comment by davorchap** [comment]
@mo-tenstorrent can we close this?

**Comment by mo-tenstorrent** [comment]
No
