### ISSUE TITLE
Eth Kernels + Brisc Kernels as part of the same Program results in Eth Kernels written to Tensix cores

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent-metal/tt-metal#5604]
Issue observed in TestWatcherWaypoints. Steps to reproduce:

1. Make a copy of `tests/tt_metal/tt_metal/test_kernels/misc/watcher_waypoints.cpp`, `tests/tt_metal/tt_metal/test_kernels/misc/watcher_waypoints_eth.cpp`
2. Change `tests/tt_metal/tt_meta/unit_tests_common/watcher/test_waypoint.cpp` to call the copied kernel for eth cores
3. Run `TT_METAL_SLOW_DISPATCH_MODE=1 ./build/test/tt_metal/unit_tests --gtest_filter=*TestWatcherWaypoints`
4. Check `built/watcher.log`, and see that `watcher_waypoints_eth` is written to ethernet cores (0,0) and (1,0), but also to tensix cores (0,0) and (1,0) (all coords logical).

**Comment by tt-dma** [comment]
I also ran into this issue when debugging #6096. Root cause appears to be that `Program::update_kernel_groups()` uses logical coords. This means that eth kernels will clash with tensix kernels, resulting in incorrect kernel groupings (which causes errors when we try to run the program). Likely this is also the root cause for #5398

**Comment by aliuTT** [comment]
Fixed on main with `adba3c92c3e14f2d981e59f4589a59132d23a56d`
