### ISSUE TITLE
Don't create new threads during `CompileProgram`

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent-metal/tt-metal#5629]
For example, these calls are binding a lambda to a new thread:

https://github.com/tenstorrent-metal/tt-metal/blob/024108b208967887328ef9dea3dbedb5b377f45c/tt_metal/jit_build/build.cpp#L602

https://github.com/tenstorrent-metal/tt-metal/blob/024108b208967887328ef9dea3dbedb5b377f45c/tt_metal/jit_build/build.cpp#L626

Creating a new thread per call takes time, and this is also cluttering our Tracy runs with many, many extra lines in the GUI (each new thread corresponds to an extra line).

We already have a threadpool managed by Taskflow. An example of where it's used:

https://github.com/tenstorrent-metal/tt-metal/blob/024108b208967887328ef9dea3dbedb5b377f45c/tt_metal/impl/program/program.cpp#L1028

**Comment by vtangTT** [comment]
fix merged in main: https://github.com/tenstorrent-metal/tt-metal/pull/5860
