### ISSUE TITLE
watcher doesn't differentiate between workers/dram/pcie when reporting noc errors

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent-metal/tt-metal#5635]
In DebugSanitizeNocInvalidUnicast, a bad address is reported as "L1".  This code should look up the noc address (if valid) and report this as L1, DRAM, or PCIE.

**Comment by tt-dma** [comment]
Closing due to overlap with https://github.com/tenstorrent-metal/tt-metal/issues/6736, will track the work there
