### ISSUE TITLE
Backward op support for Repeat

### ISSUE THREAD

**Issue by umadevimcw** [tenstorrent-metal/tt-metal#5644]

**Comment by ruthreshx** [comment]
yes @jliangTT, with few constraints the repeat backward has been completed.

**Comment by jliangTT** [comment]
Do you mind enumerating the constraints here and then we can review and close. thanks!

**Comment by ruthreshx** [comment]
We can't enumerating the constraints here @jliangTT, since it requires more dim support, hence we restricted the repeat backward. Repeat backward has been already merged to main, hence we close the ticket.
