### ISSUE TITLE
Support sharding for silu op

### ISSUE THREAD

**Issue by tt-nshanker** [tenstorrent-metal/tt-metal#5658]
Need height sharding and block sharding support.

**Comment by jliangTT** [comment]
which op category does activation function fall into? @shwetankTT , can you assign a proper label?

**Comment by mywoodstock** [comment]
@nsmithtt This is the silu sharding one

**Comment by shwetankTT** [comment]
> which op category does activation function fall into? @shwetankTT , can you assign a proper label?

Added the label as eltwise.
