### ISSUE TITLE
[WH] Core temp too high

### ISSUE THREAD

**Issue by zhoujingya** [tenstorrent-metal/tt-metal#5683]
Is the core temp normal? We put a Wormhole n150 on our server, but the core temp is beyond the threshold

![img_v3_028f_8cd4f655-7fca-4717-8cec-a5329f8109cg](https://github.com/tenstorrent-metal/tt-metal/assets/104264072/d6071ace-e624-4ad9-a936-4c287d8bb4c8)

**Comment by olofj** [comment]
This seems to be a system/hardware issue, the WH cards are passively cooled and they need airflow provided by the system.

Please reach out to the sales representative to receive support, this is not a tt-metal issue.
