### ISSUE TITLE
Watcher failed to create log file 

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent-metal/tt-metal#5685]
Watcher failed to create the `watcher` log (I added extra print out to dump filename):

```
tests/tt_eager/python_api_testing/unit_testing/test_moreh_layernorm.py::test_moreh_layernorm_backward[input_shape2-elementwise_affine=False-CHW-1e-12-4-10]                   Metal | INFO     | Initializing device 0
              LLRuntime | INFO     | Watcher thread stopped watching...
                  Metal | INFO     | AI CLK for device 0 is:   1000 MHz
                 Always | FATAL    | Watcher failed to create log file /home/ubuntu/bteng/tt-metal/built/watcher.log

ERROR                     Op | INFO     | Program Cache: disabled and cleared.
```

To reproduce:

1) `pip install pytest-repeat`

2) `TT_METAL_WATCHER=10 pytest --count=10 tests/tt_eager/python_api_testing/unit_testing/test_moreh_layernorm.py -xv`

In case this is a machine-specifc issue, I was running on `tt-metal-ci-vm-23`

**Comment by TT-billteng** [comment]
`--count=5` doesn't fail, but `--count=10` always does,

**Comment by tt-dma** [comment]
PR https://github.com/tenstorrent-metal/tt-metal/pull/5795 has the fix for this, I've run the above command and seen it fail before my fix and pass after.
