### ISSUE TITLE
AllGather hangs with logging enabled

### ISSUE THREAD

**Issue by cglagovich** [tenstorrent-metal/tt-metal#5706]
**Describe the bug**
When building tt-metal with `TTNN_ENABLE_LOGGING=1`, AllGather tests hang. Removing this env var and rebuilding leads to tests passing.

**To Reproduce**
1. `TTNN_ENABLE_LOGGING=1 make build`
2. `pytest -svv tests/tt_eager/python_api_testing/unit_testing/test_all_gather.py::test_all_gather[1-mem_config0-input_shape12-3-layout12]`

**Expected behavior**
The test hangs.

**Please complete the following environment information:**
- T3000 machine in mesh topology
- 800 MHz
- 4-chip test

**Comment by arakhmati** [comment]
> **Describe the bug** When building tt-metal with `TTNN_ENABLE_LOGGING=1`, AllGather tests hang. Removing this env var and rebuilding leads to tests passing.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. `TTNN_ENABLE_LOGGING=1 make build`
> 2. `pytest -svv tests/tt_eager/python_api_testing/unit_testing/test_all_gather.py::test_all_gather[1-mem_config0-input_shape12-3-layout12]`
> 
> **Expected behavior** The test hangs.
> 
> **Please complete the following environment information:**
> 
> * T3000 machine in mesh topology
> * 800 MHz
> * 4-chip test

@cglagovich you want to be able to see ops on stdout when logging, right?

**Comment by arakhmati** [comment]
We removed `TTNN_ENABLE_LOGGING`. Please try running again. Refer to @eyonland's message above for instructions on how to enable the logging
