### ISSUE TITLE
Enable SD tests for WH

### ISSUE THREAD

**Issue by boris-drazic** [tenstorrent-metal/tt-metal#5716]
Tests for SD modules currently use `@skip_for_wormhole_b0()` and don't execute on WH during CI runs.

Please update tests in `tests/ttnn/integration_tests/stable_diffusion` to also run on WH.

**Comment by punithsekar** [comment]
Enabled `tests/ttnn/integration_tests/stable_diffusion` tests to run on WH.

Corresponding PR(#5763)

**Comment by Sudharsan-V** [comment]
This PR is merged with main, hence closing the ticket.
CI tests passed, [link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/8097179746)
