### ISSUE TITLE
SD: Circular buffers in program clash with L1 buffers on core range

### ISSUE THREAD

**Issue by boris-drazic** [tenstorrent-metal/tt-metal#5722]
Running SD demo for multiple iterations throws the following error:

```
tt_eager/tt_dnn/op_library/sliding_window_op_infra/tt_py_composite_conv.py:771: in composite_conv_with_deallocate_input
    return conv_(utwh_output)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

activation = <tt_lib.tensor.Tensor object at 0x7faf40279130>

    def conv_(activation):
>       return ttl.tensor.optimized_conv(
            activation,
            self.weight,
            self.bias,
            conv_reader_indices,
            [R, S, U, V, P_H, P_W],
            K,
            False,
            self.bias is not None,
            fuse_relu,
            math_fidelity,
            opt_conv_parall_conf,
            opt_conv_block_conf,
            0,
            output_mem_config=activation.memory_config() if output_mem_config is None else output_mem_config,
            output_dtype=output_dtype,
            input_tensor_shape=self.input_tensor_shape,
            use_shallow_conv_variant=self.use_shallow_conv_variant,
        )
E       RuntimeError: TT_THROW @ tt_metal/impl/program/program.cpp:490: tt::exception
E       info:
E       Statically allocated circular buffers in program {} clash with L1 buffers on core range {}. L1 buffer allocated at {} and static circular buffer region ends at {}
E       22822
E       [(x=0,y=0) - (x=11,y=4)]
E       586784
E       588068
```

This happens after 8th iteration on my BM with GS.
To reproduce you need to run demo that is currently on branch (and rebase and install two libraries).
```
git checkout keerthana/stable_diffusion_ttnn_demo
git rebase main
pip install torchmetrics
pip install torch-fidelity
```
Edit file `models/experimental/functional_stable_diffusion/demo/demo.py:399` to run for more than 2 iterations (num_inference_steps):
```
@pytest.mark.parametrize(
    "num_inference_steps",
    ((20),),
)
```
Finally, run the test with `pytest --timeout=60000 --disable-warnings models/experimental/functional_stable_diffusion/demo/demo.py::test_demo_diffusiondb`

This is blocking us from running SD for more than 10 iterations when generating images.

**Comment by jvasilje** [comment]
@boris-drazic you need to make sure that the memory layout in L1 is identical at the start of every iteration. 
you should be able to do this by moving tensors out of L1 before the start of every iteration. then memory allocation should be deterministic.

**Comment by jvasilje** [comment]
fyi - @eyonland @arakhmati 

this is something we may want to add into docs eventually. how to avoid this issue in the future. 
pinning this to the ttnn board for now.
