### ISSUE TITLE
Watcher perf regression

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent-metal/tt-metal#5724]
Running `time ./tests/scripts/run_pre_post_commit_regressions_fast_dispatch.sh` on my local VM (same specs as CI runner):

real    99m43.799s
user    288m37.736s
sys     59m16.770s

With watcher enabled (`TT_METAL_WATCHER=30`), this takes much longer. I cancelled my run after 6h or so.

We currently use watcher in the stress test pipeline and 1 iteration of this script takes ~12h right now. We used to be able to get through 10+ iterations of post-commit in a 24h span.

**Comment by tt-dma** [comment]
PR https://github.com/tenstorrent-metal/tt-metal/pull/5795 implements the fix for this. See comments there for more details.
