### ISSUE TITLE
EnqueueProgram test hangs on 1x N300

### ISSUE THREAD

**Issue by davorchap** [tenstorrent-metal/tt-metal#5741]

**Comment by davorchap** [comment]
* Confirm that we indeed see different behavior between 1x N300 and T3000 (4x N300).
* Investigate if a specific commit caused a regression

**Comment by abhullar-tt** [comment]
Narrowed down regression to 67238f6dde6b9e9ea319ca935c1c7f586440a45d

With fix implemented in c6f06f8e5f3997f975bc086cab86d2f2a19c1725
