### ISSUE TITLE
Add support for broadcast multiply along batch dimension (W)

### ISSUE THREAD

**Issue by kpaigwar** [tenstorrent-metal/tt-metal#5769]
## Requirement
Need support for an op which can perform element-wise multiply and broadcast along batch dim.
For example, (32, 1, 32, 1024)*(1, 1, 32, 1024)

**Comment by kpaigwar** [comment]
fyi @apalaguha  @esmalTT

**Comment by kpaigwar** [comment]
This op is crtical for us when doing element-wise multiplication of conv1D weights (batch independent) with inputs (batch dependent). The workaround makes the implementation harder.

**Comment by bharane-abb** [comment]
We have come up with two ideas for multiplication without using broadcasting:

1. Using the repeat function, we will repeat the smaller tensor into the required shape and then proceed with multiplication.
2. Using the unpad function, we can unpad the larger tensor into a smaller tensor and multiply it with the smaller tensor. However, this process is time-consuming as it involves many unpad, multiply, and concat operations.

**Comment by kpaigwar** [comment]
@bharane-ab first approach would be ideal

**Comment by umadevimcw** [comment]
Tried to update the `eltwise_binary_op.hpp` to apply changes to all ops in binary. But getting error shown in below image. Suggested flag (in the image not helping). 

<img width="1195" alt="Screenshot 2024-03-15 at 1 31 37 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/29221091/276d121e-ae81-4ad8-b400-3dbc5c092ebc">

@kpaigwar Regarding the above why are we just considering mul operation alone? What about other binary, operations like squared_diff, add, sub, etc.. ? If we make changes in commonplace then it would be applied to all. 

@kpaigwar Do you want me to go with separate op like `batch_mul` or some thing? Any suggestions?

**Comment by umadevimcw** [comment]
Tried the implementation in composite as a separate batch mul op https://github.com/tenstorrent-metal/tt-metal/pull/6442

**Comment by tt-aho** [comment]
If you are targeting performance, are you planning to run this model/op sharded? Or exactly as specified in this issue? The optimizations/support for sharding are different than interleaved so want to make sure we're targeting/optimizing the right thing. Similar question for #6361

**Comment by kpaigwar** [comment]
Since both are related to repeat, I will drop the priority of this issue and would address P0 first #6361

**Comment by umadevimcw** [comment]
@kpaigwar Please find the updated PR https://github.com/tenstorrent-metal/tt-metal/pull/6587 for batch mul support. It doesn't involve new op. Also changed the code in common place hence it is working for other binary op as well

**Comment by umadevimcw** [comment]
Support Merged to Main
