### ISSUE TITLE
watcher: small ring buffer of latest status

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent-metal/tt-metal#5785]
DEBUG_STATUS only handles characters and doesn't have any history.
This request is for a small (32?) entry ring buffer where kernels can log what they are up to and have that dumped by the watcher.
The buffer would involve no handshake, ie, the device can just write in a loop w/o a handshake to the host.
Ideally, there would be 1 buffer shared by all 5 riscvs and would be safe to write w/ atomics.  Not sure if that is feasible w/ current hw (may need 5x32 buffers...which may not be worth it).

**Comment by tt-dma** [comment]
Implemented with https://github.com/tenstorrent-metal/tt-metal/pull/6652, only caveat is that we don't have atomics and don't have access to noc semaphores from triscs. So ring buffer access from multiple riscs on the same core results in undefined behaviour. Re-visit this in later when we have atomics support
