### ISSUE TITLE
GS watcher error in `test_layernorm_sharded.py::test_layernorm_sharded_rm`

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent-metal/tt-metal#5797]
This was working early January, but recent changes lead to PCC errors when watcher is enabled on Grayskull. To reproduce:

`TT_METAL_WATCHER=30 pytest tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_layernorm_sharded.py::test_layernorm_sharded_rm -xv`

```
        ref_lnorm = ref_fn(in0 + in1, in0.shape[-1:], gamma.flatten(), beta.flatten(), epsf)
    
        passing, output = comp_pcc(tt_got_back, ref_lnorm, 0.999)
        logger.info(output)
>       assert passing
E       assert False

tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_layernorm_sharded.py:184: AssertionError
```

**Comment by TT-billteng** [comment]
@tt-aho @yugaoTT please have a look as only you two have touched this file

**Comment by yugaoTT** [comment]
I'm not seeing any errors locally, running `TT_METAL_WATCHER=30 pytest tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_layernorm_sharded.py::test_layernorm_sharded_rm -xv`

**Comment by yugaoTT** [comment]
@TT-billteng can we close it if this is no longer in CI?

**Comment by yugaoTT** [comment]
sweep test added back and merged, I'll close
