### ISSUE TITLE
Run u-benchmark tests on WH_B0

### ISSUE THREAD

**Issue by yugaoTT** [tenstorrent-metal/tt-metal#5799]
I tried running the test_compute_mm. I did make build `ENABLE_PROFIELR=1, make tests ENABLE_PROFIELR=1`
and then run
`./build/test/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm --m 11264 --n 3072 --k 768 --num-tests 1 --fast-dispatch 1 --bypass-check 0`

but got this error
`Process tear down with device 0 still active`

Is there sth wrong with my input command, or is it code related?

Another question is, how do I enable log_debug info to be printed out to the terminal? 
`log_debug(LogTest, "detail::LaunchProgram done");` to be printed out 
Thanks

**Comment by yugaoTT** [comment]
Update: I managed to workaround the problem by using a smaller tensor. 
Further question: how do I enable the device profiling for this test, it doesn't show any kernel duration currently, just host profiling is shown in the .csv file

**Comment by dongjin-na** [comment]
Hi @yugaoTT, I guess you are running it on WH_B0 right?
Please refer to 2. WH_B0 (compute_with_storage_grid_size is (x, y) = (8, 7)) in this link.
https://github.com/tenstorrent-metal/tt-metal/pull/3060#issuecomment-1917480755

```
ubuntu@tt-metal-dev-moreh-wh-9:~/tt-metal/build/test/tt_metal/perf_microbenchmark/1_compute_mm$ ./test_compute_mm --m 9216 --n 3072 --k 768 --num-tests 1 --fast-dispatch  --bypass-check
                  Metal | INFO     | Initializing device 0
                 Device | INFO     | Opening user mode device driver
CHECKING: [0, 0, 0, 0]
CHECKING: [1, 0, 0, 0]
2024-02-29 00:39:56.538 | INFO     | SiliconDriver   - Detected 1 PCI device : {0}
2024-02-29 00:39:56.565 | WARNING  | SiliconDriver   - init_detect_tt_device_numanodes(): Could not determine NumaNodeSet for TT device (physical_device_id: 0 pci_bus_id: 0000:00:08.0)
2024-02-29 00:39:56.565 | WARNING  | SiliconDriver   - Could not find NumaNodeSet for TT Device (physical_device_id: 0 pci_bus_id: 0000:00:08.0)
2024-02-29 00:39:56.567 | WARNING  | SiliconDriver   - bind_area_memory_nodeset(): Unable to determine TT Device to NumaNode mapping for physical_device_id: 0. Skipping membind.
---- ttSiliconDevice::init_hugepage: bind_area_to_memory_nodeset() failed (physical_device_id: 0 ch: 0). Hugepage allocation is not on NumaNode matching TT Device. Side-Effect is decreased Device->Host perf (Issue #893).
2024-02-29 00:39:56.570 | WARNING  | SiliconDriver   - bind_area_memory_nodeset(): Unable to determine TT Device to NumaNode mapping for physical_device_id: 0. Skipping membind.
---- ttSiliconDevice::init_hugepage: bind_area_to_memory_nodeset() failed (physical_device_id: 0 ch: 1). Hugepage allocation is not on NumaNode matching TT Device. Side-Effect is decreased Device->Host perf (Issue #893).
2024-02-29 00:39:56.680 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 6.3.0 (Device 0)
2024-02-29 00:39:56.681 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 6.3.0 (Device 1)
                  Metal | INFO     | AI CLK for device 0 is:   1000 MHz
                   Test | INFO     | Input M, N, K = 9216, 3072, 768 / 288, 96, 24 tile(s)
                   Test | INFO     | Num tests 1
                   Test | INFO     | time duration: 1.3177e+06 ns, rmax_tflops 32.98
                   Test | INFO     | Avg Rmax(TFLOPS) 32.981, Rpeak 114.800, Rmax / Rpeak 28.73%
                  Metal | INFO     | Closing device 0
                 Always | INFO     | CSV_MICROBENCHMARK:title:test_compute_mm
                 Always | INFO     | CSV_INPUT:M:9216:N:3072:K:768:fast-dispatch:true
                 Always | INFO     | CSV_OUTPUT:RMax(TFLOPS):32.98
                 Always | INFO     | CSV_RESULT:pass:true
                   Test | INFO     | Test Passed
                 Device | INFO     | Closing user mode device drivers
```

**Comment by dongjin-na** [comment]
> Further question: how do I enable the device profiling for this test, it doesn't show any kernel duration currently, just host profiling is shown in the .csv file

- `--fast-dispatch` doesn't use the device profiler. 
- running test_compute_mm without `--fast-dispatch` calculates Rmax using device profiler, so it needs to set the env variable `TT_METAL_DEVICE_PROFILER=1`.

`TT_METAL_DEVICE_PROFILER=1 ./build/test/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm --m 9216 --n 3072 --k 768 --bypass-check`

**Comment by yugaoTT** [comment]
Thank you for the clarification, 
Is there a way to modify the code to use device profiler for fast dispatch? I want to get the kernel side duration, so fast dispatch will definitely give us a much better perf.

**Comment by yugaoTT** [comment]
In the pytest, it can generate a csv file like the below, we can get the device kernel duration, which measures exactly how long the matmul lasts. Do we have this capability to do that in the c++ test?
<img width="1035" alt="Screenshot 2024-02-28 at 8 51 20 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/145494740/45d8ee80-6e84-44e3-ba75-1c16e44ff27f">

**Comment by dongjin-na** [comment]
> Is there a way to modify the code to use device profiler for fast dispatch? I want to get the kernel side duration, so fast dispatch will definitely give us a much better perf.

Here's the patch.
```
diff --git a/tests/tt_metal/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm.cpp b/tests/tt_metal/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm.cpp
index 7bcbd3f60..dccd5c314 100644
--- a/tests/tt_metal/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm.cpp
+++ b/tests/tt_metal/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm.cpp
@@ -334,14 +334,23 @@ int main(int argc, char** argv) {
             } else {
                 log_debug(LogTest, "calling EnqueueProgram");
                 std::chrono::duration<double, std::nano> duration;
-                auto t_begin = std::chrono::high_resolution_clock::now();
                 EnqueueProgram(device->command_queue(), program, false);
                 Finish(device->command_queue());
                 log_debug(LogTest, "EnqueProgram done");
-                auto t_end = std::chrono::high_resolution_clock::now();
-                duration = t_end - t_begin;
-                rmax_tflops.push_back(static_cast<double>(num_of_matmul_ops) / duration.count() / 1000);
-                log_info(LogTest, "time duration: {:.5} ns, rmax_tflops {:.2f}", duration.count(), rmax_tflops[i]);
+
+                uint64_t t0_to_any_riscfw_end = get_t0_to_any_riscfw_end_cycle(device, program);
+                double cycle_time = 1 / static_cast<double>(tt_npu_clock) / giga_byte;
+                auto execution_time = t0_to_any_riscfw_end * cycle_time;
+                rmax_tflops.push_back(static_cast<double>(num_of_matmul_ops) / execution_time / tera_byte);
+
+                log_debug(LogTest, "cycle time {:.8f}s", cycle_time);
+                log_debug(LogTest, "t0_to_any_riscfw_end {}", t0_to_any_riscfw_end);
+                log_info(
+                    LogTest,
+                    "time duration: {:.5}us ({}cycles) rmax_tflops {:.2f}",
+                    execution_time,
+                    t0_to_any_riscfw_end,
+                    rmax_tflops[i]);
             }
         }
```

**Comment by dongjin-na** [comment]
> In the pytest, it can generate a csv file like the below, we can get the device kernel duration, which measures exactly how long the matmul lasts. Do we have this capability to do that in the c++ test?

Would you share an example of how to get that csv file using pytest?

**Comment by yugaoTT** [comment]
in python, you can run `./tt_metal/tools/profiler/profile_this.py -c "pytest tests/tt_eager/python_api_testing/unit_testing/matmul.py` to get the csv. the underlying infra will handle the profiling.The profiler is configured in `run_device_operation` in `run_operatino.cpp`.
