### ISSUE TITLE
ttnn.lerp operation is missing weight parameter

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent-metal/tt-metal#5817]
ttnn.lerp operation is missing weight parameter which has no default value in torch and tt_lib implementations.

ttnn docs: https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/ttnn/lerp.html
tt_lib docs: https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/dependencies/tt_lib.html
torch docs: https://pytorch.org/docs/stable/generated/torch.lerp.html#torch.lerp

**Comment by jliangTT** [comment]
@boris-drazic , assigning this as the eltwise bug. I don't think you are working on this are you?

**Comment by VirdhatchaniKN** [comment]
Hi @nemanjagrujic , @jliangTT 
Weight parameter was missed in the bindings. 
#6630 would fix it.

**Comment by nemanjagrujic** [comment]
@VirdhatchaniKN Great!

Can you let me know when this is merged? So we can add sweeps.

**Comment by VirdhatchaniKN** [comment]
> @VirdhatchaniKN Great!
> 
> Can you let me know when this is merged? So we can add sweeps.

Sure. Once Approved, I can merge it to main. Will let you know when done.

**Comment by jliangTT** [comment]
amazing work.

**Comment by VirdhatchaniKN** [comment]
Merged #6630
