### ISSUE TITLE
Fix broken conv in certain cases on GS ttnn stable diffusion in test_resnet_block_2d on nightly, causing circular buffers > 1MB allocated

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent-metal/tt-metal#5835]
I did not see this error for at least 5 invocations of slow dispatch pipeline before https://github.com/tenstorrent-metal/tt-metal/actions/runs/7998045556, and saw it immediately after.

It did not appear in `v0.44.0-rc11`.

My suspicion therefore is that the commit range in which this happened is:

4db6308e27d506df7afee74afe2356c61f833499 (`v0.44.0-rc11`)

and

d8a522e92f383c1b73cd1dbd51e6485a3c3044f1

```
FAILED tests/ttnn/integration_tests/stable_diffusion/test_resnet_block_2d.py::test_resnet_block_2d_512x512[batch_size=2-in_channels=1920-input_height=16-input_width=16-index1=2-index2=0-block_name=up-out_channels=1280] - RuntimeError: TT_THROW @ tt_metal/impl/program/program.cpp:487: tt::exception
info:
Statically allocated circular buffers on core range {} grow to {} B which is beyond max L1 size of {} B
[(x=0,y=0) - (x=7,y=4)]
1979684
1048576
backtrace:
 --- tt::tt_metal::detail::ConfigureDeviceWithProgram(tt::tt_metal::Device*, tt::tt_metal::Program&)
 --- tt::tt_metal::detail::LaunchProgram(tt::tt_metal::Device*, tt::tt_metal::Program&)
 --- /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tt_eager/tt_lib/_C.so(+0x5a3664) [0x7f4c634f0664]
 --- tt::tt_metal::operation::detail::run_device_operation(std::optional<std::reference_wrapper<tt::tt_metal::CommandQueue> >, tt::tt_metal::operation::DeviceOperation const&, std::vector<tt::tt_metal::Tensor, std::allocator<tt::tt_metal::Tensor> > const&, std::vector<std::optional<tt::tt_metal::Tensor const>, std::allocator<std::optional<tt::tt_metal::Tensor const> > > const&, std::vector<std::optional<tt::tt_metal::Tensor>, std::allocator<std::optional<tt::tt_metal::Tensor> > > const&)
 --- tt::tt_metal::operation::run(tt::tt_metal::operation::DeviceOperation const&, std::vector<tt::tt_metal::Tensor, std::allocator<tt::tt_metal::Tensor> > const&, std::vector<std::optional<tt::tt_metal::Tensor const>, std::allocator<std::optional<tt::tt_metal::Tensor const> > > const&, std::vector<std::optional<tt::tt_metal::Tensor>, std::allocator<std::optional<tt::tt_metal::Tensor> > > const&)
 --- tt::tt_metal::operation::run_without_autoformat(tt::tt_metal::operation::DeviceOperation const&, std::vector<tt::tt_metal::Tensor, std::allocator<tt::tt_metal::Tensor> > const&, std::vector<std::optional<tt::tt_metal::Tensor const>, std::allocator<std::optional<tt::tt_metal::Tensor const> > > const&, std::vector<std::optional<tt::tt_metal::Tensor>, std::allocator<std::optional<tt::tt_metal::Tensor> > > const&)
 --- tt::tt_metal::optimized_conv(tt::tt_metal::Tensor const&, tt::tt_metal::Tensor const&, std::optional<tt::tt_metal::Tensor const>, std::optional<tt::tt_metal::Tensor const>, std::vector<int, std::allocator<int> >, unsigned int, bool, bool, bool, MathFidelity, tt::tt_metal::OptimizedConvParallelizationConfig const&, tt::tt_metal::OptimizedConvBlockConfig const&, unsigned int, std::optional<tt::tt_metal::MemoryConfig>, std::optional<tt::tt_metal::DataType>, std::optional<std::array<unsigned int, 4ul> >)
```

I will be investigating some commits from Moreh and models team first.

cc: @arakhmati @eyonland @jliangTT @TT-billteng

**Comment by tt-rkim** [comment]
This has been in the pipelines for over a week.

**Comment by tt-rkim** [comment]
We're seeing this on FD as well: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8091702376/job/22111192865

**Comment by tt-rkim** [comment]
@tt-nshanker Conv changes from last week have broken some SD tests.

Please investigate and fix. The scheudled pipelines are broken.

**Comment by tt-rkim** [comment]
We will disable the broken cases while we focus on this sprint. @tt-nshanker and @mywoodstock to fix after this week.

**Comment by tt-rkim** [comment]
cc: @jliangTT

**Comment by mywoodstock** [comment]
@tt-rkim The info provided in this issue is not enough to find what was failing. Can you point me to the nightly run where this failed (SD)? The one linked above is a successful run, and the run immediately following this has a different test failure.
Additionally I do not see the failing test config mentioned above in the test.
I see the FD error above though.

**Comment by tt-rkim** [comment]
Example: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8035954154/job/21949107038

**Comment by mywoodstock** [comment]
Just realized this is GS, and I don't believe SD's unit tests are supported on GS, only WH.
https://github.com/tenstorrent-metal/tt-metal/pull/6106

**Comment by mywoodstock** [comment]
Sorry about that, since SD is back on GS, we will fix this (I believe we already have it fixed in our dev branches)

**Comment by mywoodstock** [comment]
This should work now in main. Running locally is all good in both SD and FD

**Comment by tt-rkim** [comment]
I think we can close this now? I don't see this on nightly slow dispatch (although seeing a diff ttnn integration test error now)
