### ISSUE TITLE
Hang in WH MM

### ISSUE THREAD

**Issue by AleksKnezevic** [tenstorrent-metal/tt-metal#5862]
Stable Diffusion hangs on WH_B0 

to repro run `pytest -svv "tests/ttnn/integration_tests/stable_diffusion/test_transformer_2d_model.py::test_transformer_2d_model_512x512[model_name=CompVis/stable-diffusion-v1-4-input_shape=(2, 640, 32, 32)-index1=1-index2=1-attention_head_dim=80-block=down]"` 

on `aknezevic/MM_hang`

**Comment by TT-BrianLiu** [comment]
The hang is from the very first mm for qkv, not from attention scores. It seems deterministic.

**Comment by TT-BrianLiu** [comment]
UPDATE: Doesn't hang for bfloat8_b. Lowering to P1 for now

**Comment by AleksKnezevic** [comment]
No longer hangs when rebased off latest main. Closing issue.
