### ISSUE TITLE
Increase T3000 host memory

### ISSUE THREAD

**Issue by cglagovich** [tenstorrent-metal/tt-metal#5910]
Give `sjc-snva-t3002` 512GB of host DRAM.

Thanks! 😄

**Comment by jliangTT** [comment]
ok. talked to Dave. this will be our spec to fulfill this system with the following.

32GB DIMM (ECC RDIMM, DDR4-3200MHz) x 16 

Now, google-mapping the nearest computer store

**Comment by cglagovich** [comment]
You are the greatest!

**Comment by jliangTT** [comment]
yeah we are targeting EOD (PST time) ETA if all goes well. DIMM's is being purchased and pick up this afternoon and installation is queued up right after that.

**Comment by jliangTT** [comment]
i think we are done. please check @cglagovich

**Comment by cglagovich** [comment]
Looks good to me
