### ISSUE TITLE
MaxPool Op should support and retain any incoming padding

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent-metal/tt-metal#5923]
Currently we need to remove padding before feeding into Maxpool

**Comment by nsmithtt** [comment]
@tapspatel, do you have a fix for this?  How is this currently working in Unet?

**Comment by nsmithtt** [comment]
This issue seems to have been fixed on main, after rebasing it no longer repros.  Closing for now, we can reopen if we find a repro.
