### ISSUE TITLE
Hang in stable diffusion bfp8

### ISSUE THREAD

**Issue by AleksKnezevic** [tenstorrent-metal/tt-metal#5930]
Stable diffusion with all ops on device is hanging, somewhere in the first upblock resnet block. Can you please triage? 

To reproduce, please run `pytest -svv tests/ttnn/integration_tests/stable_diffusion/test_unet_2d_condition_model.py -k 512` on `aknezevic/SD_upblock0_hang` on a wormhole N150.

**Comment by AleksKnezevic** [comment]
Thanks @arakhmati for pointing me to the logs, based on that, seems it's groupnorm that hangs. @yugaoTT can you please take a look?

**Comment by mywoodstock** [comment]
@yugaoTT did some investigation -- there is a deadlock in the groupnorm kernels on the semaphores: the sender is waiting for receivers notifications, but it seems that the number of cores its waiting on is not correct in this particular config. 
Probably something is off with the mcast groups?
I'll dig further.

**Comment by eyonland** [comment]
It's quite possible that this is the same bug as #5789

**Comment by AleksKnezevic** [comment]
#5789 on hangs while profiling, this is during normal execution.

**Comment by yugaoTT** [comment]
should be the same bug in #5970. The problem is the sharding shape is wrong in TTNN test, I added asserts to capture this in branch nshanker/aleks_nitika_branch_rebased_to_main
