### ISSUE TITLE
Fix performance drop in device perf pipeline

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent-metal/tt-metal#5969]
ResNet has sank to 8-9 fps according to the pipeline: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8119606888/job/22195690796

We believe it is because of this commit:

```
2024-03-01 (f1953b646) by Yan Zaretskiy (Author yzaretskiy@tenstorrent.com) : #4438: Make Resnet use the new fold op instead of plain Python implementation
```

which adds this fold and pad op that take around 2.3*10^9 ns kernel duration just by their own:

![image](https://github.com/tenstorrent-metal/tt-metal/assets/109366641/d2523d92-411c-46ee-b4c9-cfc4c3da1ec1)

reported by @rtawfik01

**Comment by yan-zaretskiy** [comment]
We knew that the initial fold impl would be slow. To avoid unnecessary performance drops, I'm reverting the usage of the new fold op until I finish its sharded version.
