### ISSUE TITLE
Hang in ttnn Stable Diffusion model demo in Wormhole

### ISSUE THREAD

**Issue by vigneshkeerthivasanx** [tenstorrent-metal/tt-metal#5970]
**Describe the bug**
Stable diffusion demo is hanging in Wormhole machine.

**To Reproduce**
1. checkout to branch `keerthana/stable_diffusion_ttnn_demo`
2. Run `pytest --disable-warnings --input-path="models/experimental/functional_stable_diffusion/demo/input_data.json" models/experimental/functional_stable_diffusion/demo/demo.py::test_demo` to test demo with data from input_data.json.

**Expected behavior**
Indefinite hang in demo when run in Wormhole

**Comment by boris-drazic** [comment]
@yugaoTT this looks like it is the same issue as [#5930](https://github.com/tenstorrent-metal/tt-metal/issues/5930)

**Comment by yugaoTT** [comment]
It should have been resolved and passed on unit test. The problem is the sharing shape is wrong in TTNN test, I added asserts to capture this in branch `nshanker/aleks_nitika_branch_rebased_to_main`
