### ISSUE TITLE
Rebase and Merge: FD pipelines hanging on N300 after python sweep tests

### ISSUE THREAD

**Issue by aliuTT** [tenstorrent-metal/tt-metal#5972]
With all the tunneling and FD changes, we are seeing a deterministic CI hang, looks like during setting up remote chip. Only happens on N300 machines on CI, cannot reproduce locally, at least on a t3000. If I comment out ```./tests/scripts/run_python_sweep_tests.sh```
from
`fast-dispatch-build-and-unit-tests.yaml`, tests pass.

Example: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8127882306/job/22213201896

**Comment by abhullar-tt** [comment]
I am able to produce it locally on a N300. @tt-aho do you know if the pytest sweeps do anything differently for device setup/teardown compared to the pytest unit test?

**Comment by aliuTT** [comment]
@abhullar-tt for datapoint, is your N300 running at 800Mhz or 1GHz?

On CI, it's 1GHz N300. For my local machine, it's a 800Hmz T3000

**Comment by abhullar-tt** [comment]
> @abhullar-tt for datapoint, is your N300 running at 800Mhz or 1GHz?
> 
> On CI, it's 1GHz N300. For my local machine, it's a 800Hmz T3000

N300 running 1GHz

**Comment by aliuTT** [comment]
`tests/scripts/run_pre_post_commit_regressions_fast_dispatch.sh` passes locally for me on BM 129

**Comment by abhullar-tt** [comment]
Update: locally after resetting on N300 WH BM 130 the hang is not reproducible

We were able to get successful run by running gtests before pytests and resetting after pytests run on one machine but the same commit results in another hang on a different machine:

failing run: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8160677237
passing run: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8160700016

note: this is a different hang signature as the original hang since we are able to run some gtests before seeing the hang but I believe it is related

**Comment by aliuTT** [comment]
Another pass: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8162805655

**Comment by aliuTT** [comment]
Another pass: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8162863567

**Comment by abhullar-tt** [comment]
To enable the tunnelling PR (#5986) we are going to temporarily move the R chip gtests into the nightly test suite and only run L chip tests on post commit 

Once we get syseng drop for tt-smi fix + 800 MHz (targeted for 03/06) we will re-test the R chips on VMs

**Comment by jliangTT** [comment]
checking in on this. Did we verify with the latest syseng fix?

**Comment by aliuTT** [comment]
Not yet, are all machines now flashed with new syseng release? If so I can start a CI branch to spam R chip for push. If stable I can make the revert happen maybe over the weekend

**Comment by aliuTT** [comment]
Candidate commit: https://github.com/tenstorrent-metal/tt-metal/commit/1350d91647c81e0b6ed7a29545ea0c752bd6e064

I'll spam CI

**Comment by aliuTT** [comment]
Hmm, all my tries ended up being hangs. I feel like with how consistent it's hanging now, maybe something actually regressed since we last tried to enable R chip.

**Comment by abhullar-tt** [comment]
we should probably try on the provisioned VM to see if the hang is deterministic and reproducible now? the BMs still look good?

**Comment by tt-rkim** [comment]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8329368635/job/22791698154

We have an instance of this failing on X2 VM with 800MHz + latest SMI reset which resets eth queues + newest firmware.

**Comment by tt-rkim** [comment]
@aliuTT re-ran the previous 3-time passing pipeline on runners 2 weeks ago, but that was before the flash and SMI upgrades.

One thing infra will try is to see the stability of this test on X2 VMs with previous firmware and X2 VMs with current firmware.

Let's slim down the post-commit to make this go faster. Get rid of GS and X1 configs on branch, and target old FW and new fw.

**Comment by davorchap** [comment]
@TT-billteng and @tt-rkim is N300 clean now, can we close?

**Comment by tt-rkim** [comment]
Good w/ me after our C++ test isolation @TT-billteng

**Comment by TT-billteng** [comment]
N300 pipeline is clean now
