### ISSUE TITLE
Enable temporary bare metal (BM) CI for X2 ethernet tests

### ISSUE THREAD

**Issue by davorchap** [tenstorrent-metal/tt-metal#6036]
post-commit push split across VM / BM:

BM CI:
just R + multi-chip tests

VM CI:
anything just L / pytests

**Comment by davorchap** [comment]
fyi @jliangTT @abhullar-tt @aliuTT

**Comment by tt-rkim** [comment]
Action items:

- @tt-rkim add t3004 to constant CI, not just nightly
- Install new SMI on 2x2 cloud machine and t3004
- Dependent issues for enabling this over all CI:
  - https://github.com/tenstorrent/cloud/issues/2053
  - https://github.com/tenstorrent-metal/metal-internal-workflows/issues/94
  - https://github.com/tenstorrent-metal/metal-internal-workflows/issues/108

cc: @ttmchiou  @TT-billteng @jliangTT

**Comment by tt-rkim** [comment]
> meeting tomorrow to look at network isolation

+1 for this!! I see the meeting. This is gonna be great for both development and CI!

**Comment by tt-rkim** [comment]
Unblocked models and FD people, moving to P1

**Comment by tt-rkim** [comment]
@davorchap People can now add X2 tests depending on 800 MHz flash with ethernet resets into the nightly pipeline.

we will be slowly adding them into post-commit capacity once they are all converted by cloud to Q35.
