### ISSUE TITLE
Port unet to WH

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent-metal/tt-metal#6076]

**Comment by tapspatel** [comment]
Initial repro instructions
```
git checkout tpatel/unet-wh
python tests/ttnn/integration_tests/unet/test_ttnn_shallow_unet.py
```

**Comment by tapspatel** [comment]
need to disable shallow Conv optimization as its not functional on wormhole yet

**Comment by tapspatel** [comment]
Disabling any over config overrides
```
#if "act_block_h" in config_override:
    #    act_block_h_override = config_override["act_block_h"]
    #    assert act_block_h_override % 32 == 0, "act_block_h must be divisible by 32 (tile height)"
```

another change that must be made is the padded input channels into c1 should be changed to 32
```
ttnn_module_args.c1["padded_input_channels"] = 32
```

this takes us to the next error on c1
```
Statically allocated circular buffers on core range {} grow to {} B which is beyond max L1 size of {} B
[(x=0,y=0) - (x=7,y=7)]
1679588
1499136
```

**Comment by nsmithtt** [comment]
@tapspatel, sorry I didn't realize an issue already existed, closing as a dup of https://github.com/tenstorrent-metal/tt-metal/issues/5924

I'll copy paste your comments over.
