### ISSUE TITLE
Worker core not receiving "go" signal

### ISSUE THREAD

**Issue by SeanNijjar** [tenstorrent-metal/tt-metal#6082]
# Bug Description
When running a tt metal program, the program hangs because one of the worker cores never receives its "go" signal. All other cores receive the go signal and advance as far as possible. 

I narrowed this down by adding trace statements to the startup sequence for brisc/ncrisc and noticed that worker core [0,0] (noc0: [1,1]) was not getting its go signal. It reported waiting for the go signal but never printed the statement right after.

On branch I was able to (unreliably, but most of the time) work around this by shifting the worker cores around, without any other changes. I'm keeping as P1 because the workaround doesn't reliably work.

Note that this test case has a mix of workers and eriscs active at the same time.

# To Reproduce
1. Checkout branch: `snijjar/issue-missing-go-signal`
2. Setup WH env
3. Build: `scripts/build_scripts/build_with_profiler_opt.sh`
4. Run test: `pytest -vvv  tests/tt_eager/python_api_testing/unit_testing/test_all_gather.py -k 1-mem_config0-input_dtype0-input_shape38-3-layout38`
  - Test will hang

# Expected Behaviour 
Worker [0,0] (noc0: [1,1]) should get the go signal and the test should run to completion. Sometimes fails PCC but this is a separate issue.

# Environment
- Branch: `scripts/build_scripts/build_with_profiler_opt.sh`
- Arch: Wormhole B0
- Machine Type: T3000
- Machine: t3008

# Additional context
This test has 12 worker cores. You can shift them around by modifying the following lines in `tt_eager/tt_dnn/op_library/all_gather/multi_core/all_gather_op_multi_core.cpp` and rebuilding/rerunning. 

Simply add an offset of 2 for each of these (~line 224)
FROM:
```
uint32_t receiver_worker_row = (fit_sender_and_receiver_workers_on_same_row ? i: 2 * i);
uint32_t sender_worker_row = (fit_sender_and_receiver_workers_on_same_row ? i: (2 * i) + 1);
```

TO:
```
uint32_t receiver_worker_row = (fit_sender_and_receiver_workers_on_same_row ? i + 2: (2 * i) + 2);
uint32_t sender_worker_row = (fit_sender_and_receiver_workers_on_same_row ? i + 2: ((2 * i) + 1) + 2);
```

**Comment by SeanNijjar** [comment]
Tagged as fast-dispatch for now although this might not be the right category after triage is concluded.

FYI @DrJessop

**Comment by SeanNijjar** [comment]
Assigning to @aliuTT after discussion - he suspects its under his umbrella.

**Comment by SeanNijjar** [comment]
It turns out this is currently blocking even my unidirectional changes from getting into main because once I go to 8 chips, the probability of failure is very high.

**Comment by aliuTT** [comment]
I'm putting together a PR to fix this

**Comment by aliuTT** [comment]
Fixed on main here: `adba3c92c3e14f2d981e59f4589a59132d23a56d`, can you close issue once you're happy with all tests?

**Comment by SeanNijjar** [comment]
Hey Allan, it seems like the version on main causes my all-gather tests to hang, but the one you provided with me works fine. I think there is something wrong and I'll need your help to look into is. As it is now, it looks like allgather is blocked from being mainlined

**Comment by aliuTT** [comment]
Hmm the only functional difference should be this calculation here:
```
uint32_t num_workers = 0;
num_workers += program.logical_cores().at(CoreType::WORKER).size();
num_workers += program.logical_cores().at(CoreType::ETH).size();
```

**Comment by SeanNijjar** [comment]
Weird. Whatever the problem is, it looks like it's before the main program actually really even starts. Would you like two branches (one with the mainline commit and one with the pre-merge commit you gave me?)

**Comment by aliuTT** [comment]
sure, gimme

**Comment by aliuTT** [comment]
I made the change, because without it was incorrectly calculating num_workers = 0 for programs with just ETH cores, hence getting mismatches on a lot of multichip unit tests. Maybe something weird with WORKER + ETH. I'll try to debug tonight or tmrw

**Comment by SeanNijjar** [comment]
You can pickup `snijjar/issue-6082`. It has the version that works. To make it fail, all I would do on my end is to drop the top commit (your "good" one) and pickup your mainlined commit (which is the next commit on main from where the branch is based).

You should see an `ERROR` message when running `pytest  tests/tt_eager/python_api_testing/unit_testing/misc/test_all_gather.py`

**Comment by SeanNijjar** [comment]
I should note that I did try an initial debug (build debug mode, break on exceptions throw, run in hopes that the error is from a thrown exception. In this case, no such error appeared to be through, so I currently have no idea where this `ERROR` is coming from. I also couldn't find a corresponding message, even with `Trace` logging enabled.

**Comment by aliuTT** [comment]
@SeanNijjar does the erisc datamover kernels actually finish? or just spin in a while loop?

**Comment by SeanNijjar** [comment]
They are supposed to finish. In the past, I've verified that they'll reach the end of the kernel, and the op will hang if they don't.

**Comment by aliuTT** [comment]
I'm running this test `pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_all_gather.py::test_all_gather_on_t3000[mem_config1-input_dtype0-input_shape41-2-layout41-8-1]`, able to repro what you're reporting. I'm seeing 6 cores used in the program, 4 worker cores and 2 ethernet cores. Previously on the passing commit, I was erroneously computing total workers as 4, therefore dispatch core was only expecting 4 increments from 6 cores. On the hanging commit, I correctly program the dispatcher core to wait for 6 cores done, but in both cases I'm only seeing 4 increments from all 6 cores. So, it may be passing before by accident. I'm also seeing some weird prints so we should look at this together.

**Comment by SeanNijjar** [comment]
Are you seeing hanging behaviour? On my end, all I'm seeing is a `ERROR` message and the test terminating right away. From my end I was able to DPRINT "EDM Done" messages within my kernel so I would suspect if a finish signal isn't arriving, it's because of the wrapper code?

**Comment by SeanNijjar** [comment]
I'm unable to reproduce the `ERROR` message I saw earlier now. I wonder if maybe the machine was in a questionable state (even though I did have a couple passing tests)... I'm going to close this now that the original issue is fixed as well and I'm able to merge onto the fix.
