### ISSUE TITLE
RN50 device perf pipeline failing with PCC error

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent-metal/tt-metal#6084]
Just observed this. For example:
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8165882376/job/22323726457

Its been like that for almost a week, so need investigation and bisect etc.

**Comment by tt-rkim** [comment]
@vtangTT @TT-billteng 
Should we try a bisect with running just this test and seeing where PCC fails?

Also, we should ensure we separately report functionality of models so it's obvious, as this is a case where we still output the performance metrics but don't know that rn50 failed unless we scroll up

**Comment by vtangTT** [comment]
bisecting with `pytest models/demos/resnet/tests/test_metal_resnet50.py::test_run_resnet50_inference[HiFi4-activations_BFLOAT16-weights_BFLOAT16-batch_8]` looking for a PCC fail returned this commit: 
https://github.com/tenstorrent-metal/tt-metal/commit/76a34d5c971f5f23436b2b2a61d7bb9d71001b18

**Comment by mywoodstock** [comment]
thanks @vtangTT 
will take a look

**Comment by mywoodstock** [comment]
@yugaoTT these are the fp32 accum support changes you added to the convs. Would you be able to investigate the PCC drop?

**Comment by yugaoTT** [comment]
@mywoodstock yes I can take a look, is the fp32 causing pcc drop?

**Comment by mywoodstock** [comment]
No this is grayskull

**Comment by yugaoTT** [comment]
found the issue, compute kernel config arg is not passed in to some modules

**Comment by yugaoTT** [comment]
PR here 
https://github.com/tenstorrent-metal/tt-metal/pull/6147

**Comment by yugaoTT** [comment]
pipeline passed

**Comment by yugaoTT** [comment]
merged, wil close this issue
