### ISSUE TITLE
cmds return to completion queue with out of order event IDs after FD1.3 changes

### ISSUE THREAD

**Issue by kmabeeTT** [tenstorrent-metal/tt-metal#6093]
Hit this issue of completed event-ids being out of order, locally today on some tests WIP not yet in main.    Demoted to warning instead of assert in commit on branch,  to not get board stuck:

```
	                  Metal | WARNING  | Event ID is expected to increase. Wrapping not supported for sync. (cq_id: 0 completed event 4 but last recorded completed event is 5)
```

I pushed some debug changes to branch here right after the FD1.3 merge so you can see it's easy to repro pass when excluding the FD1.3 merge:

**Branch:**

```
kmabee/event_id_assert_debug_after_fd_changes
```

**Test/Observations**

- Issue is event_id=5 returns first, then event_id=4 despite being issued in opposite order (I hope/think) see below for test outline
- It's in the 2CQ test suite and requires env-var, but it's just a single CQ test right now, for illustrative purposes.
- First test I added that mixes Programs and Events exposed this issue after FD1.3 changes.
- Test doesn't fail if it's run alone, only fails if it's run after another test, cmd below is for 2 back to back tests.
- Test only hits this sometimes (50% of the time) so it's non-deterministic
- Tried replacing `EnqueueProgram(), EnqueueRecordEvent()` pair that go out of order with `EnqueueProgram(), EnqueueWaitForEvent()` and they also go out of order, so I get impression the cmd type after Program doesn't matter.

```
    EnqueueWriteBuffer(cq_write, buffers[1], input_vec, config.blocking); // event_id=0
    EnqueueRecordEvent(cq_write, sync_event);
    EnqueueWaitForEvent(cq_prog, sync_event);
    EnqueueProgram(cq_prog, program, config.blocking);
    EnqueueWriteBuffer() (this is implicitly added to load the program above). (event_id=4)
    EnqueueRecordEvent(cq_prog, sync_event); (event_id=5)
    EnqueueWaitForEvent(cq_read, sync_event);
    EnqueueReadBuffer(cq_read, buffers[2], result_vec, config.blocking);
```

**Command:**

Run this test cmd few times and you'll see one run hit the warning (demoted from assert on branch) in the 2nd test on cmdline called `MultiCommandQueueSingleDeviceFixture.TestEventsWriteProgram_NB_CQ0_Passthrough_Events`:

```
% make -j32 tests/tt_metal/unit_tests_fast_dispatch_single_chip_multi_queue
 
% TT_METAL_NUM_HW_CQS=2 ./build/test/tt_metal/unit_tests_fast_dispatch_single_chip_multi_queue  --gtest_filter='MultiCommandQueueSingleDeviceFixture.TestEventsWriteProgram_B_CQ0_Passthrough:MultiCommandQueueSingleDeviceFixture.TestEventsWriteProgram_NB_CQ0_Passthrough_Events' |& tee 2_tests.log


	
	                   Test | INFO     | test_events_write_program_read starting w/ blocking: false CqMode: CommandQueueMode::PASSTHROUGH cq_write: 0 cq_prog: 0 cq_read: 0
	               Dispatch | INFO     | EnqueueWriteBuffer (event_id: 0) for channel 0
	                   Test | INFO     | Inserting RecordEvent on cq: 0 (write) and WaitForEvent on cq: 0 (prog)
	                   Test | INFO     | EnqueueRecordEvent (event_id: 1) on CQ: 0
	                  Metal | INFO     | EnqueueWaitForEvent() issued on Event(device_id: 0 cq_id: 0 event_id: 1) from device_id: 0 cq_id: 0
	                   Test | INFO     | EnqueueWaitForEvent (event_id: 2) on CQ: 0
	                  Metal | INFO     | Setting last_completed_event: 0 for cq_id: 0
	                  Metal | INFO     | Setting last_completed_event: 1 for cq_id: 0
	                  Metal | INFO     | Setting last_completed_event: 2 for cq_id: 0
	               Dispatch | INFO     | EnqueueWriteBuffer (event_id: 3) for channel 0
	                   Test | INFO     | EnqueueProgram (event_id: 4) on CQ: 0
	                   Test | INFO     | Inserting RecordEvent on cq: 0 (prog) and WaitForEvent on cq: 0 (read)
	                   Test | INFO     | EnqueueRecordEvent (event_id: 5) on CQ: 0
	                  Metal | INFO     | EnqueueWaitForEvent() issued on Event(device_id: 0 cq_id: 0 event_id: 5) from device_id: 0 cq_id: 0
                          Metal | INFO     | Setting last_completed_event: 3 for cq_id: 0
	                  Metal | INFO     | Setting last_completed_event: 5 for cq_id: 0
	                   Test | INFO     | EnqueueWaitForEvent (event_id: 6) on CQ: 0
	                  Metal | INFO     | Setting last_completed_event: 4 for cq_id: 0
	                  Metal | WARNING  | Event ID is expected to increase. Wrapping not supported for sync. (cq_id: 0 completed event 4 but last recorded completed event is 5)
	                  Metal | INFO     | Setting last_completed_event: 6 for cq_id: 0
	                  Metal | INFO     | Setting last_completed_event: 7 for cq_id: 0

```

Other Misc Observation about Events + FD1.3:

 - Not sure what is going on here, but command_queue_consumer.cpp file I was familiar with seems... not used...anymore possibly (was going to add debug prints there) so I realized I have no idea what is happening with FD1.3.
 
 - These are in cq_prefetcher.hpp after the merge  (used to be in command_queue_consumer.hpp)  I think maybe should have been added to cq_dispatcher.hpp ? 

```
FORCE_INLINE void record_last_completed_event(uint32_t event_id) {
FORCE_INLINE void wait_for_event(uint32_t event_id, uint32_t noc_x, uint32_t noc_y) {
```

 - Not related to this failure, but events code is via these two function calls in `command_queue_consumer.cpp` , does it need to be ported somewhere in FD 1.3 code?
 
 ```
             wait_for_event(header->event_sync_event_id, header->event_sync_core_x, header->event_sync_core_y); <=== This
             
             <snip>
             
_queue_push_back(completion_data_size, completion_queue_start_addr, 
        record_last_completed_event(header->event); <==== This
        
 ```

**Comment by kmabeeTT** [comment]
FYI @abhullar-tt 

Followup to my last observation (and unrelated to this specific bug/fail), but yes assuming `command_queue_consumer.cpp` isn't used in WH single chip anymore, I see Events code (`record_last_completed_event()` call, and `wait_for_event()` call)  isn't used elsewhere (FD1.3), and it would explain why I was seeing occasional fails (data mismatch) in one of the more stressful tests starting yesterday night (was looking into that in parallel), locally (`MultiCommandQueueSingleDeviceFixture.TestEventsReadWriteWithWaitForEventCrossCQsPingPong`) - it's timing dependent, but with FD1.0 would have failed consistently if test was modified to skip using events feature `use_events = false` in test body, but with FD1.3 it only fails sometimes (hard to repro).

Confirmed by uncommenting some code in another single-CQ test in `test_events.cpp` that is supposed to hang when syncing on a future event that never was sent to device (and it doesn't hang because the events feature is missing):

```
        // Uncomment this to confirm future events not yet seen would hang.
        auto future_event = sync_events.at(0);
        future_event->event_id = 0xFFFF;
        log_info(tt::LogTest, "The next event (event_id: {}) is not yet seen, would hang", future_event->event_id);
```

It sucks that none of the events tests in CI caught this, so I am not upset (just at myself) since I am currently working on some more tests, and test updates that could more easily catch events feature breakage (part of them needed multi-cq and async queues which just got released, and also has some bugs being fixed)... but yeah, in process of beefing up tests.

**Comment by abhullar-tt** [comment]
ah yes we refactored single chip FD as part of tunnelling PR and I think in the process we dropped some features that were added during the refactor was completed. 

Event syncing was on our list but we merged when we saw current gtests passing

**Comment by kmabeeTT** [comment]
> ah yes we refactored single chip FD as part of tunnelling PR and I think in the process we dropped some features that were added during the refactor was completed.
> 
> Event syncing was on our list but we merged when we saw current gtests passing

Makes sense. Can we use this ticket for getting the Events functionality (those 2 function calls) added back to FD1.3?  Feel free to send me a cherry pick or discuss offline, or let me know if I should try stuff.  Looking closer at code, I think half of it is adding this after the 3x `completion_queue_push_back()` calls in `cq_prefetcher.cpp` these days:

```
record_last_completed_event(header->event);
```

For the other half (waiting for event) maybe it needs to be in each place we have `if (is_program)` in the same file?

```
        } else if (is_event_sync) {
            wait_for_event(header->event_sync_event_id, header->event_sync_core_x, header->event_sync_core_y);
```

Will keep working on new tests that actually fail in the meantime.

**Comment by abhullar-tt** [comment]
> > ah yes we refactored single chip FD as part of tunnelling PR and I think in the process we dropped some features that were added during the refactor was completed.
> > Event syncing was on our list but we merged when we saw current gtests passing
> 
> Makes sense. Can we use this ticket for getting the Events functionality (those 2 function calls) added back to FD1.3? Feel free to send me a cherry pick or discuss offline, or let me know if I should try stuff. Looking closer at code, I think half of it is adding this after the 3x `completion_queue_push_back()` calls in `cq_prefetcher.cpp` these days:
> 
> ```
> record_last_completed_event(header->event);
> ```
> 
> For the other half (waiting for event) maybe it needs to be in each place we have `if (is_program)` in the same file?
> 
> ```
>         } else if (is_event_sync) {
>             wait_for_event(header->event_sync_event_id, header->event_sync_core_x, header->event_sync_core_y);
> ```
> 
> Will keep working on new tests that actually fail in the meantime.

I think adding record_last_completed_event(header->event) whenever we write an event to completion queue makes sense. 

wait_for_event is for multi-CQ event syncing? 
to enable multi-CQ on N300 WH we would need to define additional dispatch cores for the L chip. atm we have four dispatch cores per N300. On L chip two are used to service L CQ 0 and two are used to service R CQ 0, to service L CQ 1 we would need two more dispatch cores (same goes for multi-CQ on R but we aren't supporting that atm)

**Comment by kmabeeTT** [comment]
> wait_for_event is for multi-CQ event syncing?

Yep that's right. Okay, I see the situation after offline discussion. I've been locally using N150 for multi-cq (and will continue to do so until situation changes) but the suite `MultiCommandQueueSingleDeviceFixture` is running on CI so I am a bit curious if there is something forcing it on N150 machines only?

Will try out above changes locally tonight/tomorrow and see if Events feature can get back to working.

For original problem reported to @DrJessop above (out-of-order events in completion queue) I still don't know what would cause that but my guess is maybe _non-program_ commands via `EnqueueRecordEvent()` and `EnqueueWaitForEvent()` aren't properly handled/supported in FD1.3 (in terms of writing back to completion queue when their currently-NOP-like job is finished) like they were in FD1.0.

**Comment by kmabeeTT** [comment]
Some offline discussions, I got some local changes working here for two different issues talked about:

1. Set stall=true required on non-program cmds of mine `EnqueueWaitForEvent()` and `EnqueueRecordEvent()` that must be ordered with programs... this works to solve the out-of-order event-id in completion queue issue reported in this issue
2. Add back events feature (`record_last_completed_event()` and `wait_for_event()` calls, in their new home `cq_prefetecher.cpp` for FD1.3

Will open PR for these after some more cleanup/testing tonight.
