### ISSUE TITLE
Add slice support to Interleaved2sharded

### ISSUE THREAD

**Issue by AleksKnezevic** [tenstorrent-metal/tt-metal#6112]
In stable diffusion we have a very large MHA section, which we can't perform MM+softmax+MM on in L1. We'd like to be able to time-shard it. Can we add support to interleaved2sharded to be able to slice out a section of the interleaved (DRAM) tensor and shard straight into L1. This avoids having to do two TM ops (unpad and i2s).

**Comment by AleksKnezevic** [comment]
For stable diffusion I'd need to be able to select on batch and Z

**Comment by tarafdarTT** [comment]
@AleksKnezevic can you add a P-label to this issue (e.g P1, P0, P2)

**Comment by tarafdarTT** [comment]
is @ttmtrajkovic working on this?

**Comment by AleksKnezevic** [comment]
This appears to have been handled by https://github.com/tenstorrent-metal/tt-metal/pull/6508
I'll double check it covers the cases we need for stable diffusion and close issue if no longer relevant.
