### ISSUE TITLE
Add update support to sharded to interleaved

### ISSUE THREAD

**Issue by AleksKnezevic** [tenstorrent-metal/tt-metal#6113]
Can we add support to sharded2interleaved to only update a part of the output tensor.
This is the flip side on #6112, i.e. a large tensor in DRAM that we need to update one section at a time with data residing in sharded L1.

**Comment by tarafdarTT** [comment]
I think Jasmina mentioned @ttmtrajkovic is working on this is that the case?

**Comment by AleksKnezevic** [comment]
Already done.
