### ISSUE TITLE
Hang on Matmul for sharded activations

### ISSUE THREAD

**Issue by djordje-tt** [tenstorrent-metal/tt-metal#6125]
**Describe the bug**
I am trying to shard activations across (4,2) grid and run matmul with weights streamed from DRAM. After proper memory_config setup and program_config generation in ttnn code it looks like it hangs on a matmul call. In file ttnn_falcon7b/tt/falcon_mlp.py there is call of ttnn.linear that hangs. 
**To Reproduce**
1. git clone/pull/checkout divanovic/mlp_sharded_hang
2. cd tt-metal
3. pytest models/demos/ttnn_falcon7b/tests/test_falcon_mlp.py 

**Expected behavior**
Test should fail on pcc assert in pytest by pass ttnn.linear call. 

**Please complete the following environment information:**
- Wormhole_b0 nebula_x1

**Comment by pavlejosipovic** [comment]
Here is the UT I've extracted that hangs in the same way 

```
@pytest.mark.parametrize("M", [128])
@pytest.mark.parametrize("N", [512])
@pytest.mark.parametrize("weights_dtype", [ttnn.DataType.BFLOAT16])
def test_sharded_matmul_2_ttnn(
    device, M, N, weights_dtype, function_level_defaults
):
    K = 4 * 32

    in0_shape = [1, 1, M, K]
    in1_shape = [1, 1, K, N]

    grid_size = ttnn.CoreGrid(2, 2)
    compute_grid_size = device.compute_with_storage_grid_size()
    if grid_size.x > compute_grid_size.x or grid_size.y > compute_grid_size.y:
        pytest.skip(f"Need {grid_size} grid size to run this test but core grid is {compute_grid_size}")

    sharded_mem_config = ttnn.create_sharded_memory_config(
        (M, K),
        grid_size,
        ttnn.ShardStrategy.BLOCK,
        ttnn.ShardOrientation.ROW_MAJOR,
    )

    in0 = torch.randn(in0_shape).bfloat16().float()
    in1 = torch.randn(in1_shape).bfloat16().float()

    in0_t = ttnn.from_torch(in0, device=device, layout=ttnn.TILE_LAYOUT, dtype=ttnn.DataType.BFLOAT16, memory_config=sharded_mem_config)
    in1_t = ttnn.from_torch(in1, device=device, layout=ttnn.TILE_LAYOUT, dtype=ttnn.DataType.BFLOAT16, memory_config=ttnn.DRAM_MEMORY_CONFIG)

    output_t = ttnn.linear(in0_t, in1_t, dtype=ttnn.DataType.BFLOAT16, memory_config=ttnn.DRAM_MEMORY_CONFIG, use_1d_systolic_array=False)

    pt_out = in0 @ in1

    tt_out = ttnn.to_torch(output_t)

    passing, output = comp_pcc(pt_out, tt_out)
    logger.info(output)
    assert passing
```

**Comment by TT-BrianLiu** [comment]
I am adding the check for this, so the use case here will now have `in0_block_w` set to 71, which may be too large.

**Comment by pavlejosipovic** [comment]
As far as I can tell max value for in0_block_w is 8, if I push it over 8 then matmul fails with acc (I"m getting 0.25 pcc in such cases).
Given the grid size of 8x8 this limits the inner dim of 2d matmul with block sharding on in0 to 64 tiles.
Does this make sense to you?

**Comment by pavlejosipovic** [comment]
Any case, I've tried sweeping with UT and I can't any example work if in0_block_w> 8, can you come up with example that works?

**Comment by TT-BrianLiu** [comment]
Falcon40B MLP second "dense_4h_to_h" matmul has `in0_block_w` set to 32 tiles. Take a look here: `models/demos/falcon40b/tt/model_config.py`

**Comment by TT-BrianLiu** [comment]
I am going to close this issue. Can you open a separate issue for `in0_block_w` giving you bad pcc if it's still an issue for you?

**Comment by pavlejosipovic** [comment]
I've logged #6345, it seems that is not specific to in0_block_w dim, but I've logged the issue anyway since some setups don't work for me.
And thx for fixing this original issue!
