### ISSUE TITLE
ttnn Stable Diffusion hangs on GS

### ISSUE THREAD

**Issue by vigneshkeerthivasanx** [tenstorrent-metal/tt-metal#6140]
**Describe the bug**
When tested the performance file of the Ttnn Stable Diffusion model on GS, we encountered an indefinite hang.

**To Reproduce**
1. Checkout to the branch `vignesh/stable_diffusion_ttnn_test_perf`
2. Run `pytest tests/ttnn/integration_tests/stable_diffusion/test_performance.py`

**Expected behavior**
Indefinite hang in test perf file for stable diffusion model when run in GS

**Comment by boris-drazic** [comment]
This hang can be reproduced on main by running
`pytest models/experimental/functional_stable_diffusion/tt2_multiple_iteration.py`

Test hangs during the execution of `UNet2D` model in these lines
```
ttnn_output = model(
                ttnn_latent_model_input, #input
                timestep=_t,
                encoder_hidden_states=ttnn_text_embeddings,
                class_labels=None,
                attention_mask=None,
                cross_attention_kwargs=None,
                return_dict=True,
                config=config,
)
```

This hang was introduced by commit [53ee273](https://github.com/tenstorrent-metal/tt-metal/tree/53ee273451851b229930d44e63081e7524216989) with changes to file 
`tt-metal/tt_eager/tt_dnn/op_library/sliding_window_op_infra/tt_py_composite_conv.py`
If we revert two changes to `if self.enable_auto_formatting and not activation.is_sharded():` conditions (old lines numbers 964 and 967, new line numbers 972 and 975) the test does not hang.

**Comment by mywoodstock** [comment]
thanks @boris, will take a look. (We had not tested this on GS since we were under the impression that we only need to focus on WH for SD! )

**Comment by mywoodstock** [comment]
fix is now in main.
