### ISSUE TITLE
microbenchmark pipeline failure on WH: test_noc_unicast_vs_multicast_to_single_core_latency

### ISSUE THREAD

**Issue by yugaoTT** [tenstorrent-metal/tt-metal#6164]
Bisecting the microbenchmark pipeline failures for `tests/tt_metal/microbenchmarks/noc/test_noc_unicast_vs_multicast_to_single_core_latency.py`

It caused the perf regression from dispatch core to worker core test. `Unicast cycles not within bounds. Received 333, was expecting between 200 and 300`

The error is introduced between commit 0905b14a2 to 6ae078784

To repro:
`./scripts/build_scripts/build_with_profiler_opt.sh`
`make tests`
`pytest tests/tt_metal/microbenchmarks/noc/test_noc_unicast_vs_multicast_to_single_core_latency.py`

**Comment by yugaoTT** [comment]
fyi @tt-rkim

**Comment by tt-rkim** [comment]
Thank you

**Comment by abhullar-tt** [comment]
with the tunnelling changes, the issue queue reader and completion queue writer cores are the same. this was causing regressions. Test has been updated to use the dispatch core as the consumer (same flow as GS)
