### ISSUE TITLE
silu needs to support row major format

### ISSUE THREAD

**Issue by AleksKnezevic** [tenstorrent-metal/tt-metal#6184]
In stable diffusion silu is sandwiched between groupnorm and conv. We need it to support row major format to reduce data movement. Note another silu change is required for this model, might make sense to group the work (see #5658). 

- [x] #6662

- [x] [shard size >= 1024]  tested with couple of shapes where the shard size is not multiple of 1024. Compared with the golden output derived by torch. The tt-output is matching with the golden output. 

- [x] #6818

**Comment by shwetankTT** [comment]
I am working on it.
