### ISSUE TITLE
ttnn ci tests are broken

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent-metal/tt-metal#6187]
Discovered regression tests after ttnn tests were added back into workflow.
Tests came from this PR.
https://github.com/tenstorrent-metal/tt-metal/issues/5730 

Disabled TTNN tests listed here in:
ttnn/unit_tests/test_multi_device.py
test_multi_device_open_close_using_context_manager
Test Fails and exits gracefully

ttnn/unit_tests/test_multi_device.py
test_ttnn_to_and_from_multi_device_shard(...)
Test Fails and exits gracefully

ttnn/unit_tests/test_multi_device.py
test_multi_device_open_close_using_context_manager()
Test Fails and exits gracefully

ttnn/unit_tests/operations/test_conv2d.py
test_sd_conv()
Test hangs the machine

ttnn/unit_tests/tests_multi_device.py
test_multi_device_check_per_device_shard()
Test Fails and exits gracefully

**Comment by mywoodstock** [comment]
I fixed the conv bug:
```
ttnn/unit_tests/operations/test_conv2d.py
test_sd_conv()
```
Assigning back to you -- please assign to relevant people.

**Comment by ttmchiou** [comment]
Issues generated and assigned to @cfjchu for debugging

**Comment by ttmchiou** [comment]
closing since all sub issues are fixed
