### ISSUE TITLE
Update Cache Performance

### ISSUE THREAD

**Issue by cglagovich** [tenstorrent-metal/tt-metal#6193]
**Describe the bug**
The `update_cache` op is slow and compute bound. As a required op in all LLM decode demos, maximizing its perf is important.

For context, `update_cache` currently accounts for 14% of device time for Llama2 decode.

**Analysis**
I find that `update_cache` is compute bound since commenting out tilization and untilization in [tt-metal/tt_eager/tt_dnn/op_library/update_cache/kernels/compute/update_cache.cpp](https://github.com/tenstorrent-metal/tt-metal/blob/main/tt_eager/tt_dnn/op_library/update_cache/kernels/compute/update_cache.cpp) leads to the op executing >2x faster.

**Repro**
```bash
./tt_metal/tools/profiler/profile_this.py -c "pytest -svv tests/tt_eager/python_api_testing/unit_testing/misc/test_update_cache.py::TestUpdateCache::test_update_cache_decode[cache_dtype0-0-input_dtype0-True-1-32-2048-64]"
```

Results should show that the vanilla op has `DEVICE_FW_DURATION = 68962 ns`.

After commenting out untilize/tilize calls, op should have `DEVICE_FW_DURATION=37215 ns`.

There are more optimizations we can make to overlap reader/writer with compute, but speeding up the compute kernel should come first.

**Please complete the following environment information:**
- T3000 machine @ 800MHz, running test on single chip

**Comment by jliangTT** [comment]
@eyonland , it doesn't look obvious if it is a kernel op issue. assigning to you to help triage.

**Comment by eyonland** [comment]
Looks like @rtawfik01 took ownership.  Moving to the kernel board.

**Comment by cglagovich** [comment]
Made some developments here.

@rtawfik01 optimized the untilize function to use packer untilization. This brought kernel time from `68380` to `37345`.


Beyond that, it seemed that the coordination between Compute and Writer kernels was the next perf issue.

Making compute and writer kernels operate with a granularity of 2 led to further improvement. In addition, the output CB was upsized to hold the full output, allowing write sync to occur at end of loop. This takes kernel time to `30485`.

Finally, reader became the bottleneck. Making the reader async read 2 inputs before syncing led to further improvement, taking kernel time to `21410`.

**Comment by rtawfik01** [comment]
Thanks @cglagovich for optimizing the reader/writers for this op!

**Comment by rtawfik01** [comment]
PR #6372 is merged
