### ISSUE TITLE
Adding Support for num_users < 32 for update_cache op.

### ISSUE THREAD

**Issue by caixunshiren** [tenstorrent-metal/tt-metal#6204]
# Issue
The current `update_cache` op takes in the following arguments:

```
cache_tensor: [num_users, n_heads, seq_len, head_dim]
input_tensor: [1, n_heads, num_users, head_dim]
cache_idx: int
```

The current implementation forces num_users to be 32. In some occasions such as parallelizing Llama2 70b on 32 chips, we might want num_users in the cache to be less than 32. For example, a cache tensor of [8, 1, 4096, 128]. Using a smaller cache, in some circumstances, could be useful because it enables more light weight batch matmul for attention.

# Proposed Solution
I propose the following modification to the API:
If num_user is less than 32, then we keep cache_tensor as with smaller batch, but takes in an input_tenso padded to 32 in dim [-2]. During update cache, only the first num_users in the untilized input tensor are used to update the cache. 

i.e. the new update_cache op takes in arguments 
```
cache_tensor: [num_users, n_heads, seq_len, head_dim]
input_tensor: [1, n_heads, max(num_users, 32), head_dim]
cache_idx: int
```

FYI @cglagovich @kevinmiTT11 @TT-BrianLiu

**Comment by caixunshiren** [comment]
Added support for this feature on `model-team/llama2-sprint`. Fully tested on various num_users and made sure existing test cases do not regress. Next step: merge the commit to main.

**Comment by TT-BrianLiu** [comment]
Sounds useful to have support for this. We should just extend `num_users` to be actual number of users in a given run. This would require model level tracking of `num_users`, but we would only update actual kv-cache we need.
