### ISSUE TITLE
[Bug Report] Runtime Error while running reshard op with large input-tensor 

### ISSUE THREAD

**Issue by mtatsumiTT** [tenstorrent-metal/tt-metal#6206]
**Describe the bug**
on n150 B0 machine, running a unit-test for reshard op raises the error below:
~~>       output_tensor_b = ttl.tensor.reshard(sharded_input_tensor.value, output_sharded_memory_config)
E       RuntimeError: TT_THROW @ tt_metal/impl/kernels/kernel.cpp:191: tt::exception
E       info:
E       1KB runtime args targeting kernel reshard_reader on (x=0,y=0) are too large.                Cannot be written as they will run into memory region reserved for result. Max allowable size is 1 KB.
E       backtrace:~~ 

EDIT: It seems the shard specs have changed in the latest SD model, and applying `ttl.reshard` op is failing with the following error:
```
E           RuntimeError: TT_FATAL @ tt_eager/tt_dnn/op_library/sharded/sharded_op.cpp:97: same_row_size
E           info:
E           row major must have shard_spec[1] be the same on both input and output
```

**To Reproduce**
1. Switch to branch `mtatsumi/reshard_test`
2. Run the following test command:
~~pytest -svv "tests/ttnn/unit_tests/test_reshard.py::test_sd_reshard[input_shape=(1, 1, 8192, 320)-input_shard_config={'shape': (1, 1, 160, 1024), 'core_grid': CoreGrid(y=2, x=8), 'strategy': <ShardStrategy.BLOCK: 3>, 'orientation': <ShardOrientation.COLUMN_MAJOR: 2>}-output_shard_config={'shape': (1, 1, 64, 1024), 'core_grid': CoreGrid(y=5, x=8), 'strategy': <ShardStrategy.BLOCK: 3>, 'orientation': <ShardOrientation.COLUMN_MAJOR: 2>}]"~~

EDIT: 
```bash
pytest -svv tests/ttnn/unit_tests/operations/test_core.py::test_reshard
```

**Expected behavior**
test should pass

**Screenshots**
N/A

**Please complete the following environment information:**
n150 B0 machine on IRD 

**Additional context**
N/A

fyi @AleksKnezevic @tt-nshanker @nsmithtt

**Comment by mtatsumiTT** [comment]
I tried out the latest reshard op for SD model but it seems the shard-specs have changed from the ones in the original unit tests. Currently I'm seeing the following error for all reshard cases:
```
E           RuntimeError: TT_FATAL @ tt_eager/tt_dnn/op_library/sharded/sharded_op.cpp:97: same_row_size
E           info:
E           row major must have shard_spec[1] be the same on both input and output
```
I updated `tests/ttnn/unit_tests/operations/test_core.py::test_reshard` with the reshard specs in the latest SD in my branch `mtatsumi/reshard_test`. @tarafdarTT could you take a look? I'll update the issue description as well.

**Comment by tarafdarTT** [comment]
@mtatsumiTT since we narrowed down the problem to no longer be of a large tensor (the large tensor works now).

Anad have identified a diff problem of the 16B aligned issue that requires padding, I have made a new issue here: https://github.com/tenstorrent-metal/tt-metal/issues/7040

I'm closing this one as I have addressed the large tensor issue.
