### ISSUE TITLE
ttnn test_multi_device test_ttnn_to_and_from_multi_device_shard failure 

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent-metal/tt-metal#6221]
run tests/ttnn/unit_tests/test_multi_device.py

Error message  from test_ttnn_to_and_from_multi_device_shard test
"malloc(): mismatching next->prev_size (unsorted)
Fatal Python error: Aborted"

Discovered from patching missing ttnn test coverage
https://github.com/tenstorrent-metal/tt-metal/issues/6187

**Comment by cfjchu** [comment]
Fixed in: [7d52e5b](https://github.com/tenstorrent-metal/tt-metal/commit/7d52e5b1f4bc8d7fde5b7fe8497907d8b0fd9a75)
