### ISSUE TITLE
ttnn test_multI_device.py test_multi_device_check_per_device_shard test failure

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent-metal/tt-metal#6222]
run tests/ttnn/unit_tests/test_multi_device.py

Test fails on test_multi_device_check_per_device_shard

"Fails all 3 configs
first config: Device storage isn't supported
second config: just fails
third config: 
Always | FATAL    | Mixing fast and slow dispatch is prohibited!
terminate called after throwing an instance of 'std::runtime_error'
  what():  TT_FATAL @ ./tt_metal/detail/tt_metal.hpp:28: fd == isFastDispatch
info:
Mixing fast and slow dispatch is prohibited!"

Issue discovered from https://github.com/tenstorrent-metal/tt-metal/issues/6187

**Comment by cfjchu** [comment]
Fixed in: [7d52e5b](https://github.com/tenstorrent-metal/tt-metal/commit/7d52e5b1f4bc8d7fde5b7fe8497907d8b0fd9a75)
