### ISSUE TITLE
ttnn - test_ttnn_multi_device_all_gather test failure

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent-metal/tt-metal#6223]
run tests/ttnn/unit_tests/test_multi_device.py 

Test fails on test_ttnn_multi_device_all_gather

 RuntimeError: TT_FATAL @ tt_eager/tt_dnn/op_library/all_gather/all_gather_op.cpp:28: page_size % 32 == 0
first config: Device storage isn't supported
second config:
tests/ttnn/unit_tests/test_multi_device.py:119:
E       RuntimeError: TT_FATAL @ tt_eager/tt_dnn/op_library/all_gather/all_gather_op.cpp:28: page_size % 32 == 0
E       backtrace:
E        --- /home/vtang/tt-metal/tt_eager/tt_lib/_C.so(+0x35e619) [0x7f5c6fbef619]
E        --- tt::tt_metal::operation::detail::run_device_operation(std::optional<std::reference_wrapper<tt::tt_metal::CommandQueue> >, tt::tt_metal::operation::DeviceOperation const&, std::vector<tt::tt_metal::Tensor, std::allocator<tt::tt_metal::Tensor> > const&, std::vector<std::optional<tt::tt_metal::Tensor const>, std::allocator<std::optional<tt::tt_metal::Tensor const> > > const&, std::vector<std::optional<tt::tt_metal::Tensor>, std::allocator<std::optional<tt::tt_metal::Tensor> > > const&)
E        --- tt::tt_metal::operation::run(tt::tt_metal::operation::DeviceOperation const&, std::vector<tt::tt_metal::Tensor, std::allocator<tt::tt_metal::Tensor> > const&, std::vector<std::optional<tt::tt_metal::Tensor const>, std::allocator<std::optional<tt::tt_metal::Tensor const> > > const&, std::vector<std::optional<tt::tt_metal::Tensor>, std::allocator<std::optional<tt::tt_metal::Tensor> > > const&)
E        --- tt::tt_metal::all_gather(std::vector<tt::tt_metal::Tensor, std::allocator<tt::tt_metal::Tensor> > const&, unsigned int, unsigned int, tt::tt_metal::MemoryConfig const&)

Issue discovered from https://github.com/tenstorrent-metal/tt-metal/issues/6187

**Comment by SeanNijjar** [comment]
@cfjchu, I merged in the fix for the hang. I'm not really in the loop for the errors above so I'll let you decide if we can close this now.

**Comment by cfjchu** [comment]
@SeanNijjar thanks! Looks good now to me.
