### ISSUE TITLE
nlp_create_qkv_heads in Falcon40b attention has bad pcc for interleaved in- and outputs

### ISSUE THREAD

**Issue by johanna-rock-tt** [tenstorrent-metal/tt-metal#6243]
**Describe the bug**
When I change the input and output memory layout for `tt_lib.tensor.nlp_create_qkv_heads` in the Falcon40b attention module I see bad PCC (output pcc: 0.48, k pcc: 0.23, v pcc: 0.047)

**To Reproduce**
1. Check out branch `jrock/prefill-seqlen@218bba398823e046e0b66f263838837c15ab60f8`
2. Run `pytest models/demos/falcon40b/tests/test_falcon_decoder.py::test_FalconDecoder_inference[BFLOAT8_B-SHARDED-falcon_40b-layer_0-prefill_seq32-4]`

**Comment by johanna-rock-tt** [comment]
I looked into this in more detail, here's what I found:
- nlp_create_qkv_heads doesn't know anything about groups.
- It assumes concat(q_heads, k_heads, v_heads) per core/device. So in our setup with 4 chips and 8 groups, the sharded version shards over 2 cores (1 group per core) which then works with the assumption of this op since every core has one group
- Using interleaved data does not work this way, because the op assumes the same format, but with 1 chip processing 2 groups the data is in the form concat(q_heads_grp1, k_heads_grp1, v_heads_grp1,q_heads_grp2, k_heads_grp2, v_heads_grp2) yielding faulty q,k,v projections
- As a workaround I'll try to port to 8 chips, this should give us a functional version

**Comment by johanna-rock-tt** [comment]
Can we make it clear to the user what this op does? Like that on sharded inputs each core expects MQA inputs and for interleaved the whole device expects MQA inputs and GQA is not supported in that sense?

**Comment by TT-BrianLiu** [comment]
Ah i see. You're right. The interleaved version expects a different arrangement of qkv heads along last dim than the sharded version. This wasn't clear in the implementation.

**Comment by TT-BrianLiu** [comment]
If we uplift `nlp_create_qkv_heads` sharded version to support HEIGHT > 32 (ie. seq_len > 32), how will the inputs be sharded? Will it be BLOCK sharded now?

**Comment by johanna-rock-tt** [comment]
I think the output of the QKV projection would ideally be BLOCK sharded. @pavlepopovic The producer of this op is the QKV projection, so on 8 chips for falcon40b the MM dims are [B, 1, S, 8192] x [1, 1, 8192, 1152], is a 2D MM with block sharded inputs the most efficient one for this?

 But currently we re-shard to 2 cores for 4 chips / 1 core for 8 chips, so de facto no sharding, correct?

**Comment by TT-BrianLiu** [comment]
> I think the output of the QKV projection would ideally be BLOCK sharded. @pavlepopovic The producer of this op is the QKV projection, so on 8 chips for falcon40b the MM dims are [B, 1, S, 8192] x [1, 1, 8192, 1152], is a 2D MM with block sharded inputs the most efficient one for this?
> 
> But currently we re-shard to 2 cores for 4 chips / 1 core for 8 chips, so de facto no sharding, correct?

We should spec it out (although BLOCK vs. HEIGHT sharded shouldn't really matter that much for implementation)

**Comment by johanna-rock-tt** [comment]
@pavlepopovic and I just went through the proposed optimization for prefill attention and we think we don't need support for a sharded version of nlp_create_qkv_heads for height > 32. I'm going to close this issue and if we find we need it later re-open it again.
