### ISSUE TITLE
Add Llama multi-chip to CI

### ISSUE THREAD

**Issue by cglagovichTT** [tenstorrent-metal/tt-metal#6244]

**Comment by tt-rkim** [comment]
Hey @cglagovichTT - not 100% sure what flow you'd like here.

Would you like me to first add the test to your branch, and then we can try getting a pass on the T3000 CI?

And how long is it? I'm assuming if it's quite long, then nightly is more appropriate.

**Comment by tapspatel** [comment]
Added llama tests here: e80763b8b66c1f2eaf09380270f2c70a87a2c81c

Checkout this file on how to add tests: tests/scripts/run_frequent_regressions_multi_device.sh
Your test case should have environment variables for path to files
```
export LLAMA_CKPT_DIR=/opt/cache/llama2_70b_cache/llama-data-repacked-2/llama-2-70b/
export LLAMA_TOKENIZER_PATH=/opt/cache/llama2_70b_cache/llama-data/tokenizer.model
export LLAMA_CACHE_PATH=/opt/cache/llama2_70b_cache/llama-data-cache/weights-cache-2
```

all data will go into` /opt/cache` on the CI machine for now
