### ISSUE TITLE
non_zero op for Mixtral8x7b bringup

### ISSUE THREAD

**Issue by sraizada-tt** [tenstorrent-metal/tt-metal#6248]
Need an op with the following functionality: 

`batch_ids_b = ttnn.non_zero( batch_ids_B)`

batch_ids_B is a 1-D tensor of size B (for the initial bringup, B=32)
batch_ids_b is a 1-D tensor of size b (<=B)

 ttnn.non_zero returns the indices of a tensor where the value is not zero. 

Eg, ttnn.non_zero([1.9, 7.2, 0, -2.3, 0]) should return [0, 1, 3]

PyTorch equivalent: https://pytorch.org/docs/stable/generated/torch.nonzero.html#torch.nonzero

**Comment by tarafdarTT** [comment]
@sraizada-tt I'm closing this for now (as there is a version in main), but we can re-open it or make a new issue if the current implementation is not sufficient.


I brought up in slack that with the current infra I don't think it's possible to do a dynamic shaped output based on the data of the tensor. The output shapes are set on the host, so the host needs data to figure this out.
