### ISSUE TITLE
Add new `frequent_multi_device` pipeline skeleton to support upcoming nightly tests for models

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent-metal/tt-metal#6252]
We will need a frequent / nightly pipeline for multi-Nebula T3K . Very similar to our split for `fast-dispatch-unit-tests` and `fast-dispatch-frequent`.

BTW, great first issue for newcomers to infra team @tenstorrent-metal/dev-ops-infra @jliangTT 

cc: @cglagovich a prerequisite for #6244  - hopefully doing by today

**Comment by tapspatel** [comment]
Frequent pipeline has been setup: 8be2327a6474637055205796c30d95d256e553b6
