### ISSUE TITLE
ViT embeddings - ttnn.concat compilation error

### ISSUE THREAD

**Issue by mbahnasTT** [tenstorrent-metal/tt-metal#6253]
**Describe the bug**
`RuntimeError: TT_ASSERT @ ./tt_metal/common/bfloat8.hpp:154: fp32_vec.size() % num_float_in_tile == 0
`

**To Reproduce**
1- https://github.com/tenstorrent-metal/tt-metal/blob/mbahnas/ttnn_vit_classify/tests/ttnn/integration_tests/vit/test_ttnn_optimized_vit.py::test_vit_embeddings
2- https://github.com/tenstorrent-metal/tt-metal/blob/mbahnas/ttnn_vit_classify/tests/ttnn/integration_tests/vit/test_ttnn_optimized_vit_highres.py::test_vit_embeddings

**Expected behavior**
```
    # TODO: enable batch on embeddings and e2e
    # cls_tokens = self.cls_token.expand(batch_size, -1, -1)
    patch_embeddings = vit_patch_embeddings(config, pixel_values, parameters=parameters.patch_embeddings)
    embedding_output = ttnn.concat((parameters.cls_token, patch_embeddings), dim=1)
```

**Screenshots**

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**

**Comment by mbahnasTT** [comment]
I solved it by adding additional line to make the output of patch_embeddings to be TILE_LAYOUT, while I was expecting it's TILE_LAYOUT by default from the preceding linear function:
```
    patch_embeddings = vit_patch_embeddings(config, pixel_values, parameters=parameters.patch_embeddings)
    patch_embeddings = ttnn.to_layout(patch_embeddings, layout=ttnn.TILE_LAYOUT)
    embedding_output = ttnn.concat((cls_token, patch_embeddings), dim=1)
```

**Comment by jliangTT** [comment]
@arakhmati and @eyonland, it seems to be a ttnn thing in term of gaps in user expectation (see last comment). Is it a bug?

**Comment by mbahnasTT** [comment]
The error is triggered within `cls_token` tensor that is supposed to be bfp8_b, on device, and Tile_layout, while the error is at tinny/ttnn/operations/core.py:line740; where it's considered RM and fp32. 
<img width="1807" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/116673264/58b909d5-dac8-439f-bfbf-f54e93c20a6f">

**Comment by mbahnasTT** [comment]
worth to mention that in the functional model (bf16), it went to the same location in core.py, but passed successfully, and generated the tensor shape of the concat inputs and output:
```
iiiiii ttnn.Shape([1, 1, 1[32], 768])
iiiiii ttnn.Shape([1, 1, 196[224], 768])
iiiiii ttnn.Shape([1, 1, 197[224], 768])
```

**Comment by jliangTT** [comment]
Sending to the top of the funnel triage point at tt-nn infra.

**Comment by arakhmati** [comment]
Yeah this is `ttnn` issue for sure. I will merge the fix to main by tomorrow morning

**Comment by arakhmati** [comment]
I merged the fix to `main`. This issue should be resolved now

**Comment by mbahnasTT** [comment]
I confirm, I have tested it on main. Thanks @arakhmati
