### ISSUE TITLE
 Supporting sharded and in-place input & output for tt_lib.tensor.silu & ttnn.silu

### ISSUE THREAD

**Issue by mikevin920** [tenstorrent-metal/tt-metal#6271]
**Is your feature request related to a problem? Please describe.**
For llama MLP with 2d fracturing, we need to an all-reduce on partial results before doing the SILU so we can't use the fused SILU with matmul. Since eventually all-reduce will take in sharded inputs and outputs, we would need silu to supported sharded tensors and in-place to save memory, and reduce two TM ops

**Describe the solution you'd like**
To pass in a output_mem_config that specify width-sharded in L1 in tt_lib.tensor.silu, with inputs width sharded, and output will stay width_sharded on the same core.

**Comment by mikevin920** [comment]
@cglagovich @caixunshiren

**Comment by jliangTT** [comment]
@TT-BrianLiu @nsmithtt , is this consider a elt-wise bucket, or need specific support frmo sharding infra?

**Comment by nsmithtt** [comment]
@jliangTT, yes eltwise

**Comment by umadevimcw** [comment]
@jliangTT We need help in understanding about sharded and inplace tensors? With whom we can discuss about the changes required in SILU?

My understanding is that we need to split the tensors across width. Also since in place is mentioned I guess the split needs to happen on the device instead of the host. Need confirmation on the same. 
Correct me if its not what meant

**Comment by jliangTT** [comment]
@mikevin920 , i think it would be the clearest if you build a unit test to embody the requirement for the functionality and the needed supported config for this operator. That would do away the ambiguity of going back and worth to figure out precisely what is needed here.

**Comment by mikevin920** [comment]
[Example unit tests](https://github.com/tenstorrent-metal/tt-metal/commit/db272f2ce21b71b08273657066ca41ffef5ffc45) @jliangTT Please let me know if this unit test is clear enough? basically just takes in input tensor sharded and outputs in the same memory config. Thanks!

**Comment by umadevimcw** [comment]
@mikevin920 Thanks for the unit tests. To be clear, whatever the steps you have followed in unit test, you want that to be handled in ttlib.tensor.silu op implementation instead of doing it externally?

**Comment by shwetankTT** [comment]
@Aswinmcw Duplicate effort. please check the PR I have raised.

**Comment by Aswinmcw** [comment]
@shwetankTT thanks for letting me know. For this issue, they expecting width sharded method, but in your PR as i saw, it contains only height and block sharded, once your PR merged, i will add width support will that be good?

**Comment by shwetankTT** [comment]
Width Sharded was already supported after tiling. but I got your point. I will try to merge it by today.

**Comment by umadevimcw** [comment]
@jliangTT  Can we close this and other issue related SILU which are in P1

**Comment by jliangTT** [comment]
yes we should de-duplicate this for sure. Can we make sure the ownership is clear between MCW team and @shwetankTT? 

also as an aside, @umadevimcw , can i get your help to review the feature in eltwise, broadcast, and reduce queue closely to make sure the duplication should be identified?

**Comment by shwetankTT** [comment]
@mywoodstock

**Comment by umadevimcw** [comment]
> yes we should de-duplicate this for sure. Can we make sure the ownership is clear between MCW team and @shwetankTT?
> 
> also as an aside, @umadevimcw , going forward, can i get your help to review the feature in eltwise, broadcast, and reduce queue closely to make sure the duplication get identified? this is the instance where i would need your help to look both the MCW queue as well as other's work within the eltwise/broadcast/reduce, so there is no **duplicated** work.

Sure @jliangTT

**Comment by umadevimcw** [comment]
Closing this issue (duplicate issue)
