### ISSUE TITLE
Adding Galaxy Attention on Emulated Chips

### ISSUE THREAD

**Issue by caixunshiren** [tenstorrent-metal/tt-metal#6293]
Add support for galaxy (32 chips) attention on emulated one chip.

**Comment by caixunshiren** [comment]
First version done. Merging to main

**Comment by cglagovich** [comment]
Can this be closed?

**Comment by caixunshiren** [comment]
> Can this be closed?

Not yet! Haven't added galaxy attention with proper update cache into main yet

**Comment by caixunshiren** [comment]
All changes added into the galaxy decoder branch. Closing this issue now and will track the issue along with galaxy decoder.
