### ISSUE TITLE
Investigate errors in models perf pipeline as of morning of March 12th

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent-metal/tt-metal#6294]

**Comment by tt-rkim** [comment]
@tt-asaigal has fixed the first issue - now we're looking for the current falcon problem

**Comment by tt-rkim** [comment]
`d1253da1d4e35270b370efe6b2d801ca196a9983` still has the GS issue for falcon, wormhole is clean

@skhorasganiTT I believe `41555da44366b8217dc4129292cc884faf7c98f4` is causing the WH issue, please check. These are API changes to the tensors

This is a run of 1 commit before 41555da44366b8217dc4129292cc884faf7c98f4 with @tt-asaigal 's fixes: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8252265596

**Comment by skhorasganiTT** [comment]
Reverting [commit 5c3d4bf](https://github.com/tenstorrent-metal/tt-metal/commit/5c3d4bf8da41912f12f17f3a7d9ad4ccc39b8459) makes the WH failure go away @tt-asaigal @tt-rkim

**Comment by tt-rkim** [comment]
We need that commit to fix another problem we were seeing

**Comment by tt-asaigal** [comment]
Taking a look after meeting

**Comment by davorchap** [comment]
@tt-rkim can we close?

**Comment by tt-rkim** [comment]
Yes
