### ISSUE TITLE
Test dprint/watcher on T3000

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent-metal/tt-metal#6315]
We have unit tests under `tests/tt_metal/tt_metal/unit_tests_common` (see specifically `DPrintFixture` and `WatcherFixture` tests), but they only run on n300 on CI. Hypothetically all dprint/watcher features should extend to >2 chips, but we should test it out to be sure. CI does not have T3000s, so can't add to CI runs yet.

To run a unit test: `./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter=*{Test Name}`

Per Mo, we should also test running all-gather test since it's exercising more of the features together than just the unit tests.

**Comment by mo-tenstorrent** [comment]
To run all gather: `pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_all_gather.py`

**Comment by ihamer-tt** [comment]
The following three tests fail on T3000:

**[  FAILED  ] DPrintFixture.TestPrintEthCores (33911 ms)**
```
| Test Error: Line 3 of gtest_dprint_log.txt did not match expected:
	1010@0.122559
	101-1.618@0.122559
tests/tt_metal/tt_metal/unit_tests_common/dprint/test_eth_cores.cpp:70: Failure
Value of: FilesMatchesString( DPrintFixture::dprint_file_name, golden_output )
```

**[  FAILED  ] DPrintFixture.TestPrintMuting (21822 ms)**
```
| Test Error: Line 2 of gtest_dprint_log.txt did not match expected:
	Printing int from arg: 1
	Printing int from arg: 2
tests/tt_metal/tt_metal/unit_tests_common/dprint/test_mute_print_server.cpp:57: Failure
Value of: FilesMatchesString( DPrintFixture::dprint_file_name, golden_output )
  Actual: false
Expected: true
```

**[  FAILED  ] DPrintFixture.TestPrintRaiseWait (23010 ms)**
```
| Test Error: file gtest_dprint_log.txt has less lines than expected (0).
tests/tt_metal/tt_metal/unit_tests_common/dprint/test_raise_wait.cpp:270: Failure
Value of: FilesMatchesString( DPrintFixture::dprint_file_name, golden_output )
  Actual: false
Expected: true
```
and
```
| Test Error: file gtest_dprint_log.txt has more lines than expected (>200).
tests/tt_metal/tt_metal/unit_tests_common/dprint/test_raise_wait.cpp:270: Failure
Value of: FilesMatchesString( DPrintFixture::dprint_file_name, golden_output )
  Actual: false
Expected: true
```

**Comment by ihamer-tt** [comment]
Watcher tests all pass.

**Comment by ihamer-tt** [comment]
I used the following env:
```
TT_METAL_DPRINT_CORES=all
TT_METAL_DPRINT_CHIPS=0,1,2,3,4,5,6,7
TT_METAL_ENV=dev
TT_METAL_WATCHER=10
```
