### ISSUE TITLE
ttnn.concat operation fails with low PCC for tensors with different dtype - Missing assert

### ISSUE THREAD

**Issue by nemanjagrujic** [tenstorrent-metal/tt-metal#6349]
**ttnn.concat** operation fails with low PCC for tensors with different dtype. Eg. when one tensor is bfloat16 and other is bfloat8_b.

**To Reproduce**
Checkout `ngrujic/ttnn_sweeps_1`  branch (soon to be merged in main). Run unit test `test_eltwise_concat.py ` using this command:

```
pytest tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_concat.py
```

**Expected behavior**
There are few test cases presented in the unit test `tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_complex_pcc.py` and they are expected to fail with low PCC error. Eg:

```
Max ATOL Delta: 93.02752685546875, Max RTOL Delta: 38.713680267333984, PCC: 0.4779800043725184, PCC check failed
```

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweep test:

```
tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_concat_test.yaml
```

To do this you should:

1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_concat_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by tt-aho** [comment]
Concat op impl does not support mixed precision at the moment. It was mentioned in tt_lib docs that it requires same dtype but is missing actual validation assert in code

**Comment by nemanjagrujic** [comment]
@tt-aho Can that assert be added?

**Comment by tt-aho** [comment]
The assert is on main now

**Comment by nemanjagrujic** [comment]
Closing since assert and fallback to torch is added now.
