### ISSUE TITLE
ViT_ttnn_optim_L1_interleaved tests hang on the top level, while runs OK on embeddings and encoder separately

### ISSUE THREAD

**Issue by mbahnasTT** [tenstorrent-metal/tt-metal#6356]
**Describe the bug**
GS: ViT_ttnn_optim_L1_interleaved tests hang on the top level, while runs OK on embeddings and encoder separately

**To Reproduce**
1. https://github.com/tenstorrent-metal/tt-metal/blob/mbahnas/vit_ttnn_L1_interleaved/tests/ttnn/integration_tests/vit/test_ttnn_optimized_vit.py::test_vit
2. https://github.com/tenstorrent-metal/tt-metal/blob/mbahnas/vit_ttnn_L1_interleaved/tests/ttnn/integration_tests/vit/test_ttnn_optimized_vit_highres.py::test_vit

**Expected behavior**
Completes without hanging, and get good PCC

**Screenshots**
<img width="1669" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/116673264/edf9147b-8335-4a5c-8712-7419b0e26867">
**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**

**Comment by jliangTT** [comment]
Adding Eyon to triage. (not clear where this should live)

**Comment by mbahnasTT** [comment]
I solved the optimized low resolution version, by adjusting the batch size =8, and will push the updates in my branch today.
But low PCC=0.83
I'll keep you posted on my progress on the optimized high resolution one (batch=1)

**Comment by mbahnasTT** [comment]
@jliangTT frankly, I don't know the root cause yet (or specific OP), that's why Eyon's look will be appreciated to identify to whom to direct the issue

**Comment by mbahnasTT** [comment]
@eyonland @jliangTT 

Status on the first unit test `https://github.com/tenstorrent-metal/tt-metal/blob/mbahnas/vit_ttnn_L1_interleaved/tests/ttnn/integration_tests/vit/test_ttnn_optimized_vit.py::test_vit`

Status on the 2nd unit test hanging (high resolution batch=1), I isolated the issue in the attention/attention_scores matmul step:
please change the sequence_size at that unit test `pytest tests/ttnn/integration_tests/vit/test_ttnn_optimized_vit_highres.py::test_vit_attention_experimental`
- sequence_size >= 900 (corresponds to 480x480 res b=1) --> 
<img width="908" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/116673264/da492dab-c455-4085-bd5a-861aaefd394b">

- sequence_size == 784 (corresponds to 448x448 res b=1) --> 
<img width="1316" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/116673264/64c3d4a8-7f1b-42cd-aaf4-24644e4def42">

-sequence_size <= 640. --> hangs

**Comment by jliangTT** [comment]
@TT-BrianLiu , can you take comment at this to see if attention is under mm category?

**Comment by TT-BrianLiu** [comment]
Attention definitely has matmuls in it, but it's not clear from the logs which op it's hanging. The L1 out of space should be easy to figure out which op it is. Simple workaround is to spill to DRAM for some of the intermediates.

**Comment by mbahnasTT** [comment]
my observation is the hanging is related to batch size 1 case, since it didn't happen on the other test case if low resolution with batch = 8

**Comment by eyonland** [comment]
@DrJessop ,   do you think you could help me rule out fast dispatch on this issue?    This issue jumped up to a P0 given it has been sitting out here for awhile.

**Comment by DrJessop** [comment]
Was this on Wormhole (n150/n300/t3000), or grayskull?

**Comment by mbahnasTT** [comment]
grayskull

**Comment by DrJessop** [comment]
More info. Apparently, even in slow dispatch mode, it hangs on program with ID=4. I cannot get the DPRINTs out from the compute kernel.

**Comment by DrJessop** [comment]
Status, I can get the DPRINTs now, was looking at the wrong math kernel with the same name. Though it looks like this is hanging at the kernel level.

**Comment by DrJessop** [comment]
It appears as if 6 cores never finish.

**Comment by DrJessop** [comment]
Some other debug data. The positioning of these kernels looks very strange
```
In program 4. Num cores: 96
RISC0 NAME: reader_writer_bmm_tile_layout_in1
CORE RANGE [(x=6,y=0) - (x=11,y=7)]
RISC1 NAME: reader_bmm_tile_layout_in0
CORE RANGE [(x=6,y=0) - (x=11,y=7)]
RISC0 NAME: reader_writer_bmm_tile_layout_in1
CORE RANGE [(x=1,y=4) - (x=5,y=7)]
CORE RANGE [(x=2,y=0) - (x=5,y=3)]
RISC1 NAME: reader_bmm_tile_layout_in0
CORE RANGE [(x=1,y=4) - (x=5,y=7)]
CORE RANGE [(x=2,y=0) - (x=5,y=3)]
COMPUTE NAME: bmm_large_block_zm_fused_bias_activation
CORE RANGE [(x=0,y=0) - (x=1,y=3)]
CORE RANGE [(x=0,y=4) - (x=0,y=7)]
RISC0 NAME: reader_writer_bmm_tile_layout_in1
CORE RANGE [(x=0,y=0) - (x=1,y=3)]
CORE RANGE [(x=0,y=4) - (x=0,y=7)]
RISC1 NAME: reader_bmm_tile_layout_in0
CORE RANGE [(x=0,y=0) - (x=1,y=3)]
CORE RANGE [(x=0,y=4) - (x=0,y=7)]
```

**Comment by DrJessop** [comment]
Re-assigning to @TT-BrianLiu  and @tt-aho  since I confirmed this can be reproduced in slow dispatch or fast, thus not a dispatch bug.

**Comment by davorchap** [comment]
Seems like an OP bug, @TT-BrianLiu  will take a look.

**Comment by davorchap** [comment]
@mbahnasTT is this a P0 ?

**Comment by mbahnasTT** [comment]
@davorchap  Actually, @smehtaTT  set it to P0, while I set it previously as P1.

**Comment by TT-BrianLiu** [comment]
@tt-aho found the bug. It's some logic with our half-half grid for mcast receivers. It's very janky but made some cases better. For now, I will remove half-half logic if we are providing user grids.

**Comment by TT-BrianLiu** [comment]
This should fix this matmul: https://github.com/tenstorrent-metal/tt-metal/pull/6968

I cherry-picked onto your branch and locally tested that the bmm is correct. @mbahnasTT Can you rebase after this is merged and see if your test works?

**Comment by jliangTT** [comment]
Have you tried this @mbahnasTT ?

**Comment by mbahnasTT** [comment]
@TT-BrianLiu Thanks!
@jliangTT I tried it on yesterday's main branch and no more hangs, so we can consider this issue resolved
