### ISSUE TITLE
LLAMA2 on 8 Chips Hangs with Program Caching changing timing

### ISSUE THREAD

**Issue by tt-asaigal** [tenstorrent-metal/tt-metal#6360]
@cglagovich please give us the repro steps and one of us can take a look.

**Comment by cglagovich** [comment]
Have to run this on `sjc-snva-t3002`, IP=10.230.36.208

**Comment by cglagovich** [comment]
This test demonstrates that the program cache hang occurs when the 8 chip MLP hits the cache.

**Comment by aliuTT** [comment]
same exit signature as https://github.com/tenstorrent-metal/tt-metal/issues/6363

**Comment by tt-asaigal** [comment]
As Allan mentioned, this workload fails the same way as the `all_gather` test in https://github.com/tenstorrent-metal/tt-metal/issues/6363 with program cache enabled. The prefetcher for a remote device is trying to write to the completion queue over a PCIe, which causes the crash/hang.

This does not seem to be a bug in the program cache itself, rather timing issues exposed by the program cache. We verified this by running 2 experiments:
1. A similar test using the program cache on T3000, which passes. Repro: 

```
git checkout asaigal/passing_program_cache_test
cd models/demos/falcon40b/tests/
pytest -svv test_falcon_model_single_chip.py::test_sharded_matmul_1d_in0_multi_chip[activations_dtype0-weights_dtype0-in0_sharded-out_sharded-lm_head_shape-8]
```
2. We added a 30ms delay in the second loop of the original workload after getting the program from the cache. The test no longer hangs, instead it fails with a PCC issue. 

These 2 datapoints indicate that the program cache is working as expected. If it wasn't any test using it on multichip systems would fail.

@DrJessop and @aliuTT are looking into why this behaviour is seen on remote chips.

**Comment by tooniz** [comment]
Thanks for the update, changed title to reflect that we think it's timing related

**Comment by tt-asaigal** [comment]
fyi @tt-snijjar was also seeing hangs with all gather sweep tests without program cache on multichip machines. Seems to be the same issue, but non-deterministically exposed over multiple loops.

**Comment by SeanNijjar** [comment]
FWIW @tt-asaigal, in my tests with program caching disabled, when I see hangs, it's after a deterministic number of loop iterations, leading me to believe it has to do with something like looping through a queue or something and a possibly bad address calculation (since device is open/running across all loop iterations).

**Comment by tooniz** [comment]
We can try @DrJessop 's fix for #6363 here too:
https://github.com/tenstorrent-metal/tt-metal/pull/6398

**Comment by jliangTT** [comment]
@tt-asaigal, can this be closed?

**Comment by cglagovich** [comment]
We no longer see program caching hangs on main with this test
