### ISSUE TITLE
TTNN model PCC debug

### ISSUE THREAD

**Issue by tt-nshanker** [tenstorrent-metal/tt-metal#6412]
It would really help functionality/pcc debugging if we have an automatic PCC checker after every op in the model.  We could save pytorch intermediate tensors and then compare against ttnn intermediate tensors at runtime. This debug flow would be disabled by default and would need a debug flag to enable it. 
@arakhmati thoughts?
@jvasilje 
@mywoodstock 
@cfjchu 
@mtatsumiTT 
@AleksKnezevic 
@nsmithtt

**Comment by tt-nshanker** [comment]
Automatically comparing against ttnn intermediate tensor is complicated because ttnn intermediate tensor's shape and layout might not match pytorch. I think we (model writers) can add the check manually wherever required and apply necessary layout conversions to be able to compare with pytorch. So, I think we only need pytorch intermediate tensors to be automatically saved/dumped to file.

**Comment by arakhmati** [comment]
You can use this: [models/experimental/bloom/tests/test_perf_bloom.py](https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/usage.html#debugging-intermediate-tensors). The layout is always converted to row-major. And you can go and update torch_function to do the right thing for dtype

And there is also this: https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/usage.html#debugging-intermediate-tensors
