### ISSUE TITLE
WH Hang In compile program

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent-metal/tt-metal#6429]
WH frequently hangs for me during program compile, multiple threads are all stuck waiting on mutex inside of `detail::async` from `build->build`.

Run the following test a few times:
```
python tests/ttnn/integration_tests/unet/test_ttnn_shallow_unet.py
```

For some reason this only seems to happen on WH machines, though the bug itself seemingly should be device agnostic since this is host side compile flow.

I can workaround the issue entirely by commenting out all of the `detail::async` calls and just do compiles on the main thread.

**Comment by jliangTT** [comment]
@vtangTT , are you working on this issue?

**Comment by jliangTT** [comment]
sorry. my question was not super clear. Is this *supposed* to be on your plate? This seems to be a runtime thing. Want to make sure this sit in the right queue even it is not being worked on right now. thanks!

c.c. @TT-billteng

**Comment by TT-billteng** [comment]
> sorry. my question was not super clear. Is this _supposed_ to be on your plate? This seems to be a runtime thing. Want to make sure this sit in the right queue even it is not being worked on right now. thanks!
> 
> c.c. @TT-billteng

we made this change to avoid a gazillion unique threads showing up in the tracy GUI. Also, if we have an existing thread pool, why create new threads?

**Comment by nsmithtt** [comment]
@TT-billteng, I'm not sure I understand your point.  This issue is reported against vanilla main, it is using the existing thread pool mechanism and I was seeing a deadlock.  My workaround is to remove the thread pool entirely and just compile on the main thread, single threaded.

**Comment by vtangTT** [comment]
after rebasing, wasn't able to repro hang on n150 after 100 iterations, waiting for if @nsmithtt can repro on his machine

**Comment by nsmithtt** [comment]
Seems to have gone away, can no longer repro.  Will reopen if I run into it again
