### ISSUE TITLE
Falcon40 4/8 chip prefill demo not working

### ISSUE THREAD

**Issue by s-jovic** [tenstorrent-metal/tt-metal#6439]
**Describe the bug**
Demo produces random output when prefill on device is enabled. The PCC that we get when we compare device kv cache and host kv cache is unstable - drops to 0.6 at some point and comes back to 0.95 at the end. Running prefill for the same prompt in `test_falcon_end_to_end.py` gives stable PCC not dropping below 0.97, so it seems that there is some issue with the demo code. 

**To Reproduce**
Running the following command on main produces bad output:
`pytest --disable-warnings -q -s --input-method=cli --cli-input="Tell me a joke."  models/demos/falcon40b/demo/demo.py`

**Additional context**
Program cache and persistent kernel cache are both turned off.

**Comment by s-jovic** [comment]
Demo works with max_seq_len 32, 512 and 1024, while it produces bad output for max seq len 128. Moreover, the output from variants with max_seq_len 512 and 1024 produces meaningful output, but it is different from what we get with 32 max_seq_len.

Measuring the PCC between prefill done on host and on the device gives the following results
- with the demo written as is - PCC is bad ~0.4
- with the update of passing `prefill_ids` instead of `prefill_ids[:, :num_input_tokens]` PCC goes up to 0.8-0.9 but is not really stable - this is because to the device we pass full prefill_ids so we have some numbers for tokens between num_input_tokens and 32
- with the previous update and passing `num_input_tokens=32` instead of the actual num_input_tokens to the model_preprocessing method PCC is stable and around 0.97-0.98

However the demo with max_seq_len 128 still doesn't work even with good PCC - the same PCC we get with max_seq_len=32 and this works in the demo. I will continue to debug from here in the following manner:

1. Run prefill and save kv cache in a file; reset chip; run demo with kv cache loaded from the file to exclude the possibility that we leave device in a bad state after the prefill.
2. Try to play with fill_cache ops in case they end up doing some memory corruption when the initialized kv cache size is different.

**Comment by smehtaTT** [comment]
@TT-BrianLiu @aliuTT @tarafdarTT to help team

**Comment by s-jovic** [comment]
Synced with Brian, will try:
- watcher
- dumping memory layout
- different max seq lengths close to problematic 128

**Comment by s-jovic** [comment]
Closing this one since the problem resulted in 2 different issues. Opened separate issues:
https://github.com/tenstorrent-metal/tt-metal/issues/6650
https://github.com/tenstorrent-metal/tt-metal/issues/6651
