### ISSUE TITLE
Unet: Remove remaining s2i and i2s, replace with reshard

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent-metal/tt-metal#6471]
For example, before every upsample there is a s2i and i2s, but these should be able to be replaced with reshard.

**Comment by tapspatel** [comment]
Add this change to branch: tpatel/nsmith/unet_test_perf2-fork

Opts done

1. concat opt
2. upsample kernel opt
3. maxpool kernel opt
4. remove all i2s and s2i to reshard
5. synced to tip

Closing issue. Opening a new issue to merge perf branch into main
