### ISSUE TITLE
vm-57 reset issues

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent-metal/tt-metal#6522]
vm-57 has been resetting during a CI run

https://github.com/tenstorrent-metal/tt-metal/actions/runs/8334275601/job/22812152750

This was recently loaned to @tt-nshanker and she said she was noticing weird hangs

**Comment by vtangTT** [comment]
observed a involuntary reboot on the first test of the fd gtest unit tests, reboot was fine and could ping/get back onto the machine

is repro and the first test is CommandQueueSingleCardFixture.TestArbiterDoesNotHang when running the suite
commit: `e80763b8b66c1f2eaf09380270f2c70a87a2c81c`

ran once on most recent main: `abfb173` and does not hang/reboot the machine

**Comment by TT-billteng** [comment]
so are you saying with our latest code, you can't hang / reboot the machine?

**Comment by ttmchiou** [comment]
Added Vm-57 back into CI pool.
Reset issue could be due to two developers working on machine at same time or 
Will close issue if no further issues pop up.

**Comment by TT-billteng** [comment]
vm-57 is running fine now
