### ISSUE TITLE
Matmul Tests hang in slow dispatch mode when L1_UNRESERVED_BASE is moved to lower address

### ISSUE THREAD

**Issue by ubcheema** [tenstorrent-metal/tt-metal#6577]
```
CommonFixture.MatmulMultiCoreMultiDRAMIn0MCastIn1MCast
CommonFixture.MatmulMultiCoreMultiDRAMIn0MCast
```
Tests hang when L1_UNRESERVED_BASE is changed from 120 * 1024 to a lower address.

In branch: `ucheema/fd-on-idle-erisc-rebased-03-18` that implements FD on Idle Ethernet cores, L1_UNRESERVED_BASE has been moved lower. This causes above tests to hang in slow dispatch mode.

When I move the define back to 120 * 1024, the tests pass on the branch.

To Reproduce:
checkout: `ucheema/fd-on-idle-erisc-rebased-03-18`
`make build; make tests`

`TT_METAL_SLOW_DISPATCH_MODE=1 ./build/test/tt_metal/unit_tests --gtest_filter=*.MatmulMultiCoreMultiDRAMIn0MCastIn1MCast`

Test will hang.

Change `L1_UNRESERVED_BASE` to 120 * 1024 in `common_runtime_address_map.h`

```
-constexpr static std::uint32_t L1_UNRESERVED_BASE = CQ_CONSUMER_CB_BASE + CQ_CONSUMER_CB_ADDR_RESERVATION; //CQ_CONSUMER_CB_BASE + 16 * L1_ALIGNMENT; // Start of unreserved space                                                                           │·············································································································
+constexpr static std::uint32_t L1_UNRESERVED_BASE = 120*1024;                                                                                                                                                                                                │·············································································································
+//constexpr static std::uint32_t L1_UNRESERVED_BASE = CQ_CONSUMER_CB_BASE + CQ_CONSUMER_CB_ADDR_RESERVATION; //CQ_CONSUMER_CB_BASE + 16 * L1_ALIGNMENT; // Start of unreserved space    
```

reset board, make build and run the test again. It passes with the change.

**Comment by davorchap** [comment]
@DrJessop this can be closed?

**Comment by DrJessop** [comment]
Just merged the fix.
