### ISSUE TITLE
[Bug Report] Deallocate bug with sharding

### ISSUE THREAD

**Issue by pavlepopovic** [tenstorrent-metal/tt-metal#6638]
I've stumbled into a weird deallocate bug with sharding, reproducible at this branch : `ppopovic/deallocate_bug`
On that branch, there is a file `tests/ttnn/unit_tests/test_failing_deallocate.py` that contains 2 unit tests which reveal the bug.

In the first unit test (test_deallocate_full), I'm trying to execute the following sequence.

```
sharded_in0 = interleaved_to_sharded(in0, ...)
mm1 = tt_lib.matmul(sharded_in0, in1)

sharded_in0.deallocate()

mm2 = tt_lib.matmul(mm1, in2)

# ...

compare_pcc(mm2, ref_mm2) # compare with reference
```

The pcc fails in this case.
If we remove the deallocate call, the test is passing.
If we move the deallocate call below mm2, the test is passing as well.
This leads me to believe that something is wrong with deallocate, and that it does something out of the bounds.

In the second unit test (test_deallocate_slice), we're trying to do the same thing as in the first unit test, except the fact that we:

1. Make the input tensor twice as big
2. Use the new interleaved_to_sharded_partial op (and sharded_to_interleaved_partial), in order to perform 2 partial sequences (one on first half of activations, and the other of the second half), and spill back results in the output tensor via s2i_partial (one half at a time)

What's weird that in this case, only the first half of the output tensor is wrong, whereas the second one is correct (pcc here checks one half of the tensor at a time and compares it to matching parts of the reference implementation).
Again, moving `deallocate()` call after the second matmul makes the test pass.

The failing PCC (in both cases) is deterministic across runs, and using slow dispatch does **not** make a difference.

**Comment by tt-asaigal** [comment]
This seems to be a bug with the allocator itself. It looks like we have overlapping buffers, due to the size of `mm2_sharded` being computed incorrectly.

Buffer alloc/dealloc order for relevant tensors when we call `deallocate` after computing `mm1_sharded` (all of these tensors are allocated top down):

```
1. L1 Buffers for query_layer_sharded get allocated at 0x169800
2. L1 Buffers for mm1_sharded get allocated at 0xDB800
3. Buffers for query_layer_sharded get deallocated when the user explicitly calls deallocate
4. L1 Buffers for mm2_sharded get allocated at 0x169800 (where query_layer_sharded lived)
```

Seems like `mm2_sharded` overlaps with `mm1_sharded`, when we allocate it at `0x169800`. When I manually move the buffers for `mm1_sharded` to `0xD7800` the original test passes.

The reason we don't see a mismatch without the deallocate is because `mm2_sharded` is allocated below `mm1_sharded`.

**Comment by davorchap** [comment]
@tarafdarTT can you provide the update on this bug -- is this interleaved2sharded / sharded2interleave buff calculation bug?

fyi @TT-BrianLiu , in case this is a matmul bug.

**Comment by davorchap** [comment]
fyi @yugaoTT

**Comment by tarafdarTT** [comment]
> @tarafdarTT can you provide the update on this bug -- is this interleaved2sharded / sharded2interleave buff calculation bug?
> 
> fyi @TT-BrianLiu , in case this is a matmul bug.

Hey Davor, 

After looking at this,  if we go the interleaved_to_sharded path then the allocation is not being done through the sharded allocater, but once we deallocate it , it uses the sharded logic. I think there might be state related to sharding that isn't generated when allocating the interleaved buffer that is required for sharding, and when deallocating the sharded buffer (that was initially allocated as an interleaved buffer) we see this problem. 
@tt-nshanker do you have the bandwidth to look at this. This might be related to the sharded allocater you worked on a while back, if not I can have a look at it (but might need to sync with you on how to do this).

**Comment by shwetankTT** [comment]
@pavlepopovic I am unable to reproduce this issue on the mainline. Can you please check and confirm? I can confirm the issue exist in your branch. Should we still investigate this issue?

**Comment by shwetankTT** [comment]
Could be an alignment issue. I tried with couple tests of more shapes, all passed. @tarafdarTT has fixed this issue here. [https://github.com/tenstorrent-metal/tt-metal/blob/93765e9d091d059f8f67f9e6ec48d91898199155/tt_metal/impl/dispatch/command_queue.cpp#L1360](LINK)

**Comment by pavlepopovic** [comment]
Yes, this PR seems to have fixed the issue: https://github.com/tenstorrent-metal/tt-metal/pull/7196
Thanks @shwetankTT
