### ISSUE TITLE
[Bug Report] Incorrect result for lte_unary and gte_unary

### ISSUE THREAD

**Issue by Aswinmcw** [tenstorrent-metal/tt-metal#6676]
**Describe the bug**

The `lte_unary`  and `gte_unary` op return incorrect result

**To Reproduce**
1. Modified `relu6_bw` implementation to check the result of `lte_unary` as provided in this screenshot
<img width="1512" alt="Screenshot 2024-03-22 at 12 38 22 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/156493059/82cf1802-6872-430c-9272-f81800a52737">

2. Modify the `relu6_bw` test file `tests/tt_eager/python_api_testing/unit_testing/backward_ops/test_backward_relu6.py` to pass the input as 5 to compare 5 vs 5
3. It will return 0 which is not expected

**Expected behavior**
Expected result is True(1), as `5 <= 5`

**Additional context**
Same issue is faced in `gte_unary` also

**Comment by umadevimcw** [comment]
PR merged to main
