### ISSUE TITLE
ttnn.reglu operation fails with "Chunk not divisible by tile" error [Grayskull and Wormhole]

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent-metal/tt-metal#6687]
**Describe the bug**
**ttnn.reglu** operation breaks with "Chunk not divisible by tile" error in some test cases. 

**To Reproduce**
1. Checkout `main` branch
2. Run unit test `test_eltwise_reglu.py` using this command:
`pytest tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_reglu.py`

**Expected behavior**
There is a test case presented in the unit test `tests/ttnn/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_reglu.py` and it is are expected to fail with _Chunk_ error
For example, the test is expected to fail with this error message: 
```
TT_FATAL @ tt_eager/tt_dnn/op_library/split/split_tiled.cpp:40: (chunk_size % TILE_WIDTH == 0)
E       info:
E       Chunk not divisible by tile
```

**Getting Additional info for the operation under test and its behavior**
To get additional information and results for different combinations of input shapes, types, layouts and memory configs for which this operation was tested you can also run locally sweeps for ttnn.geglu and check the results. To do this you should:
1. Follow the `Getting Started` page to setup the repo, environment variables and `python-env`
2. Activate `source build/python_env/bin/activate`
3. Run sweeps by using `python tests/tt_eager/python_api_testing/sweep_tests/run_pytorch_test.py -i tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/ttnn_reglu_test.yaml -o ./result-sweeps`
4. After the run is completed all test sweeps results should be available inside specified output directory (in this case ./result-sweeps). There you will find `geglu_sweep.csv` which holds all executed sweeps, among which you can also find the ones that failed and were recreated by the unit test, which you can get by searching unique `data_seed` field.

**Comment by umadevimcw** [comment]
Same as discussed here https://github.com/tenstorrent-metal/tt-metal/issues/6537#issuecomment-2044268664
