### ISSUE TITLE
watcher doesn't handle misaligned DRAM/PCIe reads that are written to L1

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent-metal/tt-metal#6695]
NOC reads require that the L1 dest address match the alignment restrictions of the src.  This an issue for reads from DRAM/PCIe which have 32 byte alignment while L1 has 16 byte alignemnt.  Watcher should flag this error.

**Comment by tt-dma** [comment]
PR https://github.com/tenstorrent-metal/tt-metal/pull/6901 implements this
