### ISSUE TITLE
Create a T3000 perf pipeline for models

### ISSUE THREAD

**Issue by uaydonat** [tenstorrent-metal/tt-metal#6701]
Similar to tests/scripts/run_performance.sh which runs on single WH, we need similar perf testing for T3000 (and Galaxy in the future)

**Comment by uaydonat** [comment]
any updates?

**Comment by tapspatel** [comment]
Added perf pipeline: https://github.com/tenstorrent-metal/tt-metal/pull/7127
See here for pipeline run: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8595207270

Tripled # of t3000 runners. Closing issue

**Comment by uaydonat** [comment]
@cglagovichTT we should move llama to this perf pipeline and keep track of its perf.

**Comment by cglagovichTT** [comment]
fyi @mikevin920

**Comment by uaydonat** [comment]
fyi @skhorasganiTT

**Comment by s-jovic** [comment]
@tapspatel do you plan to merge this to main? can we start adding tests, are there enough resources?

**Comment by tapspatel** [comment]
@s-jovic you can start adding tests, there are enough resources now.
