### ISSUE TITLE
ViT shared low PCC - split_query_key_value_and_split_heads support

### ISSUE THREAD

**Issue by mbahnasTT** [tenstorrent-metal/tt-metal#6712]
**Describe the bug**
The OP split_query_key_value_and_split_heads() in the sharded mode is restricted to Bert tensor shape, so I had to hack and comment out that line https://github.com/tenstorrent-metal/tt-metal/blob/main/tt_eager/tt_dnn/op_library/transformer_tms/transformer_tms.cpp#L22

After that the model was functioning but attention function has PCC=0.65, and I was able to isolate the issue in the split function where PCC=0.01 after that step
I see that Falcon, Bloom, Whisper has their special config for the split function, can you please help with enabling it for ViT? or generalize the main function?

**To Reproduce**
1. Go to 'branch' `mbahnas/vit_ttnn_sharded/`
2. `pytest tests/ttnn/integration_tests/vit/test_ttnn_optimized_sharding_vit.py::test_vit_attention`

**Expected behavior**

**Screenshots**
<img width="1794" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/116673264/05a63acf-146b-4e2a-b6c2-6c2a1af267cd">

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**

**Comment by jliangTT** [comment]
hey @TT-BrianLiu, don't know who can work on this yet (won't assigned you). But need your input on triaging - is this a bug or feature?

**Comment by mbahnasTT** [comment]
Worth to mention that the L1_interleaved version of the model, has 0.98 PCC, and that split OP went to ` NlpCreateHeads` implementation, instead of the low PCC sharded one that went to `
tt::operations::primary::transformers::SplitFusedQKVAndSplitHeads`

**Comment by TT-BrianLiu** [comment]
It's a feature request. Our sharded versions on of NLP TMs are not that general yet. What are the shapes you are trying to run?

**Comment by mbahnasTT** [comment]
@TT-BrianLiu 
My current use case of resolution 3x224x224 and batch=8
There are 12 heads and head size is 64 , 12x64=768
So my fused input tensor to the split OP is [8, 224, 2304]
- the 224 in the tensor shape is coming from (input resolution / patch size)^2 = 224/16 = 196, then I contact to 197, so padded to 224
- Other use case will be high resolution (1280x800) and batch=1 so hidden layer size = 4032

**Comment by arakhmati** [comment]
I started a new issue with a standalone failure: https://github.com/tenstorrent-metal/tt-metal/issues/6805. @TT-BrianLiu can you please take a look?

**Comment by TT-BrianLiu** [comment]
Is #6805 tracking the same thing as this issue?

**Comment by TT-BrianLiu** [comment]
PR with new op: https://github.com/tenstorrent-metal/tt-metal/pull/7323

This should work for ViT shapes on Grayskull.

**Comment by TT-BrianLiu** [comment]
I integrated new split/create heads op into ViT for attention. Attention now has 0.99 PCC
