### ISSUE TITLE
improve watcher noc error messages

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent-metal/tt-metal#6736]
Watcher currently prints, eg:
   ncrisc using noc0 tried to accesss core (00,01) L1[addr=0x400974f0,len=16]

3 things:
 - accesss is a typo
 - would be great to know what type of core that is, eg: "tried to access DRAM core"
 - L1 can be misleading for dram/pcie cores, so should be L1[...] or DRAM[...] or PCIE[...]
 
Valid types are DRAM, ETH, TENSIX, PCIE

**Comment by pgkeller** [comment]
another thing that could piggy back on this: cores dumped in the watcher log file are physical cores, should be logical cores.  This issue and #6738 go together, probably do all in one pass.

**Comment by tt-dma** [comment]
In DebugSanitizeNocInvalidUnicast, a bad address is reported as "L1". This code should look up the noc address (if valid) and report this as L1, DRAM, or PCIE.

**Comment by tt-dma** [comment]
PR: https://github.com/tenstorrent-metal/tt-metal/pull/7098 implements this
