### ISSUE TITLE
Add device dump at exit on python only runs with tracy module

### ISSUE THREAD

**Issue by mo-tenstorrent** [tenstorrent-metal/tt-metal#6776]
Similar to conftest.py  calls to device profiler dumps. We should call dump for non python calls as well. 

Solutions:

1) Call dump in device profiler destructor
2) Call dump in python atexit 
3) Call dump at the end of tracy.py ?? Is that possible?

**Comment by mo-tenstorrent** [comment]
@nsmithtt Actually Nick even the destructor api is dangerous. It get's called after python is finished with ttlib, meaning we can easily run into scenarios where device is closed and profiler destructor is trying to read profiling data. 

Until we remove device close from ttnn/ttlib and fully leave it to  the C++ destructor, we can't bring profiler dumps in profiler destructor. 

I am afraid python only runs should call profiler dump explicitly. Until we can have FD2.0 in and can work on https://github.com/tenstorrent-metal/tt-metal/issues/5662 to have device notify host on when to do dumps

**Comment by nsmithtt** [comment]
@mo-tenstorrent, thanks for looking into this, seems like we should hold off then until FD2 is in.  It's not too big a deal to convert a python script into a pytest.

**Comment by mo-tenstorrent** [comment]
Great, will close this ticket then.
