### ISSUE TITLE
Tracy dependencies not installed in IRD docker

### ISSUE THREAD

**Issue by s-jovic** [tenstorrent-metal/tt-metal#6820]
When trying to run tracy or profile_this script on yyz-lab-114 IRD machine, I get the following warning:

`Perf report generation is skipped!! Tracy tools can't be installed,  make sure tt_metal dev packages are installed`

Building csvexport and capture fails because of missing dependencies. Installing the following dependencies resolves the issue:
 - libtbb-dev
 - libcapstone-dev
 - pkg-config

I guess these dependencies should either be added to the docker or the command for installing them should be added to one of the Makefiles.

**Comment by mo-tenstorrent** [comment]
This is already mentioned in documentation. Developer dependencies need to be installed before running profile this.
