### ISSUE TITLE
Reduce number of clicks to get to installation instructions for TT-Metalium

### ISSUE THREAD

**Issue by adifrancescoTT** [tenstorrent-metal/tt-metal#6850]
As pointed by @milank94, we can remove one unnecessary hop to get to software installation instructions. Can we have the "installation guide" link [on this page](https://tenstorrent-metal.github.io/tt-metal/latest/tt-metalium/get_started/get_started.html#quick-start-guide ) point to [this page](https://github.com/tenstorrent-metal/tt-metal/blob/main/INSTALLING.md) directly without passing by [the current intermediary page](https://github.com/tenstorrent-metal/tt-metal?tab=readme-ov-file#installing)

**Comment by jliangTT** [comment]
@tt-rkim, any suggestion on how we can do this?

**Comment by jvasilje** [comment]
Install page has been refactored

**Comment by tt-rkim** [comment]
Thanks @jvasilje 

@adifrancescoTT I've addressed your issue in this separate PR: https://github.com/tenstorrent-metal/tt-metal/pull/6953
