### ISSUE TITLE
Mistral-7B perf regression

### ISSUE THREAD

**Issue by mtairum** [tenstorrent-metal/tt-metal#6882]
A recent correctnesss fix to Mistral-7B introduced in commit [`0ebb1d81`](https://github.com/tenstorrent-metal/tt-metal/commit/0ebb1d81a65802a131086aa1bbfeaef01a388723) lead to a decrease in performance of the model.

Measured in CI from 0.16s to 0.27s.

The introduced slice operation is required so that the attention softmax avoids padded values. However the slice op is falling back to host, leading to the performance degradation.

This issue will keep track of the progress of a fix on device. The fix should also update the inference time back to the lower value.

**Comment by arakhmati** [comment]
Here is the fix for `__getitem__`: https://github.com/tenstorrent-metal/tt-metal/pull/6886

In this change, I updated `__getitem__` to run without falling back to torch
