### ISSUE TITLE
Suppress chatty build logs for frequent-fast-dispatch tests

### ISSUE THREAD

**Issue by cfjchu** [tenstorrent-metal/tt-metal#6928]
There's a lot of noisy build logs being emitted for these CI jobs. It makes it really hard to see the logs for the actual test runs

example:
![image](https://github.com/tenstorrent-metal/tt-metal/assets/122298491/226091e7-2ad8-4398-a98e-acaea0dda085)

https://github.com/tenstorrent-metal/tt-metal/actions/runs/8477800452/job/23229183883

Since I don't see this issue on some of the post-commit workflows, I'm guessing there's a "silent-mode" that's not being enabled here?

**Comment by TT-billteng** [comment]
@cfjchu have a look at the new frequent pipelines, should look better

**Comment by cfjchu** [comment]
> @cfjchu have a look at the new frequent pipelines, should look better

Looks amazing, thanks!
