### ISSUE TITLE
Split device perf pipeline similarly to how we split the e2e models perf pipeline

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent-metal/tt-metal#7021]
cc: @jliangTT @TT-billteng

**Comment by TT-billteng** [comment]
@mo-tenstorrent and I have something going

**Comment by tt-rkim** [comment]
Thanks guys, will let you handle

**Comment by tt-rkim** [comment]
Closing this and using's @mo-tenstorrent 's issue
