### ISSUE TITLE
[Metal Trace] Add support for tracing events in FD2

### ISSUE THREAD

**Issue by tooniz** [tenstorrent-metal/tt-metal#7070]
**Describe the bug**
Current tracing doens't support events

Host currently increments a completion q entries counter on enqueue_record_event, but if the event is traced then we should not increment it, however when the trace is replayed we do want to increment it.

We need to think about the proper interaction and how to also handle the fact that event_id traced are static whereas host assumes event_id to keep increasing? fyi @abhullar-tt  

During tracing:
- skip pushing ReadBufferDescriptors into issued_completion_q_reads
- skip incrementing num_entries_in_completion_q
- instead trace instance needs to keep an internal state that for above

During replay:
- EnqueueTrace pushes a prefetcher command to execute the trace buffer that's already in DRAM
- extract ReadBufferDescriptors and num_entries_in_completion_q incr value
- pushing ReadBufferDescriptors into issued_completion_q_reads
- incrementing num_entries_in_completion_q
- call finish

**Comment by abhullar-tt** [comment]
when reading from the completion queue host pops the event and expects that it matches the event ID in ReadEventDescriptor 

I believe `EventSynchronize` mechanism expects events to be completed in order. Host tracks last completed event and expects this to be increasing. We could modify this to handle out of order events. 

Is the following a valid use case:

1. Instantiate a trace (event ids 0 to n assigned to cmds in the trace)
2. End trace 
3. Call some non-traced enqueue apis (event ids n + 1 to n + x assigned and popped from completion queue)
4. Run trace (events 0 to n will be popped from completion queue)

if so, then host can track which events have been completed to relax the assumption that events are returned in-order

**Comment by tooniz** [comment]
Yes that's a valid case. If we follow your offline proposal to capture the evend_id from "Run trace" step and add them to the completions from the trace as soon as we pop them, then they'll appear like event_id kept increasing. I'll go through the code look at the details

**Comment by tooniz** [comment]
The final implementation is the following:

On InstantiateTrace:
- record only relative event_id starting from 0 within a trace, events are recorded as commands into the trace buffer
- record the ReadEventDescriptors into a trace descriptor rather than pushing it onto the pending completion_q

On EnqueueTrace:
- we replay the trace using the usual mechanism -- issuing a exec_buf prefetcher command
- we push the ReadEventDescriptors (with a flag set to indicate that this is part of a trace replay) from the trace descriptor into the pending completion_q

On completion_q processing:
- if the ReadEventDescriptor has the trace replay flag set, then upon event completion we apply a global event_id offset to map the relative id back into the global event_id space

This is merged to FD2 main
