### ISSUE TITLE
EnqueueProgram Functional: TestRandomizedProgram gtest hangs on GS

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent-metal/tt-metal#7222]
Steps to reproduce:
* Re-enable the test in `tests/tt_metal/tt_metal/unit_tests_fast_dispatch/command_queue/test_EnqueueProgram.cpp`
* `/build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter=*TestRandomizedProgram`

Works fine on N150/N300, but hangs on E150.

**Comment by tt-dma** [comment]
TestPipelineAcrossRows appears to fail in the same way on GS

**Comment by davorchap** [comment]
> TestPipelineAcrossRows appears to fail in the same way on GS

This one uses semaphores, something to look into

**Comment by aliuTT** [comment]
Why is this P2? Seems pretty basic. Maybe I can look at this next?

**Comment by tt-dma** [comment]
> Why is this P2? Seems pretty basic. Maybe I can look at this next?

I filed it yesterday and did not know where to put it haha, feel free to change to where it should be (p0 since this is blocking parity?)

**Comment by aliuTT** [comment]
this is now passing after latest rounds of binaries and runtime arg changes.
