### ISSUE TITLE
EnqueueProgram Functional: Runtime args need to have multiple fetch queue entries since they are huge

### ISSUE THREAD

**Issue by aliuTT** [tenstorrent-metal/tt-metal#7260]

**Comment by davorchap** [comment]
@aliuTT can you provide more information. Don't we want to pack multiple run-time args into a single page and use a single fetch queue entry?

**Comment by aliuTT** [comment]
Currently we have 64Kb fetch queue entry. For some unit tests we have 256 runtime args * 3 kernels per core * 120 cores, so this is over the 64Kb. In general, to support the whole range of runtime args we need multiple fetch queue entries.
