### ISSUE TITLE
Bug in hex8_to_hex32 after converting from python script to cpp

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent-metal/tt-metal#7271]
https://github.com/tenstorrent-metal/tt-metal/commit/4b39362cefd996597df7bf192c65b8738f8e8e25 uplifted python script to be a c++ function but caused regression in kernel compilation for

```
./build/test/tt_metal/perf_microbenchmark/dispatch/test_pgm_dispatch -s 256 -n -t
```
Fails with:
```
                  Metal | INFO     | AI CLK for device 0 is:   1202 MHz
                 Always | FATAL    | Memory image has unreadable line.
```

Reverting this commit allows test to pass

**Comment by TT-billteng** [comment]
can you have a look @vtangTT ?

**Comment by vtangTT** [comment]
after some investigation, kernels and sizes that fail: 

brisc: 128 256 512
trisc: 256
ncrisc: 128 256 512

**Comment by vtangTT** [comment]
fix in main, https://github.com/tenstorrent-metal/tt-metal/pull/7439
