### ISSUE TITLE
tt_eager c++ moreh tests not being run

### ISSUE THREAD

**Issue by vtangTT** [tenstorrent-metal/tt-metal#7272]
The following moreh c++ tests are not being run anywhere, are we able to remove them?

`tests/tt_eager/ops/test_moreh_adam_op`
`tests/tt_eager/ops/test_moreh_matmul_op`
`tests/tt_eager/ops/test_moreh_layernorm_op`

@tt-rkim not sure who to tag or what board to put on 

CC: @TT-billteng

**Comment by TT-billteng** [comment]
@jliangTT @razorback3 seems like we have some unused Moreh tests, is this intentional?

**Comment by dongjin-na** [comment]
Hi @TT-billteng , and @vtangTT ,
it's okay to remove those c++ tests.

**Comment by vtangTT** [comment]
removed with https://github.com/tenstorrent-metal/tt-metal/pull/7423
