### ISSUE TITLE
Low PCC when running ttnn.transformer.attention_softmax_

### ISSUE THREAD

**Issue by arakhmati** [tenstorrent-metal/tt-metal#7305]
Branch: `main`

Test: 
```
# Comment out @pytest.mark.skip(reason="This test is failing due to a mismatch")
pytest "tests/ttnn/unit_tests/operations/test_transformer.py::test_transformer_attention_softmax_"
```

**Comment by yugaoTT** [comment]
there are two problems with it, the test itself should set the causal mask to true. 
the op side, was not considering the case that sequence_size not equal to target_sequence_size.
These are fixed now

**Comment by jliangTT** [comment]
workaround available now per @arakhmati , downgrade to p1

**Comment by yugaoTT** [comment]
just merged the fix, closing issue
