### ISSUE TITLE
GTESTS - CommonFixture.DRAMLoopbackSingleCore hang

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent-metal/tt-metal#7330]
`./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter=CommonFixture.DRAMLoopbackSingleCore`, result is a hang.

**Comment by abhullar-tt** [comment]
This test tries to relay / write a buffer where the page size > 4K and is not 4K aligned. In this case `process_write_paged` tries to write to buffer in 4K chunks. 

Hang appears because we went up underflowing `write_length` loop var
