### ISSUE TITLE
[Bug Report] load_tensor doesn't check if device is nullptr for old weights format

### ISSUE THREAD

**Issue by s-jovic** [tenstorrent-metal/tt-metal#7354]
**Describe the bug**
Recently updated load_tensor method takes device as a second argument; if the weights have the new format, the function checks whether device is nullptr, but if the format is the old one, it is assumed that device is not nullptr. In Falcon model initialization, we use load_tensor without the second argument, so we get an exception after this commit.

https://github.com/tenstorrent-metal/tt-metal/blob/main/tt_eager/tensor/serialization.cpp#L263

I fixed it locally for myself to avoid regenerating the weights since it is not necessary and takes a while.

**Comment by arakhmati** [comment]
Thank you for the catch! I totally missed that. I will fix it soon

**Comment by arakhmati** [comment]
I added the check. The issue should be resolved
