### ISSUE TITLE
Use precompiled headers to speedup kernel build

### ISSUE THREAD

**Issue by coffeeandcheesecake** [tenstorrent-metal/tt-metal#950]
https://stackoverflow.com/questions/58841/precompiled-headers-with-gcc

- Just tried enabling precompiled headers, before full build was ~420ms for this kernel (eltwise_binary)
the longest thing was actually trisc2 compile, it was about 295ms
with pch it’s about 0.149s
This was a manual test i’d need to refactor some headers to make it work and change the build a bit
So we should save about 150ms off 420ms - so about 1.55x on full kernel build (for eltwise_binary in this case).

![Image](https://user-images.githubusercontent.com/125414021/228672195-a94c93a8-4389-4c0a-8a71-dec25121f5d8.png)

![Image](https://user-images.githubusercontent.com/125414021/228672263-e880b779-f011-4120-abf2-b8403bbe37e5.png)

![Image](https://user-images.githubusercontent.com/125414021/228672380-6eea89c0-d363-4a21-a728-80901ed4cf8a.png)

Note that if we combine this with removing -g flag it can save another 40-50ms (from compile+link)

Also I think as our LLK library grows, this will scale better.

Another observation - something else we could get from .pch is if we hash it (the .pch file) we get a hash for all the deps that are outside of immediate kernel code. This will help with having a robust kernel cache.

**Comment by pgkeller** [comment]
I'm closing this.  It is related to #1920, but it is premature to say we should use precompiled headers before we fix the other build perf issues.
