### ISSUE TITLE
WH: FP32 Accumulation in Matmul (compute kernel + Metal Unit test)

### ISSUE THREAD

**Issue by kkwong10** [tenstorrent-metal/tt-metal#952]
Add support for FP32 accumulation in kernels + LL APIs

LLKs have all the hooks and code for FP32 support -- 

Next Steps:
- [ ] connecting and hooking up compute_kernel_api
- [ ] exposing a user facing interface.

**Comment by davorchap** [comment]
fyi @chekangliang

**Comment by davorchap** [comment]
@yugaoTT this is done (implementation + test), we can close?

**Comment by yugaoTT** [comment]
@davorchap right I'll close

**Comment by jliangTT** [comment]
Not urgent but would like to understand the some question about the current implementation for this feature: 

Given that Current implementation applies this functionality to the entire kernel
- So the entire operations in a kernel should use fp32 dest accumulation or not
- Wonder if it can be changed to apply it separately for each computation in a kernel

Should we open another issue with track or we can answer it? 

@razorback3 @yugaoTT

**Comment by yugaoTT** [comment]
This is applied to the entire compute kernel, the llk functions use the global defines to decide whether to perform fp32 or not. To separate it, one way it to split the llks, one set use fp32, the other set don't.
