### ISSUE TITLE
commonize NOC parameters that a shared between host / device

### ISSUE THREAD

**Issue by davorchap** [tenstorrent-metal/tt-metal#955]
Currently `command_queue.hpp` inlcudes a device-only file (it is also an arch-specific file),  
 `"tt_metal/src/firmware/riscv/grayskull/noc/noc_parameters.h"`
We have to have these in hostdevcommon, or just replicate them in host-side. 
These are not changing for arch that is in silicon.

Need to make a solution that works both for GS and WH w/o host re-compile of CQ.
CQ should build as part of `make build` which will be device agnostic (a separate case owned by KM).
Tests/application should not be re-building `tt_metal` host impl such as CQ, APIs, etc.

fyi @kkwong10

**Comment by DrJessop** [comment]
Stale.
