### ISSUE TITLE
Replace `tilize`/`untilize` optional args in BMM to inferring from the input/output tensor format as `TILE` or `ROW_MAJOR` instead

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent-metal/tt-metal#965]
The optional `tilize`/`untilize` arguments input/output activations can be removed, and can directly infer whether to tilize/untilize based on the input/output activations tensor formats. This will simplify the code and remove extra compatibility checks.

**Comment by davorchap** [comment]
Inference of args is done at ttnn level.
